### PR TITLE
Mute examples videos

### PR DESCRIPTION
**Pull request by gary149**
Videos examples autoplay on mouseover but maybe we want to mute them by default? (I got jump scared)
No super strong opinion on it open to discussions.
example: https://huggingface.co/spaces/radames/edit-video-by-editing-text

### CODE REVIEW

**Comment by abidlabs** [comment]
Seems reasonable -- @aliabid94 do you have any objections or should I go ahead and merge?

**Comment by radames** [comment]
I've added a commit to this, with some hacks to make it work on Safari/IOS

**Comment by aliabid94** [comment]
what were the hacks to get around? @pngwn might have thoughts on how to resolve those issues, but LGTM otherwise.

**Review by aliabid94 — APPROVED** [review]

**Comment by gary149** [comment]
> I've added a commit to this, with some hacks to make it work on Safari/IOS

Nice catch I'll let @pngwn check that.

**Pull request merged**
