### PR TITLE
Preserve uploaded file names

### PR DESCRIPTION
**Pull request by abidlabs**
Currently, names of files that are uploaded through Gradio components are not preserved. Building off of a nice suggestion by @aliabid94, this PR persists file names of files uploaded through any Gradio component.

The basic change is that instead of files being saved in `/tmp/{orig_filename}_{hash}.{suffix}` path, they are now saved in the `/tmp/{hash}/{orig_filename}.{suffix}` path. This applies to both output files and uploaded files.

Removes the need for `file.orig_name` as `file.name` will return the original filename.

Fixes: #360 
Fixes: #943

### CODE REVIEW

**Comment by freddyaboulton** [comment]
@abidlabs I'm having trouble running this locally on mac.

Getting this when running `model3D` demo

```bash
ValueError: File cannot be fetched: /var/folders/t1/j7cmtcgd0mx43jh9nj_r9mmw0000gn/T/78170efd55f69ea61bda4ab184ba0776c78c5b5c/Duck.glb. All files must contained within the Gradio python app working directory, or be a temp file created by the Gradio python app.
```

And the model3d files do not show up

image

Can someone else on mac make sure I'm not going crazy?

**Comment by freddyaboulton** [comment]
If I remember correctly, last time this happened is because on Mac, `/var/` is `/private/var`, I think we had to call `.resolve()` on the path?

**Comment by abidlabs** [comment]
Thanks for testing, let me fix that!

**Comment by abidlabs** [comment]
Can you test it now @freddyaboulton? I think it should work

**Comment by aliabid94** [comment]
filenames preserved in mac

**Review by aliabid94 — APPROVED** [review]
LGTM

**Comment by abidlabs** [comment]
Thanks @aliabid94 and @freddyaboulton for reviewing!

**Pull request merged**
