### PR TITLE
Fix audio streaming out

### PR DESCRIPTION
**Pull request by aliabid94**
Fix audio streaming caused by broken URL.

Test with streaming_audio_out demo.

Fixes: #7497

### CODE REVIEW

**Review by freddyaboulton — APPROVED** [review]
Nice looks good to me @aliabid94 !

**Comment by freddyaboulton** [comment]
We should add an e2e test for this because I think this has regressed before.

**Comment by abidlabs** [comment]
Agreed with @freddyaboulton about the test

Let me tag @pseudotensor who reported this as well, if you'd like to confirm the fix @pseudotensor

**Comment by pseudotensor** [comment]
Yes, it works now!  Thanks!

**Pull request merged**
