### PR TITLE
Adds the option to run gradio from the remote Jupyter notebook accessible at the non-localhost IP address.

### PR DESCRIPTION
**Pull request by adamryczkowski**
# Description

## Motivation

I want to run gradio on the Jupyter notebook on the server accessible via the LAN/VPN

## Summary of the change 

Adds a new launch parameter, `network_interface_address`, that denotes the IP address of the network interface to be used to serve the gradio content. Defaults to the local interface (127.0.0.1) if `server_name` is None, or all local interfaces (0.0.0.0) if `server_name` is specified. 

Changes the meaning of the `server_name` parameter. Now it is used to specify the address of the gradio server as seen from the browser perspective. Defaults to the server's fully qualified domain name if `network_interface_address` is provided, otherwise `localhost`. 

My change modifies the number of the elements returned by the `networking.py:start_server` function. 

I did not write unit tests for this change.

- [X] I have performed a self-review of my own code
- [X] My code follows the style guidelines of this project
- [X] I have commented my code in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by abidlabs** [comment]
Hi @adamryczkowski thanks for opening this PR. Can you help me understand why the `server_name` parameter is not sufficient for this use case?

**Comment by adamryczkowski** [comment]
As of now, the `server_name` does not work, because it will be replaced with `localhost` anyway. 
It could be a bug, and in fact my first attempt to this PR was to fix it, so the `server_name` would be enough. Then I realized that this may brake some of your other applications, because there are two completely different concepts: one is where the `gradio` should be served from the server (backend) perspective, and the other, how the gradio should be referred to from the back-end perspective. 

That's why I ended up adding additional parameter.

**Comment by abidlabs** [comment]
Hi @adamryczkowski would you be able to provide more details with what's going wrong with the original implementation? I'm afraid I don't quite follow the motivation. It would be great if you can file an issue with code / reproduction instructions that this PR closes.

**Comment by abidlabs** [comment]
Hi @adamryczkowski, will close this PR as part of some general repo housekeeping. Still would like to help if you're running into any issues, but please create a dedicated issue and then we can work from there. Thanks!

**Comment by adamryczkowski** [comment]
Does it mean you are abandoning my PR without giving an explanation why?

Sep 29, 2022 22:18:10 Abubakar Abid ***@***.***>:

**Comment by abidlabs** [comment]
Hi @adamryczkowski like I mentioned in my earlier comments, we need more details to understand the issue that you are facing and the motivation for this PR. Please open an issue providing a reproducible code example so that we can understand the problem. Then, we'd be happy to review a PR to solve that problem. Currently, it is not clear what this PR is solving.

**Comment by abidlabs** [comment]
Thanks @adamryczkowski I've created the issue here: https://github.com/gradio-app/gradio/issues/2382 and we'll take a look it. Feel free to add more details

**Comment by wormcode** [comment]
I have come across the same issue on amazon SageMaker studio lab platform, the following will give some test results:
1.code
`import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
    
demo.launch() #share=True)  
`

gradio_jupyternotebook_error

the corresponding iframe html is



<iframe src="http://127.0.0.1:7866/" allow="autoplay; camera; microphone; clipboard-read; clipboard-write;" allowfullscreen="" width="100%" height="500" frameborder="0"></iframe>


2. change server_name to remote domain name :
`import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
    
demo.launch(server_name="h3wvtdkldcldp1uvqp.studio.us-east-2.sagemaker.aws") #share=True) `

results:
ERROR:    [Errno 99] error while attempting to bind on address ('18.190.140.180', 7869): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('18.190.96.147', 7870): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('18.190.66.74', 7871): cannot assign requested address
ERROR:    [Errno 99] error while attempting to bind on address ('18.190.140.180', 7872): cannot assign requested address
....
seems endless attempting

@abidlabs 
if you would like to reproduce this issue, you could apply a sagemaker studio lab account to try for yourself 

I think the following bugs share the same symptom 
[https://github.com/gradio-app/gradio/issues/2382](url)
[https://github.com/gradio-app/gradio/issues/248](url)
[https://github.com/gradio-app/gradio/pull/2324](url)

**Pull request closed without merging**
