### PR TITLE
Restore offline support

### PR DESCRIPTION
**Pull request by aliabid94**
Allow gradio to work offline

### CODE REVIEW

**Review by pngwn — APPROVED** [review]
Looks good to me. Although this doesn't actually close the issue. There are some other cases where an internet connection is required (certain Plots) and I think gradio plus fonts should be working before we close that issue. 

I think this is a good quick fix though.

**Comment by aliabid94** [comment]
cool, removed the fix claim, this should be good for most use cases

**Comment by akx** [comment]
According to the comment in https://github.com/gradio-app/gradio/pull/4335#issuecomment-1567643746 ignoring CSS load errors would make the UI unusable..? 😅

**Comment by pngwn** [comment]
Changed my mind. The snark is really endearing tho.

**Comment by Saad-Aljebreen** [comment]
Still not able to run ChatInterface offline

**Comment by kmulka-bloomberg** [comment]
@Saad-Aljebreen The ChatInterface example from the docs is working for me offline in version 4.9.0. Could you let us know which version isn't working, and a minimal reproduction of the problem?

**Comment by marouahamdi** [comment]
hello everyone i m stuck with this project where in the company we work fullyyy without internet. any help plz?

**Comment by Saad-Aljebreen** [comment]
Hi @marouahamdi,
I solved this through this [,](https://github.com/gradio-app/gradio/issues/4332) it helped me as in the offline mode Gradio is trying to access google fonts API.

**Pull request merged**
