### PR TITLE
#1692: Ploty sliders and animation controls not displayed

### PR DESCRIPTION
**Pull request by dawoodkhan82**
# Description

Please include: 
* relevant motivation
* a summary of the change 
* which issue is fixed. 
* any additional dependencies that are required for this change.

Closes: # (issue)
#1692

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by freddyaboulton — APPROVED** [review]
@dawoodkhan82 Confirmed this fixes the problem stated in the repros in the issue

image

**Comment by abidlabs** [comment]
@dawoodkhan82, going to go ahead and merge this in for 3.1!

**Comment by Warvito** [comment]
Hi @dawoodkhan82 , sorry, I was not able to replicate the working example after installing the main branch version. I am afraid that maybe I am installing it wrongly. Did you add any particular changes to get it working? Could you please share the example that you used to generate your image? Do you have any planned date to release the next gradio's version?

**Comment by abidlabs** [comment]
Hi @Warvito, it should be working now, with `gradio==3.0.25`!

**Pull request merged**
