### PR TITLE
Latex Rendering Fix

### PR DESCRIPTION
**Pull request by dawoodkhan82**
## Description
Fixes how latex is rendered. there was an issue where the markdown parser would apply its rules to latex equations which would cause rendering issues.

Closes: #8780

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Haven't taken a deep look at this PR yet, but noticed that the UI tests look off:

image

is latex rendering broken or do the storybook tests need to be updated?

**Comment by dawoodkhan82** [comment]
@abidlabs I might've broken something. This changes how the markdown/latex is rendered, so might be some bugs.

**Comment by abidlabs** [comment]
Yeah I tested and its not working for me, for example

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.Markdown("""
    I know $1+1=2$
    """, latex_delimiters=[{ "left": "$", "right": "$", "display": True }])
    
demo.launch()
```

should render:

image

which it does on `main`, but here, it produces:

image

**Comment by dawoodkhan82** [comment]
Yeah it seems I broke it for custom latex_delimiters. Will fix.

**Comment by dawoodkhan82** [comment]
@abidlabs Should be fixed now.

**Comment by dawoodkhan82** [comment]
@abidlabs Should be fixed now.

**Review by abidlabs — APPROVED** [review]
beauitful lgtm @dawoodkhan82!

**Pull request merged**
