### PR TITLE
make printing the error message from a `gr.Error` to the console configurable

### PR DESCRIPTION
**Pull request by obendidi**
## Description

> This would allow not printing stack traces for "expected" errors (while still using gr.Error in order to nicely display the error message in the UI). For instance in ZeroGPU, Spaces logs are full of "quota exceeded" stack traces that bring a lot of noise to the logs.
> Example usage: raise gr.Error("my error message", print_exc=False) ==> won't print the exception in the logs

Closes: #10136

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Testing and Formatting Your Code

1. PRs will only be merged if tests pass on CI. We recommend at least running the backend tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the backed tests: `bash scripts/run_backend_tests.sh`

2. Please run these bash scripts to automatically format your code: `bash scripts/format_backend.sh`, and (if you made any changes to non-Python files) `bash scripts/format_frontend.sh`

### CODE REVIEW

**Review by abidlabs — APPROVED** [review]
lgtm thanks @obendidi for the PR. cc @cbensimon for visibility

**Review by abidlabs — CHANGES_REQUESTED** [review]
Sorry hold on this doesn't work for events that are run through the queue (which is the default case in Gradio) as can be verified with a simple example:

```py
import gradio as gr

def test(x):
    raise gr.Error("Sorry", print_exception=False)
    return x

gr.Interface(test, "text", "text").launch()
```

We need to make sure we apply this change to all of the places that `traceback.print_exc()` is being called for errors.

**Comment by obendidi** [comment]
Good catch, missed that, I've updated the queuing and utils modules to follow the same pattern.

The gradio client also prints the traceback, but It's not related to this feature so didn't update it (the client should always print the traceback IMO)

**Review by abidlabs — APPROVED** [review]

**Comment by abidlabs** [comment]
Great thanks @obendidi for making the changes, lgtm! Will merge in after CI runs

**Pull request merged**
