### PR TITLE
Fix lazy caching

### PR DESCRIPTION
**Pull request by abidlabs**
Closes: https://github.com/gradio-app/gradio/issues/8925, check with example in repro

cc @apolinario @hysts

### CODE REVIEW

**Review by hysts — APPROVED** [review]
Thanks! LGTM!

**Comment by freddyaboulton** [comment]
@abidlabs - I'm having an issue running an image to image demo (`image_mod_default_image`) with lazy caching. I get the following exception:

```
  File "/Users/freddy/sources/gradio/gradio/helpers.py", line 449, in sync_lazy_cache
    for output in fn(*input_values):
  File "/Users/freddy/sources/gradio/gradio/utils.py", line 1324, in wrapped
    yield fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/Users/freddy/sources/gradio/demo/image_mod_default_image/run.py", line 6, in image_mod
    return image.rotate(45)
           ^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'rotate'
```

I think we need to call the component preprocess?

**Comment by abidlabs** [comment]
ah I need to write some better tests for lazy caching. thanks for catching, will fix!

**Comment by abidlabs** [comment]
Should be fixed now @freddyaboulton @hysts if you want to take another pass. I'll add a better test in the meantime

**Comment by abidlabs** [comment]
I'll go ahead and merge this in

**Pull request merged**
