### PR TITLE
Support new tasks with Hugging Face integration

### PR DESCRIPTION
**Pull request by osanseviero**
# Description

This PR adds support for `document-question-answering`, `visual-question-answering`, and `image-to-text` in the integrations with the Hub. One is `.from_pipeline`, which loads the model using transformers and runs inference locally. The other is with `load("models/...")`, which uses the free Inference API. **Two cases need further support related to encoding**

```python
import gradio as gr
from transformers import pipeline

# works
pipe = pipeline("document-question-answering", "impira/layoutlm-document-qa")
gr.Interface.from_pipeline(pipe).launch()

# works 
pipe = pipeline("visual-question-answering", "dandelin/vilt-b32-finetuned-vqa")
gr.Interface.from_pipeline(pipe).launch()

# works 
pipe = pipeline("image-to-text", "Salesforce/blip-image-captioning-base")
gr.Interface.from_pipeline(pipe).launch()

# works
gr.Interface.load("models/nlpconnect/vit-gpt2-image-captioning").launch()

# don't work 
gr.Interface.load("models/dandelin/vilt-b32-finetuned-vqa").launch()
gr.Interface.load("impira/layoutlm-document-qa").launch()
```

Closes: # (issue)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by osanseviero** [comment]
Happy to complete it tomorrow and will open the PR for review

**Comment by osanseviero** [comment]
Hi @freddyaboulton. I added some others tasks and added support in external as well. There is a part that is still not working on inference, some support would be appreciated

**Comment by abidlabs** [comment]
Thanks @osanseviero! I fixed the remaining two cases with the inference API -- turns out they accept images in a different format (base64) than the other image API endpoints (binary blobs), and added a test for that. All your changes look good so I'll go ahead and merge this in tomorrow.

**Comment by osanseviero** [comment]
Thanks a lot! :heart:

**Pull request merged**
