### PR TITLE
update vite and vitest

### PR DESCRIPTION
**Pull request by pngwn**
## Description

Supersedes #6655 and #6649 

Closes: #(issue)

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Review by abidlabs — APPROVED** [review]

**Review by abidlabs — CHANGES_REQUESTED** [review]
jk there's an issue with custom components development mode

Running:

```bash
gradio cc dev
```

gives me:

```
♻ Launching demo/app.py in reload mode

file:///Users/abidlabs/dev/gradio-repos/gradio/gradio/node/dev/files/index-db553d80.js:215

        existsSync(join$2(__dirname, localName)) ? localName : `@rollup/rollup-${packageBase}`

                          ^



ReferenceError: __dirname is not defined in ES module scope

This file is being treated as an ES module because it has a '.js' file extension and '/Users/abidlabs/dev/gradio-repos/gradio/gradio/node/package.json' contains 
"type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.

    at file:///Users/abidlabs/dev/gradio-repos/gradio/gradio/node/dev/files/index-db553d80.js:215:20

    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

Backend server failed to launch. Exiting.
```

**Comment by abidlabs** [comment]
Full commands:

```
gradio cc create Textboxv5 --template Textbox
cd textboxv5
gradio cc dev
```

As you mentioned @pngwn it would be great if we could add a test to catch dev mode failing in the future

**Comment by freddyaboulton** [comment]
dev mode test issue is here #6221 ! It's on my radar!

**Comment by pngwn** [comment]
This isn't worth the effort right now will close until it makes more sense. I'll open a PR to disable the auto updates for these packages.

**Pull request closed without merging**
