### PR TITLE
Website Tracker Slackbot

### PR DESCRIPTION
**Pull request by aliabd**
Building a slackbot to send a notification when the website is no longer tracking master

Has not been tested

### CODE REVIEW

**Comment by abidlabs** [comment]
Awesome

**Comment by aliabid94** [comment]
It will only send a notification if the docker steps fail. This is necessarily the same as tracking master. For example, when earlier, the git pull step failed so it was not tracking master, this would not have caught that.

**Comment by aliabid94** [comment]
also of course, move the slack url webhook to an os variable

**Comment by aliabd** [comment]
Tested significantly in devserver. but could not test the `tail -n 25 /var/mail/ubuntu` command as its only on the gradio instance. 

@aliabid94 I can catch git pull errors now and read the webhook URL from an os variable (deleted old one)

**Comment by aliabd** [comment]
This is ready to be merged. On the gradio machine we'll install `jo` for json formatting and the cron job will point to the new shell script.

**Pull request merged**
