### PR TITLE
Quick fix: custom dropdown value

### PR DESCRIPTION
**Pull request by dawoodkhan82**
## Description

Fixes:

```
import gradio as gr

text = gr.Dropdown(["a", "b", "c"], label="Select a letter", value=None, allow_custom_value=True)
iface = gr.Interface(fn=lambda x: print(x), inputs=[text], outputs=[])
iface.launch()
```

Closes: #7549
Closes: https://github.com/gradio-app/gradio/issues/7613

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by Paillat-dev** [comment]
Btw @dawoodkhan82 That same error happens if you wanna update the dropdown choices, if you wanna take a look:
```python
import gradio as gr

text = gr.Dropdown(["a", "b", "c"], label="Select a letter", value=None, allow_custom_value=True)
iface = gr.Interface(fn=lambda x: gr.Dropdown(choices=["a", "b", "c", x]), inputs=[text], outputs=[text])
iface.launch()
```

**Comment by Paillat-dev** [comment]
By the way, the following is throwing the same error, including with this pr:

```python
import gradio as gr

text = gr.Dropdown(["a", "b", "c"], label="Select a letter", value=None, allow_custom_value=True)
iface = gr.Interface(fn=lambda x: [gr.Dropdown(choices=[], value=None)], inputs=[text], outputs=[text])
iface.launch()
```

**Comment by dawoodkhan82** [comment]
@Paillat-dev @abidlabs thanks for testing, taking a look at the issues.

**Comment by dawoodkhan82** [comment]
```
import gradio as gr

text = gr.Dropdown(["a", "b", "c"], label="Select a letter", value=None, allow_custom_value=True)
iface = gr.Interface(fn=lambda x: gr.Dropdown(choices=[], value=None), inputs=[text], outputs=[text])
iface.launch()

```

@Paillat-dev This works fine for me by the way.

**Comment by abidlabs** [comment]
@dawoodkhan82 did you try submitting the Interface? That's when the error happened for me

**Comment by Paillat-dev** [comment]
> ```
> import gradio as gr
> 
> text = gr.Dropdown(["a", "b", "c"], label="Select a letter", value=None, allow_custom_value=True)
> iface = gr.Interface(fn=lambda x: gr.Dropdown(choices=[], value=None), inputs=[text], outputs=[text])
> iface.launch()
> 
> ```
> 
> @Paillat-dev This works fine for me by the way.

Yeah that's what I was saying, the error only happens when you (lambda) return a list with only one item, it being the drop-down, but not when you return it alone. Maybe it also happens when returning a one item tuple, I should try. Nonetheless, since a list works with multiple items it should also work with one.

**Comment by dawoodkhan82** [comment]
@abidlabs are you testing this code?

```
import gradio as gr

text = gr.Dropdown(["a", "b", "c"], label="Select a letter", value=None, allow_custom_value=True)
iface = gr.Interface(fn=lambda x: gr.Dropdown(choices=[], value=None), inputs=[text], outputs=[text])
iface.launch()
```

https://github.com/gradio-app/gradio/assets/12725292/76d11c01-62ae-440f-bb4e-6d5e6c896d35

Works for me, when _not_ returning the dropdown as a list. I'm not sure returning a list is supposed to work

**Comment by abidlabs** [comment]
Ah that's true, when `gr.Dropdown()` has `multiselect=False`, the return type should be a string, not a list. I'm not sure @Paillat-dev what you mean by this:

> returning multiple items as a list, just not with one. And especially when in the function the outputs are still specified as a list

**Comment by abidlabs** [comment]
Ah good point @dawoodkhan82! 

@Paillat-dev when you have a single output component, you should *not* wrap the return in a list / tuple. You should just return the output as is. The reason we don't support singleton lists is that it becomes impossible to distinguish whether you are intending on returning a singleton list or the item within it in some scenarios. Consider this example:

```py
import gradio as gr

gr.Interface(lambda x:[{"abc": "def"}], "textbox", "json").launch()
```

In this case, both are possible: the user might be intending on returning a list, or just the dict within it. When you have multiple output components, this ambiguity is resolved.

So in that case, this PR looks good to me @dawoodkhan82 if we could just add a js unit test to prevent regressions!

**Review by abidlabs — APPROVED** [review]

**Comment by Paillat-dev** [comment]
I did not think of that. Sounds logical now, thanks for the explanation. And thanks for the fix :)

**Comment by dawoodkhan82** [comment]
> In addition to the issue @Paillat-dev pointed out, I noticed that the case of value="" is not handled correctly:
> 
> ```python
> import gradio as gr
> 
> with gr.Blocks() as demo:
>     text = gr.Dropdown(["a", "b", "c"], label="Select a letter", value="", allow_custom_value=True, interactive=True)
> 
> demo.launch()
> ```
> 
> This should initialize the Dropdown with a value of "" but instead it initializes with "a" -- I think there could be a related issue happening.
> 
> Finally, could we add js unit tests for these fixes @dawoodkhan82?

Taking a look at this again, and according to the dropdown tests. When initializing the dropdown with `value=""`, it should pre-select the first dropdown option.

**Comment by abidlabs** [comment]
> Taking a look at this again, and according to the dropdown tests. When initializing the dropdown with value="", it should pre-select the first dropdown option.

Oh weird, is that the case when initializing with any value that is not one of the choices? I guess that makes sense

**Comment by abidlabs** [comment]
LGTM @dawoodkhan82! Thanks for adding the test.

I've confirmed that this fixes: https://github.com/gradio-app/gradio/issues/7613 so I've added it to the parent comment. 

I'll go ahead and merge this in so that we can get it out for the release!

**Pull request merged**
