### PR TITLE
HEIC support for images

### PR DESCRIPTION
**Pull request by smikhai1**
## Description

Adds support of HEIC images by installing PIL's plugin 

Closes: #7482 

## Tests
All tests passed locally

### CODE REVIEW

**Comment by abidlabs** [comment]
Thank you @smikhai1 for creating this PR. I am not a fan of adding more dependencies to Gradio, so let me respond on the original issue

**Review by akx — COMMENTED** [review]
Pretty sure this (and the extra dependency) shouldn't be in Gradio's core – if an app requires HEIF, it can run these two lines itself?

**Comment by pngwn** [comment]
Yeah, I don't even think this should be a custom component. Just add the extra lines of code. heif is becoming more popular but it isn't that common atm.

**Comment by abidlabs** [comment]
I'll go ahead and close this PR and issue. @smikhai1 please see the suggestions mentioned above

**Comment by abidlabs** [comment]
I think @smikhai1, having a public demo on [Hugging Face Spaces](https://huggingface.co/spaces) might be better for visibility and to provide guidance for users.

**Pull request closed without merging**
