### PR TITLE
Add `container parameter` to `gr.HTML` component

### PR DESCRIPTION
**Pull request by yinsumirage**
## Description
add a `container` parameter to `gr.HTML` component to help it have the same outer borders

test with code under 
```python
import gradio as gr

# HTML content
html_content = """
<h1>Hello, World!</h1>
"""

html_content_1 = """
<h1>Hello, World!</h1>
"""

# Markdown content
markdown_content = """
# Markdown Example
This is a demonstration of the **gr.Markdown** component.

- It supports lists
- **Bold text**
- *Italic text*
- Links: [Gradio](https://gradio.app)
"""

# Create Gradio interface
with gr.Blocks() as demo:
    gr.HTML(html_content, container=True)
    gr.HTML(html_content)
    gr.Markdown(markdown_content, container=True)
    gr.Markdown(markdown_content)

demo.launch()
```
the result like this

and sorry again for my mistake of pr

Closes: #10010

### CODE REVIEW

**Review by abidlabs — APPROVED** [review]
Great thanks for this contribution @yinsumirage!

**Comment by nuclearrockstone** [comment]
Thank you bro

**Comment by nuclearrockstone** [comment]
image
There is only one small problem, and I believe this problem occurs in the front-end code. When both the container and show_label attributes are set to True at the same time, there will be an obvious conflict between the two.
I think the problem is that the labels used in the two are different. The label of the html component uses ```<span>```, while other components use ```<label>```
image
image

**Comment by abidlabs** [comment]
@nuclearrockstone can you create a new issue for this please?

**Pull request merged**
