### PR TITLE
Make Remove All button in `gr.Dropdown` configurable

### PR DESCRIPTION
**Pull request by space-nuko**
# Description

- Makes Remove All button in `gr.Dropdown` hidable with `show_remove_all=False`
- Provide `default_value` to switch to if button is clicked in single-select mode
- Remove All button is hidden in single-select if default value is selected
- Remove All button is hidden in multiselect if no values are selected

Closes: #3526, closes: #3435

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by abidlabs** [comment]
I find the name `default_value` confusing, as it sounds like the value that should be shown in the `Dropdown` component when it is first loaded (what `value` currently refers to). A better name imo would be `cleared_value` -- and, I would set the `.cleared_value` attribute of the `Dropdown` class to be equal to this `cleared_value` parameter. The effect of this would be that in `gr.Interface`, when the "Clear" button is clicked, then the `Dropdown` would reset to this value. (and I would similarly rename `show_remove_all` to be `show_clear_button` -- to refer to this parameter and be parallel to `show_copy_button`).

**Comment by freddyaboulton** [comment]
I'm wary of adding `cleared_value` to the API since an app author can implement that themselves in their event handler (`dropdown_value = cleared_value if not value else value`) and it's very different from how the other components behave. What's the use case?

**Comment by space-nuko** [comment]
The `cleared_value` can be used even if there are no event handlers on the `gr.Dropdown`, it affects the behavior of the button instead of anything caused by an event

**Comment by pngwn** [comment]
Why not just add a clear event instead?

I don't understand why we would want to remove the clear button for multiselect dropdowns either. Single select should not have a clear button at all.

**Comment by space-nuko** [comment]
So instead of the additions there should be a `clear()` event for dropdowns?

> `default_value` seems unnecessary when you can choose a default in the predict function that the dropdown is an input for or select an initial value.

What does this mean? I was imagining having a choices list like `["None"] + models_list` autogenerated and being able to easily default to `"None"` if the button is clicked, otherwise it can be hidden

**Comment by pngwn** [comment]
> What does this mean? I was imagining having a choices list like ["None"] + models_list autogenerated and being able to easily default to "None" if the button is clicked, otherwise it can be hidden

Ah, I misunderstood. `default_value` is intended as `cleared_value` rather than a default. I think this could be handle with events without the need for additional constructor kwargs.

See what @freddyaboulton and @abidlabs think.

**Comment by abidlabs** [comment]
Reading over this PR again, I agree with the hesitation about adding another parameter, `cleared_value`, to the `gr.Dropdown`, for several reasons:

* It breaks user expectations -- when a user clicks on an "X" in a Dropdown, they expect the Dropdown to clear, not to be set to some customizable value
* The `value` parameter already exists and `cleared_value` forces developers to think about two different kinds of defaults: one when the page loads and one when the dropdown is cleared

I suggest we adopt @pngwn's suggestion here and simply do this:

* remove the clear button for single select dropdowns (this would solve #3435)
* keep the clear button for multiselect dropdowns as is

This wouldn't solve the second part of #3526, but like I mentioned above, imo that's not a good UX anyways.

**Comment by space-nuko** [comment]
Okay thanks for the feedback, I will redo my changes in accordance with @pngwn's ideas

**Pull request closed without merging**
