### PR TITLE
Add line numbering and collapse/expand logic to gr.JSON

### PR DESCRIPTION
**Pull request by hannahblair**
## Description

Adds line numbers and collapse and expand toggles to `gr.JSON`.

- Toggle and expand via toggle button
- Expand via preview ( `Object(3) text` )
- Line numbers cant be highlighted

~~💭 By default all key vals are expanded. WDYT of adding a `collapsed` param to gr.JSON to allow devs to collapse certain paths?~~

Now added an `open` param to expand all nodes and collapsed all nodes with a depth of >=3 by default

Demo here: https://huggingface.co/spaces/hmb/json_test

Closes: #1175 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Review by dawoodkhan82 — APPROVED** [review]
Nice! lgtm. Also I like the idea of a `collapsed` param

**Comment by dawoodkhan82** [comment]
Also, I realized we're using custom css for the json font colors. Should we import the codemirror themes, like in `gr.Code()`

**Comment by abidlabs** [comment]
I think a global `open` parameter (similar to `gr.Accordion`) that sets the initial state of `gr.JSON` could be useful. Not sure if we need it to be path-specific.

**Review by abidlabs — APPROVED** [review]
Wow looks really nice!

**Pull request merged**
