### PR TITLE
Add js/lite/package.json

### PR DESCRIPTION
**Pull request by whitphx**
## Description

Make `js/lite` an NPM package to be published.

@pngwn Is it true that all the public packages including `js/lite` in this PR will be automatically released by the CI/CD workflow defined in `publish-npm.yml`?

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests & Changelog

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

1. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`
  
1. Unless the pull request is labeled with the "no-changelog-update" label by a maintainer of the repo, all pull requests must update the changelog located in `CHANGELOG.md`:

Please add a brief summary of the change to the Upcoming Release section of the `CHANGELOG.md` file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

### CODE REVIEW

**Comment by pngwn** [comment]
@whitphx Yep. They should be. The first time we merge it should get released because there is nothing published. Subsequent releases will need to follow the change sets process I described in another PR. I'm happy to jump on a call to explain that further if that is helpful but I will also be documented it soon.

**Comment by pngwn** [comment]
Should we merge this and see if it works as expected?

**Comment by whitphx** [comment]
@pngwn Sorry I added some lines to build `@gradio/lite` in the CI workflow. Plz review them again.

> change sets

I got it, thanks. So basically when we want to release a new version of `@gradio/lite`, we have to run `pnpm changeset add`, select the package name in the CLI prompt, and commit the changes?

> Should we merge this and see if it works as expected?

Yes, please :)

**Comment by pngwn** [comment]
Yep. And it will create a new PR with a change log generated and versions bumped. When we merge that, everything gets released.

**Comment by pngwn** [comment]
Failed. Just looking into it.

**Comment by pngwn** [comment]
Could be an outdated lockfile

**Pull request merged**
