### PR TITLE
Add support for python client connecting to gradio apps running with self-signed SSL certificates

### PR DESCRIPTION
**Pull request by abidlabs**
This PR adds an `ssl_verify` parameter to `gradio_client.Client` to match the corresponding parameter in `launch()`

Not easy to write a unit test for this but you can run the following to confirm:

1. `openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 365 -nodes` in terminal
2. In the same directory, launch a gradio app:

```py
import gradio as gr

demo = gr.Interface(lambda x:x, "image", "image")

_, url, _ = demo.launch(
    ssl_certfile="cert.pem",
    ssl_keyfile="key.pem",
    ssl_verify=False
)
```

3. Connect with the client:

```py
from gradio_client import Client, file

client = Client(url, ssl_verify=False)

client.predict(file("cheetah.jpg"))
```

Fixes: https://github.com/gradio-app/gradio/issues/5497

### CODE REVIEW

**Review by freddyaboulton — APPROVED** [review]
Looks good @abidlabs ! I think we're missing `check_for_cancel` and (`download_byte_stream`, `stream_sse_v0`, `download_temp_copy_of_file`) so that this parameter can work for 3.x spaces

**Comment by abidlabs** [comment]
As part of this PR, I moved the `download_files()` and `upload_files()` from utils.py to client.py since we were passing so many of the client attributes as parameters anyways. I've updated the tests accordingly.

**Comment by abidlabs** [comment]
Thanks @freddyaboulton for the review and for catching those. I'll go through and add

**Comment by abidlabs** [comment]
Should be all good now, will merge in after CI passes

**Pull request merged**
