### PR TITLE
Update docs on equal_height param for Rows

### LINKED ISSUE #2120: equal_height referenced in the docs but appears to be deprecated
### Describe the bug

This is not at all blocking, but I figured I'd post because I got a bit confused as a new user. The docs mention the `equal_height` parameter [here](https://gradio.app/controlling_layout/). But when I ran the app locally, I got a message that it's deprecated. If so, it'd be helpful to new users to remove it.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

Simply add `equal_height=True` to a `gr.Row()` and run the app (happy to put together something more detailed if needed).

### Screenshot

_No response_

### Logs

```shell
venv/lib/python3.10/site-packages/gradio/deprecation.py:43: UserWarning: You have unused kwarg parameters in Row, please remove them: {'equal_height': True}
  warnings.warn(
```
```


### System Info

```shell
gradio>>> gradio.__version__
'3.1.7'
```
```


### Severity

annoying

### PR DESCRIPTION
**Pull request by freddyaboulton**
# Description

Fixes #2120

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have added a short summary of my change to the CHANGELOG.md
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by abidlabs** [comment]
@aliabid94 I thought we deprecated `equal_height`? I tried the example mentioned in this Guide and `equal_height` seems to have no effect

**Comment by freddyaboulton** [comment]
@abidlabs I think the default is `equal_height=True`. Setting `equal_height=False` does have an effect:

image


Code: 

```python
import gradio as gr

with gr.Blocks() as demo:
    with gr.Row().style(equal_height=False):
        textbox = gr.Textbox()
        btn2 = gr.Button("Button 2")

demo.launch()
```

**Comment by abidlabs** [comment]
Ah good to know! LGTM @freddyaboulton

**Review by abidlabs — APPROVED** [review]

**Comment by freddyaboulton** [comment]
Thanks @abidlabs !

**Pull request merged**
