### PR TITLE
render markdown examples with markdown

### PR DESCRIPTION
**Pull request by abidlabs**
Small fix to actually render the Markdown examples using Markdown

Fixes: #4509 

Test with repro in the original example. 

One slightly annoying thing is that we don't have access to the Markdown component's attributes in the example frontend component, like we do in the static/interactive versions of the component. So what I did instead was to use some sensible defaults -- sanitize html, but no latex rendering.

### CODE REVIEW

**Comment by pngwn** [comment]
> One slightly annoying thing is that we don't have access to the Markdown component's attributes in the example frontend component, like we do in the static/interactive versions of the component.

This would be relatively easy to do as long as know which instance of each component each example belongs to (preferably via the id).

**Comment by abidlabs** [comment]
> This would be relatively easy to do as long as know which instance of each component each example belongs to (preferably via the id).

Oh interesting, I actually _just_ added support for this in the backend to solve a different bug. The `Dataset` component now has a `component_ids` value that it exposes in the config.

**Comment by pngwn** [comment]
I need to check where the example changes are. Not sure if they are in main or v4, to decide where to implement this.

**Comment by pngwn** [comment]
I'm going to refactor component loading next week so maybe I can do it at the same time.

**Comment by abidlabs** [comment]
That'd be great thanks @pngwn. Probably some custom components could also benefit from having component props in the examples

In the meantime, I'll revert this to a draft PR

**Comment by abidlabs** [comment]
I'm going to do this again, but targeting `v4` now

**Pull request closed without merging**
