### PR TITLE
Handle special arguments when extracting parameter names for view API page

### PR DESCRIPTION
**Pull request by abidlabs**
Closes: https://github.com/gradio-app/gradio/issues/8399

Test with:

```py
import gradio as gr
import time


def echo(message, request: gr.Request, num):
    return message

demo = gr.Interface(
    echo,
    ["textbox", "slider"],
    ["textbox"],
)

demo.launch()
```

For the case of `gr.ChatInterface`, we can't get the original parameter names because we construct a wrapper function over the user's defined function, so in such cases, the parameter names are generated automatically:

image

### CODE REVIEW

**Comment by freddyaboulton** [comment]
Can we use something like functools.wraps in the chat_interface case to preserve the original signature?

Also, I was wondering why we need to construct the special args within the chat_interface function. Shouldn't that be handled by the regular request life-cycle in Blocks.

**Comment by abidlabs** [comment]
> Can we use something like functools.wraps in the chat_interface case to preserve the original signature?

I think so yes I'll take a look

> Also, I was wondering why we need to construct the special args within the chat_interface function. Shouldn't that be handled by the regular request life-cycle in Blocks.

Sorry what are you referring to by this?

**Comment by freddyaboulton** [comment]
> Sorry what are you referring to by this?

If we can use something like `functools.wraps` to preserve the original signature, then I don't think we need to call `special_args` within `submit_fn` because `gr.Blocks` will know to pass the request as an input if it sees the type hint.

**Comment by abidlabs** [comment]
Thanks @freddyaboulton for the suggestion. Refactored to use `functools.wraps`, so now we handle `gr.ChatInterface` with additional parameters correctly as well. For the example in the original issue, we now have:

image

**Comment by abidlabs** [comment]
Indeed. Thanks @freddyaboulton for the reviews and suggestions.

**Pull request merged**
