### PR TITLE
Add link to Github on nav bar

### PR DESCRIPTION
**Pull request by aliabd**
Adds the Github logo to the website nav bar and links our github

Screen Shot 2022-07-29 at 10 23 16 AM

### CODE REVIEW

**Review by freddyaboulton — APPROVED** [review]
Thanks @aliabd ! Works for me locally

**Comment by aliabd** [comment]
@abidlabs Fixed both issues, please take another look.

**Comment by abidlabs** [comment]
The color issue is fixed, but I'm still seeing the responsiveness issue (for example, here's how it looks when screen width is 645 px):

image

**Comment by aliabd** [comment]
Sorry @abidlabs you're right. Guess I didn't have a strong understanding of tailwind breakpoints. Fixed now and implemented the way you want. Let me know if you're still having issues.

I also reduced the gaps in the nav bar in expanded position to make things more manageable and rely on tailwind default breakpoints. it looks fine to me but if you think its too crammed we can bring back original spacing and define our own breakpoints.

**Comment by abidlabs** [comment]
Beautiful @aliabd, thanks for making sure it works across all screen sizes!

**Review by abidlabs — APPROVED** [review]

**Pull request merged**
