### PR TITLE
Add download button for audio

### PR DESCRIPTION
**Pull request by leuryr**
## Description

- Adds download button for audio component.
- Adds `show_download_button` param that determines download button visibility in static Audio components.

Closes: #4087

## Tests & Changelog

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

1. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`
  
1. Unless the pull request is labeled with the "no-changelog-update" label by a maintainer of the repo, all pull requests must update the changelog located in `CHANGELOG.md`:

Please add a brief summary of the change to the Upcoming Release section of the `CHANGELOG.md` file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

### CODE REVIEW

**Comment by leuryr** [comment]
Was interested in getting involved and contributing, and saw this was one of the issues with the `good first issue` label. I tried to follow PR #3581 for this to keep the code consistent, and given it was [alluded to](https://github.com/gradio-app/gradio/issues/4085#issuecomment-1537146284) in the discussion around this open issue.

I thought to add a test for the addition like there was in that PR, but that file isn't in the repo anymore, so I thought maybe there's a different approach now. Happy to make any changes though!

**Comment by abidlabs** [comment]
Thanks @leuryr for this nice contribution! Would you be able to add a `show_download_button` parameter to `gr.Audio` as well, similar to this PR: https://github.com/gradio-app/gradio/pull/4959

It can be `True` by default, but it would allow developers to hide the button if they'd like

**Comment by leuryr** [comment]
@abidlabs sure thing! I'll work on adding it in later today.

**Comment by abidlabs** [comment]
Thanks @leuryr for the nice PR! Tested and everything lgtm

**Comment by abidlabs** [comment]
Actually let me revert real quickly, only because we are trying out a new changelog process.

**Comment by leuryr** [comment]
Ah ok, no worries. Thank you for the review @abidlabs , and looking forward to seeing the new changelog process implemented! I read over the PR a bit, and it looks like a substantial change, but one that will overall streamline the process.

**Pull request merged**
