### PR TITLE
Trigger state change event on iterators

### LINKED ISSUE #9172: Async state changes do not trigger events
### Describe the bug

Changes to a `gr.State` do not trigger a `render` decorator to re-render. This does not happen with other components (I've tested Textbox).

This only happens when updating the value with an async function that yields updates.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

Try swapping out `text_count`, or the `increment` func

```python
import gradio as gr


async def increment(count):
    yield str(int(count) + 1)


# async def increment(count):
#     return str(int(count) + 1)


with gr.Blocks() as demo:
    text_count = gr.State("0")
    # text_count = gr.Textbox("0")

    add_btn = gr.Button("Add Box")
    add_btn.click(increment, text_count, text_count)

    @gr.render(inputs=text_count)
    def render_count(count):
        boxes = []
        for i in range(int(count)):
            box = gr.Textbox(key=i, label=f"Box {i}")
            boxes.append(box)

        def merge(*args):
            return " ".join(args)

        merge_btn.click(merge, boxes, output)

    merge_btn = gr.Button("Merge")
    output = gr.Textbox(label="Merged Output")

demo.launch()
```

### Screenshot

_No response_

### Logs

_No response_

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Darwin
gradio version: 4.42.0
gradio_client version: 1.3.0

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 3.7.1
fastapi: 0.112.1
ffmpy: 0.4.0
gradio-client==1.3.0 is not installed.
httpx: 0.27.0
huggingface-hub: 0.24.6
importlib-resources: 6.4.4
jinja2: 3.1.4
markupsafe: 2.1.5
matplotlib: 3.9.2
numpy: 1.26.4
orjson: 3.10.7
packaging: 24.1
pandas: 2.2.2
pillow: 10.4.0
pydantic: 2.8.2
pydub: 0.25.1
python-multipart: 0.0.9
pyyaml: 6.0.2
ruff: 0.6.1
semantic-version: 2.10.0
tomlkit==0.12.0 is not installed.
typer: 0.12.4
typing-extensions: 4.12.2
urllib3: 2.2.2
uvicorn: 0.30.6
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.6.1
httpx: 0.27.0
huggingface-hub: 0.24.6
packaging: 24.1
typing-extensions: 4.12.2
websockets: 12.0
```

### Severity

Blocking usage of gradio

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

We only triggered the state change event when the component finished but this would lead to bugs like #9172 

Closes #9172

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by aliabid94** [comment]
Looks great @freddyaboulton! Just one thought - if the iterator yields multiple values to a state variable, the state change does not trigger until the last yield. Is this the desired behaviour? Shouldn't any state change automatically trigger the state.change event listener? It seems instead that they stack up. Take a look at this demo for repro:
```python
import gradio as gr
import time

with gr.Blocks() as demo:
    async def increment(x):
        for i in range(x + 2):
            print("setting", i)
            yield i
            time.sleep(0.3)

    n_text = gr.State(0)
    add_btn = gr.Button("Iterator State Change")
    add_btn.click(increment, n_text, n_text)

    sv = gr.Textbox(label="State val")
    def iden(x):
        print("iden", x)
        return x
    n_text.change(iden, n_text, sv)

    @gr.render(inputs=n_text)
    def render_count(count):
        print("rendering", count)
        for i in range(int(count)):
            gr.Markdown(value = f"Success Box {i} added", key=i)


if __name__ == "__main__":
    demo.launch()
```

**Comment by freddyaboulton** [comment]
@aliabid94 Thanks for the review! I was confused by your demo at first too. But the issue is that since increment is async, you need to use `await asyncio.sleep` instead of `time.sleep`. Otherwise, the entire event loop on the server gets locked until the iterator finishes and then all the "stacked up" change events fire.

**Review by hysts — APPROVED** [review]
LGTM!

**Review by whitphx — APPROVED** [review]
LGTM!

**Review by yvrjsharma — APPROVED** [review]
LGTM too!

**Pull request merged**
