### PR TITLE
Quick fix for partial functions

### PR DESCRIPTION
**Pull request by abidlabs**
Partial functions don't have the `__name__` attribute, so were causing a problem with Interface/Blocks. This fixes: #2195 and adds a test to prevent regressions in the future.

### CODE REVIEW

**Review by freddyaboulton — APPROVED** [review]
Looks good to me @abidlabs ! I might also check the `fn` name in the config is set to `fn`

**Review by dawoodkhan82 — APPROVED** [review]

**Comment by cobryan05** [comment]
I was running into an issue last night with partial functions and integrating the new iterative output.  My partial async functions were failing the `inspect.iscoroutinefunction` calls in blocks.py, since the 'iscouroutinefunction' wasn't unwrapping the partial. Is there any chance this change might also fix that issue?

**Comment by freddyaboulton** [comment]
@cobryan05 You have an async generator defined in your app? The iterative output feature [does not support](https://github.com/gradio-app/gradio/blob/main/gradio/blocks.py#L631) async generators (rationale [here](https://github.com/gradio-app/gradio/pull/2162#issuecomment-1237495624)). I can look into it but right now the expectation is for async generators to not work regardless of whether they are partial functions or not.

**Comment by cobryan05** [comment]
> @cobryan05 You have an async generator defined in your app?
I'm probably getting terminology mixed up. I have a function that yields.  

I tried lots of combinations of 'async' and type hints and such while trying to get it to work before I figured out it was the partial.

But basically, I have a function that has a yield statement, but since I have it wrapped in 'partial' the 'inspect' routines don't think it is going to be a function that yields. 

I just saw 'partial' in the name here and thought "Hey, I was just dealing with an issue like that, I wonder if their fix is the 'better' fix for the issue" :)

**Comment by cobryan05** [comment]
Awesome, sounds like exactly what I needed! Will try it out tonight :)

**Comment by abidlabs** [comment]
Thanks a bunch for the reviews @freddyaboulton and @dawoodkhan82! I've added a test to check the config and will merge this PR once the CI finishes running.

**Pull request merged**
