### PR TITLE
[DO NOT MERGE] Add logs to debug kitchen sink

### PR DESCRIPTION
**Pull request by Wauplin**
Related to https://github.com/gradio-app/gradio/pull/2509#issuecomment-1303984643.
FRP tunneling gets an error when working on `kitchen_sink` demo.

Here is a PR that adds some logs (especially keeping track of nb running threads).
See logs:
- `hello_world_1_user_logs.txt` => basic hello world example, only 1 tab opened
- `hello_world_2_user_logs.txt` => basic hello world example, but 2 tabs opened => works as well, same nb of threads
- `kitchen_sink_1_user_fails_logs.txt` => opens a LOT of threads (~90), e.g. a lot of connections. At some point a socket is closed without notice. I guess the number of opened connections depends on the complexity of the page. I still don't get why the FRP server is requesting the open new connections (code `114`) as for what I understand it shouldn't even be aware of what Gradio is doing (blind tunneling).

### CODE REVIEW

**Comment by Wauplin** [comment]
For more context, here is the hello world example I'm using :
```py
import gradio as gr

def greet(name):
    return "Hello " + name + "!"

demo = gr.Interface(fn=greet, inputs="text", outputs="text")
demo.launch(share=True)
```

And locally I run `python demo/kitchen_sink/run.py > kitchen_sink_logs.txt` to store the logs in a file. To get the URL on which the gradio is shared, please check the ad-hoc `shared_url.txt` file that is created. It's dirty but meant only for debugging anyway.

**Comment by abidlabs** [comment]
Thanks so much @Wauplin for adding these logs. @aliabid94 and I will be investigating this FRP issue in the next few days and this will be super helpful

**Comment by Wauplin** [comment]
Good luck for with it @abidlabs ! As I said, I think it will be necessary to watch the RPC server logs at the same time (which I didn't). Would be useful to understand why so many connections are requested server-side.

**Comment by abidlabs** [comment]
Closing in favor of #2746 but thank you @Wauplin!

**Pull request closed without merging**
