### PR TITLE
Add the brand assets page to the website

### PR DESCRIPTION
**Pull request by whitphx**
## Description

Please include a concise summary, in clear English, of the changes in this pull request. If it closes an issue, please mention it here.

Closes: #(issue)

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Review by aliabd — APPROVED** [review]
This LGTM! thanks @whitphx!

**Comment by whitphx** [comment]
Added PNG files converted from the SVGs with the following commands:
```
inkscape -w 512 gradio-logo.svg -o gradio-logo.png
inkscape -w 1024 gradio-logo-with-title.svg -o gradio-logo-with-title.png
```

**Comment by abidlabs** [comment]
https://gradio-qdrrmdk0t-hugging-face.vercel.app/brand looks great! Feel free to merge @whitphx

**Review by abidlabs — APPROVED** [review]

**Comment by abidlabs** [comment]
Just remembered this old issue from back in the day: https://github.com/gradio-app/gradio/issues/1441 :)

**Pull request merged**
