### PR TITLE
Allow setting title in gr.Info/Warning/Error

### PR DESCRIPTION
**Pull request by ABucket**
## Description

Allow users to manually set the title (i.e. through gr.Info("Message", title="Title"). 

Closes: #9670 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Review by freddyaboulton — COMMENTED** [review]
Looks good @ABucket - I think we need to add a title parameter to `gr.Error` and we can merge.

**Review by abidlabs — DISMISSED** [review]
Thanks @ABucket this PR looks great. Just noticed one thing -- the position of the `title` argument is not consistent across `Info`, `Warning`, and `Error`. For consistency and to allow backwards-compatibility to developers who may have provided these arguments positionally, can you make `title` the **last** argument in all of these classes? Thanks!

**Comment by abidlabs** [comment]
Changes look good, thanks @ABucket. I tested this out and I think it would be better if the title did _not_ support HTML, just a standard string. I'll go ahead and make that change and we can merge this in

**Review by abidlabs — APPROVED** [review]
LGTM! test code:

```py
import gradio as gr
import time

def test():
  time.sleep(1)  
  gr.Info("some info", title="new info")
  time.sleep(1)  
  gr.Warning("some warning", title="new <i>warning</i>")
  time.sleep(1)  
  raise gr.Error("some error", title="new error")

# def test():
#   time.sleep(1)  
#   gr.Info("some info")
#   time.sleep(1)  
#   gr.Warning("some warning")
#   time.sleep(1)  
#   raise gr.Error("some error")

with gr.Blocks() as demo:
  demo.load(test, None, None)

demo.launch()
```

**Review by abidlabs — APPROVED** [review]
Great PR, thanks again @ABucket!

**Pull request merged**
