### PR TITLE
Add styles to gallery component

### PR DESCRIPTION
**Pull request by dawoodkhan82**
# Description
- Adds ability to specify columns + rows of the gallery grid
- Adds ability to specify `object-fit` css variable for thumbnail images. This might be too specific, so open to feedback on whether we should include this. But it was requested, so thought I would add it to this PR

Please include: 
* relevant motivation
* a summary of the change 
* which issue is fixed. 
* any additional dependencies that are required for this change.

Closes: #3385

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have added a short summary of my change to the CHANGELOG.md
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Review by pngwn — CHANGES_REQUESTED** [review]
We can't remove `grid` right now as that would be a breaking change. Is there a way to add the new functionality while keep `grid`?

**Comment by dawoodkhan82** [comment]
@pngwn good point. `grid` is essentially number of columns, i guess we could leave it named as grid and still have `grid_rows` and `object-fit` as new style params.

**Comment by abidlabs** [comment]
I find the name `grid` very confusing for this parameter. The parameters `rows` and `columns` are more intuitive, but since we've already released with `grid`, we need to keep it for backwards compatibility. How about we start a deprecation process:

* Let's create parameters `rows` and `columns` 
* Let's keep the `grid` parameter, and if a user provides it, then it should be mapped to `columns` (but a warning should be raised saying that the parameter has been renamed to `columns` and it will be deprecated in the future
* In the docstring for `grid`, we should also note that it's been renamed to `columns`

**Comment by dawoodkhan82** [comment]
@pngwn good to merge?

**Review by pngwn — APPROVED** [review]
Looks good!

**Pull request merged**
