### PR TITLE
Restore Interpretation, Live, Auth, Queueing

### PR DESCRIPTION
**Pull request by aliabid94**
Interpretation, Auth, Live restored in format of blocks. Also included:
- Setting False to a Row or Column hides that panel of components.

Note: 
- There is currently no "blocker" from submitting while a request is in progress. Also applies to changes in live mode.
- Currently no loading animation on submit, or updates when queued.
- @pngwn some issues:
  - for some components, on:change events seem to fire with the "pre-change" value of the component. For example, with the Radio element in calculator_live/run.py, if you change from 'add' to 'subtract', it will trigger the on:change but use the value 'add'.  
  - with debouncing, it is possible that I type in an input field and click submit very quickly, and the submission does not take in the latest value of input field.

### CODE REVIEW

**Comment by abidlabs** [comment]
Fixed the formatting, but frontend "functional-tests" are failing @aliabid94

**Comment by abidlabs** [comment]
Would be good to close #906 as part of this if possible

**Comment by abidlabs** [comment]
Generally looks good to me. However, there are some issues that I noticed:
* Clear button does not work when `live=True`
* Clear button does not work when `interpet="default"` 
* In general, the clear button seems to be a bit buggy actually -- doesn't work for image examples like `demo\image_classifier\run.py` for example
* Interpretation doesn't seem to work for textbox. See `demo\gender_sentence_default_interpretation\run.py`
* Multiple tests are not passing because presumably we changed the config -- pls take a look

**Comment by aliabid94** [comment]
Fixed above issues

**Pull request merged**
