### PR TITLE
Ensure all upload components have consistent upload regions.

### LINKED ISSUE #6503: [ImageEditor]- allow users to drag an image to upload (maybe also click)
- [ ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

**Describe the solution you'd like**  

**Additional context**

### LINKED ISSUE #8652: The drop area is too restricted in Image
using Image as input, one can drop a file to upload only in the middle of the component. Ideally the entire Image area should take the drop. 

Screen Shot 2024-06-26 at 17 10 36

### PR DESCRIPTION
**Pull request by pngwn**
## Description

Adds click + drag to upload for the `ImageEditor` and gives all upload components a more consistent UX.

I extended the hit region for the `ImageEditor` beyond the canvas size to ensure there is no unexpected behaviour. Clicking is generally pretty safe with regions of this size but dragging can be annoying (especially with a trackpad). Instead of being limited to the canvas, the hit region stretches the whole width of the container, starts at the very top of the container and extends down to the bottom of the canvas container. The screenshot below illustrates this.

Test with this:

```py
import gradio as gr

with gr.Blocks() as demo:
    audio = gr.Audio(label="Audio")
    file = gr.File(label="File")
    image = gr.Image(label="Image")
    video = gr.Video(label="Video")
    im_edit = gr.ImageEditor(label="Image Editor")
    model3d = gr.Model3D(label="3D Model")

if __name__ == "__main__":
    demo.launch()
```

Demo:

https://github.com/user-attachments/assets/b17d5f16-814b-43f3-b390-fc9299eb2f0a

New Hit regions visualised:

Screenshot 2024-07-16 at 12 59 01
Screenshot 2024-07-16 at 12 59 28
Screenshot 2024-07-16 at 13 00 02

Closes: #6503
Closes: #8652.
Closes: https://github.com/gradio-app/gradio/issues/8788

### CODE REVIEW

**Comment by abidlabs** [comment]
@pngwn for the ImageEditor, I'm seeing the row of buttons floating in the middle of the component instead of sticking the bottom:

image

```py
import gradio as gr

with gr.Blocks() as demo:
    im_edit = gr.ImageEditor(label="Image Editor")

if __name__ == "__main__":
    demo.launch()
```

**Comment by pngwn** [comment]
Yeah I'm debugging the floaty buttons. The actual issue is that the height is being stretched for some reason. 

Will see if I can add the dotted border too.

**Comment by pngwn** [comment]
Okay should be fixed now!

**Review by abidlabs — APPROVED** [review]
Nice @pngwn! The drag-drop and upload behavior looks great. 

One nit: when you upload a tall image in the ImageEditor and then clear it, the ImageEditor keeps the height of that image instead of snapping back to the original size. Not a big deal but just wanted to point it out in case its unintentional

**Comment by lllyasviel** [comment]
hi how can i install nightly version to test? is there any whl that does not require build?

**Comment by pngwn** [comment]
We will release early next week.

**Comment by lllyasviel** [comment]
unfortunatly this will make color picker broken
now I cannot draw in any colors other than the default red color
test with

```
import gradio as gr
import time


def sleep(im):
    time.sleep(5)
    return [im["background"], im["layers"][0], im["layers"][1], im["composite"]]


def predict(im):
    return im["composite"]


with gr.Blocks() as demo:
    with gr.Row():
        im = gr.ImageEditor(
            type="numpy",
            crop_size="1:1",
        )
        im_preview = gr.Image()
    n_upload = gr.Number(0, label="Number of upload events", step=1)
    n_change = gr.Number(0, label="Number of change events", step=1)
    n_input = gr.Number(0, label="Number of input events", step=1)

    im.upload(lambda x: x + 1, outputs=n_upload, inputs=n_upload)
    im.change(lambda x: x + 1, outputs=n_change, inputs=n_change)
    im.input(lambda x: x + 1, outputs=n_input, inputs=n_input)
    im.change(predict, outputs=im_preview, inputs=im, show_progress="hidden")

if __name__ == "__main__":
    demo.launch()
```

codes from https://www.gradio.app/docs/gradio/imageeditor

**Comment by pngwn** [comment]
Oh this is weird. Will take a look. 

Thanks for testing!

**Pull request merged**
