### PR TITLE
Fix Chatbot, Dataframe, Markdown custom components

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Closes: #8309

You can verify this works by templating off of DataFrame or Chatbot and making the following modifications to `@gradio/markdown` in node_modules.

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Do you think it would make sense to add a test to ensure all of our core components can be used as templates for custom components?

**Comment by pngwn** [comment]
I think to test this we would have to run dev or build after generating them and this process is quite slow, so this would add a substantial amount of time to CI. Open to any suggestions to speed it up though, it would be nice to have some kind of check.

**Comment by freddyaboulton** [comment]
Yes a CI test would make sense. I tried to add one in #6715 but it would not work in CI. @pngwn is right though that it would be really slow to test all core components. Maybe we can create a giant custom component directory and launch a kitchen sink style demo. 

@pngwn let me know if this particular change looks good though.

**Review by pngwn — APPROVED** [review]
Look great! Thanks @freddyaboulton!

**Comment by freddyaboulton** [comment]
Thank you @pngwn 🙏

**Pull request merged**
