### PR TITLE
Add fullscreen mode to `gr.Chatbot`

### PR DESCRIPTION
**Pull request by hannahblair**
## Description

Adds a full screen mode to chatbot using the `maximize` and `minimize` icons, similar to what we have for gr.Gallery.

Q: Should `True` or `False` be the default? 

Another note, the original issue from @hysts was about changing the size of the chatbot area and making it resizeable, but @abidlabs suggested this full screen mode as an alternative. Do we think this is sufficient? 

Closes: #8240 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by hysts** [comment]
I tried to run this, but it didn't seem to work.

```python
import gradio as gr


def fn(message, history):
    return message


demo = gr.ChatInterface(fn=fn, chatbot=gr.Chatbot(allow_fullscreen=True))
demo.launch()
```

> Another note, the original issue from @hysts was about changing the size of the chatbot area and making it resizeable, but @abidlabs suggested this full screen mode as an alternative. Do we think this is sufficient?

Well, it's nice to be able to show the chat area in full screen, but I think this PR is a bit different from what I had in mind.
I couldn't check how the full screen view of chat component looks like, so maybe I'm missing the point, but I want to take screenshots of Chat Spaces, including the outside of the chat area. Users often put the model name and a short description at the top of the Space, and I want to include them in the screenshot as well.

**Comment by abidlabs** [comment]
Same, I didn't see any maximize/minimize icons when using `gr.Chatbot` directly, or with @hysts's example.

image

Upon further reflection, I think this issue is a bit tricky to implement because we would need both the input textbox *and* the Chatbot component itself to be maximized to provide a useful DX on mobile. Is that possible? Perhaps this would need to be a parameter in `gr.ChatInterface`? 

@hysts I'm not sure what kind of UI you are thinking of -- the title of a chatbot could be arbitrarily connected to the chatbot so I'm not sure how we could maximize both. Is there a specific Space you have in mind? Perhaps we could look at how to improve the UI of that space specifically. Otherwise, we might just want to table this issue.

**Comment by hysts** [comment]
I'm not sure if it's easy or possible, but the UI I was thinking of is adding this little triangle thing in the bottom right corner to the `gr.Chatbot` so users can adjust the height of the chat area.

**Comment by abidlabs** [comment]
I think we can go ahead and close this @hannahblair?

**Comment by abidlabs** [comment]
Closing for now @hannahblair

**Pull request closed without merging**
