### PR TITLE
Clamps values for typeable slider input when out of range

### PR DESCRIPTION
**Pull request by dawoodkhan82**
# Description
Shows warning popup on slider textbox when value is out of range

https://user-images.githubusercontent.com/12725292/193510091-e8fa212e-91a9-40ae-a37d-4b12a63bd963.mov

Please include: 
* relevant motivation
* a summary of the change 
* which issue is fixed. 
* any additional dependencies that are required for this change.

Closes: #2371 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by dawoodkhan82** [comment]
TODO: Stop from submitting values out of range.

**Comment by pngwn** [comment]
I think it would be better to just clamp the value as it requires less effort from the user, which would also stop the form from submitting the wrong value. 
- if > max set to max
- if < min set to min

Something like this will do it:

```js
const clamp = (num, min, max) => Math.min(Math.max(num, min), max);
```

I think setting the min/max on the input (as this PR does) is a good idea too.

**Comment by abidlabs** [comment]
@dawoodkhan82 and I chatted on Friday about clamping and our initial concern was that someone might be in the process of typing out a larger value and the "intermediate value" could get clamped if it is lower than the slider minimum. But if the clamping only happens if a user unfocuses from the typing box, then it should be fine

**Comment by abidlabs** [comment]
Side note: given https://github.com/gradio-app/gradio/pull/2329#issuecomment-1265434011, we may want to give users a way to disable the typeable box.

**Comment by apolinario** [comment]
I also agree with clamping - if we can find a good UX for it - the clamping after focus only sounds good to me) - as just a warning may not be enough if someone is deliberately interested in going over the application limits

**Comment by dawoodkhan82** [comment]
Updated so that on blur (input box is unfocused), the value is set to the min or max when typeable value is out of range 


https://user-images.githubusercontent.com/12725292/193939053-2115fb55-c6dc-4e2b-9ea3-2fad0724f36b.mov

**Review by pngwn — APPROVED** [review]
looks great!

**Review by abidlabs — APPROVED** [review]
Good stuff! Let's merge it in?

**Pull request merged**
