### PR TITLE
ensure translations for audio work correctly

### PR DESCRIPTION
**Pull request by hannahblair**
## Description

Initialises i18n in `preview.js` and fixes Audio translation. 

Closes: #(issue)

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Review by pngwn — APPROVED** [review]
Looks great! Thanks @hannahblair!

**Comment by abidlabs** [comment]
@hannahblair I'm still seeing this with the microphone:

image

**Comment by abidlabs** [comment]
Hmm hard reloading didn't solve it for me. What about in the Deployed Space? Here's what I see:

image

**Review by pngwn — CHANGES_REQUESTED** [review]
This needs to be in curlies:

```
$_('audio.stop_recording')
```

->

```
{$_('audio.stop_recording')}
```

**Comment by pngwn** [comment]
and my bad i missed this.

**Comment by abidlabs** [comment]
Working for me now, thanks @hannahblair @pngwn!

I did a quick search for `$_(` in the codebase, and I saw that this file also has the same syntax. Do curly brackets need to be added here as well? https://github.com/gradio-app/gradio/blob/4b58ea6d98e7a43b3f30d8a4cb6f379bc2eca6a8/js/app/src/Embed.svelte

**Review by pngwn — APPROVED** [review]
Nice.

**Review by abidlabs — APPROVED** [review]

**Pull request merged**
