### PR TITLE
Allow selecting texts in dataframe cells

### PR DESCRIPTION
**Pull request by shubhamofbce**
## Description
I have used user-select css property to allow users to select texts in dataframe cells. This will fix the issue where users where not able to copy text from output(non-editable) cells of dataframe.

Closes: #6086 
Related: #6981 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

https://github.com/gradio-app/gradio/assets/45156638/8c442fb2-5aba-4a13-82e3-7888d39b468a

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by shubhamofbce** [comment]
@abidlabs What do you suggest, I should keep the show_copy_button default to false or true.
I was also not able to copy the output cells in the dataframe as reported, so true makes more sense to me. What do you suggest ??

**Comment by abidlabs** [comment]
Hi @shubhamofbce, thanks for this very interesting PR. 

The problem with adding a copy button to each cell is that it becomes very cluttered. The better approach would be to simply allow users to select any cell and copy it using ctrl/cmd+C as they would intuitively try to do. This should not require any new parameters and would keep the UI clean.

Could you refactor this PR so that you can just copy cell values by using the standard copy shortcut?

**Comment by shubhamofbce** [comment]
Sure, I can do that as well. I will make the required changes.

**Comment by shubhamofbce** [comment]
@abidlabs I have updated the PR, now we can select data normally from any dataframe cells.

**Comment by abidlabs** [comment]
LGTM @shubhamofbce! Thanks for this PR.

I agree it closes #6086 as this allows copying from individual cells, but it doesn't close #6981 as that was related to copying entire dataframes. I think the ideal UX for copying the entire dataframe would be an excel-like UX where you could select multiple cells (by holding the shift key) and then then copying them all using the standard keyboard shortcuts.

**Review by abidlabs — APPROVED** [review]

**Comment by shubhamofbce** [comment]
@abidlabs Thanks for the quick feedback.

**Pull request merged**
