### PR TITLE
Lite: Use Vite's library mode to make the bundle importable

### PR DESCRIPTION
**Pull request by whitphx**
## Description

With this change, the `@gradio/lite` package can be imported from other projects as below.
```ts
import { create } from "@gradio/lite";
import "@gradio/lite/style.css";
```

Vite's library-mode is now used to package it as a production build,
as I found a workaround to use the library mode in a way compatible with Gradio-lite's static file structure.

---
Also, many lite-specific files have been put into `js/app` such as `tsconfig.lite.config` in this PR and it's getting messy, so I will move them to `js/lite`, while I put them there at first because I wanted to reuse the tuned build config `vite.config.ts`.
I will do it in a separate PR after this as it may make big diffs.

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests & Changelog

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

1. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`
  
1. Unless the pull request is labeled with the "no-changelog-update" label by a maintainer of the repo, all pull requests must update the changelog located in `CHANGELOG.md`:

Please add a brief summary of the change to the Upcoming Release section of the `CHANGELOG.md` file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

### CODE REVIEW

**Comment by pngwn** [comment]
I'll test this properly next week but I don't think library mode is going to suitable here because it will bundle everything into a single file. I know you've handled the python assets but there are many other that should be split too.

**Comment by whitphx** [comment]
Thanks, do you have some suggestion on what can be the alternative of the library mode?

**Comment by whitphx** [comment]
Also, it would be helpful if you find the actual examples of such files when you test it.
We may find the direction from it.

**Comment by whitphx** [comment]
@pngwn Thank you.
I think, while lib mode inlines media assets such as `*.png|jpg` into JS code, it keeps JS chunks split and outputs a CSS file separately as well, while the CSS is bundled into a single `style.css` file.
Did the lazy-loading you wrote mean something different from `await import()` in the JS files, or is the media asset inlining critical?

At least, this very simple app is working with the lib-mode bundle, and looks like the JS chunks are lazily loaded.
CleanShot 2023-08-21 at 20 16 39@2x

**Comment by pngwn** [comment]
@whitphx It honours dynamic imports as expected but it doesn't chunk CSS in the same way and it doesn't preload CSS + JS together as it should. Only app mode does this.

**Comment by whitphx** [comment]
@pngwn Thank you,

> but it doesn't chunk CSS in the same way and it doesn't preload CSS + JS together as it should.

Yes, I understand those features are omitted in the lib mode, but why are they needed? Is it just for performance, or does something become broken?

FYI, the following code (copied from https://www.gradio.app/docs/button) including components that have split CSS chunks (`Button` and `Image`) still worked on the Gradio-lite bundled in the library mode that has a single bundled `style.css`.
```python
import gradio as gr
import os


def combine(a, b):
    return a + " " + b


def mirror(x):
    return x


with gr.Blocks() as demo:

    txt = gr.Textbox(label="Input", lines=2)
    txt_2 = gr.Textbox(label="Input 2")
    txt_3 = gr.Textbox(value="", label="Output")
    btn = gr.Button(value="Submit")
    btn.click(combine, inputs=[txt, txt_2], outputs=[txt_3])

    with gr.Row():
        im = gr.Image()
        im_2 = gr.Image()

    btn = gr.Button(value="Mirror Image")
    btn.click(mirror, inputs=[im], outputs=[im_2])


if __name__ == "__main__":
    demo.launch()
```
CleanShot 2023-09-18 at 20 09 21@2x

**Comment by pngwn** [comment]
They are not only needed for performance but also avoid flashes of unstyled content as the vite preload ensures that CSS is loaded and mounted before instantiating the JavaScript.

**Comment by whitphx** [comment]
@pngwn 

I see. (It's https://vitejs.dev/guide/features.html#css-code-splitting, right?)

I think it's not a problem in this case because
* CSS is not chunked and all styles are loaded as a single file at init, so the evaluation timing control on the async-loaded JS modules is not necessary in the lib mode.
* The single big CSS file `style.css` (which is 1.5MB) may hit the performance and I understand it's a problem in usual cases, but in the case of Gradio-lite, loading Pyodide and necessary wheel files is dominant and loading `style.css` finishes during  such other file loads in practice.
  * If we are sensitive to the possible FOUC that can happen if loading `styles.css` doesn't finish before other initializations, we can write JS code to wait it in another PR.

So I think using the lib mode to make Gradio-lite importable as an ESM is beneficial in balance to these concerns.

**Comment by pngwn** [comment]
But we want the files to be chunked for performance reasons. Just because some things are slow doesn't mean we should make everything slow.

**Comment by pngwn** [comment]
The solution I proposed does not prevent us from importing this in esm. 

We are going around in circles discussing this. You can close this PR, I'll take care of it shortly.

**Comment by whitphx** [comment]
@pngwn 
> The solution I proposed does not prevent us from importing this in esm.

You mean we can make the bundle ESM-importable in app mode? Sorry I didn't know it and missed something. Can you tell me how?

> We are going around in circles discussing this

No no, I think we are getting deeper understanding on the topic and my latest question above (how to make the app an ESM with the app mode) may finally solve everything.

**Comment by whitphx** [comment]
> But we want the files to be chunked for performance reasons. Just because some things are slow doesn't mean we should make everything slow.

Well, can't [my prev comment](https://github.com/gradio-app/gradio/pull/4910#issuecomment-1725102351) be an answer to this? Let me break it down;
* I don't mean we should make everything slow, (while I don't know what "everything" here exactly means...)
  * The lib mode is only applied to Gradio-lite. No effect on the normal Gradio.
  * Even about Gradio-lite,
    * The JS files are still chunked.
    * CSS is the ONLY drawback unfortunately, but _I think_ its performance flaw is not a problem **in practice** due to the reason written above.

**Comment by whitphx** [comment]
While everything is solved if app-mode can make `@gradio/lite` ESM-importable,
just in case, what about aaf1a40?

With the sample code of https://github.com/gradio-app/gradio/pull/4910#issuecomment-1723196410, the loaded resources were like below. The lists are sorted in size. It shows that the files are loaded as chunks and there is no exceptionally huge chunk.

All files:
CleanShot 2023-09-20 at 19 16 55@2x

JS files:
CleanShot 2023-09-20 at 19 18 22@2x

**Comment by pngwn** [comment]
Closing for now, this is pretty stale. We can reopen or open a new PR when we have an approach.

**Pull request closed without merging**
