### PR TITLE
Add section to show W&B reports in Gradio apps

### PR DESCRIPTION
**Pull request by scottire**
# Adds some documentation to embed W&B reports within gradio

Closes: #2757 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by freddyaboulton — APPROVED** [review]
Thanks for the contribution @scottire !!

Can you add an entry to `CHANGELOG.md` Happy to merge once that's in!

**Review by aliabd — CHANGES_REQUESTED** [review]
Thanks for the contribution @scottire. 

Something funny is happening with the guide, our markdown interpreter is trying to actually iframe the page in your python code. Please replace the `<` key with `&lt;` and the `>` key with `&gt;`

This will fix it from showing up like this: 

Screen Shot 2023-01-18 at 9 02 48 AM

To: 

Screen Shot 2023-01-18 at 9 11 38 AM

**Comment by abidlabs** [comment]
Friendly ping @scottire, would you be up for making these changes so we can go ahead and merge in this PR? Thanks!

**Comment by abidlabs** [comment]
This PR is quite stale (our CI as well as the names of the guides have changed) so it might just be easiest to make a new PR with @scottire's changes and merge that in. @scottire would you be up for that? Or @aliabd would you be able to take it?

**Comment by aliabd** [comment]
I will just take it. Will close this PR and make the changes on a new one.

**Comment by scottire** [comment]
Sorry for missing all of these friendly pings. Thanks for running with this

**Pull request closed without merging**
