### PR TITLE
Add a `settings` link to the footer with i18n options & pwa instructions

### PR DESCRIPTION
**Pull request by abidlabs**
Adds a new Settings link in the footer:

image

Clicking on the Settings link opens up a page that allows toggling the theme, localization, and pwa installation instructions:

image

While I was at it, I also went through and filled in many of the missing entries in our i18n translation files (thanks Claude!) in https://github.com/gradio-app/gradio/pull/10254/commits/35f8706558419bd48b2f7c190cc4cc04916ce60f.

Closes: https://github.com/gradio-app/gradio/issues/655, Closes: https://github.com/gradio-app/gradio/issues/785

### CODE REVIEW

**Review by whitphx — APPROVED** [review]
I tested it locally and it LGTM, thanks!

**Comment by aliabid94** [comment]
where are all the json language changes coming from?

**Comment by aliabid94** [comment]
Visual feedback:

- Setting icon looks strange. I think the whole icon should just be gray, and lighter in tone.
- The footer gets bunch up on phone-size screens. Consider hiding on smaller screen?
Screenshot 2024-12-30 at 12 04 58 PM

- Think we can remove the language text, its self explanatory and takes up space. "Gradio automatically detects the language of your browser. You can also choose a language manually:

**Review by aliabid94 — APPROVED** [review]
lgtm! left some visual comments

**Comment by abidlabs** [comment]
> Setting icon looks strange. I think the whole icon should just be gray, and lighter in tone.

Made it entirely gray. Lighter looked off to me, so kept the same shade of gray though.

> The footer gets bunch up on phone-size screens. Consider hiding on smaller screen?

Good catch. I actually think it makes more sense to hide the API link on mobile. Here's what it looks like now on mobile:

image

**Comment by abidlabs** [comment]
> Think we can remove the language text, its self explanatory and takes up space. "Gradio automatically detects the language of your browser. You can also choose a language manually

Done!

**Pull request merged**
