### PR TITLE
Chatbot bug fixes

### PR DESCRIPTION
**Pull request by dawoodkhan82**
## Description
Fixes the chatbot image bugs @yvrjsharma reported.
- image sizing
- single example not showing properly
- webp images should show a preview

Screenshot 2024-09-26 at 10 44 58 AM
Screenshot 2024-09-26 at 10 43 53 AM

Closes: #(issue)

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by yvrjsharma** [comment]
Thanks @abidlabs for checking on your machine. Strangely, I am still experiencing all the same issues on Google Colab. However, when I build the code locally on my machine, the sizing issues seem to be resolved.

I'm still encountering the following issues:
- Preview of a `.webp` image is not available when I use it as an example.
- When I upload a `.webp` image, the chatbot doesn't display the image for me (unlike a `.jpg` or a `.png` image).
image
- I am unable to remove error messages from the chat window after clicking the cross button.
image

**Comment by yvrjsharma** [comment]
This seemed like a Windows issue as I am able to use a `.webp` image successfully as an example and when uploaded to the chatbot directly. Thanks for helping out with suggestions on Slack @abidlabs!

**Comment by dawoodkhan82** [comment]
Fixed all the issues mentioned. Except the error one, it works fine with chatbot but for some reason not in chat interface. The error relates to the "file not being uploaded by user" so maybe something with allowed paths. Any ideas @abidlabs

**Comment by abidlabs** [comment]
Design changes look great @dawoodkhan82! Looking into the chat interface processing bug

**Review by abidlabs — APPROVED** [review]
LGTM @dawoodkhan82!

**Comment by abidlabs** [comment]
I'll go ahead and merge this in @dawoodkhan82!

**Pull request merged**
