### PR TITLE
Await gather_data to fix queue getting stuck

### PR DESCRIPTION
**Pull request by FarukOzderim**
Tries to fix #2374

### CODE REVIEW

**Comment by FarukOzderim** [comment]
@freddyaboulton could you test the queue with the latest changes, whether if it gets stuck or not?

https://huggingface.co/spaces/gradio-pr-deploys/pr-2420-all-demos

**Comment by freddyaboulton** [comment]
@FarukOzderim For sure! Will test tomorrow. Thank you for the help 😊 

One question though - shouldn’t we await gather_data before starting process_event in the background? If we don’t, I think the same problem  can happen where the background function sends the ‘send_data’ message when gather_data coroutine is running.

**Comment by FarukOzderim** [comment]
I don't think that will happen.

Because if event.data is None that means gather_data was not awaited for that event, ie. It came into an empty queue.

If gather_data is awaited for that event it means event.data is not None, so no network call be realized.

Advantage of this is, process and gather_data runs concurrently.

**Comment by freddyaboulton** [comment]
@FarukOzderim I think this is still getting stuck. I have tried twice and the script is not able to complete. This is what I'm running.

```python
import asyncio
from datetime import datetime
import json
import random
import time
from typing import List
import websockets
import gradio as gr
import pandas as pd
import argparse

FN_INDEX_TO_DATA = {
    "image": (0, gr.media_data.BASE64_IMAGE),
    "text": (1, "A longish text " * 15),
    "audio": (2, gr.media_data.BASE64_AUDIO),
    "video": (3, gr.media_data.BASE64_VIDEO)
}


async def get_prediction(host):
    async with websockets.connect(host, timeout=5) as websocket:
        start = time.time()
        name = random.choice(["image", "text", "audio", "video"])
        fn_to_hit, data = FN_INDEX_TO_DATA[name]
        while True:
            raw_msg = await websocket.recv()
            msg = json.loads(raw_msg)
            msg = msg["msg"]
            if msg == "queue_full":
                return
            elif msg == "send_data":
                await websocket.send(json.dumps({'data': [data], "fn_index": fn_to_hit}))
            elif msg == "estimation":
                pass
            elif msg == "process_starts":
                pass
            elif msg == "process_completed":
                end = time.time()
                duration = end - start
                return {"fn_index": name, "duration": duration}


async def main(host, n_results=1000):
    results = []
    while len(results) < n_results:
        print(f"N results {len(results)}")
        batch_results = await asyncio.gather(*[get_prediction(host) for _ in range(20)])
        for result in batch_results:
            if result:
                results.append(result)

    data = pd.DataFrame(results).groupby("fn_index").agg({"mean"})
    data.columns = data.columns.get_level_values(0)
    data = data.reset_index()
    data = {"fn_index": data["fn_index"].to_list(), "duration": data["duration"].to_list()}
    json.dump(data, open(f"{datetime.now()}_results.json", "w"))
    return data


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Upload a demo to a space")
    parser.add_argument("host", type=str, help="Name of demo to upload")     
    args = parser.parse_args()
    out = asyncio.run(main(args.host))
    print(out)
```

**Comment by freddyaboulton** [comment]
Thank you @FarukOzderim ! Closing for now but we might revisit again in the future.

**Pull request closed without merging**
