### PR TITLE
Fix Chatbot Examples Error

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Fixes:
- Chatbot examples were given "assistant" role instead of "user" as reported by @hysts
- Clear button was not working properly with chatbot examples 
- Undo button was not working when there was only one message in the chat

Added e2e tests

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by freddyaboulton** [comment]
The e2e tests pass locally for me - `pnpm test:browser -g "test_chatinterface_examples`

**Review by aliabid94 — APPROVED** [review]
LGTM!

**Review by abidlabs — APPROVED** [review]
LGTM nice one @freddyaboulton!

**Comment by abidlabs** [comment]
will merge in in case there are conflicts with @aliabid94's PR.

**Comment by freddyaboulton** [comment]
Thanks all!

**Pull request merged**
