### PR TITLE
Fix Chatbot Multimodal Examples

### PR DESCRIPTION
**Pull request by dawoodkhan82**
## Description
Fixes issue with image examples being too big. Also adds support for video and audio in `multimodaltextbox` examples, instead of just showing the filepath.

Main:
Screenshot 2024-07-24 at 1 53 38 PM

This PR:
Screenshot 2024-07-24 at 1 53 07 PM

Closes: #8834

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Can we create a version of https://huggingface.co/spaces/merve/llava-interleave with this pr installed, will make it easier to test

**Comment by dawoodkhan82** [comment]
@abidlabs https://huggingface.co/spaces/dawood/llava-interleave

Can change the layout if you have feedback.

**Comment by abidlabs** [comment]
The examples still look huge (and the chat interface tiny) to me? 

image

I think the examples should be like 1/4 of the height

**Comment by gray311** [comment]
9920217c61961d0f59f36f2e9b9f8b4e
I updated to gradio-4.39.0 but it looks like video still only shows paths!

**Comment by dawoodkhan82** [comment]
@gray311 can you try installing from the build in this PR and try again?
pip install https://gradio-builds.s3.amazonaws.com/33d6b5456a6606e9b08fb5aeb6e6d71fc78a9c6e/gradio-4.39.0-py3-none-any.whl

**Pull request merged**
