### PR TITLE
Fixing issues

### LINKED ISSUE #745: Dataframe Component examples are not working
### Describe the bug

Examples paramter for Dataframe component is not showing up in the app. Even for tax calculator app in the docs page is not showing dataframe examples.

### Reproduction

https://colab.research.google.com/drive/1DV1J45I-pkbwPEh0e6xVOkPgtLaXn3Zx

### Screenshot

image

### Logs

_No response_

### System Info

```shell
2.8.5
```

### Severity

annoyance

### LINKED ISSUE #767: Webcam input flips after taking picture
### Describe the bug

When I click the camera button, my image is flipped

### Reproduction

See https://huggingface.co/spaces/osanseviero/remove-bg-webcam

Code

```python
import os
os.system('pip install gradio===2.8.6')

import gradio as gr

gr.Interface.load(
  "spaces/eugenesiow/remove-bg", 
  inputs=[gr.inputs.Image(label="Input Image", source="webcam"),],
).launch()
```

### Screenshot

_No response_

### Logs

_No response_

### System Info

```shell
Spaces, Gradio 2.8.6
```

### Severity

annoyance

### PR DESCRIPTION
**Pull request by aliabid94**
Fix #767 webcam flip - what was the reason for putting the horizontal flip in the first place? @pngwn
Also 745 (incomplete). Added preview for dataframe example. However clicking still does not load the dataframe.

Also hid null values in dataframe.

### CODE REVIEW

**Comment by aliabid94** [comment]
@pngwn while I was trying to fix #745 and came across an issue that output dataframes don't seem to change after submitting after the first time. try the filter_records demo for example. Can you take a look?

**Comment by abidlabs** [comment]
@dawoodkhan82 can confirm but I think the flip was added because the Video upload input component was flipping videos

**Comment by dawoodkhan82** [comment]
> Fix #767 webcam flip - what was the reason for putting the horizontal flip in the first place? @pngwn Fix #745 (incomplete). Added preview for dataframe example. However clicking still does not load the dataframe.
> 
> Also hid null values in dataframe.

Added the flip, because the camera was mirrored

**Comment by aliabid94** [comment]
The camera is mirrored when the scaleX(-1) CSS is applied, and gone when I remove it. Is it different in different browsers / on mobile? @dawoodkhan82

**Comment by dawoodkhan82** [comment]
> The camera is mirrored when the scaleX(-1) CSS is applied, and gone when I remove it. Is it different in different browsers / on mobile? @dawoodkhan82

Yeah for me the scaleX(-1) CSS fixes the mirroring. Can you try opening your photobooth camera app on your mac. Are they identical without the scaleX(-1) CSS?

**Pull request merged**
