### PR TITLE
add status tracker to md and html

### LINKED ISSUE #1985: HTML block does not display spinner
### Describe the bug

Most blocks when they are used as output like Textbox display an orange spinner indicating that the model is running. 
For HTML blocks no such spinner is available which from a UX perspective is very confusing if the output is only HTML. 

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

See https://huggingface.co/spaces/simonduerr/3dmol.js as demo

### Screenshot

_No response_

### Logs

```shell
UX bug
```

### System Info

```shell
using gradio 3.1.4
```

### Severity

annoying

### LINKED ISSUE #2473: html and markdown don't have a loading indicator
### Describe the bug

They should have the loading indicator

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

-

### Screenshot

-

### Logs

```shell
-
```

### System Info

```shell
-
```

### Severity

annoying

### PR DESCRIPTION
**Pull request by pngwn**
# Description

Adds status tracker to Markdown and HTML components in order to give end users feedback that the a response is pending.

Closes #2473.
Closes #1985 

Can be tested with the following snippet:

```py
from time import sleep

import gradio as gr


def fn():
    sleep(3)
    return [
        '<div style="text-align: center"><h1>Hello</h1><h2>Hello again</h2><p>hello to all of the people</p></div>',
        "# hello friends\n> who are you?",
    ]


with gr.Blocks() as demo:
    gr.Textbox()
    html = gr.HTML()
    md = gr.Markdown()
    demo.load(fn, inputs=None, outputs=[html, md])

if __name__ == "__main__":
    demo.launch()
```

Please include: 
* relevant motivation
* a summary of the change 
* which issue is fixed. 
* any additional dependencies that are required for this change.

Closes: # (issue)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by pngwn** [comment]
I'll let you in on a secret.

When i created that other issue i ticked this:

> I have searched the existing issues

But i didn't search the existing issues at all.

**Comment by ola13** [comment]
Thanks so much for working on this @pngwn! Any idea when this change will get deployed on spaces?

**Comment by abidlabs** [comment]
Hi @ola13 most likely this should be our tomorrow in gradio 3.5.1

**Comment by ola13** [comment]
Hi @abidlabs a quick question - how can I upgrade the version manually? Should I create a requirements file with the specified version? I rebooted my app and it seems it's installing gradio 3.1.3:
```
Collecting gradio==3.1.3
  Downloading gradio-3.1.3-py3-none-any.whl (5.6 MB)
  ```

**Comment by pngwn** [comment]
Yeah, this is a bug, will take a look.

**Comment by abidlabs** [comment]
@ola13 with regards to your question, you will need to update the `sdk_version` in the `README.md` file in the Space

**Comment by ola13** [comment]
Thanks @abidlabs!

**Pull request merged**
