### PR TITLE
add STL 3D model support

### PR DESCRIPTION
**Pull request by Mon-ius**
Since V4 supports adding .STL file in examples path which can render correctly in the box. There is no need to limit ".stl" file in the accepted upload list.

Example code:

```py
import numpy as np
import gradio as gr
import trimesh, os

def load_mesh(mesh_file_name):
    return mesh_file_name

print(
    os.path.join(os.path.dirname(os.path.dirname(__file__)), "dataset/1/output_0.stl")
)

T3D = gr.Interface(
    fn=load_mesh,
    inputs=gr.Model3D(label="3D Mesh File"),
    outputs=gr.Model3D(clear_color=[0.0, 0.0, 0.0, 0.0], label="3D Model"),
    examples=[
        [os.path.join(os.path.dirname(os.path.dirname(__file__)), "dataset/1/output_0.stl")],
        [os.path.join(os.path.dirname(os.path.dirname(__file__)), "dataset/2/output_0.stl")],
        [os.path.join(os.path.dirname(os.path.dirname(__file__)), "dataset/3/output_0.stl")],
    ],
    cache_examples=True,
)

T3D.launch(share=False)

```

Adding STL support can contribute a lot to 3D print industry, without extra convert, people can play more seamless 🤗  

For more details, see https://huggingface.co/spaces/MassiveDL/T3D

### CODE REVIEW

**Comment by freddyaboulton** [comment]
Thanks @Mon-ius ! I think this looks good to me! Tagging @dawoodkhan82 @hannahblair for quick review from them.

**Comment by Mon-ius** [comment]
Great! Some checks need external auth for vercel deploy failed, should not be a problem!

**Review by dawoodkhan82 — APPROVED** [review]
Nice! tested, and works. It would be great, if you can update the `model3D` demo to include a `.stl` example.

**Comment by Mon-ius** [comment]
@dawoodkhan82 No problem! I will update a new model3D demo with `.STL` format file 🤗

**Review by freddyaboulton — APPROVED** [review]
Thanks @Mon-ius ! I added the stl file to the existing model3D demo as opposed to creating a new one. Will merge once CI passes!

**Comment by Mon-ius** [comment]
@freddyaboulton Good Job! Cheers!

**Pull request merged**
