### PR TITLE
Issue #1160: Model 3D component not destroyed correctly

### PR DESCRIPTION
**Pull request by dawoodkhan82**
# Description

Please include: 
* relevant motivation
* a summary of the change 
* which issue is fixed. 
* any additional dependencies that are required for this change.

Closes: #1160

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by abidlabs** [comment]
I was able to actually reproduce this issue with our `demo/model3d/run.py` example, and the problem is not fixed by this PR. 

To reproduce the problem:
* Navigate to the `/model3d/` directory
* Make sure to delete the `gradio_cached_examples` folder if it exists
* Run `python run.py` 
* When the interface loads, click on one of the examples
* **Without pressing clear**, click on one of the other examples

For me, the second example does _not_ load. I'm perpetually stuck in this state:

image

**Comment by abidlabs** [comment]
Any update on this @dawoodkhan82?

**Comment by abidlabs** [comment]
Cool, this fixed it for me! @radames it would be great if you can confirm that it fixes it for you too!

**Comment by shankch** [comment]
Hello @abidlabs, I am facing the same problem now. When I run the first time , the 3d model output works, but when I submit again, the output shows "ERROR".  My app takes text as input and generates 3d model as output. Please fix this.

**Comment by dawoodkhan82** [comment]
> Hello @abidlabs, I am facing the same problem now. When I run the first time , the 3d model output works, but when I submit again, the output shows "ERROR". My app takes text as input and generates 3d model as output. Please fix this.

@shankch This should be fixed by https://github.com/gradio-app/gradio/pull/1939. Which should be released in version 3.1.4b. Can you give that a try?

**Pull request merged**
