### PR TITLE
A few dropdown fixes

### PR DESCRIPTION
**Pull request by dawoodkhan82**
# Description
Seems like there were some issues introduced with the dropdown, probably when changing switching to our current theming.

Fixes: 
active option bg color when keyboard arrows are used to hover over an option
checkmark next to option hides/unhides as expected
remove all icon is hid when no options are selected

Please include: 
* relevant motivation
* a summary of the change 
* which issue is fixed. 
* any additional dependencies that are required for this change.

Closes: #3140

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have added a short summary of my change to the CHANGELOG.md
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Review by freddyaboulton — APPROVED** [review]
Tested with `sentence_builder` in both light and dark mode and it fixes the issue!

Thanks @dawoodkhan82 !

**Comment by abidlabs** [comment]
Tested on my end and works well too!

**Review by abidlabs — APPROVED** [review]

**Comment by aliabid94** [comment]
lgtm! the text size and padding when the box is empty look a little off to me:
Recording 2023-02-07 at 13 44 05

if you wanna just patch in this PR, or maybe tackle later

**Comment by abidlabs** [comment]
> lgtm! the text size and padding when the box is empty look a little off to me:

I agree, although it looks like that was the case before this PR as well just FYI

**Comment by abidlabs** [comment]
Discussed with @dawoodkhan82 and he'll fix the size issue in another PR. Will get this in for 3.18

**Pull request merged**
