### PR TITLE
Processes `avatar_images` for `gr.Chatbot` and `icon` for `gr.Button` correctly, so that respective files are moved to cache

### PR DESCRIPTION
**Pull request by abidlabs**
Closes: https://github.com/gradio-app/gradio/issues/6329

Test with `chatbot_multimodal` demo

### CODE REVIEW

**Review by aliabid94 — APPROVED** [review]
LGTM. Seems like it would be cleaner to move `move_resource_to_block_cache` to be a `Block` method, instead of having to pass `self` everywhere it's called.

**Comment by abidlabs** [comment]
Thanks @aliabid94. That's a good idea, I'll make the change

**Comment by abidlabs** [comment]
I'll refactor it so that the `Block` class has its own `move_resource_to_block_cache()` instance method, but I'll also leave the original `move_resource_to_block_cache` method in `postprocessing_utils.py` for backwards compatibility for any custom components created in Gradio 4.2.0 or earlier.

**Comment by aliabid94** [comment]
>> I'll also leave the original move_resource_to_block_cache method in postprocessing_utils.py for backwards compatibility

Then have postprocessing_utils.move_resource_to_block_cache just call the block.move_resource_to_block_cache?

**Comment by abidlabs** [comment]
Made the refactor, and then also included a test using the `gradio_pdf` custom component that @freddyaboulton created to ensure backwards compatibility. Will merge after CI is green. Thanks for the review @aliabid94!

**Pull request merged**
