### PR TITLE
Simplifies format of Changelog

### PR DESCRIPTION
**Pull request by abidlabs**
Reduces the number of categories in the changelog to 4:

* new features
* bug fixes
* other changes
* breaking changes

This should make it easier for contributors to add changes in the right section, as well as clarify that documentation or website-related changes do not need to be included in the changelog.

### CODE REVIEW

**Review by pngwn — COMMENTED** [review]
Looks good to me! Do we need to update the action? I think it generates new sections when we clear the changelog?

**Review by pngwn — APPROVED** [review]
Awesome.

**Comment by freddyaboulton** [comment]
This deploy-pypi gh action is running this script: https://github.com/gradio-app/gradio/blob/main/scripts/format_release_notes.py which has the old section names.

**Comment by abidlabs** [comment]
Wait what, we have an action for this? I've always done it manually lol

**Pull request merged**
