### PR TITLE
Backend for optional labels

### PR DESCRIPTION
**Pull request by abidlabs**
Added a boolean parameter, `show_label` to every `Component`, based on our discussion in #946. Note that I've added it to every component instead of just the form components, to provide a more unified API across our components. 

We still need to add frontend support: if `show_label` is `True`, then the label should not be visible. However, we should still make it available for screen readers for accessibility purposes. @pngwn feel free to push to this branch direct.y.

Closes (the backend part of) #946

### CODE REVIEW

**Comment by abidlabs** [comment]
I still need to fix the tests but since that is a very manual process, want to make sure we are all good with this prop

**Comment by pngwn** [comment]
Then i think that needs to be changed as well. We can't do anything meanginful with `label`s for layout components for example or buttons. I think that made sense with the interface usecase but with the flexibility of blocks if becomes more problematic.

In the case of `Button`, we may well set the `label` as the button text but in that case we cannnot hide it for any reason either (we can only hide the whole button). This is why i think it should be a little more granular.

Could we not create a 'LabelledComponent' subclass that some components could extend from? Surely that would allow us to keep things clean while still having more granularity.

**Comment by abidlabs** [comment]
That should work! Will implement

**Comment by abidlabs** [comment]
@pngwn the backend is ready. I've created an `IOComponent` class that has methods and props specific to those components that can be used as inputs or outputs.

Feel free to merge or push to this branch.

**Pull request merged**
