### PR TITLE
Button default name

### PR DESCRIPTION
**Pull request by FarukOzderim**
# Description

Add a default button name since it was not looking good in default.

Before:
image

Now:
image

### CODE REVIEW

**Comment by abidlabs** [comment]
Looks good, I think this is a good change. The other alternative would be just to make a Button's value a required parameter, but this works as well. Let's get feedback from @gary149 or @pngwn as well.

**Comment by pngwn** [comment]
I think "Run" is a reasonable default, although the sole puprose of this button is to render some text, I don't think asking users to pass in a value is unreasonable. I'd be happy with either the default or making it required.

**Comment by gary149** [comment]
> Looks good, I think this is a good change. The other alternative would be just to make a Button's value a required parameter, but this works as well. Let's get feedback from @gary149 or @pngwn as well.

I think it makes more sense as a required param (so buttons always get the right wording), but no super strong opinion on it.

**Comment by pngwn** [comment]
Lets make it required then, seems reasonable.

**Comment by FarukOzderim** [comment]
If there is no strong opinion on this I would suggest we continue with default values.
Since we are supporting component shortcuts in the Blocks as well, and component shortcuts are initializing components with default values.

Check [demo](https://github.com/gradio-app/gradio/blob/main/demo/blocks_component_shortcut/run.py)

**Comment by pngwn** [comment]
The string shortcut is a good point. Lets merge this.

**Review by pngwn — APPROVED** [review]

**Pull request merged**
