### PR TITLE
Make `gr.Code` support `lines`, expand to fill entire element

### PR DESCRIPTION
**Pull request by space-nuko**
# Description

- `gr.Code` now supports `lines` like `gr.Textbox`
- `gr.Code` expands to fill the entire height of its wrapper

Closes: #3551, closes: #3528

Testcase:

```python
#!/usr/bin/env python

import gradio as gr

with gr.Blocks() as demo:
    with gr.Row():
        gr.Textbox("Focus me", interactive=True)
    with gr.Row():
        gr.Code("a = 42", language="python", interactive=True)
        gr.HTML("test<br>" * 40)
    with gr.Row():
        gr.Code("a = 42", language="python", interactive=True, lines=12)


demo.queue().launch(server_port=9876)
```

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by aliabd** [comment]
Great work @space-nuko! I tested this and it mostly works as expected, but i'm still seeing the behavior you describe in #3551 when using Interface (vs Blocks). Not sure why.. maybe some style elements are clashing.. Let's have @pngwn take a look as well.

**Comment by aliabd** [comment]
Unrelated, I noticed an issue where using `gr.Code.update()` sets `interactive=True` which it shouldn't, so pushed a commit that fixes that (for `Code` and also `BarPlot`)

**Comment by space-nuko** [comment]
> i'm still seeing the behavior you describe in https://github.com/gradio-app/gradio/issues/3551 when using Interface (vs Blocks)

Would you have a repro for that?

**Comment by space-nuko** [comment]
It's because of the `.unequal-height` class, which `gr.Interface` seems to add internally

Don't know if that should be made configurable?

**Comment by abidlabs** [comment]
@aliabid94 or @pngwn do you have any suggestions here? Or should we just merge this in for now and then address the Interface case later?

**Comment by pngwn** [comment]
Yeah. I think we can fix that issue in another PR. Will take one last look over before merging.

**Pull request merged**
