### PR TITLE
Update blocks in memory after prediction

### PR DESCRIPTION
**Pull request by NimaBoscarino**
# Description 

The dependencies are being updated in the front-end, but not on the server-side. This causes some issues with certain components, such as the Radio component (see #1566).

This PR adds a small step for each non-stateful dependency in `postprocess_data`, so that any prediction of type `update` will have all of its attributes copied over to the relevant block. I've tested this manually with a few components.

Note that this PR is being opened as a draft to get feedback the approach. Let me know if this seems like an appropriate solution!

Also, the only tests that I can see that hit `postprocess_data` are:

```
test.test_external.TestLoadInterface.test_numerical_to_label_space
test.test_routes.TestRoutes.test_predict_route
test.test_routes.TestRoutes.test_predict_route_without_fn_index
test.test_routes.TestRoutes.test_state
```

But these all do it through either `.load` or the API routes. Any recommendations on good ways to test this? I was thinking of doing it in `test.test_blocks.TestBlocks`.

@abidlabs @aliabd

Closes: #1566

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by abidlabs** [comment]
Hmmm I don't think this will work. The problem is that this will update the component's values for *all users* of the app, since all of the users share a single backend. So if user 1 presses the Run button, it will update the state of the component in the backend, but that will also affect user 2.

I think the solution here needs to be that we pass in the updated component configs from the frontend into the backend when we call the `/api/predict` endpoint. cc-ing @aliabid94 @pngwn for their thoughts as well

**Comment by abidlabs** [comment]
Here's an example where this does not work:

```py
import gradio as gr


def set_radio_options():
    choices = ["A", "B", "C"]

    return (
        gr.Radio.update(choices=choices)
    )


def set_text(input_val):
    return gr.Text.update(input_val)


demo = gr.Blocks()

with demo:
    button = gr.Button()
    radio = gr.Radio(choices=["D", "E", "F"], type="index")  # changing to type="value" works, but index doesn't
    text = gr.Text()
    

    button.click(
        fn=set_radio_options,
        inputs=[],
        outputs=[radio]
    )

    radio.change(
        set_text,
        inputs=[radio],
        outputs=[text]
    )

demo.launch()
```

If you just run the demo in a single browser tab, then there are no problems. However, if you open a second tab, and after clicking Run in the first tab, try to use the demo in the 2nd tab without clicking Run, you'll see an Error.

**Comment by NimaBoscarino** [comment]
Aw, dang! I had a feeling that it couldn't be such an easy fix :sim

**Comment by NimaBoscarino** [comment]
Aw, dang! I had a feeling that it couldn't be such an easy fix 🥲 I might have some more time later this week to take another shot at it, or early next week.

**Comment by NimaBoscarino** [comment]
Closing since I don't think I'll have time to work on it anytime soon.

**Comment by pngwn** [comment]
Going to repoen this to track + for visibility. We are ok with issues staying open even if we aren't working on them currently.

**Comment by pngwn** [comment]
it is a PR not an issue. my bad,

**Pull request closed without merging**
