### PR TITLE
Allow skipping an arbitrary number of output components, and also raise a warning if the number of output components does not match the number of values returned from a function

### PR DESCRIPTION
**Pull request by abidlabs**
This PR does two things to improve the DX when working with many output components:

(1) It allows passing in a single `gr.skip()` to skip updating all of the components. It also documents `gr.skip()`, which had been completely undocumented. Closes: https://github.com/gradio-app/gradio/issues/9109

(2) It raises a warning when the number of output components is smaller than the number of returned values from a function. Closes: https://github.com/gradio-app/gradio/issues/6883

### CODE REVIEW

**Comment by abidlabs** [comment]
Fixed a few unrelated python typing issues on `5.0-dev`

**Comment by abidlabs** [comment]
The failing Python tests are also failing on `5.0-dev`, as are the failing Lite tests. I'll take a look at the failing Python tests next, and @whitphx is looking into the Lite tests

**Review by freddyaboulton — APPROVED** [review]
PR looks good but returning the single skip feels a bit magical to me. What's the use case?

**Comment by abidlabs** [comment]
When you have a very large number of components, it’s inconvenient to create a list of skips if you just want to “abort early”. Stepped away for a little bit but it’s in issue linked from the linked issue above I believe

**Comment by freddyaboulton** [comment]
Sounds good to me @abidlabs !

**Comment by abidlabs** [comment]
Thanks for the review @freddyaboulton!

**Pull request merged**
