### PR TITLE
V4: Use beta release versions for '@gradio' packages

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Fix my mistake 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks @freddyaboulton! I think this looks good

**Comment by freddyaboulton** [comment]
Actually, I think some may be off. Will double check and merge in a bit.

**Review by pngwn — CHANGES_REQUESTED** [review]
This isn't quite right.

We want to make the the `version` field in the package.json always refers to the beta version on npm but the `dependencies` should all still say `workspace:^`, so we can work with the local files in development.

**Comment by freddyaboulton** [comment]
Thanks @pngwn - think it's good now

**Review by pngwn — APPROVED** [review]
Looks good! Thanks @freddyaboulton!

**Comment by pngwn** [comment]
Need to resolve some conflicts so will merge.

**Pull request merged**
