### PR TITLE
fix hidden error toast

### LINKED ISSUE #2687: Make gr.Error `position: Fixed` in an iframe
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Currently gr.Error is on the top-right. However if your application scrolls down, the user can never read what error it was unless they scroll back up
image

**Describe the solution you'd like**  
Have `gr.Error` to have a `position: Fixed` or analogous to show on the top-right regardless of scroll

### PR DESCRIPTION
**Pull request by pngwn**
## Description

closes #2687.

Scrolls to the top of the iframe when we are in spaces.

Please include a concise summary, in clear English, of the changes in this pull request. If it closes an issue, please mention it here.

Closes: #(issue)

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests & Changelog

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

1. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`
  
1. Unless the pull request is labeled with the "no-changelog-update" label by a maintainer of the repo, all pull requests must update the changelog located in `CHANGELOG.md`:

Please add a brief summary of the change to the Upcoming Release section of the `CHANGELOG.md` file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

### CODE REVIEW

**Comment by pngwn** [comment]
i can write a test for this one just yet.

**Review by freddyaboulton — APPROVED** [review]
Works great @pngwn !!!!

Tested here: https://huggingface.co/spaces/freddyaboulton/scroll-to-top-error

scroll_to_top

Would be incredible if you unit test this

**Comment by pngwn** [comment]
Does work properly on a small screen so just going tweak it. 

I can't test atm because this actually only work in space but I'm gonna try to create a spaces-like test environment soon.

**Comment by pngwn** [comment]
Thanks for the review @freddyaboulton!

**Pull request merged**
