### PR TITLE
Fix `CrossOriginWorkerMaker` to cache the blob URL

### PR DESCRIPTION
**Pull request by whitphx**
## Description

There is a bug that multiple SharedWorker-s are created for the same site when the Lite's worker script (`webworker.js`) is loaded from a different origin through `CrossOriginWorkerMaker`.
It is because [this part](https://github.com/gradio-app/gradio/blob/24626ea362a35606d344f341a308556c52b34cc0/js/wasm/src/cross-origin-worker.ts#L23-L33) is called every time a new worker is created.
To avoid it, caching mechanism is introduced in this PR.

### CODE REVIEW

**Comment by aliabd** [comment]
@whitphx the changes look good, but how should I test this?

**Comment by whitphx** [comment]
@aliabd 
The points are
* Serve the Lite scripts and a web site from different origins.
* Run multiple Lite apps in a browser.
* Confirm only one SharedWorker is created.

For example,
1. Build Lite and serve the scripts from one port of localhost, e.g. from `localhost:8000`.
2. Import the served script (`http://localhost:8000/path/to/lite.js`) from another website (e.g. `js/_website`) and embed a Lite app enabling the SharedWorker mode. 
3. Serve the website from a different port e.g. `localhost:5173`. 
4. Open the website e.g. `http://localhost:5173/path/to/page` in Chrome in multiple tabs, and confirm the Lite app is working.
5. Open chrome://inspect/#workers and confirm only one SharedWorker is created.

**Comment by whitphx** [comment]
@pngwn Updated 👍

**Comment by abidlabs** [comment]
I'll go ahead and merge this in to get it out for the release. 

cc @aliabd as well for visibility

**Pull request merged**
