### PR TITLE
Add elem classes

### PR DESCRIPTION
**Pull request by aliabid94**
Add classes to components with `elem_classes` just like `elem_id`
Fixes: #2962

### CODE REVIEW

**Comment by abidlabs** [comment]
One thing I noticed is that when you are applying css to classes, you have to use `!important` to override the default css, whereas you don't have to do this for ids. Here's example:

```py
import gradio as gr

css = """
.abc {
    background-color: green;
}

#hi {
    background-color: red;
}
"""

gr.Interface(
    lambda x:x, 
    [
        gr.Textbox(elem_classes="abc"),
        gr.Textbox(elem_id="hi"),
        gr.Textbox(),
    ],        
    gr.Image(elem_classes=["abc"]),
    css=css,
).launch()
```

Produces:

image


Whereas if you add the `!important`, it works:

```py
import gradio as gr

css = """
.abc {
    background-color: green !important;
}

#hi {
    background-color: red;
}
"""

gr.Interface(
    lambda x:x, 
    [
        gr.Textbox(elem_classes="abc"),
        gr.Textbox(elem_id="hi"),
        gr.Textbox(),
    ],        
    gr.Image(elem_classes=["abc"]),
    css=css,
).launch()
```

image

Is this expected?

**Comment by abidlabs** [comment]
The three Plot components are missing the docstring for `elem_classes` although they include the parameter: 
* BarPlot
* LinePlot
* ScatterPlot

**Comment by abidlabs** [comment]
Other than those two points, LGTM @aliabid94!

**Review by abidlabs — APPROVED** [review]

**Comment by aliabid94** [comment]
ok I updated the docstrings.

Unfortunately I cannot think of a good way to have class rules overwrite the default css without `!important`. The reason is because the default CSS rules are attached by combing the css rules in svelte with a randomly generated class identifier at runtime, to keep the svelte css scoped. See below, the random string class attached to each element and ruleset are generated at compile time.
Screen Shot 2023-03-14 at 8 01 27 PM

because these default rules are selected by their default specifier AND a random class name, they overrule the CSS rules with just a class specifier - in CSS, the more specific rule always wins.

If you have ideas lmk, otherwise we can document that class rules should have `!important`. Using `!important` is not good practice, but neither is using `css=` lol

**Comment by abidlabs** [comment]
Thanks for the explanation @aliabid94. I think that's okay, it won't be necessary for every css property, just the ones that conflict with the built-ins. Let's definitely document this in the Guide & I'll comm to the Automatic1111 folks as well.

**Comment by abidlabs** [comment]
Not to block merging, but let's tag @pngwn for his thoughts on this when he's back.

**Pull request merged**
