### PR TITLE
Allow `info=` to render markdown

### PR DESCRIPTION
**Pull request by dawoodkhan82**
## Description

`info=` renders markdown

Closes: #9193

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by dawoodkhan82** [comment]
Should we always render markdown for `info=` or introduce a new param to disable it?

**Review by abidlabs — APPROVED** [review]

**Comment by abidlabs** [comment]
Updated the docstrings, should be good to go! Will merge once CI passes to get things ready for the launch

**Review by abidlabs — APPROVED** [review]
LGTM nice one @dawoodkhan82!

**Comment by abidlabs** [comment]
Will go ahead and merge this in to get ready for launch!

**Pull request merged**
