### PR TITLE
Fix programmatic tab selection

### PR DESCRIPTION
**Pull request by aliabid94**
`selected` was not being respected for tabitems, because the `id` property of a tabitem was being overwritten internally. Renamed internal use of `id` to `_id`.

Test with:
```python
import gradio as gr

def select_c():
    return gr.Tabs(selected="c")

with gr.Blocks() as demo:
    with gr.Tabs(selected="b") as tabs:
        with gr.Tab("A", id="a"):
            gr.Markdown("## A")
        with gr.Tab("B", id="b"):
            gr.Markdown("## B")
        with gr.Tab("C", id="c"):
            gr.Markdown("## C")

    btn = gr.Button("Switch to tab C")
    btn.click(select_c, None, tabs)

demo.launch()
```

Fixes: #7726

### CODE REVIEW

**Review by pngwn — APPROVED** [review]
Ah nice catch. Thanks @aliabid94!

We should probably lint against 'shadowing' variables. I wonder if this fixes #7786 as well?

**Review by freddyaboulton — COMMENTED** [review]
Nice @aliabid94 ! Can we add a test for this? It's regressed before

**Comment by aliabid94** [comment]
Added tests. While I was adding tests, I caught an error that wouldn't show up in dev mode for some reason: If a gr.Tabs() had `selected=` set to a value in its constructor, than any event listener trigger that would cause a redraw would reset the gr.Tabs to the selected tab. I made changes to Tab.svelte to fix this, @pngwn if you could just take a quick pass at it again.

**Comment by aliabid94** [comment]
actually my solution won't work in the case that an app programmatically tries to set the selected tab to the same tab a second time after a user moved away from that tab. Is there any way for gradio to know if the selected tab being passed is the result of an event listener output, or just a redraw resetting the prop?

**Comment by pngwn** [comment]
What is the actually problem, sorry. In principle we shouldn't need to know the difference.

**Comment by pngwn** [comment]
This feels like the accordion thing tbh. Gonna take a closer look.

**Comment by aliabid94** [comment]
Sorry let me clarify. The issue I was trying to fix with selected, _selected, and old_selected_prop is that event listeners were causing the component to re-render, which was causing the props to be reset to their set values. So the selected tab would get reset to the constructor-set value. So if there was a gr.Tabs(selected="b") setting the default to "b", and a user clicked away to tab "a", when an event listener triggered a re-render, the tab would reset to "b".

**Comment by pngwn** [comment]
I see. That does sound very similar to the accordion issues where it resets to the default.

**Comment by pngwn** [comment]
@aliabid94 I have just opened #7963 to fix the accordion 'reset' issue, and this feels similar. When that is merged in i think if you merge main into this it may fix the remaining issue you are having.

**Review by pngwn — APPROVED** [review]
Looks great! Thanks for fixing this and adding those extra tests @aliabid94!

**Comment by arose26** [comment]
So, how do I change the tab programmatically? (not from a button, just from code).
I've tried changing the tab instance's 'selected' property directly but it doesn't do the job. gr.Tabs.update(selected=newid) doesn't work either.

**Comment by avfranco-br** [comment]
> So, how do I change the active tab programmatically? (not from a button, just from code). I've tried changing the tab instance's 'selected' property directly but that only works BEFORE calling launch. After launch, it doesn't do the job. gr.Tabs.update(selected=newid) doesn't work either. I want to change selected tab in real time, from python code.

Hi @arose26 , have you found a fix for this issue yet? I'm having the same issue. Thanks, Alexandre

**Comment by ben-directai** [comment]
Also experiencing this issue

**Pull request merged**
