### PR TITLE
Allow app to fill width

### PR DESCRIPTION
**Pull request by aliabid94**
Useful for dashboards and other complex apps that want to use all the screen space.

Closes: https://github.com/gradio-app/gradio/issues/8201
Closes: https://github.com/gradio-app/gradio/issues/6732

### CODE REVIEW

**Comment by abidlabs** [comment]
Niceee I just needed this for the app I'm building 😆

**Comment by abidlabs** [comment]
Two quick comments:

(1) I think `.launch()` would be a better place to put this parameter. I know we put a lot of global styling features in `gr.Blocks` like `css` and `theme` but this doesn't make sense since `Blocks` can be nested within other `Blocks` and only the style parameters in the outer `Blocks` apply.

(2) Not a strong opinion, but instead of a boolean, should we make this a more flexible parameter that can take in a specified width e.g. full width corresponds to 100%. And the default setting could be a tuple of ints corresponding to the current widths at different screen breakpoints

**Comment by aliabid94** [comment]
> (1) I think .launch() would be a better place to put this parameter.

We already have fill_height in gr.Blocks() though

> Not a strong opinion, but instead of a boolean, should we make this a more flexible parameter that can take in a specified width e.g. full width corresponds to 100%. And the default setting could be a tuple of ints corresponding to the current widths at different screen breakpoints

I don't think that's necessary until we see a request for it, seems like overkill.

**Comment by abidlabs** [comment]
> We already have fill_height in gr.Blocks() though

Ah good point, ok then

> I don't think that's necessary until we see a request for it, seems like overkill.

Hmm but would be a breaking change if we do get requests for it.

**Review by freddyaboulton — APPROVED** [review]
Nice - also agree Blocks init is the best place for the parameter

**Comment by abidlabs** [comment]
After sleeping on it, I do think the `fill_width` parameter looks fine as a boolean and is symmetric with the `fill_height` parameter

2 things:

* This parameter doesn't seem to have any effect on Spaces: compare https://huggingface.co/spaces/abidlabs/fill-width and https://huggingface.co/spaces/abidlabs/fill-width-2 -- I think its due to the fact that Spaces adds its own margin around the iframe. Can we work with Spaces to fix that?
* Can we add `fill_height` and `fill_width` to `Interface` and `ChatInterface` as well?

**Review by pngwn — APPROVED** [review]
Looks great. Thanks @aliabid94!

**Comment by aliabid94** [comment]
> On very wide screens, this will cause Gradio apps to look very stretched out and distorted. Instead of a boolean parameter, do you think we should set a higher max width instead of 100%

There is already a max-width set by gradio's container that's meant to prevent this. When you set full_width to True, you are specifically asking to skip this, so we should take all the width in this case.

> This parameter doesn't seem to have any effect on Spaces: compare https://huggingface.co/spaces/abidlabs/fill-width and https://huggingface.co/spaces/abidlabs/fill-width-2 -- I think its due to the fact that Spaces adds its own margin around the iframe. Can we work with Spaces to fix that?

I'll message Spaces team

> Can we add fill_height and fill_width to Interface and ChatInterface as well?

Done.

**Pull request merged**
