### PR TITLE
Adding `maxlength` attribute handling of `textarea` and `input` HTML element for the `gr.TextBox()` component via a `max_length` parameter

### PR DESCRIPTION
**Pull request by WH-Yoshi**
## Description

This PR aims to be able to modify the maximum number of characters to insert in a `gr.TextBox()`.
To do this, a `max_length` parameter is added to the `gr.TextBox()` component. 
This results in the modification of the svelte files for this component with the addition of a prop handler named `max_length` which will give its value to the HTML attribute `maxlength` responsible for the limit.

Closes: #9145

All tests have been run, some of them failed for unknown reasons or not caused by the modification of these last files.

### CODE REVIEW

**Comment by WH-Yoshi** [comment]
Thanks @abidlabs for the clues!

**Comment by abidlabs** [comment]
Hi @WH-Yoshi is there a reason you closed this PR?

**Comment by WH-Yoshi** [comment]
Hi yes, the tests are unsuccessful and I don't find the issue, so I wanted to make sure on my part before opening a PR maybe

**Comment by abidlabs** [comment]
You mind if I reopen and take a Quick Look?

**Comment by WH-Yoshi** [comment]
Sure, I'm a bit lost ngl

**Review by abidlabs — APPROVED** [review]
LGTM @WH-Yoshi, thanks for the nice PR! Just made a small addition to `gradio/templates.py`

**Pull request merged**
