### PR TITLE
Minor changes to monitoring

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

- Prints the console url in cyan so that it's easier to see
image

- Renames `analytics` to `monitoring` to be consistent and to differentiate from analytics collected during launch

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Code changes look good, but the cyan color is a little hard to read on a light background, e.g. jupyter notebook:

image

**Comment by freddyaboulton** [comment]
I made it orange which is similar to the gradio brand and looks good in my dark terminal and jupyter. WDYT?

image

Screenshot 2024-06-07 at 1 53 37 PM

**Comment by abidlabs** [comment]
I'm not sure if we should change the font color @freddyaboulton because:
1. people have weird terminal settings sometimes and I think its better to let the default color shows rather than a hardcoded color that may not display well on their background
2. this rich print makes the link unclickable in jupyter notebooks

**Comment by freddyaboulton** [comment]
Opted for just bold + underline the link @abidlabs !

**Comment by abidlabs** [comment]
Thanks @freddyaboulton! Sorry I keep running into usability issues, but I think with rich_print(), printed links are not clickable in jupyter / colab notebooks. 

image

**Review by aliabid94 — APPROVED** [review]
lgtm, thanks freddy!

**Comment by freddyaboulton** [comment]
Thank you for the reviews @aliabid94 @abidlabs !

**Pull request merged**
