### PR TITLE
Fixed upload dialog being showed after pressing "x" button

### PR DESCRIPTION
**Pull request by mezotaken**
# Description

The issue caused by commit https://github.com/gradio-app/gradio/commit/996cd8b814e7198cc50cf2f6356237828bce7350 as it seems. Variable `disable_click` being set to false every time when "x" button is used because at the moment it happens there exists no image.
~~`click` variable serves no purpose, not imported anywhere else in the project (correct me if i'm wrong).~~
To prevent this behavior stopPropagation property was applied to click event on the "x" buttons. Should be done for every similar button, but my main concern is for the images.

Also user cannot upload same image after clear, because upload is triggered with `on:change` event for `hidden_upload` element, so that's fixed too. 

Closes: #2476 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by abidlabs** [comment]
Thank you very much for the contribution @mezotaken. I've tested the code and confirms this solves the underlying issue.

@pngwn would you be able to review the code changes and if it looks good, we can merge this in?

**Comment by mezotaken** [comment]
@abidlabs as i can see from the failed static check, the `click` variable is used after all. Albeit only once in the table.svelte and it does exactly what disable_click does? am i correct on this?
So changing 
image
to 
image
should be fine? I need confirmation on this

**Comment by pngwn** [comment]
I won't have time to look over this for a week or so unfortunately.

**Comment by dawoodkhan82** [comment]
> @abidlabs as i can see from the failed static check, the `click` variable is used after all. Albeit only once in the `table.svelte` and it does exactly what disable_click does? am i correct on this? So changing image to image should be fine? I need confirmation.

Yeah Looks like it was an unnecessary variable.

**Comment by dawoodkhan82** [comment]
tested and it fixes the issue; also code looks good. LGTM!

**Comment by abidlabs** [comment]
Thanks so much @mezotaken and @dawoodkhan82!

**Pull request merged**
