### PR TITLE
E2E tests for Lite

### PR DESCRIPTION
**Pull request by whitphx**
## Description

Closes: #6141

The failed tests for `Chatbot` should be solved with #6897

### CODE REVIEW

**Comment by whitphx** [comment]
@abidlabs It's still under development. Rebasing the main...

**Review by pngwn — APPROVED** [review]
I think this is fine to merge, we'll need to merge in order to test.

**Comment by pngwn** [comment]
I need to fix CI on main to get these visual tests to behave.

**Comment by whitphx** [comment]
ok, will merge this while maybe the test won't work soon. Enabled the auto-merge.

**Comment by abidlabs** [comment]
CI was being weird, but went ahead and merged it automatically @whitphx!

**Pull request merged**
