### PR TITLE
Fix mistake on Audio Mixer Demo

### PR DESCRIPTION
**Pull request by magical-l**
## Description

fix a misuse

Closes: #8621

### CODE REVIEW

**Comment by aliabd** [comment]
thanks @magical-l can you run `python scripts/generate_notebooks.py` from root and commit the changes?

**Comment by magical-l** [comment]
@aliabd Well, that stumps me a little bit... Where am I supposed to run `python scripts/generate_notebooks.py` ? in my local clone from my fork repo? can it work to the source repo?

**Comment by aliabd** [comment]
@magical-l yes on your fork go to the root of the repo and run: 

`python scripts/generate_notebooks.py`

To clarify, the PR is failing a 'notebooks match' check, because it changes a demo but not its associated python notebook. If you run this script https://github.com/gradio-app/gradio/blob/main/scripts/generate_notebooks.py it will generate the right notebook, then you just need to push the changes to this pr.

**Comment by aliabd** [comment]
actually @magical-l i went ahead and did it.

**Review by aliabd — APPROVED** [review]
Thanks @magical-l LGTM!

**Pull request merged**
