### PR TITLE
fix typescript issue with custom components

### LINKED ISSUE #8897: gradio cc dev not working for Model3D template
### Describe the bug

Starting from yesterday I cannot get gradio cc working for Model3D template. After creating the custom component using the template, when I enter the URL returned by gradio cc dev, it will report the following error. It worked fine last week. I've tried on the same environment I used last week and with different environments/different versions of gradio but still got the same error. I'm not very familiar with svelte, is this a problem on my side or a possible bug related to some updates happened on the server side?

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

gradio cc create mycomponent --template Model3D
gradio cc dev
(Open the frontend URL)

### Screenshot

Screenshot from 2024-07-24 12-28-13

### Logs

_No response_

### System Info

```shell
Ubuntu 22.04 (also tried on Ubuntu 24.04)
Gradio 4.39.0 (also tried 4.38.0 and earlier version)
```

### Severity

Blocking usage of gradio

### PR DESCRIPTION
**Pull request by pngwn**
## Description

There is a weird issue due to the tsconfig of `@gradio/wasm` this fixes it.

Closes #8897

### CODE REVIEW

**Comment by freddyaboulton** [comment]
I believe this closes https://github.com/gradio-app/gradio/issues/8897 ?

**Review by freddyaboulton — APPROVED** [review]
Not sure how to test this - I tried creating a model3d component in `js/preview/test` on main but that works fine which makes me think the `js/preview` environment is doing something different than what would happen in the wild. We should talk about the best way to test un-released changes to `@gradio/preview`. 

Approving because it fixes the problem according to users though

**Comment by pngwn** [comment]
Yeah. I don't know how to test it either. I tested it by editing my node modules with this change in a live project but slightly annoying.

**Comment by pngwn** [comment]
It does indeed fix that issue.

**Pull request merged**
