### PR TITLE
Lazy load interactive or static variants of a component individually, rather than loading both variants regardless. This change will improve performance for many applications.

### PR DESCRIPTION
**Pull request by pngwn**
## Description

Lazy load only the interactive or static variant of a component as required rather than loading both. This needs a follow up or two but works well.

Closes: #3360

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by pngwn** [comment]
@abidlabs READY FOR REVIEW!!!

**Comment by dawoodkhan82** [comment]
@pngwn Don't think updating `interactive=False` is working properly. I tried modifying `hello_blocks` for example: 

```
import gradio as gr

def greet(name):
    return "Hello " + name + "!", gr.Textbox.update("sorry", interactive=False)

with gr.Blocks() as demo:
    name = gr.Textbox(label="Name")
    output = gr.Textbox(label="Output Box")
    greet_btn = gr.Button("Greet")
    greet_btn.click(fn=greet, inputs=[name], outputs=[output, name], api_name="greet")

if __name__ == "__main__":
    demo.launch()
```

**Comment by aliabid94** [comment]
> Don't think updating interactive=False is working properly

I think this is because now we're loading the appropriate interactive/static version once at load time, right? 

One issue I noticed is that even as an output component, the dataframe component still allows for editing the component. Seems like this issue was introduced before this PR though. 

Otherwise looks great!

**Comment by pngwn** [comment]
> I think this is because now we're loading the appropriate interactive/static version once at load time, right?

I added some logic to load new components (if necessary when `interactive` changes), it just wasn't working all of the time, cos i messed up the order.

@dawoodkhan82 it should work now, if you can retest.

@aliabid94 I think i broke the dataframe in my refactor. Fixed that here as well.

**Comment by dawoodkhan82** [comment]
@pngwn tested and it works great now!

**Review by dawoodkhan82 — APPROVED** [review]

**Pull request merged**
