### PR TITLE
Document SSR environment variable

### PR DESCRIPTION
**Pull request by abidlabs**
Small PR that closes: https://github.com/gradio-app/gradio/issues/10138

### CODE REVIEW

**Review by aliabd — APPROVED** [review]
LGTM!

**Comment by abidlabs** [comment]
Thanks!

**Comment by anirbanbasu** [comment]
@abidlabs thanks for the PR. Any idea why https://www.gradio.app/guides/environment-variables isn't updated yet (I tried clearing my browser cache)?

**Comment by abidlabs** [comment]
Its because the docs will be updated after we do a release. In the meantime, you can look at the version of the docs that reflect `main`: https://www.gradio.app/main/guides/environment-variables

**Pull request merged**
