### PR TITLE
Gallery events WIP

### PR DESCRIPTION
**Pull request by abidlabs**
Colab with @pngwn to add `click()` and `change()` events to `Gallery`.

* The `click()` event should fire when an image is clicked, so that it can be used for some downstream function
* The `change()` event should fire when the Gallery loads images, allowing it to trigger downstream actions

Fixes: #1976, fixes: #1379 which should be marked as duplicates

### CODE REVIEW

**Comment by abidlabs** [comment]
@pngwn I'll close this PR for now?

**Comment by temirov** [comment]
The PR seems to be closed without merging, but it would have fixed many reported issues. Has it not worked as expected? (I see no tests in the PR)

**Comment by abidlabs** [comment]
We were unable to get a fix that truly worked. However, I agree that this is a pretty important issue. We'll look into this in the near future

**Comment by temirov** [comment]
Is it on the roadmap, if I may ask? E.g. do we have a vague feeling of the ETA? :-)

**Comment by abidlabs** [comment]
It is on the roadmap, but not something we can attend to in the next month at least

**Pull request closed without merging**
