### PR TITLE
Ensure undo/try shows for final bot message in gr.Chatbot

### PR DESCRIPTION
**Pull request by hannahblair**
## Description

The `retryable` and `undoable` props weren't reactive and thus weren't updating when new messages came in. This PR fixes that. 

Screenshot 2024-10-09 at 01 27 40

Closes: #9588

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Review by freddyaboulton — APPROVED** [review]
Functionality looks good @hannahblair !!

At least in spaces though the color of the retry button and copy button is white which means it does not show up. Is it a mobile/spaces issue or can you repro locally?

https://huggingface.co/spaces/freddyaboulton/chatinterface_streaming_echo

image

**Review by abidlabs — DISMISSED** [review]
This isn't working for me, when I run `demo/chatinterface_streaming_echo/run.py`, I see the following error in the console preventing usage of the app:

image

**Comment by aliabid94** [comment]
I got the same error as @abidlabs

**Comment by aliabid94** [comment]
I fixed in branch `undo-retry-chatbot-type-fix`, simple type fix but in case you also want to test @abidlabs https://github.com/gradio-app/gradio/compare/undo-retry-chatbot...undo-retry-chatbot-type-fix?expand=1

**Review by aliabid94 — APPROVED** [review]
LGTM as well!

**Pull request merged**
