### PR TITLE
Redesign file upload

### PR DESCRIPTION
**Pull request by hannahblair**
## Description

Bar in the background total progress of all files, and a circular progress bar next to the file name shows progress of file currently uploading and changes to the next one once that's done. 

Screenshot 2023-11-09 at 12 42 58

Screenshot 2023-11-09 at 12 43 07

Kapture 2023-11-09 at 11 51 27

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Looks super nice @hannahblair! We noticed a couple of issues when we were testing it in sync:

* In the `Image` component (and maybe the other components as well), there's a shaded progress bar that appears in the background of the component, it looks a little weird and starts about halfway in the screen. Its not necessary since we have the spinner, would be great if we could remove it: 

image

* After the image is uploaded, sometimes the Image component collapses before showing the image. Would be great to remove that

* It looks like not all of the file names are shown when uploading multiple files. It seems that at least the first file name is skipped. Not sure if this is a frontend issue or some info missing from the `/upload` route. cc @freddyaboulton

**Comment by freddyaboulton** [comment]
I removed the background, fixed the "skip the first filename" issue, and removed the flicker caused by transitioning from UploadProgress -> Upload -> Original component.

@hannahblair this looks good to me! Feel free to merge if you're happy with the changes 

https://github.com/gradio-app/gradio/assets/41651716/f8a88236-9c69-4302-b770-42103d96f988

**Review by freddyaboulton — APPROVED** [review]

**Comment by freddyaboulton** [comment]
Ah ok, maybe what happened was that since the first file uploaded super quickly, the shaded part started at the half of the screen and we got confused.

I think the spinner is also showing the total progress and not the progress for the current file. But I think the main takeaway I got from the meeting was that we preferred the spinner over the background shade as a measure of total upload progress.

**Comment by freddyaboulton** [comment]
Do you have thoughts on the above @pngwn @aliabid94 @dawoodkhan82 (cc @gary149 )?

In summary - which of the following should we go with?

1) the shaded background show total progress and the wheel show individual file progress
2) The wheel shows total progress (what it is now)
3) The wheel shows individual file progress

**Comment by pngwn** [comment]
I like the spinner for total progress with the file name changing as it progresses with no shaded background.

**Pull request merged**
