### PR TITLE
Fixes streaming event race condition

### PR DESCRIPTION
**Pull request by aliabid94**
Happened because of how we were closing event streams. Added a test that blasts lots of events rapidly so we don't run into this again. Test by running demo/rapid_generation on main and this branch.

Fixes: #7921

### CODE REVIEW

**Review by freddyaboulton — APPROVED** [review]
Nice fix @aliabid94 !

**Comment by yvrjsharma** [comment]
I can confirm that I no longer see the issue in the [duplicated (private atm) mPLUGOwl/Doc](https://huggingface.co/spaces/ysharma/DocOwl) Space when using the gradio wheels from this PR. Thanks @aliabid94 !

**Comment by pngwn** [comment]
Can you explain what the race condition is here? It isn't obvious from the code or tests.

**Review by pngwn — APPROVED** [review]
Looks good otherwise! Thanks @aliabid94!

**Comment by aliabid94** [comment]
race condition was that sometimes the client would receive the `close_stream` event from the backend before it had finished processing pending callbacks. This would cause the callback to be called with `close_stream`, but we shouldn't be calling the callback with that message, as would cause issues with apply_diff_stream

**Comment by dawoodkhan82** [comment]
Thanks for fixing @aliabid94

**Comment by keenranger** [comment]
This helped me streaming agent a lot! TY!

**Pull request merged**
