### PR TITLE
Added polars dataframe support with demo

### PR DESCRIPTION
**Pull request by cswamy**
## Description

Please include a concise summary, in clear English, of the changes in this pull request. If it closes an issue, please mention it here.

Closes: #6973 and new demo `sort_records` added

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Review by freddyaboulton — COMMENTED** [review]
Nice pr @cswamy ! I don't think we should add more dependencies to gradio though, we want to trim them as much as possible. See (#6974 ). Can you please refactor this to assume polars is optional? So if `type='polars'`. First check if polars is installed and raise an error if not.

The type hint may be off but I think that's an acceptable tradeoff. There's also this post that we can look into: https://stackoverflow.com/questions/61384752/how-to-type-hint-with-an-optional-import

**Comment by cswamy** [comment]
Hi @freddyaboulton please check now. Added additional checks in `Dataframe:postprocess()` so that tests `TestDataframe:test_postprocess()` and `test_components:test_dataframe_process_example_converts_dataframes()` can pass.

**Comment by freddyaboulton** [comment]
Thanks @cswamy! will review in a bit

**Comment by freddyaboulton** [comment]
Thanks for the nice PR @cswamy ! I made some changes to how we check for polars to avoid using the `global` and made sure the type check passed. Excited to release this.

**Comment by cswamy** [comment]
Fantastic, thanks @freddyaboulton 👍

**Comment by abidlabs** [comment]
Thanks @cswamy for this nice contribution!

**Comment by cswamy** [comment]
Happy I could help 😊

**Pull request merged**
