### PR TITLE
update docstring for the the "variant" parameter in `gr.Button`

### PR DESCRIPTION
**Pull request by fadingNA**
## Description

Align parameter document of button api reference 

## 🎯 PRs Should Target Issues
Closes: #9787

## Tests

All tests pass.

### CODE REVIEW

**Comment by fadingNA** [comment]
@abidlabs  I made PR for you to review

Thank you

**Comment by fadingNA** [comment]
@abidlabs  do I have to wait you approve for the CI to run is that correct?

**Review by abidlabs — APPROVED** [review]
used this as an opportunity to make some other tweaks to the docstrings, but this looks good. Thanks @fadingNA!

**Comment by fadingNA** [comment]
> used this as an opportunity to make some other tweaks to the docstrings, but this looks good. Thanks @fadingNA!

Thank you so much @abidlabs

**Pull request merged**
