### PR TITLE
[Docs] Resolve numerous typos

### PR DESCRIPTION
**Pull request by tomaarsen**
Hello!

# Pull Request overview
* Resolve numerous typos in docs, guides, comments, CHANGELOG, a variable and a warning.

# Description

I noticed a typo in the [DataFrame docs](https://gradio.app/docs/#dataframe) and took it on myself to resolve it - alongside many more.
The typos were automatically detected using [`codespell`](https://github.com/codespell-project/codespell) and manually fixed if they indeed were a typo.

# Checklist:

- [ ] ~~I have performed a self-review of my own code~~ N/A
- [ ] ~~I have added a short summary of my change to the CHANGELOG.md~~ N/A
- [ ] ~~My code follows the style guidelines of this project~~ N/A
- [ ] ~~I have commented my code in hard-to-understand areas~~ N/A
- [x] I have made corresponding changes to the documentation
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~ N/A
- [x] New and existing unit tests pass locally with my changes

I don't have permissions to label this as `"no-changelog-update"`, but I am favour of adding it here. Users reading a changelog should not be shown that some typos were fixed.

- Tom Aarsen

### CODE REVIEW

**Comment by tomaarsen** [comment]
My apologies for accidentally pushing `test.py`! That one's on me - my bad.

I ran `generate_notebooks.py`, but the CI still seems to complain. Perhaps it's because of my OS (i.e. Windows).

- Tom Aarsen

**Comment by abidlabs** [comment]
Let me try on my side

**Comment by tomaarsen** [comment]
Seems to work now - although GitHub doesn't love it, it seems:
image

(Screenshot taken from [here](https://github.com/gradio-app/gradio/pull/4170/commits/3a182c0f51ef06e7c333e6e17a027872768f7adc))

**Comment by abidlabs** [comment]
> Seems to work now - although GitHub doesn't love it, it seems:

Hmm that's happening on `main` too though. cc @aliabd 

But shouldn't stop this from being merged

**Comment by aliabd** [comment]
no idea what that is, will take a look

**Comment by abidlabs** [comment]
Merged, thanks again @tomaarsen!

**Pull request merged**
