### PR TITLE
Fix plots

### PR DESCRIPTION
**Pull request by pngwn**
## Description

Please include a concise summary, in clear English, of the changes in this pull request. If it closes an issue, please mention it here.

Closes: #(issue)

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Nice, Lite tests are passing! Are js test failures expected?

**Comment by pngwn** [comment]
I'm just checking the type checking now.

**Comment by pngwn** [comment]
I think everything should pass now.

**Comment by pngwn** [comment]
> I'm just checking the type checking now.

who watches the watchmen

**Comment by pngwn** [comment]
okay this time!

**Comment by abidlabs** [comment]
Tests are looking good @pngwn but I'm seeing this error:

image


in the `native_plots` demo: https://gradio-pr-deploys-pr-9464-all-demos.hf.space/demo/native_plots/?__theme=light

**Comment by pngwn** [comment]
i think it works now

**Review by abidlabs — APPROVED** [review]
lgtm @pngwn! thanks for taking care of this. plots are working great now

**Comment by abidlabs** [comment]
I'll go ahead and merge this in shortly so that we can benefit from the fixed tests in the other PRs

**Pull request merged**
