### PR TITLE
fix pnpm filters for 7.x

### LINKED ISSUE #1820: Support pnpm versions > 6
### Describe the bug

this error is thrown
```
 ERR_PNPM_RECURSIVE_EXEC_FIRST_FAIL  not found: build:local
 ELIFECYCLE  Command failed with exit code 1.
```
when i run `bash scripts/build_frontend.sh`
-  used `pnpm version 7.5.2` which i installed via `npm install -g pnpm`

According to @NimaBoscarino , the simple solution would be to go into `ui/package.json` and change the build script to say 		`"build": "pnpm --filter @gradio/app build:local --emptyOutDir",`

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

.

### Screenshot

_No response_

### Logs

```shell
.
```

### System Info

```shell
.
```

### Severity

serious, but I can work around it

### PR DESCRIPTION
**Pull request by pngwn**
Closes #1820

### CODE REVIEW

**Comment by abidlabs** [comment]
@NimaBoscarino and @chrisemezue will be happy about this!

**Comment by pngwn** [comment]
Now i realise how simple the fix is, should have done it months ago :P

**Review by aliabid94 — APPROVED** [review]
tested, lgtm

**Comment by pngwn** [comment]
I take it back, it was not simple and this exactly why i avoided it. Should all be fine now. I've also installed all test deps locally to ensure we can keep them pinned to compatible version.

**Pull request merged**
