### PR TITLE
fix: redundant meta tags that are unwanted

### PR DESCRIPTION
**Pull request by qkdxorjs1002**
## Description

I am fixing mistakes made in the previous PR(#7510) by removing unwanted duplicate for-loop.

Closes: #7642

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
@dawoodkhan82 could you take a look at this PR?

**Comment by dawoodkhan82** [comment]
@abidlabs taking a look

**Review by dawoodkhan82 — APPROVED** [review]
LGTM

**Comment by abidlabs** [comment]
Nice will merge this in to get it out for the release

**Pull request merged**
