### PR TITLE
More dropdown fixes

### PR DESCRIPTION
**Pull request by space-nuko**
# Description

Fixes more `gr.Dropdown` issues and enhances usability

List of changes:
- Can now filter any time single-select dropdown is opened
- Changed color of filtering text to distinguish it from currently selected element text
- Display selected element in filter placeholder
- Autoselect element if filtered text matches exactly
- Filtering text is cleared when focus is released
- Key actions trigger on key down instead of key up, improves responsiveness
- Multiselect options are now deleted if there's no filter text and they're backspaced into

Bug fixes:
- Dropdown reopening itself when filtered element selected
- Dropdown reopening itself when arrow/edge of box selected
- Dropdown not opening when text of selected element is clicked
- Dropdown not opening when clicking in specific places due to gaps/div element in the way
- Dropdown filter being focused, but options not opened
- Dropdown having overflow in X direction
- Filter box triggering default `<input>` key up/key down action (jumping to start/end of text)

Closes: #3701, closes: #3702, closes: #3533

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Review by pngwn — CHANGES_REQUESTED** [review]
Could you remove these two features:

> Display selected element in filter placeholder

This isn't what the placeholder is for and is bad for accessibility.

> Autoselect element if filtered text matches exactly

I don't think this matches standard  dropdown semantics, which is the goal with the single select dropdown. User should be required to select and option in order to change it.

**Comment by space-nuko** [comment]
I would argue the filtering doesn't match `<select>` semantics either since it's so advanced, presumably that's why the `<select>` component was moved away from into a custom HTML component for that extra feature

Was mostly a workaround since I couldn't use the arrow keys to select elements from that selected element bug

**Comment by aliabid94** [comment]
Thanks a lot for this PR @space-nuko, sorry for the delay in getting back to ya! Just to go through point by point:

Changes:

- Can now filter any time single-select dropdown is opened 
  - ✅
- Changed color of filtering text to distinguish it from currently selected element text 
  - ✅, I think a better color here may be `var(--body-text-color-subdued)`, I'll look into this
- Display selected element in filter placeholder
  - this was reversed I believe
- Autoselect element if filtered text matches exactly 
  - also reversed I believe
- Filtering text is cleared when focus is released
  - Why do we want it to clear? To make sure there's nothing selected? I think it'd be better to leave the filtered text there, and since it's a different color now, it's clear that nothing has been selected
- Key actions trigger on key down instead of key up, improves responsiveness
  - ✅
- Multiselect options are now deleted if there's no filter text and they're backspaced into
  - ✅, love this

Bug fixes:

- Dropdown reopening itself when filtered element selected
  - didn't quite understand this one
- Dropdown reopening itself when arrow/edge of box selected
  - ✅
- Dropdown not opening when text of selected element is clicked
  - Could not reproduce?
- Dropdown not opening when clicking in specific places due to gaps/div element in the way
  - ✅
- Dropdown filter being focused, but options not opened
  - Could not reproduce?
- Dropdown having overflow in X direction
  - Works. Just to clarify though, why don't we want a visible scrollbar in the case the option text is very long? Seems appropriate. Could also make the option text wrap.
- Filter box triggering default <input> key up/key down action (jumping to start/end of text)
  - ✅

Thanks again @space-nuko! if you and @pngwn could chime in on my questions above, I'd be happy to make the changes, merge main conflicts, and get it across the finish line.

**Comment by pngwn** [comment]
> Filtering text is cleared when focus is released

We don't want to do this.

> Dropdown having overflow in X direction

In this case we should match the default dropdown behaviour which will typically just make itself as big as it can to fit the content. If the item is wider than the screen size then I think it should wrap. Dropdowns generally adapt their size to fit the content.

Everything else looks good to me.

**Comment by abidlabs** [comment]
Thanks for the review folks! @aliabid94 do you wanna take another pass and wrap this PR up?

**Comment by space-nuko** [comment]
Apologies for the delay I only just now noticed this

> Display selected element in filter placeholder

I just want to remember the current filtering if the box is reselected, whatever you think is the best UX is okay

> Autoselect element if filtered text matches exactly

I liked this because it's the same behavior of `ivy-mode` in emacs, but I'm okay with giving it up

> Filtering text is cleared when focus is released

Because to me clicking the dropdown again with the intention of selecting a new element seemed kind of awkward if there was text already input, it makes it feel like you're interacting with two different element types at once. Again if there's a way to make clicking the dropdown work like a `<select>` even if there's text I don't mind

> Dropdown reopening itself when filtered element selected

At one point if I selected an element with Enter the dropdown would reopen the list of elements again, don't know if that still happens

> Dropdown not opening when text of selected element is clicked

Ditto with what I was mentioning with filter text clearing

> Dropdown filter being focused, but options not opened

It's alright if it's not an issue anymore

> Dropdown having overflow in X direction

Because gradio's current behavior is not the behavior of the native `<select>` element as far as I understand, native select can use parts of the screen outside the browser window if necessary to show the content without hard wrapping to the width of the selected element area. I had a comparison in another issue but the point was it was a big visual difference and was difficult to navigate with many elements in the list because of the wrapping/overflow

**Comment by aliabid94** [comment]
I think everything's been resolved, @pngwn could I get a quick re-review to unblock the merge?

**Comment by aliabid94** [comment]
sample file to play around with different dropdown settings:
```python
import gradio as gr

choices = ["World", "Gradio", "World2", "abc "*50, "You"]
with gr.Blocks() as demo:
    drop1 = gr.Dropdown(choices, label="simple")
    drop2 = gr.Dropdown(choices, label="multi", multiselect=True)
    drop3 = gr.Dropdown(choices, label="custom", allow_custom_value=True)
    drop4 = gr.Dropdown(choices, label="multi-max3", multiselect=True, max_choices=3)
    btn = gr.Button("Click me!")
    with gr.Row():
        with gr.Column():
            gr.Markdown("On Click")
            val1 = gr.Textbox(label="simple")
            val2 = gr.Textbox(label="multi")
            val3 = gr.Textbox(label="custom")
            val4 = gr.Textbox(label="multi-max3")
        with gr.Column():
            gr.Markdown("On Change")
            ins1 = gr.Textbox(label="simple")
            ins2 = gr.Textbox(label="multi")
            ins3 = gr.Textbox(label="custom")
            ins4 = gr.Textbox(label="multi-max3")
    btn.click(lambda *args: args, [drop1, drop2, drop3, drop4], [val1, val2, val3, ins4])
    drop1.change(lambda x:x, drop1, ins1)
    drop2.change(lambda x:x, drop2, ins2)
    drop3.change(lambda x:x, drop3, ins3)
    drop4.change(lambda x:x, drop4, ins4)
        
demo.launch()
```

**Review by pngwn — APPROVED** [review]
Looks good! Thanks @space-nuko and @aliabid94!

**Comment by abidlabs** [comment]
Great thanks everyone! Merging in so we can get it out in a release later today

**Pull request merged**
