### PR TITLE
Url path

### PR DESCRIPTION
**Pull request by bottledmind**
# Description

I cannot install frontend, because of pnpm. I'm getting a bunch of errors, that seem to be the same for my code and your main without an installed frontend. So, I need someone's help with running the tests on my version (and main to compare. There was an IndexError, idk if it's from frontend).
Once the tests are passing and you're satisfied with my solution, I'm gonna write some tests for my code

Please include: 
* relevant motivation 
    - check the issue below. I personally had deployment issues
* a summary of the change - 
    - added server_url_path parameter to `.launch()` method
    - check the provided path for a collision with reserved by Gradio and FastAPI
* which issue is fixed
    - https://github.com/gradio-app/gradio/issues/344
* any additional dependencies that are required for this change.
    - None

Closes: #344

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas (I believe there are none)
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by bottledmind** [comment]
Oh, you actually have CI

**Comment by bottledmind** [comment]
Well, can someone explain me whats the difference between CI black and local black?
image

**Comment by freddyaboulton** [comment]
Hi @bottledmind ! You probably have a different version of black installed locally. The dependencies on CI are installed via bash scripts/install_test_requirements.sh

**Comment by abidlabs** [comment]
Hi @bottledmind, thanks for making this PR! We'd love to get a solution to this, but I think the right way to do it is to add a URL prefix, since we'd need to adjust all of the URL endpoints (such as `api/predict` and `/login'), not just the main Gradio app landing page ('/')

FastAPI supports URL prefixes in a couple of different ways, it looks like:
* Sub-applications:  https://fastapi.tiangolo.com/advanced/sub-applications/
* API Routers: https://fastapi.tiangolo.com/tutorial/bigger-applications/#another-module-with-apirouter

I think the first (sub-application) approach should work quite well. 

Secondly, we will need to make sure that in the frontend, all of the paths are updated to include the prefix as well so that they target the right API endpoints.

cc @aliabid94

**Comment by bottledmind** [comment]
> Secondly, we will need to make sure that in the frontend, all of the paths are updated to include the prefix as well so that they target the right API endpoints.

If so, I think I have to close this PR since I haven't written a single JS app or even script in my life

**Comment by abidlabs** [comment]
Hi @bottledmind yes, the frontend will need adjustment, otherwise it will send requests to the original API endpoint. I will close the PR for now then and we'll work on this later!

**Pull request closed without merging**
