### PR TITLE
SSR e2e + fixes

### PR DESCRIPTION
**Pull request by pngwn**
## Description

Please include a concise summary, in clear English, of the changes in this pull request. If it closes an issue, please mention it here.

Closes: #(issue)

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Taking a look at this now. I'll

* Verify that `css`, `js`, and `head` work in SSR
* Verify that SPA mode continue to work
* Try to get the remaining SSR e2e tests to pass

**Comment by abidlabs** [comment]
Seeing this error:

> Uncaught TypeError: Cannot destructure property 'tick' of 'window.__gradio__svelte__internal' as it is undefined.
    at VM176 index-CSqBRzlx.js:9:12880

in the deployed Spaces: https://huggingface.co/spaces/gradio-pr-deploys/pr-9590-all-demos

**Review by abidlabs — APPROVED** [review]
Thanks @pngwn! I can confirm that custom css and head params work, so I'll go ahead and approve this.

I do still notice two differences between SSR mode and SPA mode:

* The title in an Interface/chatinterface is not centered in SSR mode
* The height of ChatInterface is much smaller in SSR mode (this one in particular will degrade a lot of Chat Spaces imo)

Both of these can be seen by running: `GRADIO_SSR_MODE=true python demo/chatinterface_multimodal/run.py `

**Comment by pngwn** [comment]
Thanks @abidlabs! I'll fix in a follup.

**Pull request merged**
