### PR TITLE
Adding Timestamps for logs.csv

### PR DESCRIPTION
**Pull request by harjyotbagga**
Since most of us use gradio during the development cycle. I thought it is essential to add Timestamps for our logs so that we could keep track of all the logs.
Hence, I added the 'Timestamp' field to the csv file. I have tested and have run these changes locally.

gradio-logs-csv

### CODE REVIEW

**Comment by aliabid94** [comment]
Neat addition! What do you think about using unix timestamps instead?

**Comment by harjyotbagga** [comment]
I did think about that, but not everyone understands UNIX timestamps. My main aim was to make the logs (and log timings) comprehendible to beginners as well.
Still if you insist, I'll change them to UNIX timestamps.

**Comment by aliabid94** [comment]
I think your reasoning is fair, it's helpful to have readable timestamps. I'll take care of the merge conflict soon - thanks for the submission @harjyotbagga !

**Comment by harjyotbagga** [comment]
Is there anything to change with regards to the PR?

**Comment by aliabid94** [comment]
Nope, I’ll merge it in later today :)

**Comment by aliabid94** [comment]
Thanks for the submission! I moved the timestamps column to the end to provide backwards compatibility for csv files using older gradio flagged data readers.

**Pull request merged**
