### PR TITLE
Lite load perf ci

### PR DESCRIPTION
**Pull request by whitphx**
## Description

Closes: #8193

### CODE REVIEW

**Comment by whitphx** [comment]
@pngwn @freddyaboulton What do you think is an appropriate way to inform the performance measurement result to us from the CI runs?
Use `comment-pr` [extending it](https://github.com/gradio-app/github/blob/b522cdb7e17e78c269dd5d9862442510bf1ca608/packages/comment-pr/index.ts#L280-L367) to an accept additional key e.g. "functional" for this run type?

**Comment by pngwn** [comment]
Depends on how we want to display it / how much info there is to display. We could add an additional entry to the table, or we could add another chunk of markdown to the  comment, after or before the `pip install` instructions.

How do you think it would be best to display the info?

**Comment by whitphx** [comment]
@pngwn I think showing a new Markdown section would be good.
At this moment the info to display is only the total loading time,
and perhaps it will be a table with a few rows displaying a bit more detailed durations.

**Comment by abidlabs** [comment]
What's the status of this @whitphx?

**Comment by whitphx** [comment]
@pngwn Do you have any idea about how to post messages to the PR pages from the test-functional workflow?
If not, wdyt about merging this PR at this point leaving the posting functionality as a todo?

**Comment by pngwn** [comment]
I forgot to respond shortly.

**Comment by pngwn** [comment]
I think it's good to merge now. We can follow up the PR comment in a new PR.

**Comment by abidlabs** [comment]
Let's go ahead and merge in for the release! Thanks @whitphx

**Pull request merged**
