### PR TITLE
Export `Tabs` type from `@gradio/tabs` and fix the Playground to be compatible with the new Tabs API

### PR DESCRIPTION
**Pull request by whitphx**
## Description

Fix the bug at https://www.gradio.app/playground. `<Tabs>` now requires the `initial_tabs` prop.

```
20.BbLaLaJX.js:315 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'findIndex')
    at Jk (20.BbLaLaJX.js:315:16140)
    at K (index.DLy6jnDj.js:1:1499)
    at new Zk (20.BbLaLaJX.js:315:18293)
    at Bm (20.BbLaLaJX.js:2394:985)
    at Array.E_ (20.BbLaLaJX.js:2401:3828)
    at mt (scheduler.sY3Ewlbx.js:1:840)
    at i_ (20.BbLaLaJX.js:315:22957)
    at K (index.DLy6jnDj.js:1:1698)
    at new l_ (20.BbLaLaJX.js:315:25177)
    at M_ (20.BbLaLaJX.js:2401:6971)
```

CleanShot 2024-10-17 at 10 32 30@2x

### CODE REVIEW

**Review by pngwn — APPROVED** [review]
This looks great. Thanks for catching this @whitphx. We should probably also add a default empty array to the Index.html just to be safe (but your changes are still kind of needed to be SSR friendly).

**Comment by whitphx** [comment]
Thanks! Like this?

**Comment by pngwn** [comment]
Yep. That's perfect.

**Comment by abidlabs** [comment]
Thanks folks! Merging in to reduce the number of open PRs

**Pull request merged**
