### PR TITLE
Update running-gradio-on-your-web-server-with-nginx.md

### PR DESCRIPTION
**Pull request by lfuelling**
## Description

This PR adds the `proxy_buffering off;` parameter to the example NGINX config.

Closes: #6341

## Tests

I've only changed a guide, no tests should be necessary for this.

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks @lfuelling we can update this. Could you please just confirm that you've tested this in the latest version of Gradio (4.9.1) and this configuration works for you?

**Comment by abidlabs** [comment]
Just wanted to check in @lfuelling on the comment above?

**Comment by lfuelling** [comment]
@abidlabs sorry for the slow response.

The `proxy_buffering off;` directive was required to get it to work at all in my case, previously requests would fail in a weird way.

**Comment by abidlabs** [comment]
Thanks makes sense, which version of Gradio were you running?

**Comment by lfuelling** [comment]
I am using Gradio 4.4.1

**Comment by abidlabs** [comment]
Ok great, I'll go ahead and merge this in then, as Gradio 4.4.1 uses the new SSE approach in favor of websockets. Thanks for the fix!

**Comment by lfuelling** [comment]
Ah that makes sense, I read something about websockes and was massively confused when I only saw "regular" HTTP :)

**Comment by abidlabs** [comment]
Ah that's probably outdated documentation, working on fixing that!

**Pull request merged**
