### PR TITLE
Fix issue with `head` param when adding more than one script tag

### PR DESCRIPTION
**Pull request by dawoodkhan82**
## Description
Fixes issue with `head` param when adding more than one script tag.

Closes: #6426

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by dawoodkhan82** [comment]
@abidlabs Trying to debug, not sure what changed.

**Comment by abidlabs** [comment]
@dawoodkhan82 just fyi I think this was the case before as well -- the script would not get executed

**Comment by abidlabs** [comment]
Based on this part of the original issue:

> Additionally, in this case it seems like the script tag is added to the head section after the page already loads, so it never gets executed? The console output is empty.

**Comment by pngwn** [comment]
The script being added later shouldn't stop it from being executed.

**Comment by dawoodkhan82** [comment]
Fixed, realized I was pushing to the wrong branch...

**Comment by dawoodkhan82** [comment]
Also, now it works when trying to call an external `js` file:

```
import gradio as gr
import os

path = os.path.join(os.path.dirname(__file__), "test.js")
head = """
<script type="text/javascript" src={}></script>
<script>console.log('hello')</script>
""".format(path)

with gr.Blocks(head=head) as demo:
    pass

demo.launch()
```

**Comment by freddyaboulton** [comment]
I took a pass and I wasn't able to get the external script loading to work. @dawoodkhan82 is looking into it! 🙏

**Comment by abidlabs** [comment]
Beautiful! Works for me. 

The original code I shared works as well as loading js from an external PR. 

Here's what I tried:

```py
import gradio as gr
import os

head = """
<script type="text/javascript" src="/file=test.js"></script>
<script>console.log('hello')</script>
""".format(path)

with gr.Blocks(head=head) as demo:
    pass

demo.launch(allowed_paths=["test.js"])
```

Here's `test.js`:

```
console.log('world');
```

**Review by abidlabs — APPROVED** [review]
Awesome stuff @dawoodkhan82

**Comment by dawoodkhan82** [comment]
@abidlabs Thanks for the review!
@freddyaboulton does adding `demo.launch(allowed_paths=["test.js"])` to the demo fix the issue you were seeing?

**Comment by abidlabs** [comment]
merging ahead of the release

**Pull request merged**
