### PR TITLE
Remove `IOComponent.add_interactive_to_config`

### PR DESCRIPTION
**Pull request by space-nuko**
Related: #3438

### CODE REVIEW

**Comment by abidlabs** [comment]
Hi @space-nuko, thanks for making this contribution. I think the best way to make this fix is actually to treat `interactive as any other parameter in `.update()` -- so instead of:

```py
"mode": "dynamic" if interactive else "static",
```

we change it to:

```py
"interactive": interactive
```

And then in the `postprocess_update_dict()` in `blocks.py`, we convert the "interactive" key to the "mode" key. That way, we avoid a lot of the code repetition. 

Would you be able to make that change?

Also, thanks for updating the Guide. Are you interested in contributing a component? We're working on revamping that whole process to make it much better.

**Comment by abidlabs** [comment]
Thanks for making the update @space-nuko! I believe the tests are failing because we don't leave the key `interactive` in the config dictionary. I've suggested a fix above. Once this is fixed, and you've added an entry to `CHANGELOG.md` so that we can credit you for the fix, we should be good to merge.

**Comment by abidlabs** [comment]
Thanks for getting the tests to work out @space-nuko, LGTM! We’ll merge in later today or tomorrow before we release the next  version of Gradio to Pypi

**Review by abidlabs — APPROVED** [review]

**Comment by space-nuko** [comment]
Yeah np, sorry about that it's difficult for me to run the tests on my box right now with the dependency issue

**Comment by abidlabs** [comment]
There was just one issue with the line endings. Apparently `test/test_blocks.py` had been committed with windows-style endings, which meant that the GitHub diff showed every line as changed. I've converted that back to Linux style line endings (you can configure that locally for yourself by running `git config --global core.autocrlf true` [as described here](https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings))

**Comment by abidlabs** [comment]
Merged. Thanks again @space-nuko for the PR!

**Pull request merged**
