### PR TITLE
Upload audio ios

### PR DESCRIPTION
**Pull request by aliabid94**
iOS is not able to filter for audio files correctly. Seems like a longstanding bug, and prevents users form uploading any audio files. So if on iOS, allows user to upload any file for the audio component.

Fixes: #4021

### CODE REVIEW

**Comment by abidlabs** [comment]
Cool @aliabid94! Based on the discussion in the original issue, I think a simpler solution might be just to list the mimetypes out explicitly: list each allowed audio type explicitly, `accept="audio/mp3, audio/wav,..."`, and then you can include "audio/*" at the end to be safe. (Haven't tested this, but cc @drscotthawley)

**Comment by drscotthawley** [comment]
This works on my iPhone. 👍

**Comment by aliabid94** [comment]
> list each allowed audio type explicitly, accept="audio/mp3, audio/wav,...", and then you can include "audio/*" 

This works, changed to this

**Comment by abidlabs** [comment]
Nice, it even allows you to upload a video from your phone and it automatically extracts the audio. Very cool LGTM @aliabid94!

**Review by abidlabs — APPROVED** [review]

**Pull request merged**
