### PR TITLE
fix wc error in dev mode

### PR DESCRIPTION
**Pull request by pngwn**
This fixes an error we have been getting with the web component in dev mode. I do not know if this was causing any issues, nor do I know if this will fix the recent issues some people have had with dev mode not working correctly.

### CODE REVIEW

**Comment by freddyaboulton** [comment]
How do I test this? dev mode reloads fine for me on latest main

**Comment by pngwn** [comment]
If there are no errors in the console when running dev mode then it is working basically. Not sure if it had any impact really but thought it was worth cleaning up.

**Review by freddyaboulton — APPROVED** [review]
Cool, thanks @pngwn !

**Comment by freddyaboulton** [comment]
Merging - thanks again @pngwn !

**Pull request merged**
