### PR TITLE
Issue 5245: consolidate usage of requests and httpx

### PR DESCRIPTION
**Pull request by cswamy**
## Description

Please include a concise summary, in clear English, of the changes in this pull request. If it closes an issue, please mention it here.

Closes: #5245 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks @cswamy for this nice PR! It'd be great to eliminate `requests` as a dependency.

It looks like some backend tests are failing as a result of this refactor. Would you be able to see why and make the necessary fixes?

**Comment by cswamy** [comment]
Hi @abidlabs can you please check now? Tests passed for me (other than 3 that currently fail on main).

Screenshot 2023-11-30 at 10 40 51

**Comment by abidlabs** [comment]
Taking a look now @cswamy!

**Comment by abidlabs** [comment]
I removed `requests` from the `gradio_client` library as well, although now some client tests are failing. Need to look into this. I'll revisit this, but if you'd like to take a look in the meantime, that'd be appreciated @cswamy

**Comment by cswamy** [comment]
@abidlabs deployed few fixes. all seems fine except 1 test in client/python/test/test_utils.py that I am struggling to fix

**Comment by cswamy** [comment]
@abidlabs pushed another fix. looks like it's all good now?

**Comment by abidlabs** [comment]
Thanks again for the awesome PR @cswamy! I've confirmed that locally tests pass & that a variety of demos look good.

Merging.

**Pull request merged**
