### PR TITLE
Clean history

### PR DESCRIPTION
**Pull request by FarukOzderim**
There was a 51MB file in the recent history.
Removed it with a commit, then used [BFG](https://rtyley.github.io/bfg-repo-cleaner/) to clean the history from 50MB+ files.

`java -jar bfg-1.14.0.jar --strip-blobs-bigger-than 50M`

Previously:
```
$ git rev-list --objects --all |   git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' |   sed -n 's/^blob //p' |   sort --numeric-sort --key=2 |   cut -c 1-12,41- |   $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest | tail
37ae79b4a37b  1.8MiB dist/gradio-0.7.3-py3-none-any.whl
416c9e939517  1.9MiB build/lib/gradio/static/js/vendor/kekule.min.js
3a653eb2157a  2.5MiB demo/sepia_filter/screenshot.gif
3a714b0883bc  3.4MiB gradio/frontend/static/js/2.0081c136.chunk.js.map
e56bbca9b6c1  3.6MiB gradio/frontend/static/bundle.js.map
29ea5dade54c  3.6MiB gradio/frontend/static/bundle.js.map
758bbe5bfe94  3.6MiB gradio/frontend/static/bundle.js.map
b94db7a6e197  3.6MiB gradio/frontend/static/bundle.js.map
a74515c9c67e  5.2MiB gradio/templates/frontend/static/bundle.js
4f61e1e15af2  8.2MiB website/homepage/src/assets/img/hf_demo.gif
e2b50f155e80   53MiB demo/streaming_stt/deepspeech-0.8.2-models.pbmm
```

Currently:
```
$ git rev-list --objects --all |   git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' |   sed -n 's/^blob //p' |   sort --numeric-sort --key=2 |   cut -c 1-12,41- |   $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest | tail
37ae79b4a37b  1.8MiB dist/gradio-0.7.3-py3-none-any.whl
416c9e939517  1.9MiB build/lib/gradio/static/js/vendor/kekule.min.js
3a653eb2157a  2.5MiB demo/sepia_filter/screenshot.gif
3a714b0883bc  3.4MiB gradio/frontend/static/js/2.0081c136.chunk.js.map
e56bbca9b6c1  3.6MiB gradio/frontend/static/bundle.js.map
29ea5dade54c  3.6MiB gradio/frontend/static/bundle.js.map
758bbe5bfe94  3.6MiB gradio/frontend/static/bundle.js.map
b94db7a6e197  3.6MiB gradio/frontend/static/bundle.js.map
a74515c9c67e  5.2MiB gradio/templates/frontend/static/bundle.js
4f61e1e15af2  8.2MiB website/homepage/src/assets/img/hf_demo.gif
```

### CODE REVIEW

**Comment by FarukOzderim** [comment]
Every commit until the related commit was updated with a new commit id, see 
**git log**

```
commit 29ced6247fda1d97de2fa5119a70e476784746ee (HEAD -> Clean-History, origin/Clean-History)
Author: Ömer Faruk Özdemir <farukozderim@gmail.com>
Date:   Sat Mar 12 06:30:40 2022 +0300

    Clean-History
    - Remove 51MB file with this commit


    Former-commit-id: 84ca1ff631a92efc8c0cfd485aa27e5b143688fc

commit 03286cf5231b06b024a00b03ca63d01def19df24 (origin/master, origin/HEAD, master)
Author: Julien Chaumond <julien@huggingface.co>
Date:   Fri Mar 11 17:01:03 2022 -0500

    Fix type of server returned by `Launchable` (#810)

    * `Launchable` returns a FastAPI now

    * Update .gitignore

    Former-commit-id: ab67ce3dee572c380465145f3cd6873f7232c14f [formerly 94fac2e3df9f971f9dc7ae941447e600a6ae58d6]
    Former-commit-id: 8f3286222adedac2cab99e7b49375ec0e05c032b

commit 9a41f1b5c1b2e4ce49362bba6c819d550e411002
Author: Julien Chaumond <julien@huggingface.co>
Date:   Fri Mar 11 11:28:47 2022 -0500

    Update getting_started.md (#808)



    Former-commit-id: 79505ba76df9e99311684d06c1c5ff6e91026c87

commit 5a1e20a6577f9ad1f27dd5b003995a49eb781258
Author: Ali Abdalla <ali.si3luwa@gmail.com>
Date:   Fri Mar 11 18:24:35 2022 +0200

    fix search bug in guides (#809)



    Former-commit-id: c95ca81cb719d8c0e198e2a22ea9cf8cd0f4e388

commit c484847adf2d693741b35de9ead85c6e3f855b25
Author: Ali Abdalla <ali.si3luwa@gmail.com>
Date:   Fri Mar 11 15:15:24 2022 +0200

    Website Tracker Slackbot (#797)
...
```

**Comment by abidlabs** [comment]
LGTM.

**Comment by FarukOzderim** [comment]
> When I check out this PR and run
> 
> ```
> $ git rev-list --objects --all |   git cat-file --batch-check='%(objecttype) %(objectname) %(objectsize) %(rest)' |   sed -n 's/^blob //p' |   sort --numeric-sort --key=2 |   cut -c 1-12,41- |   $(command -v gnumfmt || echo numfmt) --field=2 --to=iec-i --suffix=B --padding=7 --round=nearest | tail
> ```
> 
> It still lists the 53MiB file. Do I need to do something different?

After I `git pull`, that seems to be the case with me as well. Let me put another commit and push and see whether that fixes it.
Maybe it is necessary to commit directly to the master.

**Comment by abidlabs** [comment]
> You will have to get a one-time permission to push to master and overwrite the whole repo. This will push new versions of all tags, it will change the branch pointer for all users of the repo (and subsequently **break all forks and outstanding pull-requests**.)

I agree we should do it, but I think we should wait until we have fewer big PRs open.

**Comment by abidlabs** [comment]
Recently, last week

**Comment by FarukOzderim** [comment]
> > You will have to get a one-time permission to push to master and overwrite the whole repo. This will push new versions of all tags, it will change the branch pointer for all users of the repo (and subsequently **break all forks and outstanding pull-requests**.)
> 
> I agree we should do it, but I think we should wait until we have fewer big PRs open.

Would it affect the open PRs though, I am not sure at that front.

**Comment by julien-c** [comment]
> Would it affect the open PRs though, I am not sure at that front.

only PRs targeting a commit (i.e., opened) on `main` after the offending commit

**Comment by LysandreJik** [comment]
I agree with @julien-c that this should be done as soon as possible, as the resulting consequences can be hard on contributors; the state of `master` can usually be recovered with `git reset origin/master --soft` if they have some local changes, and `git reset origin/master --hard` if they don't care for them.

AFAIU, GitHub should be able to handle the fact that the `master` branch was updated and should update the pull requests to the correct reference, so I don't think there should be any issues for PRs (I'm not sure for PRs opened after the problematic commit, but I think GitHub might handle this scenario well too).

**Comment by FarukOzderim** [comment]
Then I am making this update today @abidlabs?

**Comment by abidlabs** [comment]
Sounds good!

**Pull request closed without merging**
