### PR TITLE
V4: Fix component update bug 

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

`elem_classes` was being stored as `None` in the `constructor_args` property of the `Block`. When you returned a new component in an event, `elem_classes=None` was being passed to the frontend app, which caused it to break since it was expecting a list.

You can see the bug by running `fake_diffusion_with_gif` on `v4`. After you click the submit button, it will crash after the first update.

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Tested and works! However, I would have expected this to cause an issue if an output component initially has some `elem_classes` but then it is updated by returning a new component. I would have expected the custom `elem_classes` to be gone. However, this does not appear to be the case, do you know why?

**Review by abidlabs — APPROVED** [review]

**Comment by freddyaboulton** [comment]
@abidlabs We update the props that are sent to the front-end based on the props set during the event. So if elem_classes is not updated, `[]` gets sent to the front-end. If it does, the updated value gets sent. This is the same behavior on main, haven't changed that in v4 branch.

**Comment by freddyaboulton** [comment]
Thanks for the review!!

**Comment by abidlabs** [comment]
Ah I see thanks @freddyaboulton!

**Pull request merged**
