### PR TITLE
Fix cache examples for audio, video and image

### PR DESCRIPTION
**Pull request by dawoodkhan82**
# Description
Fixes issue where clicking on cached examples on and video and audio demos would not work.
Context:
https://huggingface.slack.com/archives/C02Q9UFS8AW/p1653432160679459

Please include: 
* relevant motivation
* a summary of the change 
* which issue is fixed. 
* any additional dependencies that are required for this change.

Closes: # (issue)

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by dawoodkhan82** [comment]
@abidlabs Can you verify this change makes sense? This fixes cache examples, because the frontend expects base64 representations of the examples to display in the component; not the file path. This is the same fix for the Image component in PR #1455

**Comment by abidlabs** [comment]
Both this PR and #1455 look reasonable to me, though I haven't tested extensively. @aliabid94 can you review them as well?

**Comment by aliabid94** [comment]
We actually don't want to send the entire audio and video as a base64 because that would be a massive amount of data being processed and sent at once - we instead want the frontend to be able to buffer chunks of the source audio/video at a time. We used to have frontend support for URLs and need to bring that back.

**Comment by abidlabs** [comment]
@dawoodkhan82 looks like there is a failing test here: `TestImage.test_component_functions`

There's also a failing `external.py` test but you can ignore that, as that seems to be a rate limited HF Space

**Comment by dawoodkhan82** [comment]
> @dawoodkhan82 looks like there is a failing test here: `TestImage.test_component_functions`
> 
> There's also a failing `external.py` test but you can ignore that, as that seems to be a rate limited HF Space

fixed

**Comment by abidlabs** [comment]
LGTM!

**Review by abidlabs — APPROVED** [review]

**Pull request merged**
