### PR TITLE
Performance improvements to docs 

### PR DESCRIPTION
**Pull request by aliabd**
I made some performance improvements to the docs, especially on mobile. I know we've talked about moving the website to a better framework, and we should still do that, but we have to make fixes now as they are currently unusable. 

* Enabled text compression (on nginx) 
* For mobile on load gradio js when example window is clicked. (this means no embedded components on mobile, but much better performance) 
* Figured out a memory leak that was causing the page to climb to insane amounts of memory (>9GB). Was due to some terrible js I wrote for hiding footers from embedded components. Fixed now and page stays at ~350MB.
* Fixed some annoying layout shifts 
* Made the page mobile responsive 

Before changes: 

Screen Shot 2022-11-25 at 5 10 56 PM

After: 

Screen Shot 2022-11-27 at 10 05 09 PM

Try comparing between the [website](https://gradio.app/docs/main) and [dev server](https://www.gradio-staging.com/docs/main) on mobile. Note that most of these changes will only apply to /docs/main/ until we release a new pip version and /docs gets updated. 

Closes: #2717

### CODE REVIEW

**Comment by abidlabs** [comment]
1 -> 91 🔥🔥🔥

**Review by pngwn — APPROVED** [review]
I'm not seeing the 91, i get ~60 after a few tries but ~1 -> ~60 is huge. There is also a noticeable improvement in performance even without using automated testing. The old version of the docs is frequently unusable, even on desktop for me and closing it takes many seconds + locks up my browser. On mobile the current docs are completely unusable.

Regardless of whether it is 60 or 90 we should ship this asap, huge improvement. Awesome work @aliabd!

**Comment by aliabd** [comment]
Hmm that's weird @pngwn, are you sure that's for /docs/main on www.gradio-staging.com and testing for mobile? I just got 93. I did see high 80s a few times but never 60. Maybe it's a latency thing! 

But yes, the number doesn't really matter.

**Comment by aliabd** [comment]
Btw @pngwn do you know how we'd enable text compression on the gradio.js served from s3? like https://gradio.s3-us-west-2.amazonaws.com/3.11.0/gradio.js 

I think we'll have to zip them before uploading to s3. but not sure if there's a better way?

**Comment by abidlabs** [comment]
LGTM @aliabd! The staging website loads significantly faster for me on desktop as well. 

The CircleCI test that is failing is because the Hub is down. Rerunning that should cause it to pass (although we should mark it flaky for future reference)

**Review by abidlabs — APPROVED** [review]

**Comment by aliabd** [comment]
Will try to figure out gzipping the gradio.js s3 module on a separate PR

**Pull request merged**
