### PR TITLE
Fixes data updating invoke the `select` event

### PR DESCRIPTION
**Pull request by yiyuezhuo**
# Description

Now it's strange that `data` updating will invoke a `select` event once the DataFrame is selected:

```javascript
	$: {
		if (selected !== false) {
			selected_invoked = true;
			const loc = selected.split("-");
			const row = parseInt(loc[0]);
			const col = parseInt(loc[1]);
			dispatch("select", { index: [row, col], value: data[row][col].value });
		}
	}
```

This should be fixed by adding a `selected_invoked` variable, which permits the dispatching of the `select` one time once a new cell is selected:

```javascript
	let selected_invoked: boolean = false;

	$: {
		if (selected !== false) {
			selected_invoked = false; // Prevent data updating invoke the `select` event.
		}
	}
	$: {
		if (selected !== false && !selected_invoked) {
			selected_invoked = true;
			const loc = selected.split("-");
			const row = parseInt(loc[0]);
			const col = parseInt(loc[1]);
			dispatch("select", { index: [row, col], value: data[row][col].value });
		}
	}
```

Is it required to write unit tests for the fix? The frontend test seems very sparse (if the `npm test` actually covers all the tests), so I don't know where to start.

Further works:

- Variable `selected` should be set to `false` at some places (e.x. when the pointed cell doesn't exist in the table anymore due to updating). But it's complicated, since we may still want the previous pointed location for some reason. So it's desired to be able to update the `selected` state from Python.
- Should clicking the same cell invoke multiple times invoke the `select` event multiple times? (Now it will only invoke once.)

Closes: #3856

No additional dependencies.

# Checklist:

- [X] I have performed a self-review of my own code
- [X] I have added a short summary of my change to the CHANGELOG.md
- [X] My code follows the style guidelines of this project
- [X] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks @yiyuezhuo for the fix! @aliabid94 can you review this PR?

**Comment by aliabid94** [comment]
Thanks for the PR @yiyuezhuo! I modified it slightly so that the data variable is not inside the reactive statement, so it should not be dispatching select in response to data changes.

**Comment by aliabid94** [comment]
@pngwn feel free to give my edit a quick review, otherwise will merge later today

**Comment by qtli** [comment]
Hi, thanks for your all valuable commitment. I use the newest Gradio version (3.27.0). However, the bug mentioned in #3861 is still there. 

I don't know whether I miss some updated version.

**Comment by yiyuezhuo** [comment]
@qtli 3.27.0 is released 2 weeks ago so I guess you need to clone and build from the latest main branch. For reference: https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md

**Comment by abidlabs** [comment]
Yes that's right, thanks @yiyuezhuo. @qtli you can install gradio from main by following the instructions here: https://gradio.app/docs/main

**Pull request merged**
