### PR TITLE
Add Clear Mask button to sketch mode

### LINKED ISSUE #3536: Clear mask button for `gr.Image` sketch modes
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Simple request, just a "clear mask" button for `gr.Image` sketch modes. RIght now you either have to click through your entire undo history or delete and reopen the image to clear the mask

One more thing, the "X" button for the sketch settings removes the whole image. However I frequently mistake its function for the mask clearing feature I want. I propose that

- "Clear mask" is "X"
- "Delete image" is a trash-can symbol or similar

...or whatever UX pattern makes the most sense for you

**Describe the solution you'd like**  
"Clear mask" button added to `tool=sketch` and `tool=color-sketch`

**Additional context**  
N/A

### PR DESCRIPTION
**Pull request by space-nuko**
# Description

Closes #3536

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by space-nuko** [comment]
I think the icon looks incorrect, is there a place Gradio sources icons from?

**Comment by pngwn** [comment]
Will look at this when I can.

Image is a low priority atm because it will be rewritten shortly and generally works ok. I'd like to minimise the amount of time I spend on this until we have changed some things.

**Comment by space-nuko** [comment]
The trash can is for deleting the whole image and mask, the 'X' is now the Clear Mask feature, reason is I kept thinking 'X' cleared the mask when it deleted the image

**Comment by aliabid94** [comment]
How about [carbon's Erase](https://icon-sets.iconify.design/carbon/erase/)?
Screen Shot 2023-04-06 at 1 10 00 PM

**Comment by aliabid94** [comment]
Running this locally, it seems glitchy if there's no background image, neither the clear nor trash button work. We probably should only show the clear button anyway if there's no background image. Works great if there's a background image though!

Recording 2023-04-06 at 13 25 40

**Comment by pngwn** [comment]
I don't think erase usually clears anything, it is typically a 'negative brush' so that could be confusing. I think change runs the risk of making the UI less intuitive even though it adds a new capability. Outside of a few 'core' icons, icons do not have universal meaning. This is further compounded by the fact that the icons suggested so far deviate from their common use. Trash icon is usually delete everything/ throw it away, X is close, Eraser is a brush.

I don't feel super strongly so I'm fine with us using erase for now but i don't think it is great. I'll start work on a better approach to the image component shortly to address these issues (and much more besides).

**Review by pngwn — APPROVED** [review]

**Comment by pngwn** [comment]
- use the eraser icon for clear mask, x for clear everything.
- hide the clear_mask button for non-image canvases.
- resolve conflicts.
- fix a bug -- some instances of `ModifySketch` were using the old event name (so it did nothing). This is why it wasn't working for you @aliabid94

**Comment by space-nuko** [comment]
I wonder what happens with the icons if an "erase mask" feature is implemented

**Comment by pngwn** [comment]
We'll be redesigning this component completely anyway and we won't be adding that feature until the redesign is done, so I'm not worried for now.

**Comment by abidlabs** [comment]
LGTM thanks @pngwn and @space-nuko!

**Pull request merged**
