### PR TITLE
Use state in ChatInterface

### LINKED ISSUE #4975: Switch `gr.ChatInterface` to use `gr.State` instead of passing the `gr.Chatbot` content back and forth
As [discussed internally](https://huggingface.slack.com/archives/C05G60G3DU3/p1689768571170509), we should switch `gr.ChatInterface` to use `gr.State` instead of passing the `gr.Chatbot` content back and forth to reduce the payload.

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Fixes #4975

Saves us a trip from client to server but we still send the entire history from the server to the client for streaming updates

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests & Changelog

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

1. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`
  
1. Unless the pull request is labeled with the "no-changelog-update" label by a maintainer of the repo, all pull requests must update the changelog located in `CHANGELOG.md`:

Please add a brief summary of the change to the Upcoming Release section of the `CHANGELOG.md` file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks @freddyaboulton! Taking a look

**Comment by abidlabs** [comment]
@freddyaboulton this looks good, though we can further simplify `_setup_api()` now that we are using `State()` for everything. I'll just push the changes directly to this branch?

**Comment by abidlabs** [comment]
I'm going to merge this in as I'm working on another PR for `gr.ChatInterface` that might lead to conflicts with this one

**Comment by freddyaboulton** [comment]
Thanks for the modifications @abidlabs !

**Pull request merged**
