### PR TITLE
Better empty state for the gr.Gallery component

### PR DESCRIPTION
**Pull request by dawoodkhan82**
# Description
Add empty image icon to gallery when there are no images to show

Screen Shot 2022-08-16 at 2 00 29 PM

Please include: 
* relevant motivation
* a summary of the change 
* which issue is fixed. 
* any additional dependencies that are required for this change.

Closes: # (issue)
#2013

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by dawoodkhan82** [comment]
I can also increase the height to match the empty image component if that would look better.

image

**Review by freddyaboulton — APPROVED** [review]
@dawoodkhan82 Looks good to me on the fake_gan deployed to spaces!

**Comment by dawoodkhan82** [comment]
> @dawoodkhan82 Looks good to me on the fake_gan deployed to spaces!

Nice! The spaces are so useful

**Comment by abidlabs** [comment]
LGTM @dawoodkhan82 thanks for the very quick fix!

**Comment by abidlabs** [comment]
Weird race condition @dawoodkhan82 lol but good to merge

**Pull request merged**
