### PR TITLE
Corner status tracker

### PR DESCRIPTION
**Pull request by aliabid94**
Adds support for a status tracker mode that stays in the top right corner and does not cover the output component, which can be set in an event listener with `show_progress="corner"`. This is the mode always used for chatbots, so the messages do not get covered.

Fixes: #3914 

Recording 2023-06-01 at 13 44 04

### CODE REVIEW

**Comment by pngwn** [comment]
Could we call it `transparent` or something rather than `corner`? Or maybe `minimal` might work?

**Comment by aliabid94** [comment]
> Could we call it transparent or something rather than corner? Or maybe minimal might work?

sure, how about "full", "minimal" and "hidden" then?

**Comment by pngwn** [comment]
Yeah. I think that works. Just in case we move it or redesign it or whatever.

**Comment by abidlabs** [comment]
Isn't this a breaking change? We should still support `show_progress`=True/False for backwards-compatibility. We can just map `True` to "full" and `False` to "hidden".

**Comment by aliabid94** [comment]
> Chatbot also supports show_progress="hidden" (in case someone does not want to show the eta)
okay will do
> If someone does set show_progress="full" for a Chatbot, we should at least display a warning saying that this is not supported for Chatbot
This is kinda tricky, because the default value of the param is "full", so there's no way to tell if the user set it or not. Also, show_progress is tied to event listeners, not components. I think it's fine for this component to not support "full" mode

**Comment by abidlabs** [comment]
> This is kinda tricky, because the default value of the param is "full", so there's no way to tell if the user set it or not. Also, show_progress is tied to event listeners, not components. I think it's fine for this component to not support "full" mode

Ok that's fine then

**Pull request merged**
