### PR TITLE
Fix API info bug

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

We should copy the api_info prior to modifying the urls for file-based components. This copy only happens once. 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Sorry @freddyaboulton can you explain why we need to do this? What bug is this PR addressing?

**Comment by freddyaboulton** [comment]
I noticed that the api_info route stores references to values in the config dict. So it's possible for code in the info route to change values in the config. So it's better if we copy the data (only once) prior to making any modifications.

**Review by abidlabs — APPROVED** [review]
lgtm for now, but this will further degrade performance for apps with large numbers of api endpoints, so I think we should switch to https://github.com/gradio-app/gradio/issues/9574 soon

**Comment by abidlabs** [comment]
I'll go ahead and get this in so that we have fewer open PRs, thanks @freddyaboulton!

**Pull request merged**
