### PR TITLE
Frontend fixes

### PR DESCRIPTION
**Pull request by aliabid94**
Fixes the following:
- Restores gallery mode for single components in Examples / Dataset
- Fixes loader size on initial load
- Fixes loading animation on pending request
- Shrinks size of shadow on input highlight in dark mode

### CODE REVIEW

**Comment by abidlabs** [comment]
Hmm when I click on: https://huggingface.co/spaces/gradio-pr-deploys/pr-3026-all-demos, I get the CSS all broken: 

image

**Comment by aliabid94** [comment]
@abidlabs it works when I load the internal frame directly? Wonder why that might be, looking into it

**Comment by aliabid94** [comment]
ok fixed @abidlabs

**Comment by abidlabs** [comment]
Thanks @aliabid94 for these fixes. However, there are still two differences I noticed between the original styles and the new styles: 

1. with the new styles, there is a shadow that appears when a Gradio app first loads covering the entire screen. This wasn't there in the old style and it looks weird on Spaces where the background of the page is white. It also makes the word "loading" hard to read:

**New style**:
image


**Old style**:

image

2. I _think_ the style of the status tracker is reversed. In the old style, the background of a component would be white and the status tracker would appear as a shadow that progressed from left to right. In the new style, the whole component becomes shadowed and the tracker appears from right to left, which is very unintuitive. The colors of the shadows are slightly different as well

**New style**

image

**Old style**

image

PR deploy for new style: https://huggingface.co/spaces/gradio-pr-deploys/pr-3026-all-demos
PR deploy for old style: https://huggingface.co/spaces/gradio-pr-deploys/pr-3002-all-demos

**Comment by aliabid94** [comment]
All fixed @abidlabs

**Review by abidlabs — APPROVED** [review]
Beautiful thanks @aliabid94!

**Pull request merged**
