### PR TITLE
Fix faded textbox on iOS / Safari

### PR DESCRIPTION
**Pull request by aliabid94**
Fixes: https://github.com/gradio-app/gradio/issues/3974

### CODE REVIEW

**Comment by abidlabs** [comment]
The body of the textbox looks good but the labels are still hard to read:

**Comment by abidlabs** [comment]
954BB399-1CCE-4941-B34F-E3FE0E71658F

**Review by abidlabs — COMMENTED** [review]
The body of the textbox looks good but the labels are still hard to read (see above)

**Comment by abidlabs** [comment]
LGTM, thanks @aliabid94!

**Review by abidlabs — APPROVED** [review]

**Review by freddyaboulton — APPROVED** [review]
Thanks @aliabid94 !

**Pull request merged**
