### PR TITLE
Ensure media queries work for SSR mode

### PR DESCRIPTION
**Pull request by pngwn**
## Description

Please include a concise summary, in clear English, of the changes in this pull request. If it closes an issue, please mention it here.

Closes: #(issue)

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
What's the context for this PR @pngwn?

**Comment by pngwn** [comment]
Oh sorry. This fixes some of the UI issues that were reported. 

- the UI being too wide and not resizing . 
- toasts taking up the whole width of the screen
- probably a few other things that haven't surfaced yet.

**Comment by abidlabs** [comment]
Lgtm @pngwn! I can confirm that some of the styling issues (such as the width of the error messages) have been resolved. However, there are some other ones I noticed while I was testing:

1. The `title` of a `gr.ChatInterface` or `gr.Interface` is not centered
2. The height of `gr.ChatInterface` is not full-screen (however, this might get resolved when @aliabid94 fixes https://github.com/gradio-app/gradio/issues/7714)
3. The fonts between regular mode and SSR are different, but actually think SSR mode shows the correct fonts

Repro with `demo/chatinterface_multimodal/run.py`

**Review by abidlabs — APPROVED** [review]

**Comment by pngwn** [comment]
Thanks for checking this over @abidlabs. I'll open a new PR to resolve those other issues.

**Pull request merged**
