### PR TITLE
Fixes chatbot does not display code blocks correctly

### PR DESCRIPTION
**Pull request by dawoodkhan82**
# Description
Fixes issue where the markdown parser renders code blocks in line, instead of retaining new line info.

Please include: 
* relevant motivation
* a summary of the change 
* which issue is fixed. 
* any additional dependencies that are required for this change.

Closes: #3531

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have added a short summary of my change to the CHANGELOG.md
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by abidlabs** [comment]
Nit: it would be very nice if we could add a bit of padding around the code block and maybe a copy button too :)

**Comment by dawoodkhan82** [comment]
@abidlabs @pngwn Maybe we can just reuse our code component in the chatbot for this.

**Comment by abidlabs** [comment]
Yeah potentially we could do that if codemirror is not too heavy, what do you think @pngwn?

**Comment by dawoodkhan82** [comment]
@abidlabs How about we merge this pr in for now and discuss the code component approach in this [issue](#3831)

**Comment by pngwn** [comment]
The code component is too heavy for this usecase really. I would just do the syntax highlighting on the server and send back the HTML. We can include some default css for the highlighting. If we do this for markdown too it can be shared with the chatbot.

We also need to add the necessary theme variables for syntax highlighting too.

**Comment by pngwn** [comment]
I think its fine to merge this and take care of the highlighting in another PR.

**Comment by abidlabs** [comment]
Hmm I really do think syntax highlighting makes a huge difference. Let me see if I can replicate the fastchat patch

**Comment by abidlabs** [comment]
Sadly, `markdown-it-py` does not seem to have support for server-side syntax highlighting as far as I could tell. I looked into FastChat, and they've switched over to `markdown2` for their markdown renderer. That's something we can explore, but I agree we don't need to hold up this PR for that. 

Just pushed one small tweak, which is to add spacing around the code blocks.

Before:

image

After:

image

If that looks good to you, I'm good with merging.

**Review by abidlabs — APPROVED** [review]

**Comment by abidlabs** [comment]
Merging, thanks @dawoodkhan82!

**Comment by aliabid94** [comment]
> The code component is too heavy for this usecase really

@pngwn Can we do dynamic loading of the Code component in the case that a codeblock is rendered? I think it makes sense to reuse that code.

**Comment by dawoodkhan82** [comment]
@pngwn @aliabid94 Let's move this discussion to #3831

**Pull request merged**
