### PR TITLE
Set orig_name in python client file uploads

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Closes: #8366

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
@freddyaboulton I tested this with a modified version of the repro in the original issue and not sure its working with me. Here's what I tried:

```py
import gradio as gr

def img_test(img):
    return img

with gr.Blocks() as demo:
    image1 = gr.Image(format="png", type="filepath")
    btn = gr.Button(value="process")
    btn.click(fn=img_test,inputs=[image1],outputs=[image1],api_name="process")

_, url, _ = demo.launch()

from gradio_client import Client, file

client = Client(url)
result = client.predict(
		img=file('https://raw.githubusercontent.com/gradio-app/gradio/main/test/test_files/bus.png'),
		api_name="/process"
)
print(result)
```

I still got a .webp image:

```
/private/var/folders/kf/ll6fqkys7_s05x4tvb546mdc0000gn/T/gradio/d5fe0b3ad36a18307d3bba4a5c1a0dd1caa9167c/image.webp
```

**Comment by freddyaboulton** [comment]
@abidlabs should be fixed now! Was an issue with the url case

**Comment by 2265865006** [comment]
Thanys,It looks fine now

**Review by abidlabs — APPROVED** [review]
LGTM and works great! Thanks @freddyaboulton for fixing this

**Comment by freddyaboulton** [comment]
Thank you @abidlabs !

**Pull request merged**
