### PR TITLE
4614 chatbot

### LINKED ISSUE #4514: Copy button not working in code blocks for chatbot
### Describe the bug

image

Copy button is not rendered, instead leaves white space.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr

code = """
```python
def greet(x):
    return "hello, " + x```
"""

message = [(
    "write a python program",
    code
)]

with gr.Blocks() as demo:
    gr.Chatbot(message)
    
demo.launch()
```

### Screenshot

_No response_

### Logs

```shell
N/A
```

### System Info

```shell
N/A
```

### Severity

annoying

### PR DESCRIPTION
**Pull request by pngwn**
# Description

Closes #4514.

Fix is slightly weird. There could be a bug in our code or there could be a really specific bug in Svelte but that will take some time to debug. This seems to work but I'd appreciate it if someone else could test it too.

Please include: 
* relevant motivation
* a summary of the change 
* which issue is fixed. 
* any additional dependencies that are required for this change.

Closes: # (issue)

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have added a short summary of my change to the CHANGELOG.md
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by abidlabs** [comment]
Tested both the code and LaTeX and works great @pngwn!

**Review by abidlabs — APPROVED** [review]

**Comment by abidlabs** [comment]
Unrelated to this bug, but it's been bothering me for a while that the font size of the code doesn't match the font size of the surrounding text: 

image

It looks like the font size of the code is `1em` while the font size of the text is `var(--text-lg)`. Could we make both of the same?

**Comment by pngwn** [comment]
Will merge when CI passes.

**Comment by pngwn** [comment]
wow so fast. nice one @freddyaboulton!

**Pull request merged**
