### PR TITLE
Passes `gr.Request` if type hint is `Request | None`

### PR DESCRIPTION
**Pull request by abidlabs**
Closes: https://github.com/gradio-app/gradio/issues/9002

Test with repro from original issue:

```py
import gradio as gr


def predict(request: gr.Request):
    if request:
        return request.client.host
    else:
        return "No request"


with gr.Blocks() as block:
    text = gr.Textbox(interactive=True)
    text2 = gr.Textbox(interactive=False)
    btn = gr.Button("What is my IP?")

    btn.click(predict, inputs=[], outputs=[text2])

    ex = gr.Examples(
        examples=[["foo", None]],
        example_labels=["click me"],
        inputs=[text],
        outputs=[text2],
        fn=predict,
        cache_examples=False,
    )

block.queue()
block.launch()
```

### CODE REVIEW

**Comment by aliabid94** [comment]
Did you mean to make the demo have the function signature:
`def predict(request: gr.Request | None):`
the above works, but
`def predict(request: None | gr.Request):`
doesn't.

Should there be a more general solution?

**Comment by abidlabs** [comment]
Really? Interesting.. what version of Python are you using?

**Comment by aliabid94** [comment]
Python 3.9.6,
code to repro:
```python
from __future__ import annotations

import gradio as gr


def predict(request: None | gr.Request):
    if request:
        return request.client.host
    else:
        return "No request"


with gr.Blocks() as block:
    text = gr.Textbox(interactive=True)
    text2 = gr.Textbox(interactive=False)
    btn = gr.Button("What is my IP?")

    btn.click(predict, inputs=[], outputs=[text2])

    ex = gr.Examples(
        examples=[["foo", None]],
        example_labels=["click me"],
        inputs=[text],
        outputs=[text2],
        fn=predict,
        cache_examples=False,
    )

block.queue()
block.launch()
```

**Comment by abidlabs** [comment]
I believe the problem should go away on Python 3.10 or higher, and we’re planning on dropping support for Python 3.8 and 3.9 anyways, but I’ll include a fix here

**Comment by abidlabs** [comment]
Fixed now, agreed its hacky but we can remove all this when upgrade to 5.0

**Review by freddyaboulton — APPROVED** [review]
LGTM @abidlabs - thanks for the fix.

**Comment by abidlabs** [comment]
Thanks @freddyaboulton and @aliabid94

**Pull request merged**
