### PR TITLE
Remove deprecated parameters and classes for the 5.0 release

### PR DESCRIPTION
**Pull request by abidlabs**
Closes: https://github.com/gradio-app/gradio/issues/8684

Note: there might be additional things we decide to deprecate, but I wanted to get this first batch of deprecations out to trim the codebase and this way we don't do unnecessary work (e.g. we don't have to worry about the ui redesign of the LogoutButton since we are removing it from the library)

### CODE REVIEW

**Comment by pngwn** [comment]
Why don't we close this PR and leave the branch open and target it (by default).

We can also make it a 'pre-release' branch so we get the auto versioning for pre-releases when we are ready for that.

**Comment by abidlabs** [comment]
Sorry a little confused @pngwn -- did you mean to close this PR instead? https://github.com/gradio-app/gradio/pull/8796

**Comment by pngwn** [comment]
Ah sorry, yes. Too many tabs.

**Comment by abidlabs** [comment]
Ah sure, deleted the branch, whenever you get a chance, can you designate `5.0-dev` a pre-release branch?

**Comment by abidlabs** [comment]
Should I avoid merging this PR in until we have designated `5.0-dev` a pre-release branch?

**Comment by pngwn** [comment]
Maybe yeah. It might not be an issue. But I also don't know what will happen.

**Pull request merged**
