### PR TITLE
Added gradio-in-r

### PR DESCRIPTION
**Pull request by Ifeanyi55**
## Description

I added the page that demonstrates how to build a gradio application in R.

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks so much @Ifeanyi55 for this contribution! I created a new Guide that discusses how to use Gradio in other languages, and moved this to that Guide. Feel free to make any tweaks to this, and we'll merge it in

**Review by Ifeanyi55 — COMMENTED** [review]
This looks good. Thanks for the acknowledgement as well.

**Comment by abidlabs** [comment]
> However, I think the last sentence in the "Using Gradio in R" section needs a little bit of correction, thanks

What do you mean? Feel free to push directly to this branch

**Review by freddyaboulton — APPROVED** [review]

**Review by abidlabs — APPROVED** [review]
Looks great, thanks @Ifeanyi55 for the contribution!

**Pull request merged**
