### PR TITLE
Allow more image formats

### LINKED ISSUE #2418: use next generation lossless image formats
- [X] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
For users hosting gradio for other users, bandwidth usage can be costly.

**Describe the solution you'd like**
Serving images in better lossless image formats like webp, avif and jpegxl would result in a significant drop in bandwidth usage (~20-30%). These saving could be increased significantly by allowing lossy compression (>80%), but users might want to download the lossless version of an image they liked.

**Additional context**  
I just tested this on 3.4.1. webp is already supported by pillow and I used pillow-avif-plugin for avif. As mentioned in https://github.com/python-pillow/Pillow/issues/4247, there is JXLPy too, which I didn't test.
All of those use exif which requires a small bit more work to embed metadata.

### PR DESCRIPTION
**Pull request by fienestar**
# Description

Add wildcard to image input
Fixes #2418

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks for the PR @fienestar! We'll take a look at it and share our feedback, likely early next week

**Comment by dawoodkhan82** [comment]
Thanks @fienestar looks good to me!

@pngwn Was there a reason we had it limited to specific file types?

**Comment by pngwn** [comment]
@dawoodkhan82 Just historic. It was there when i converted from Svelte -> React. Maybe @aliabid94 @abidlabs @aliabd have some insight but i don't think we need to specifically.

I'm just gonna run some tests, to see if this should just be open or configured via a flag to provide the path of least surprise for our users.

**Review by pngwn — APPROVED** [review]
Works fine. PIL supports webp just fine and ffmpeg supports webm. Haven't done extensive testing but the basics work fine with standard python libraries. 

Thanks for the PR @fienestar!

**Comment by pngwn** [comment]
I'll take care of the conflict + merge when CI passes.

**Pull request merged**
