### PR TITLE
Interface fix

### PR DESCRIPTION
**Pull request by pngwn**
Some small tweaks to fix a few errors i came across with interfaces.

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks @pngwn! What errors does this PR fix? That way, I can test them and link potentially related issues

**Comment by pngwn** [comment]
It was runtime errors when running the app. A few of those `cannnot get length of undefined` issues. It was just related to components that don't have children. I also fixed the `HighlightedText` one was a regression (named colours working as part of the color_map #724 ), I think the other was #887. The carousel needs some other work, including on the backend.


The `default_value` changes were a pre-emptive fix because changing the `value` prop to `default_value` on the frontend will break event triggers.

**Comment by pngwn** [comment]
In terms of testing, the kitchen_sink should work (apart from the carousel although it shouldn't error).

**Comment by abidlabs** [comment]
Tested and LGTM!

**Pull request merged**
