### PR TITLE
add support to markdown tables, #1886

### PR DESCRIPTION
**Pull request by zouharvi**
# Description

This 2-lines PR simply enables markdown tables in `gr.Markdown`. Where #1886 failed, the result is now a rendered table. It's however lacking any e.g. sort-by support as the proper `gr.Dataframe`. The styling may also be unsuitable.
 
image

Closes: #1886 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by abidlabs** [comment]
Thank you so much @zouharvi for fixing this! Would you also be able to add support here: https://github.com/gradio-app/gradio/blob/0474e460add85a192ac2961e3609f5195939b318/gradio/interface.py#L291

So that we can have Markdown tables in a Gradio Interface description / article?

**Comment by zouharvi** [comment]
@abidlabs I added it there as well. I knew it was there but didn't know exactly what it does so I didn't touch it before. One regression is that in the dark theme, the header doesn't get styled and as such is illegible (first two items highlighted with cursor):

image

**Comment by abidlabs** [comment]
LGTM thanks @zouharvi for the contribution!

**Comment by abidlabs** [comment]
We'll take care of the dark theme issue as part of #1746!

**Pull request merged**
