### PR TITLE
add space header

### LINKED ISSUE #8742: Add mini header for apps deployed on spaces
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  

When visiting a space via its subdomain or custom domain (not in the spaces chrome) it. An be difficult to discover the original space, source code and discussions. 

**Describe the solution you'd like**  

We should add a mini header to aid discoverabiilty of the original space. 

**Additional context**  

https://huggingface.co/docs/huggingface.js/en/space-header/README

### PR DESCRIPTION
**Pull request by pngwn**
## Description

To test we will use this space: https://huggingface.co/spaces/pngwn/space-header-test

If you visit this space there is no header  but if you go the direct domain we can see this: https://pngwn-space-header-test.hf.space/

You may not that if you go here: https://huggingface.co/spaces/gradio-pr-deploys/pr-8846-all-demos or to the direct domain https://gradio-pr-deploys-pr-8846-all-demos.hf.space/ then you never see the header. This is because this space embeds app with iframes and that is one of the heuristics we use to decide whether or not to show the header.

cc @julien-c @gary149 for visibility

Closes #8742.

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by pngwn** [comment]
I am making test. I don't know if this works.

**Comment by abidlabs** [comment]
Looks nice @pngwn! Just a few things I noticed:

image

(1) Clicking on the down array on the right side of the header causes the header to disappear. This seems unexpected?

image

(2) Re:

> to the direct domain https://gradio-pr-deploys-pr-8846-all-demos.hf.space/ then you never see the header. This is because this space embeds app with iframes and that is one of the heuristics we use to decide whether or not to show the header.

I actually don't understand why the direct domain doesn't show the spaces header? Is it because it is a FastAPI app that mounts Gradio apps on subpaths? I do see that the header pops up nicely on subpaths, e.g.: https://gradio-pr-deploys-pr-8846-all-demos.hf.space/demo/calculator/

(3) Have we tested to ensure embeds continue to work (and don't show this header in the embedded gradio app)?

(4) Noticed that the styling of the chat messages is off in the test space, I assume this is unrelated?

image

**Comment by pngwn** [comment]
> Clicking on the down array on the right side of the header causes the header to disappear. This seems unexpected?

This is the intended functionality. I discussed it with @gary149 and @julien-c.

> I actually don't understand why the direct domain doesn't show the spaces header? Is it because it is a FastAPI app that mounts Gradio apps on subpaths?

Yeah, the gradio apps are all on individual subpaths, the space inserts an iframe with the src equal to those subpaths/ Accvessing them directly bypasses the shell app that does the iframe embedding.

> Have we tested to ensure embeds continue to work (and don't show this header in the embedded gradio app)?

I did some local testing yes.

> Noticed that the styling of the chat messages is off in the test space, I assume this is unrelated?

I think so but I'll check.

**Comment by abidlabs** [comment]
Thanks @pngwn!

> Noticed that the styling of the chat messages is off in the test space, I assume this is unrelated?

Yes it seems unrelated since https://gradio-pr-deploys-pr-8846-all-demos.hf.space/demo/chatbot_multimodal/ lg

**Review by abidlabs — APPROVED** [review]
sweeet @pngwn!

**Comment by julien-c** [comment]
yay!!! i'll try to give this a try in the coming days

**Comment by julien-c** [comment]
hmm one thing i notice is when the user or org doesn't have an avatar we display a broken image:

image

(from https://gradio-pr-deploys-pr-8846-all-demos.hf.space/demo/chatbot_multimodal/ )

not sure if that'd be the case in prod or not

**Comment by julien-c** [comment]
tagging @enzostvs btw as you might want to take a look at the PR

**Pull request merged**
