### PR TITLE
Add `allow_file_downloads` param to allow downloading image/video/audio media in chatbot

### PR DESCRIPTION
**Pull request by hannahblair**
## Description

We were never (iiuc) showing the download button in media messages in chatbot. I'e added an `allow_file_downloads` (default is false) param in case it's not actually wanted by certain users. Let me know if there's a better solution here!

I've also tweaked the padding so that components dont have an unnecessary padding that only text needs (see screenshot).

| base | new |
|--------|--------|
| Screenshot 2024-11-05 at 16 22 21 | Screenshot 2024-11-05 at 16 20 07

Closes: #9217

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by freddyaboulton** [comment]
Nice! Is it possible to respect the show_download_button parameter passed to the component instead of adding a component to the chatbot? I'm confused as to why the download button shows up when passed to the component but only when like/dislike is enabled (quoting from the issue - haven't verified!)

**Review by aliabid94 — APPROVED** [review]
Looks great, thanks for the cleanup also! In response to what the issue is saying, it's only if there is a like listener that it appears in the like row automatically. I think we should remove it from the like row, and have it on media by default?
Screenshot 2024-11-06 at 1 42 22 PM

**Comment by aliabid94** [comment]
I believe now `allow_file_downloads=` is ignored and always visible. 

Unrelated to this PR, if it's a quick fix, the copy button seems broken on media/non-text responses (when there's no like buttons):

Screenshot 2024-11-14 at 2 00 55 PM

**Comment by abidlabs** [comment]
I'll go ahead and merge this in if you don't have any objections @aliabid94!

**Pull request merged**
