### PR TITLE
UI: update error message

### PR DESCRIPTION
**Pull request by gary149**
Fixes: #2206 

image

### CODE REVIEW

**Comment by gary149** [comment]
An alternative idea for non-obstructive notification (not in this PR): 
image

**Comment by abidlabs** [comment]
I really like the 2nd idea (of having the error box in the corner @gary149!). Looks very sleek and I think it is also a little more consistent with Gradio's visual identity

**Comment by gary149** [comment]
Update (I changed the inner component error too - to make it softer)

image

**Comment by abidlabs** [comment]
Beautiful @gary149! LGTM

**Comment by abidlabs** [comment]
Can we open this up for review?

**Comment by aliabid94** [comment]
gorgeous!

**Comment by abidlabs** [comment]
Merging, thank you so much @gary149!

**Pull request merged**
