### PR TITLE
Added dimensionality check to avoid bad array dimensions

### PR DESCRIPTION
**Pull request by THEGAMECHANGER416**
Added a simple dimensionality check to keep the code coherent

## Description

Added a dimensionality check that checks the image dimension and raises a ValueError for improper dimensions (checks if img is Grayscale, RGB or RGBA)

Closes: #5913 

## 🎯 PRs Should Target Issues

Closes issue #5913 which required a very simple small fix.

## Tests

1. Can be merged successfully

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks @THEGAMECHANGER416 lgtm

**Comment by THEGAMECHANGER416** [comment]
@abidlabs Thanks for your reply 
I'm not sure what I need to do next? Pls let me know
Thanks

**Comment by abidlabs** [comment]
You don't have to do anything, I'll merge it in just now

**Comment by THEGAMECHANGER416** [comment]
Hi Hannah,
Thanks for reaching out
I have sent a mail now to ***@***.***
Thanks for this opportunity

**Pull request merged**
