### PR TITLE
Prevent label change event from triggering itself

### LINKED ISSUE #4309: Label.change event re-triggers itself
### Describe the bug

The `Label.change` event fires when its value did not change

In fact the completion of handling the `change` event seems to re-trigger the `change` event

(I encountered this while trying to use a hidden Label as a workaround for `State` objects have no change event https://github.com/gradio-app/gradio/issues/2107)

Issue may be specific to the `Label` component, if I substitute a hidden `Textbox` the issue does not happen

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr

def set_label(val):
    print("set_label")
    return f"> {val}"

def on_change(val):
    print(f"on_change: {val}")

with gr.Blocks() as demo:
    inp = gr.Textbox(label="Set label")
    label = gr.Label("", visible=False)

    inp.submit(set_label, [inp], [label])

    label.change(on_change, [label], None)

demo.launch(debug=True)
```

### Screenshot

The code above gets stuck in a loop

Screenshot 2023-05-22 at 16 56 26

it seems like the change event re-triggers itself

### Logs

```shell
n/a
```

### System Info

```shell
gradio 3.32.0
```

### Severity

annoying

### PR DESCRIPTION
**Pull request by freddyaboulton**
# Description

Fixes #4309

To verify fix run repro from issue. Only one message gets printed

```
❯ python label_change.py
Running on local URL:  http://127.0.0.1:7861

To create a public link, set `share=True` in `launch()`.
set_label
on_change: {'label': '> s'}
```

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have added a short summary of my change to the CHANGELOG.md
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by pngwn** [comment]
I'm not a fan of this cheap deep equal approach. Gonna see if I can find another way.

**Comment by freddyaboulton** [comment]
Ok sounds good @pngwn - I used this approach because that's what I've seen done in other components (JSON, video).

**Comment by pngwn** [comment]
@freddyaboulton Yeah, that's why I'd like to figure something cleaner and faster out really. It is spreading. Essentially anytime the 'value' is an object.

**Comment by pngwn** [comment]
I pushed an alternative approach that I think is cleaner (an is definitely faster as it lets Svelte to the comparisons). I tested against the origina repro but could you double check it works as expected?

Essentially the issue is that new objects are only ever equal to themselves, so we keep triggering the dispatch. Svelte does compare values and bail if nothing has change but since objects in JS are only ever equal to themselves, if we create a new object with the same values svelte thinks the value has 'changed'.

What I've done here is deconstruct the object, pulling off the properties. We then use these values as a requirement for triggering change events. This gives svelte an easier time as it is able to compare the label string directly.

**Comment by pngwn** [comment]
Good to merge if this still work properly + CI is green.

**Comment by pngwn** [comment]
If this approach works fine, we should also update the other cases to use this approach (in a follow up PR).

**Comment by freddyaboulton** [comment]
Thanks @pngwn !

**Pull request merged**
