### PR TITLE
Restructure guides

### LINKED ISSUE #1720: Document the _js parameter in events
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
As a gradio user, the `_js` parameter for event updates is not documented in the website. It is not clear to me what it's for and how to use it. 

**Describe the solution you'd like**  
I think we should write a guide on how to use the `_js` parameter in practice. It's used under the hood by interfaces in the reset button as well as in the `block_js_methods` demo so those can be motivating examples. 

**Additional context**  
Similar to https://github.com/gradio-app/gradio/issues/1368 but I argue it's different. #1368 talks about documenting the event signatures in the Docs page. I think we should go into how `_js` works via examples/demos.

### LINKED ISSUE #1739: Improve documentation on stateful demos
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
As a gradio user, I wish there was more documentation on stateful demos. Right now this is only covered in the `Advanced Interface Features` guide

image

and the examples for the `Variable` component.

**Describe the solution you'd like**  
Add a "Stateful demos with Blocks" guide that covers how to create stateful demos with the blocks api. 
It should also reference the "advanced interface features" guide for guidance on stateful interface demos.
We should modify the chatbot demo to use "variable" instead of "state" since "state" was deprecated
image
We should also link the Variable component docs to the "Advanced Interface Features" and new "Stateful demos with Blocks" guides. 

**Additional context**

### LINKED ISSUE #1755: Add a guide on how to control the interactivity of components
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
As a gradio user, I wish there was a guide on how I can control the interactivity of components in my application. In particular, I would like specific guidance on how I could create a component that's not interactive.

**Describe the solution you'd like**  
A guide explaining how to control interactivity of components.

**Additional context**  
https://github.com/gradio-app/gradio/pull/1645
#1685

### LINKED ISSUE #1757: Explain how to apply custom styling to components in the documentation
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
As a gradio user, I would like some guidance on how to apply custom styling to my Interface or Blocks app.

Currently, we mention custom styling for interfaces in the "advanced interface features" guide but we don't really explain how to use it or give an example:

image

For blocks, we have a `blocks_style` demo but as far as I can tell, it's not used on the website.

**Describe the solution you'd like**  
We should document the `style` method for components on the website and link to examples. We should also write a guide on custom styling for blocks and interfaces to educate users on this feature.

**Additional context**

### LINKED ISSUE #1760: Organize the Guides landing page better
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
As a gradio user, I wish the guides on the guides page were organized in a more logical way. As a new user, I do not know which guide contains the information I'm looking for just by looking at the landing page

image

As we add more guides, the risk of guides being lost in the sea of guides becomes greater with out current landing page layout.

**Describe the solution you'd like**  
Some (possibly overlapping) solutions we've discussed as a team:

1. Add guide “tracks”, e.g. Interface, Blocks, Applications, Cook book (Integrations/Best Practices)
2. Linking to the Course
3. Make the distinction between “Feature explanation” guides and “Use case” guides clear in the guides page
4. Add numbering to guides

**Additional context**

### PR DESCRIPTION
**Pull request by aliabid94**
Guides are reorganized to be in categories and have an order. Sidebar is restored to show subheadings of current guide, as well as all other guides.

Fixes #1760 , Fixes #1757, Fixes #1739, Fixes #1720, Fixes #1755 

Edit: also Fixes: #1750

### CODE REVIEW

**Comment by abidlabs** [comment]
This is great @aliabid94!

Some initial reactions:
* I love the sidebar of the Guides. Makes them much more cohesive. I don't like this scrollbar though -- in general two scrollbars  on one page are overwhelming:

image

* Quickstart is working for me, but many of the other Guides are not, e.g.:

image


* Some guides (like Flagging) are applicable to both Interfaces and Blocks, so we'll have to figure that out...

**Comment by aliabid94** [comment]
There need to be two scrollbars. The navigation scroll bar automatically scrolls to where you are in the curriculum. It's not possible to keep the navigation pane in sync with the guide if there aren't two scrollbars. See https://svelte.dev/docs for another example of two scrollbars.

I've restructured the main guides and rewritten significant chunks of content, please re-review.

**Review by freddyaboulton — COMMENTED** [review]
@aliabid94 This is awesome! These are my first thoughts on this, wanted to give you feedback ahead of our synch in a couple of minutes.

I love the new guides landing page as well as the different tracks and the concept of the curriculum.

## Thoughts on the tracks:

In my opinion, "Using Blocks as Functions" should be in the Blocks track. 

Add a "Developer Experience" track that will include "Developing Faster with Reload Mode", "Embedding Gradio Demos", as well as the new "Adding A New Component" guide that will be merged soon.

Add a "Integrating with Other frameworks" track that will include "Gradio and ONNX on HuggingFace", "Using HuggingFace Integrations", as well as the forthcoming Weights And Biases integration guide.

I think having a separate track on guides will be helpful as we add more integrations in the future, like Ray.

The remaining guides can be recategorized into "Tutorials".

## What to do with content that applies to both Interfaces and Blocks?

There's content currently in the guides about Interpretation and Examples as they pertain to blocks apps that's not currently in this PR.

I think this content should still be in the guides page - last friday we saw a case where someone tried to add examples via gr.Dataset instead of gr.Examples and it lead to really slow inference times.

It's not clear where in the current structure they will go because Interpretation and Examples are in the Interface section right now.

## Some missing content I noticed:

We should have a place for this I think. Flexible on where. There may be more.

1. "Dataframes and Graphs" section of quick start
2. Multi-step demos of Introduction to blocks

## Nits
Make sure the docs are still linked to guides after re-naming the guides (e.g. Series and Parallel are not linked  to guides anymore)

**Comment by abidlabs** [comment]
@aliabid94 this honestly looks fantastic! I'm going through the guides and will add feedback below!

**Comment by abidlabs** [comment]
### Feedback (mostly nits since the Guides look great!)
-----

**Stylistic feedback**

1. I've said this before (and maybe my vision is just failing me...), but I find the font size for the main prose text in Guides too small.  It's smaller than the font size in the code blocks, smaller than the font used on the docs page, and smaller than font size used on [other websites](https://stripe.com/docs/checkout/quickstart)). Too small:

image

2. The font size for inline code is even smaller! It should be the same size as surrounding text:

image

**Content feedback**

1. The "Styling" section should mention the `css` parameter for `Interface` and `Blocks`, since we get lots of questions about that. You do mention it later on, but I think it deserves an earlier mention. 
2. This explanation for queuing seems to undersell queuing: "This will queue up calls so only a single call is processed at a time." Shouldn't you add something like it uses "long polling so that requests don't time out after 1 min"
3. When you say "See the link to the "API" in the app above", it's not clear to me what you're referring to. Can we include another screenshot or something to make it clear?

**Comment by aliabid94** [comment]
I believe things are ready to be merged. Responding to all the message above:
- for now, left "Using Blocks as Functions" where it is bc it also applies to Interfaces. Need to find a the right place for features common to Interface and Blocks.
- added "Integrating other frameworks" and "other tutorials"
- I had removed data components section in the getting started intentionally. I don't think it's necessary to explain this directly, there are examples in the guide later that use dataframes.
- Multi step demos was restored (by abidlabs I think)
- Restored docs link to Series and Parallel (I also think we should rethink this guides-to-docs link generally)
- Made guides text larger
- Added css= to styling section, and expanded queue explanation.
- demo above "view api" section wasn't working, fixed

Let's get this merged so that other guides can be added with this structure.

**Review by freddyaboulton — APPROVED** [review]
@aliabid94 Thanks for this awesome PR! I think it's a definite improvement over our previous structure and I like the new "Key Features" app.

Agree that we should get this merged to unblock future guide development.

Let's file a brainstorming issue to track all the nits still left in this PR:

- [ ] Copy-paste button in code snippets in guides is gone
- [ ] Is it possible to display a sidebar in the guide landing page like we do in the guides? I think it may help see all the tracks/guides as they all don't fit on one page (at least on my latpop)
image

- [ ] Figure out new homes for blocks/guides concept.

**Comment by abidlabs** [comment]
Created #1903 to track the remaining items, but this looks good to merge @aliabid94!

**Pull request merged**
