### PR TITLE
No token passed by default in `gr.load()`

### PR DESCRIPTION
**Pull request by abidlabs**

### CODE REVIEW

**Review by aliabd — APPROVED** [review]
if its just the docs change lgtm! you need to lint tho

**Comment by abidlabs** [comment]
And also the parameter default has changed

**Comment by abidlabs** [comment]
The lint and typing issues are actually already on the `5.0-dev` branch, not originating from this PR. They are not hard to fix but I'll wait until @freddyaboulton is back in case there are underlying issues that need addressing

**Comment by abidlabs** [comment]
Will go ahead and merge this in

**Pull request merged**
