### PR TITLE
Keep hidden Accordion content in DOM

### PR DESCRIPTION
**Pull request by aliabid94**
Fixes: https://github.com/gradio-app/gradio/issues/3738
Fixes: #3657 
Fixes: #3461
Fixes: #3198

### CODE REVIEW

**Comment by abidlabs** [comment]
I think this would close #3657 and #3461 as well? Maybe even #3198? 

cc @pngwn

**Comment by abidlabs** [comment]
Yes, confirmed that all three of the other issues have been fixed as well, added to parent-level comment. I don't see any issue but let's get @pngwn's thoughts in case there are any downsides to this

**Review by pngwn — APPROVED** [review]
Looks good!

**Comment by abidlabs** [comment]
Thanks for the review @pngwn! Will merge in once CI passes @aliabid94

**Pull request merged**
