### PR TITLE
Allow hiding x axis labels woth `x_axis_labels_visible=False`

### PR DESCRIPTION
**Pull request by aliabid94**
Useful for when the x-axis is made of hundred of categories, in which case simply hovering over the point for more info is cleaner.

### CODE REVIEW

**Review by freddyaboulton — APPROVED** [review]
Looks good to me @aliabid94 !

**Comment by pngwn** [comment]
Should we add y as well for consistency?

**Comment by abidlabs** [comment]
Let's target `5.0-dev` please to avoid conflicts

**Comment by aliabid94** [comment]
> Should we add y as well for consistency?

There should never be the issue of running out of space on the y axis, because we only support numeric y axes, and those will automatically be spaced out.

**Comment by aliabid94** [comment]
everything got goofed when I changed the target branch, gonna close and retry

**Pull request closed without merging**
