### PR TITLE
Refactor queuing

### PR DESCRIPTION
**Pull request by FarukOzderim**
There was not much to dig around with #1120, I created a suggestion for queuing instead of trying to debug it, since we are going to refactor it soon.

Migrated to async wait as well, since we are now on a async framework.

### CODE REVIEW

**Comment by abidlabs** [comment]
Nice, I prefer a non-file-based approach to store the queue. Let me know when you want a review!

cc @aliabid94

**Comment by aliabid94** [comment]
Is the idea that the queue will now be stored in memory? I worry about OOM errors if working with large input data amd large queues. 
I did have some thoughts though on refactoring queueing, including:
- Refactoring the API so the user does not send input data until it is their "turn" in line. This way, we don't have to store data for possibly hundreds of inputs waiting in queue. 
- Currently, even if a user closes the browser, their queued data is run. Would be nice to have some heartbeat check to see if a user has closed the browser (could use the status check that is sent every second right now), and dequeue if a user has left.
- We could possibly use celery with sqlite backend if we want a dedicated query manager.

**Comment by abidlabs** [comment]
> Is the idea that the queue will now be stored in memory? I worry about OOM errors if working with large input data amd large queues.

Ah this is a good point. We have gotten some really large queue sizes (>1000) and for image files or video files, this could go beyond RAM. 

But then wouldn't this fix that:

 > Refactoring the API so the user does not send input data until it is their "turn" in line. This way, we don't have to store data for possibly hundreds of inputs waiting in queue.

**Comment by abidlabs** [comment]
> Currently, even if a user closes the browser, their queued data is run. Would be nice to have some heartbeat check to see if a user has closed the browser (could use the status check that is sent every second right now), and dequeue if a user has left.

+1

**Comment by FarukOzderim** [comment]
> Is the idea that the queue will now be stored in memory? I worry about OOM errors if working with large input data amd large queues. I did have some thoughts though on refactoring queueing, including:
> 
>     * Refactoring the API so the user does not send input data until it is their "turn" in line. This way, we don't have to store data for possibly hundreds of inputs waiting in queue.
> 
>     * Currently, even if a user closes the browser, their queued data is run. Would be nice to have some heartbeat check to see if a user has closed the browser (could use the status check that is sent every second right now), and dequeue if a user has left.
> 
>     * We could possibly use celery with sqlite backend if we want a dedicated query manager.

Very good points!

> Refactoring the API so the user does not send input data until it is their "turn" in line. This way, we don't have to store data for possibly hundreds of inputs waiting in queue.

I think the point above solve RAM problems and need for a heartbeat check. When the users turn has come in the queue, if the user is not online(browser tab is open), we remove the user from the queue.

1. @aliabid94, would you like to integrate Frontend and Backend with this approach?
2. I think this refactoring is not very critical for 3.0 release, we could either have before or after the release, WDYT?

**Comment by FarukOzderim** [comment]
Related #572

**Comment by FarukOzderim** [comment]
Continued with #1489

**Pull request closed without merging**
