### PR TITLE
Make <UploadProgress /> Wasm-compatible

### PR DESCRIPTION
**Pull request by whitphx**
## Description

Fixed version of #6770.

Closes: #6743

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks @whitphx. This looks good, but I noticed a few interesting things.

1. I don't see the circular progress bar, just the statement of how many files are being uploaded:

image

2. If the files I upload are too large (100s of MB), the page crashes. Maybe this is to be expected, but the problem is that refreshing the page doesn't fix it for me. I have to literally close the http server and restart it.

This is somewhat of an edge case since I don't expect many users to be uploading super large files to gradio/lite, but it would be great if the failure was more graceful. Here's the simple demo I'm trying:

```html
<!doctype html>
<!-- A demo HTML file to test the bundled JS and CSS files -->
<html style="margin: 0; padding: 0; height: 100%">
	<head>
		<meta charset="utf-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1"
		/>

		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link
			rel="preconnect"
			href="https://fonts.gstatic.com"
			crossorigin="anonymous"
		/>

		<script type="module" crossorigin src="./dist/lite.js"></script>
		<link rel="stylesheet" href="./dist/lite.css" />
	</head>

	<body style="margin: 0; padding: 0; height: 100%">
		<div id="gradio-app"></div>

		<script type="module">
			// type="module" is necessary to use `createGradioApp()`, which is loaded with <script type="module" /> tag above.
			createGradioApp({
				target: document.getElementById("gradio-app"),
				code: `
import gradio as gr

def zip_files(files):
    return files

demo = gr.Interface(
    zip_files,
    gr.File(file_count="multiple"),
    "file",
)

if __name__ == "__main__":
    demo.launch()
`,
				info: true,
				container: true,
				isEmbed: false,
				initialHeight: "300px",
				eager: false,
				themeMode: null,
				autoScroll: false,
				controlPageTitle: false,
				appMode: true
			});
		</script>
	</body>
</html>

```

**Comment by aliabd** [comment]
I had the same issues as @abidlabs. though the upload was really fast when it worked. which is maybe why the spinner doesn't show up :shrug:

**Comment by whitphx** [comment]
@abidlabs @aliabd Thanks! I investigated these problems and put a short report about it.

> 1. I don't see the circular progress bar, just the statement of how many files are being uploaded:

This was caused by a combination of these reasons:

1. An HTTP request to `/upload_progress` is dispatched _before_ `/upload` in the Wasm mode, while `/upload_progress` should be _after_ `/upload`.
`/upload` is dispatched [here](https://github.com/gradio-app/gradio/blob/5e0016267f1d683e2daab82ee4a33d2f09513a34/js/upload/src/Upload.svelte#L76) and `/upload_progress` is [here](https://github.com/gradio-app/gradio/blob/5e0016267f1d683e2daab82ee4a33d2f09513a34/js/upload/src/UploadProgress.svelte#L41). They are called in this order at the same tick in the eventloop (maybe), and the actual HTTP requests are also dispatched in this order too normally. However, in the Wasm mode, the Wasm-patched `fetch` has two awaits [here](https://github.com/gradio-app/gradio/blob/5e0016267f1d683e2daab82ee4a33d2f09513a34/js/app/src/lite/fetch.ts#L47-L57) before dispatching the HTTP request to the server, while the Wasm-patched `EventSource` class doesn't have any awaits [here](https://github.com/gradio-app/gradio/blob/5e0016267f1d683e2daab82ee4a33d2f09513a34/js/wasm/src/sse.ts#L48-L69), so the `EventSource` dispatches the HTTP request in an earlier tick than `fetch` in the Wasm mode. It results in [an `IndexError` in the `/upload_progress` route](https://github.com/gradio-app/gradio/blob/5e0016267f1d683e2daab82ee4a33d2f09513a34/gradio/routes.py#L752-L754) because the specified upload_id doesn't exist yet.
2. In the Wasm-patched `fetch`, all upload data is packaged into a single "packet" and send it to the server at one time [here](https://github.com/gradio-app/gradio/blob/5e0016267f1d683e2daab82ee4a33d2f09513a34/js/app/src/lite/fetch.ts#L47-L49) by converting `ReadableStream<Uint8Array>` into `Uint8Array`. This is similar to what @aliabd wrote ("the upload was really fast").


> 2. If the files I upload are too large (100s of MB), the page crashes. Maybe this is to be expected, but the problem is that refreshing the page doesn't fix it for me. I have to literally close the http server and restart it.

It is due to a bad design of [`DownloadButton.svelte`](https://github.com/gradio-app/gradio/blob/main/js/wasm/svelte/DownloadLink.svelte) for the Wasm mode where all the data is prefetched from the Wasm worker server when the component is mounted, which should be fixed so the data is loaded when the user clicks the download link.

---

I will fix 2. first as it's obviously a bad behavior.
For 1., let me think a bit more.

**Comment by whitphx** [comment]
@abidlabs @aliabd I fixed the second problem by fixing `<DownloadLink />`.
Let me create a separate PR for 1.

**Comment by aliabd** [comment]
I can confirm the second issue is gone, just tested with some large files. 

But the playground on the website is broken. (deploy to vercel action is failing) And it's because of this error: 

```
ReferenceError: window is not defined
    at /Users/aliabdalla/Documents/dev/gradio/js/wasm/svelte/DownloadLink.svelte:80:11
```
Though that line is unchanged by this pr

**Comment by whitphx** [comment]
@aliabd Thanks.
Found the reason and pushed the solution: 7377cfd
Plz check that 👍

**Review by aliabd — APPROVED** [review]
Everything looks great! Thanks @whitphx!

**Pull request merged**
