### PR TITLE
Fix gr.Image height inconsistencies

### PR DESCRIPTION
**Pull request by hannahblair**
## Description

We have some missing `height: 100%`s in some places and the elements needed some fixing up as a result but I'm pretty sure this fixes the output image not fitting properly in the image container, and prevents the source selection being slightly cut off in the image input. 

Closes: #7748
Closes: #8838
Closes: #6979 
Closes: #6059
Closes: https://github.com/gradio-app/gradio/issues/7901

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
From what I'm seeing @hannahblair, the behavior is correct when `interactive=False`, but when `interactive=True`, the full image is not shown. E.g.

```py
import gradio as gr

with gr.Blocks() as demo:
    with gr.Row():
        im_input = gr.Image(label="Image input", height=240)
        im_output = gr.Image(interactive=False, label="Image output", height=240)
    gr.Examples(["https://www.vangoghmuseum.nl/asset/download/s0022V1962"], inputs=im_input)
    im_input.change(fn=test_fun, inputs=[im_input], outputs=[im_output])

demo.launch()
```

produces:

image

**Review by pngwn — APPROVED** [review]
Looks good. Thanks @hannahblair!

**Comment by abidlabs** [comment]
Sweet thanks @hannahblair! LGTM. I think this also fixes a couple of other issues, let me find em 😅

**Comment by abidlabs** [comment]
Yeah okay one more: https://github.com/gradio-app/gradio/issues/7901, will add to the parent comment!

**Review by abidlabs — APPROVED** [review]

**Comment by abidlabs** [comment]
merging for the release!

**Pull request merged**
