### PR TITLE
Better docs navigation on mobile 

### PR DESCRIPTION
**Pull request by aliabd**
I added a sidebar to make navigation easier on mobile. This has been a big complaint from users, you used to need to scroll all the way to the element you're looking for. Now there's a menu bar you can access at any time that will show you all the elements on the page.  

You can test it (from mobile) on this link: https://www.gradio-staging.com/docs/main/ Let me know any feedback on styling please 

https://user-images.githubusercontent.com/9021060/216216361-0db35635-0cd4-42ea-b569-1957424170f2.mp4

Also fixed some responsiveness issues

Closes: #2464

### CODE REVIEW

**Review by abidlabs — APPROVED** [review]
Beautiful!! Looks and works great.

I'll let @aliabid94 review the code changes

**Comment by aliabid94** [comment]
Looks very clean @aliabd. I don't like how the code is duplicated for the entire navbar for mobile mode vs desktop mode. Should be very possible to use media selectors to alter the HTML without having to duplicate the whole navbar. LMK if you want to sync on that.

**Comment by aliabd** [comment]
@aliabid94 you're definitely right, just refactored the code to do it using media selectors. Updated on dev: https://www.gradio-staging.com/docs/main

**Comment by aliabd** [comment]
Oof, yeah i'm getting that too @pngwn will look into it

**Review by freddyaboulton — APPROVED** [review]
Tested and works really well for me @aliabd !!!

I agree with @pngwn 's and @aliabid94 's comments.

**Review by aliabid94 — APPROVED** [review]
LGTM!

**Comment by abidlabs** [comment]
Awesome, merging in so it will get released with 3.18!

**Pull request merged**
