### PR TITLE
 Fix gather_data race condition v2

### PR DESCRIPTION
**Pull request by FarukOzderim**
RePR of  #2494, Closes #2494 

It seems there were a lot of changes in the codebase, hence another PR appears 😸 

1. fix&enable early data gathering
2. make process_starts communication concurrent

You could run a benchmark on this as well @freddyaboulton.

### CODE REVIEW

**Comment by FarukOzderim** [comment]
@freddyaboulton there is a failing test, could not figure it out. Would appreciate if you could take a look.

**Comment by freddyaboulton** [comment]
Thanks for your patience and nice PR @FarukOzderim ! I’ll test tomorrow - on Paris time this week :)

**Comment by freddyaboulton** [comment]
@FarukOzderim Thank you for the PR!

I ran some benchmarking tests locally. I wonder if you can try to do the same so that we can compare. Right now, this branch is about the same performance as main even for long inference times (5 seconds).


How to run the test:
1. Clone this space https://huggingface.co/spaces/gradio/queue-benchmark (no batching) and this space (batching): https://huggingface.co/spaces/gradio/queue-batch-benchmark-max-size-50
2. Edit the app.py file to do `sleep(5)` as opposed to 0.5
3. In one terminal window, launch the space
4. In another terminal window do, `python benchmark_script_gather.py ws://localhost:7861/queue/join --batch_size 50`
5. Repeat step 3 for main and this branch

## This is what I got (avg over 1000) predictions

### This branch
No batch
{'fn_index': ['audio', 'image', 'text', 'video'], 'duration': [9.405084899770536, 9.905506483775632, 9.408928039122602, 9.463139333422221]}

Batch
{'fn_index': ['audio', 'image', 'text', 'video'], 'duration': [5.344697227725735, 5.2707009733612855, 5.244012258529663, 5.715892826893415]}

### Main
No batch
{'fn_index': ['audio', 'image', 'text', 'video'], 'duration': [9.37141333850905, 9.366957447108101, 9.31783947978823, 9.763066995460376]}

Batch
{'fn_index': ['audio', 'image', 'text', 'video'], 'duration': [5.400402425390194, 5.393897390544192, 5.359770466238905, 5.688501126776438]}


Curious on your thoughts?

**Comment by freddyaboulton** [comment]
Additionally, I also sometimes got this error when running this space [locally](https://huggingface.co/spaces/gradio-pr-deploys/space-watcher)

You can rerun that space locally with `SLACK_WEBHOOK="any string" HF_TOKEN="<your-token>" python app.py

```python
Running on local URL:  http://127.0.0.1:7862

To create a public link, set `share=True` in `launch()`.
Task exception was never retrieved
future: <Task finished name='soeb9ad7mz8_0' coro=<Queue.process_events() done, defined at /Users/freddy/sources/gradio/gradio/queue.py:279> exception=ValueError('[<gradio.queue.Event object at 0x12e5ee4c0>] is not in list')>
Traceback (most recent call last):
  File "/Users/freddy/sources/gradio/gradio/queue.py", line 294, in process_events
    response = await self.call_prediction(awake_events, batch)
  File "/Users/freddy/sources/gradio/gradio/queue.py", line 273, in call_prediction
    json=dict(data),
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/freddy/sources/gradio/gradio/queue.py", line 356, in process_events
    self.active_jobs[self.active_jobs.index(events)] = None
ValueError: [<gradio.queue.Event object at 0x12e5ee4c0>] is not in list
```

**Comment by FarukOzderim** [comment]
@freddyaboulton hmm, it is surprising to see early data gathering decreases performance, hard to make sense out of it.

But making batch performance makes sense since batch communication is concurrent in the new version.

**Comment by FarukOzderim** [comment]
The error you got feels like 'events' did not close a slot in 'active_jobs', strange, that does not feel possible to me, what about you?

**Comment by abidlabs** [comment]
@FarukOzderim I appreciate you rebasing this PR, but given the lack of speedup, I think we'll need to close this branch. Let me know if you feel different @freddyaboulton

**Comment by abidlabs** [comment]
Going to go ahead and close this, thanks guys for investigating!

**Pull request closed without merging**
