### PR TITLE
When auth is enabled, if the HTTPS request is not used when accessing…

### PR DESCRIPTION
**Pull request by nyl1001**
… the UI remotely, the client will not pass the access-token parameter for the websocket request, which will cause the interface to report a 403 error. Therefore, in order to avoid such problems, a new https control parameter is added to expose to the foreground business, so that auth can be used normally in non-https scenarios.

# Description

Please include: 
* relevant motivation
* a summary of the change 
* which issue is fixed. 
* any additional dependencies that are required for this change.

Closes: # (issue)

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have added a short summary of my change to the CHANGELOG.md
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by nyl1001** [comment]
When auth is enabled, if the HTTPS request is not used when accessing the UI remotely, the client will not pass the access-token parameter for the websocket request, which will cause the interface to report a 403 error. Therefore, in order to avoid such problems, a new https control parameter is added to expose to the foreground business, so that auth can be used normally in non-https scenarios.

**Comment by abidlabs** [comment]
Thanks for the PR @nyl1001. I believe @freddyaboulton has *just* merged in a PR for this issue here: https://github.com/gradio-app/gradio/pull/3735

Although the PR is a little different, I think it accomplishes the same thing, can you confirm? You can try it out by installing gradio from main as described here: https://gradio.app/docs/main

**Comment by nyl1001** [comment]
> Thanks for the PR @nyl1001. I believe @freddyaboulton has _just_ merged in a PR for this issue here: #3735
> 
> Although the PR is a little different, I think it accomplishes the same thing, can you confirm? You can try it out by installing gradio from main as described here: https://gradio.app/docs/main

I think you should reject the solution #3735

**Comment by abidlabs** [comment]
Can you elaborate on why the other PR will make https websocket cookies insecure?

**Comment by nyl1001** [comment]
> Can you elaborate on why the other PR will make https websocket cookies insecure?

Yes. that solution means the cookie access-token is not necessary, the client just need pass access-token-insecure.

**Comment by nyl1001** [comment]
> Can you elaborate on why the other PR will make https websocket cookies insecure?


I think it makes sense that we should leave the choice to the applicable party

**Comment by nyl1001** [comment]
> Can you elaborate on why the other PR will make https websocket cookies insecure?


I think it makes sense that we should leave the choice to the applicable party

**Comment by nyl1001** [comment]
> Can you elaborate on why the other PR will make https websocket cookies insecure?

Yes. that solution means the cookie access-token is not necessary, the client just need pass access-token-insecure. And the access-token-insecure will always be showed in HTTP or https request.

**Comment by nyl1001** [comment]
> Can you elaborate on why the other PR will make https websocket cookies insecure?

Yes. that solution means the cookie access-token is not necessary, the client just need pass access-token-insecure. And the access-token-insecure will always be showed in HTTP or https websocket request.

**Comment by nyl1001** [comment]
> Can you elaborate on why the other PR will make https websocket cookies insecure?

Yes. that solution means the cookie access-token is not necessary, the client just need pass access-token-insecure. And the access-token-insecure will always be showed to users in HTTP or https websocket request.

**Comment by nyl1001** [comment]
> Can you elaborate on why the other PR will make https websocket cookies insecure?

Yes. that solution means the cookie access-token is not necessary, the client just need pass access-token-insecure instead. And the access-token-insecure will always be showed to all client users in HTTP or https websocket request.

**Comment by abidlabs** [comment]
I see, much appreciated @nyl1001! We'll look into this soon.

**Comment by nyl1001** [comment]
> I see, much appreciated @nyl1001! We'll look into this soon.

thanks～

**Comment by abidlabs** [comment]
Hi @nyl1001! @freddyaboulton and I discussed this issue further, and we don't follow this statement:

> Yes. that solution means the cookie access-token is not necessary, the client just need pass access-token-insecure instead. And the access-token-insecure will always be showed to all client users in HTTP or https websocket request.

It seems to us that this PR and the earlier PR #3735 accomplish the same thing, the only difference is the name of the cookie: `access-token` vs. `access-token-unsecure`. 

You'll notice that in this PR:

```py
                    response.set_cookie(
                        key="access-token",
                        value=token,
                        httponly=True,
                    )
```
vs. 
```py
                response.set_cookie(
                    key="access-token-unsecure", value=token, httponly=True
                )
```
The only difference is the name of the cookie -- otherwise, the token is in both of them, and both of them are `httponly=True`. 

Furthermore, you introduce a parameter called `enable_https` but this is set to `True` in the constructor and never set otherwise, this doesn't seem to correct either.

**Comment by abidlabs** [comment]
Hi @nyl1001 I'll close this PR for lack of follow up. If you still feel like #3735 is the wrong approach, I'd be interested in hearing your reasoning. Thanks!

**Pull request closed without merging**
