### PR TITLE
Fix custom components on windows

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

image

Closes: #6821
Closes: #7025

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by pngwn** [comment]
Does everything still work in mac/linux?

**Comment by freddyaboulton** [comment]
Yes tested on mac!

**Comment by freddyaboulton** [comment]
I guess the true test would be to do ship an release candidate of `@gradio/preview` but everything is working in the dev environment

**Review by pngwn — APPROVED** [review]
Tested locally (macOs and Asahi linux) and looks good!

Thanks @freddyaboulton!

**Comment by freddyaboulton** [comment]
Thank you @pngwn 🙏

**Pull request merged**
