### PR TITLE
Fix auth when connecting via HTTP

### LINKED ISSUE #3171: Cannot login to application when deployed on-premise
### Describe the bug

I cannot login to my gradio app when it's deployed in docker container on any server. I've tried on 2 different machines with different docker versions. After passing my credentials I'm not redirected to main but login page is refreshed. I've encountered this problem only on versions 3.17.x and 3.18.0 and only when deployed on some server. Everything works perfectly fine on my local machine, both when run locally or via docker.  

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

1. Dockerize gradio app with gradio authentication enabled and deploy on some server while exposing it
2. Open the app in your browser
3. Log in
4. Encounter page refresh with no redirection to actual app

### Screenshot

_No response_

### Logs

```shell
I have no logs for this. There's no error or logs neither on python side nor browser.
```

### System Info

```shell
Gradio version: 3.17.x, 3.18.0 (it worked previously on 3.16.2)
```

### Severity

blocking upgrade to latest gradio version

### PR DESCRIPTION
**Pull request by freddyaboulton**
# Description

Add an unsecured token that can be set/sent via HTTP. Also removing `__gradio_loader__` as that breaks auth on main, see: https://huggingface.slack.com/archives/C02SPHC1KD1/p1676671390297609?thread_ts=1676591517.723239&cid=C02SPHC1KD1

Fixes #3171

Login spaces still works, test here: https://huggingface.co/spaces/freddyaboulton/hello_login_main
https_login_spaces

Login via http now works, test here: http://ec2-54-144-135-68.compute-1.amazonaws.com:7860/

http_login_spaces

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by abidlabs** [comment]
Can confirm both links work for me, both in incognito and regular browsing mode.

**Comment by freddyaboulton** [comment]
Yes! Just modified the CHANGELOG and got rid of some of the code that was added in a separate branch I had lol

**Comment by abidlabs** [comment]
Tested locally as well, works beautifully!

**Review by abidlabs — APPROVED** [review]

**Comment by freddyaboulton** [comment]
@aliabid94 @dawoodkhan82 Can you give the `__gradio_loader__` changes a look?

**Comment by aliabid94** [comment]
Frontend LGTM!

**Comment by freddyaboulton** [comment]
Thanks for the review!!

**Pull request merged**
