### PR TITLE
Get Image click coordinates from `.select`

### PR DESCRIPTION
**Pull request by aliabid94**
Returns the image coordinates via select() method. 

Recording 2023-04-08 at 13 58 25

See `image_selections` demo in PR for code example.

Fixes: https://github.com/gradio-app/gradio/issues/2650

### CODE REVIEW

**Comment by abidlabs** [comment]
I'm testing this and looks pretty good so far. Just to clarify, this only works if `source="upload"` and `tool="editor"`, correct? Can we document this?

**Comment by abidlabs** [comment]
Also tbh I'm a little confused how this would enable segmentation (as requested in #2650). Maybe we can make the demo a little more relevant to segmentation?

**Comment by aliabid94** [comment]
Recording 2023-04-07 at 06 51 33
made the segmentation demo more obivous.
> Also tbh I'm just generally confused how this would enable segmentation
This is what was requested, the ability to select a pixel to use as input for segmentation.

**Comment by aliabid94** [comment]
> this only works if source="upload" and tool="editor", correct

No, this works with any source once the image is static, e.g. after a webcam capture.

**Review by abidlabs — APPROVED** [review]

**Comment by dawoodkhan82** [comment]
@aliabid94 Looks good. Tested and works. Maybe we can update the `image_segmentation` demo or completely replace it with `image_selections` demo.

**Review by dawoodkhan82 — APPROVED** [review]

**Comment by vvvm23** [comment]
Thanks all! This is perfect! 🤗

**Comment by JunchuanYu** [comment]
> Returns the image coordinates via select() method.
> 
> Recording 2023-04-08 at 13 58 25 [ Recording 2023-04-08 at 13 58 25 ](https://user-images.githubusercontent.com/7870876/230742515-d781b956-d2d1-4cb7-a68a-426bb9cd8786.gif) [ ](https://user-images.githubusercontent.com/7870876/230742515-d781b956-d2d1-4cb7-a68a-426bb9cd8786.gif)
> 
> See `image_selections` demo in PR for code example.
> 
> Fixes: #2650

Nice job！ This is exactly what I need, can you tell me where I can see the source code for this demo?

**Comment by JunchuanYu** [comment]
> 
I found this code in the demo, but it failed to run, and the error message is as follows:

AttributeError: module 'gradio' has no attribute 'SelectData'

@aliabid94

**Comment by hysts** [comment]
Hi @JunchuanYu 
I think this feature was added in gradio 3.25.0, and in my environment with gradio 3.26.0, [the demo](https://github.com/gradio-app/gradio/blob/main/demo/image_selections/run.py) is working fine, so maybe installing the latest gradio will fix your problem.

**Comment by JunchuanYu** [comment]
it works now！thanks

**Comment by techykajal** [comment]
@aliabid94 I want to draw/display the coordinates in real-time on the gradio.image. Is there any way to achieve this?

**Comment by CA4GitHub** [comment]
> Returns the image coordinates via select() method.
> 
> Recording 2023-04-08 at 13 58 25 [ Recording 2023-04-08 at 13 58 25 ](https://user-images.githubusercontent.com/7870876/230742515-d781b956-d2d1-4cb7-a68a-426bb9cd8786.gif) [ ](https://user-images.githubusercontent.com/7870876/230742515-d781b956-d2d1-4cb7-a68a-426bb9cd8786.gif)
> 
> See `image_selections` demo in PR for code example.
> 
> Fixes: #2650

Where are these demos available?  The link https://huggingface.co/spaces/gradio-pr-deploys/pr-3786-all-demos didn't work.

Is there a demo where the input image is updated with the segmentation info instead of shown in a 2nd image?

**Pull request merged**
