### PR TITLE
Dont move files to cache automatically in chatbot postprocess

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Closes: #9272

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Whoa yeah we should not be treating filename strings as files unless explicitly requested to do so. I should know this, but what's the syntax for actually indicating a filepath?

**Comment by freddyaboulton** [comment]
@abidlabs with the messages type, you can set the "content" to a dict with a "path" key pointing to the file you want to embed.

**Review by abidlabs — APPROVED** [review]
LGTM thanks @freddyaboulton!

**Comment by freddyaboulton** [comment]
Thank you @abidlabs !

**Pull request merged**
