### PR TITLE
Links in updated markdown open in a new tab

### PR DESCRIPTION
**Pull request by gante**
# Description

Links in updated markdown open in a new tab :D See the original issue for more info

Closes: #3234 

NOTES/QUESTIONS:
1. Regarding testing, the instructions in CONTRIBUTING.md seem to be updated (e.g. there is no `.circleci` folder, so `bash scripts/run_circleci.sh` can't run). I was unable to run the test suite locally but can confirm that the problems were fixed locally.
~2. IDK how to test this, suggestions are appreciated :)~

P.S.: TIL about the ability to run `gradio app.py`. OMG, what a superpower, kudos to whoever had the idea <3

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks for the fix @gante! We'll take a look at this PR soon. 

Btw how'd you learn about `gradio app.py`? Perhaps we should feature it more prominently in the docs

**Comment by gante** [comment]
@abidlabs markdown-related tests are failing, I'm going to have a look and attempt to fix them.

Re `gradio app.py`, found it in the [`CONTRIBUTING.md`](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md#extra-tidbits) page :)

**Comment by gante** [comment]
@abidlabs test fixed -- and the fixed test now tests that the feature is working as intended

**Comment by abidlabs** [comment]
Great, thanks for the PR @gante! Let me take a look at it and we can merge it in soon

**Comment by abidlabs** [comment]
I consolidated some of the markdown code that we had across different files, and tested. LGTM. Will merge after the CIs pass.

**Comment by abidlabs** [comment]
Tests passing, thanks again for the PR @gante!

**Pull request merged**
