### PR TITLE
Fix dataset demo

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Fixes the dataset demo that was breaking: https://huggingface.co/spaces/gradio/dataset_main

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Isn't this the expected behavior? We should error out if the examples provided are not valid choices in the `gr.CheckboxGroup`

**Comment by freddyaboulton** [comment]
Maybe checkbox group with empty choices is the culprit here. It looks really bad 

image

When would that be expected? As output component maybe?

**Comment by abidlabs** [comment]
> Maybe checkbox group with empty choices is the culprit here. It looks really bad

> When would that be expected? As output component maybe?

It really never is expected. Even when a `CheckboxGroup` is an output component, it should be instantiated with the possible choices.

**Comment by abidlabs** [comment]
The demo doesn't make sense -- it creates a `gr.CheckboxGroup` without any choices, yet the examples imply that there should be 3 options to select from

**Comment by freddyaboulton** [comment]
Fixed the demo by passing choices for Checkboxgroup @abidlabs

**Comment by abidlabs** [comment]
Nice! Thanks @freddyaboulton

**Pull request merged**
