### PR TITLE
Fix gather_data race condition

### PR DESCRIPTION
**Pull request by FarukOzderim**
Hello @freddyaboulton, while taking concurrency lecture in OS course, a solution sparked in my head :)

This PR tries to enable proactive data gathering while keeping the gather_data communication safe, could you please test whether it is safe? And how it affects the performance?

### CODE REVIEW

**Comment by freddyaboulton** [comment]
@FarukOzderim Absolutely! Thank you

**Review by freddyaboulton — COMMENTED** [review]
@FarukOzderim It does work! This is awesome. I can run the following script and it does not get stuck on a batch size of 50 😄 

```
python benchmark_script_gather.py wss://spaces.huggingface.tech/gradio/queue-benchmark-omer-v2/queue/join --batch_size 50
```

```python
import asyncio
from datetime import datetime
import json
import random
import time
import websockets
import gradio as gr
import pandas as pd
import argparse
import secrets

FN_INDEX_TO_DATA = {
    "image": (0, gr.media_data.BASE64_IMAGE),
    "text": (1, "A longish text " * 15),
    "audio": (2, gr.media_data.BASE64_AUDIO),
    "video": (3, gr.media_data.BASE64_VIDEO)
}

from asyncio import Queue

async def get_prediction(host):
    async with websockets.connect(host, timeout=5) as websocket:
        start = time.time()
        name = random.choice(["image", "text", "audio", "video"])
        fn_to_hit, data = FN_INDEX_TO_DATA[name]
        while True:
            raw_msg = await websocket.recv()
            msg = json.loads(raw_msg)
            msg = msg["msg"]
            if msg == "queue_full":
                break
            elif msg == "send_hash":
                await websocket.send(json.dumps({"fn_index": fn_to_hit, "session_hash": secrets.token_urlsafe(8)}))
            elif msg == "send_data":
                await websocket.send(json.dumps({'data': [data], "fn_index": fn_to_hit}))
            elif msg == "estimation":
                pass
            elif msg == "process_starts":
                pass
            elif msg == "process_completed":
                end = time.time()
                duration = end - start
                return {"fn_index": name, "duration": duration}


async def main(host, n_results=1000, batch_size=20):
    results = []
    while len(results) < n_results:
        print(f"N results {len(results)}")
        batch_results = await asyncio.gather(*[get_prediction(host) for _ in range(batch_size)])
        for result in batch_results:
            if result:
                results.append(result)

    data = pd.DataFrame(results[:n_results]).groupby("fn_index").agg({"mean"})
    data.columns = data.columns.get_level_values(0)
    data = data.reset_index()
    data = {"fn_index": data["fn_index"].to_list(), "duration": data["duration"].to_list()}
    json.dump(data, open(f"{datetime.now()}_results.json", "w"))
    return data


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Upload a demo to a space")
    parser.add_argument("host", type=str, help="Name of demo to upload")
    parser.add_argument("--n_results", type=int, default=1000)
    parser.add_argument("--batch_size", type=int, default=50)     
    args = parser.parse_args()
    out = asyncio.run(main(args.host, args.n_results, args.batch_size))
    print(out)
```

I'm not noticing a performance difference over the current queue though, which I would expect with gathering data for the first rank.

### Main

| Input type | Average time to complete prediction over 1000 requests |
| ------------- | ------------- |
| Audio  | 1.5452740753398222 |
| Image  | 1.5123367877716714 |
| Text | 1.5666406706197937 |
| Video |2.029747503848115|


### This branch

| Input type | Average time to complete prediction over 1000 requests |
| ------------- | ------------- |
| Audio  | 1.6504125310560314 |
| Image  | 1.5986797290903922 |
| Text | 1.5079733889390523 |
| Video | 2.0087017952894963 |

**Comment by FarukOzderim** [comment]
That's great, though I am surprised there is no improvement in the performance. Could we also try time.sleep(5) or time.sleep(10) to see if the performance does change? I expect early data gathering to be helpful when the inference times are longer.

**Comment by abidlabs** [comment]
Hi @freddyaboulton would it be possible to benchmark with longer inference times as @FarukOzderim is suggesting? If we notice a meaningful improvement, let's merge this in. Otherwise, since it needs further refactoring to work with batch, canceling, etc. we should close this branch

**Comment by freddyaboulton** [comment]
Hi @FarukOzderim ! Sorry it took me a while to get back to this. I reran the benchmarking with these two spaces:

- Version 3.6 with your changes: https://huggingface.co/spaces/gradio/queue-benchmark-omer-v2
- Version 3.6 from Pypi: https://huggingface.co/spaces/gradio/queue-benchmark-omer-v2-v36

I updated the sleep to be 5 seconds. 

### Gradio 3.6

| Input type | Average time to complete prediction over 1000 requests |
| ------------- | ------------- |
| Audio  |9.844278578539841 |
| Image  |9.613765030979632 |
| Text |9.589899317214364 |
| Video |9.957276362568939|


### This branch

| Input type | Average time to complete prediction over 1000 requests |
| ------------- | ------------- |
| Audio  |9.573372102666784 |
| Image  |9.608296090729382 |
| Text |9.173863738316756 |
| Video |9.769543515311348 |

It's about 0.3 - 0.5 seconds faster on average! Is this in line with your expectations?

**Pull request closed without merging**
