### PR TITLE
Website: WIP

### PR DESCRIPTION
**Pull request by aliabid94**
Complete reqrite of Gradio homepage. Main feature changes:
- Integrated into Gradio library, so automatically changes in sync with library changes
- All CSS done with Tailwind
- Files compressed, minified, and tree-shaken in build
- Generated files are all static - no server code needed

### CODE REVIEW

**Comment by abidlabs** [comment]
Nice work!! Really excited to take a look

**Comment by aliabid94** [comment]
image
image
image
)

**Comment by aliabid94** [comment]
Still need to:
- Embed interfaces cleanly
- Doc styling
- Add hosting documentation

**Comment by abidlabs** [comment]
Some feedback:
* For the tagline, I suggest "Build & share machine learning apps delightfully" (spell out machine learning, do lower case instead of title case, add a unique word like "delightfully" or "painlessly" or "effortlessly")
* Remove the "100% open-source"
* For the subheading, I suggest, "Gradio is the fastest way to demo your machine learning model with a friendly web  interface so that anyone can use it, anywhere!"
* Change "Click here to get started in 5 minutes" to "Get started with 5 lines of Python"
* I don't want to complicate your code examples but it would be really nice if they were copy-pasteable and immediately runnable rather than just skeletons of code. What do you think?
* I really like the Twitter wall
* Change "Working with ML" to "Machine learning examples"
* Are you still going to have a page called "Advanced Features"?
* We should have a "Private Deployment" page (this can wait)
* We should have an "Integrate seamlessly with any Python library" and then have the logos. People like seeing familiar logos/names. We should choose logos that include the library names imo and also add the hugging face logo.
* We should add a newsletter tab and sign up form ([see how PwC does it](https://paperswithcode.com/newsletter)) for @AK391's newsletter. But this can also wait

**Comment by aliabid94** [comment]
- I put the "open source" tag bc there was nowhere else we mentioned gradio is free. 
- The "skeletons of code" on the home page? If those demos are going to be interesting, they will be hundreds of lines of code (probably split between files even). The getting started page has simple "copy pasteable" pieces of code.
- I was thinking of combining "Advanced features" and "working with ML" into one page, but I'll see. Might just remove both
- Hmm I got rid of "integrates seamlessly" because I thought it didn't make much sense for most of those logos.

**Pull request merged**
