### PR TITLE
Make `gr.Image` preprocessing more efficient

### PR DESCRIPTION
**Pull request by abidlabs**
This PR changes image preprocessing so it no longer makes a copy of the input image file if its not necessary to do so. In particular, if `type="filepath"` and the developer does not choose a specific image mode, then it just returns the filepath as is. Note that this file will already be in the cache since it was uploaded by a user. 

Closes: https://github.com/gradio-app/gradio/issues/9257

### CODE REVIEW

**Review by freddyaboulton — COMMENTED** [review]
Is the problem that the uploaded image gets converted to `webp`? I think that was originally added for the image editor demos as saving to webp is fast and the UI could open it faster than png. 

Just want to make sure this doesn't cause an unintended change. WDYT of this pr @pngwn ?

**Comment by abidlabs** [comment]
Not really, the previous logic in `.preprocess()` was that if a FileData with an `.orig_name` was passed into `preprocess()`, the original suffix for the image was respected. That was this logic:

```py
        if payload.orig_name:
            p = Path(payload.orig_name)
            name = p.stem
            suffix = p.suffix.replace(".", "")
            if suffix in ["jpg", "jpeg"]:
                suffix = "jpeg"
````

However, even then, the original image file was opened via PIL and saved. Particularly in the case of `.jpg` files, it was problematic because a new `.jpeg` file was created with the original contents. That's what's happening here:

```py
        return image_utils.format_image(
            im,
            cast(Literal["numpy", "pil", "filepath"], self.type),
            self.GRADIO_CACHE,
            name=name,
            format=suffix,
        )
```

So this fix basically avoids this saving of a new file in cases where the image file does not need to be opened. 

I think the case that you are thinking about is when the `Image` component is used as an output, in which case the format is still "webp" by default, e.g. see this test:

https://github.com/gradio-app/gradio/blob/41d5ab987ba9728753be4509490c79041655809b/test/components/test_image.py#L81

**Review by aliabid94 — APPROVED** [review]
LGTM! Unrelatedly, I didn't realize we accept SVGs but that forcese the format to be filepath. I would imagine this would lead to a broken demo for any image demo that was expected a numpy array or PIL object but recieved an svg filepath. We should not allow svgs unless the format is filepath.

**Comment by abidlabs** [comment]
> We should not allow svgs unless the format is filepath.

Good point, I'll make that change in this PR as well

**Comment by abidlabs** [comment]
Thanks folks!

**Pull request merged**
