### PR TITLE
Unix socket support

### PR DESCRIPTION
**Pull request by cyberb**
Clients can pass `server_name="/path/to/socket"`
Tested this on https://github.com/AUTOMATIC1111/stable-diffusion-webui

Closes: #5606

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks @cyberb we'll take a look!

**Comment by abidlabs** [comment]
Ah looking at this PR, I noticed that it requires adding `requests-unixsocket==0.3.0` to requirements.txt. That's a pretty big downside, as we're working hard to limit dependencies in `gradio` for a variety of reasons. Is this strictly necessary?

**Comment by cyberb** [comment]
It is actually only because we are calling local_url for some reason here:

https://github.com/gradio-app/gradio/pull/5883/files#diff-d181109e25b5f0829054b7774d79faf8fdff3eba38069c63fcf0651a9b84d0aeL2083

**Comment by abidlabs** [comment]
> It is actually only because we are calling local_url for some reason here:

The reason is in case the Gradio app is launched from another FastAPI app, we need to ensure that the startup events are correctly called. 

If you would like to duplicate the code and include it in your PR to avoid the external dependency, we could consider this PR. Otherwise, its a no-go from my perspective because adding more dependencies is problematic from a maintenance and future-proofing perspective.

**Comment by cyberb** [comment]
just pushed, is something like this better?
let me test it one more time, I will let you know tomorrow.

**Comment by abidlabs** [comment]
We could consider this yes, but if we do add this functionality as something we officially support in gradio, we'll want to add tests to ensure that we don't break this in future versions.

**Comment by cyberb** [comment]
added a test for test_start_server in unix socket mode.

I could copy requests_unixsocket lib tests as well but they are based on waitress lib looks like, is it ok?
https://github.com/msabramo/requests-unixsocket/blob/master/requests_unixsocket/tests/test_requests_unixsocket.py

**Comment by cyberb** [comment]
did full test everything seems to work, but I am testing this change applied to v3.41.2 as this is where sd web is at (https://github.com/AUTOMATIC1111/stable-diffusion-webui)

**Comment by Ta180m** [comment]
> did full test everything seems to work, but I am testing this change applied to v3.41.2 as this is where sd web is at (https://github.com/AUTOMATIC1111/stable-diffusion-webui)

@cyberb Are you sure that this change works for the SD web UI? I was getting Websockets-related errors so I had to use the flag `--no-gradio-queue` to force the SD web UI to use HTTP requests instead of Websockets.

(Also, you might want to consider setting the Unix socket's permissions to 660 by default for security reasons or make the permissions configurable somehow.)

**Comment by cyberb** [comment]
In the end I had to use gradio 3.42.2 and it worked with the following parameters:
```
export COMMANDLINE_ARGS=--skip-torch-cuda-test
export GRADIO_SERVER_NAME=/var/snap/stable-diffusion/common/web.socket
export PATH=$PATH:${DIR}/python/bin
/bin/rm -f $GRADIO_SERVER_NAME
cd $DIR/python/webui
exec ${DIR}/python/bin/python -u ${DIR}/python/webui/launch.py \
  --precision full --no-half \
  --skip-prepare-environment \
  --data-dir '/var/snap/stable-diffusion/current' \
  --ckpt "/var/snap/stable-diffusion/current/v1-5-pruned-emaonly.safetensors" \
  --ldap-uri 'ldap://localhost:389' \
  --ldap-bind-dn 'cn={username},ou=users,dc=syncloud,dc=org' \
  --outdir-samples '/data/stable-diffusion/output'
```
not sure why `--no-gradio-queue` was not required for me, it definitely worked. I use this nginx config in front of it maybe that is why it worked for me:

https://github.com/syncloud/platform/blob/master/config/nginx/public.conf
```
  # apps proxy
  server {
  
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    
    server_name ~^(?P<app>.*)\.{{ domain }}$;
    
    ssl_certificate     /var/snap/platform/current/syncloud.crt;
    ssl_certificate_key /var/snap/platform/current/syncloud.key;
    ssl_protocols       TLSv1.2 TLSv1.3;
    # ssl_ciphers         ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384;
    ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!3DES:!MD5:!PSK;
    ssl_prefer_server_ciphers on;

    add_header Strict-Transport-Security "max-age=31536000; includeSubdomains";

    location / {
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $http_host;
        proxy_pass      http://unix:/var/snap/$app/common/web.socket: ;
        proxy_redirect  http://unix:/var/snap/$app/common/web.socket: $scheme://$http_host ;
    }
  }
```

> (Also, you might want to consider setting the Unix socket's permissions to 660 by default for security reasons or make the permissions configurable somehow.)

Looks like uvicorn sets the permission anyway:
https://github.com/encode/uvicorn/blob/master/uvicorn/config.py#L522
```
  def bind_socket(self) -> socket.socket:
        logger_args: List[Union[str, int]]
        if self.uds:  # pragma: py-win32
            path = self.uds
            sock = socket.socket(socket.AF_UNIX, socket.SOCK_STREAM)
            try:
                sock.bind(path)
                uds_perms = 0o666
                os.chmod(self.uds, uds_perms)
            except OSError as exc:
                logger.error(exc)
                sys.exit(1)
```

**Comment by Ta180m** [comment]
> In the end I had to use gradio 3.42.2 and it worked with the following parameters:

Thanks, I compiled your [3.43.2](https://github.com/cyberb/gradio/tree/3.43.2) branch and that fixed the error for me. I also had to edit the `requirements_versions.txt` file to prevent the SD web UI from uninstalling the patched Gradio and installing Gradio 3.41.2 from the PyPI, but the flag `--skip-prepare-environment ` that you used also solves this.

**Comment by cyberb** [comment]
> I also had to edit the requirements_versions.txt file 

Right that was part of my PR to them which also adds ldap auth support:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/13805

**Pull request closed without merging**
