### PR TITLE
Click to preview images in chatbot 

### PR DESCRIPTION
**Pull request by dawoodkhan82**
## Description
(Re-opened a new PR for this feature and branched off main)
Click to preview images in chatbot 

Closes: N/A

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Correct me if I'm wrong, but this is still in draft state, right @dawoodkhan82? I tested the `chatbot_multimodal` demo on the deployed PR and it is not working.

**Comment by abidlabs** [comment]
Is the `chatinterface_multimodal` in the deployed Space PR working for you? Weirdly images work, but not regular text:


https://github.com/gradio-app/gradio/assets/1778297/5813aded-2b51-40e8-9299-22ac445194d6

**Comment by dawoodkhan82** [comment]
Oh I see, I thought you meant the preview didn't work. I'll push a fix

**Comment by dawoodkhan82** [comment]
@abidlabs Can I get a re-review?

**Comment by abidlabs** [comment]
Thanks @dawoodkhan82 the `chatinterface_multimodal` demo is working now, but the image preview feature is not working completely. The issue I'm seeing is that that if you upload multiple images into that demo, and then click on any of the images, you'll always get the image preview of the final image


https://github.com/gradio-app/gradio/assets/1778297/144a9137-a561-4dd6-a6b2-835c41e8ed60

**Comment by dawoodkhan82** [comment]
@abidlabs should be fixed now

**Comment by abidlabs** [comment]
Now I'm seeing some weird shifting issues happening in `chatinterface_multimodal`:


https://github.com/gradio-app/gradio/assets/1778297/ccb298ca-b0b5-408a-80c3-71df0ed8d585

**Comment by dawoodkhan82** [comment]
That must've been caused by the other chatbot spacing PR. Just pushed a fix for it now.

**Comment by abidlabs** [comment]
Image preview looks great, thanks @dawoodkhan82! As mentioned in DM, there's a weird issue with placeholder popping back and forth but seems unrelated to this PR.

https://github.com/gradio-app/gradio/assets/1778297/9480e463-4706-452b-85b2-62e052f11842

**Review by abidlabs — APPROVED** [review]
LGTM

**Pull request merged**
