### PR TITLE
Adds the ability to set the `selected_index` in a `gr.Gallery`

### PR DESCRIPTION
**Pull request by abidlabs**
Adds the ability to set the `selected_index` of a `gr.Gallery`, both at initialization as well as by returning an updated `gr.Gallery` component from a function.

Test code:

```py
import gradio as gr

images = [
    "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    "https://images.unsplash.com/photo-1554151228-14d9def656e4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=386&q=80",
    "https://images.unsplash.com/photo-1542909168-82c3e7fdca5c?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxzZWFyY2h8MXx8aHVtYW4lMjBmYWNlfGVufDB8fDB8fA%3D%3D&w=1000&q=80",
    "https://images.unsplash.com/photo-1546456073-92b9f0a8d413?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=387&q=80",
    "https://images.unsplash.com/photo-1601412436009-d964bd02edbc?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=464&q=80",
]


with gr.Blocks() as demo:
    g = gr.Gallery(images, selected_index=1)
    b = gr.Button("Change to 0")
    b2 = gr.Button("Change to 2")
    b.click(lambda : gr.Gallery(label="changed", selected_index=0), None, g)
    b2.click(lambda : gr.Gallery(label="changed", selected_index=2), None, g)
    
demo.launch()
```

Closes: #5123

### CODE REVIEW

**Comment by dawoodkhan82** [comment]
Nice! I did notice this small bug:

Repro:
Click on Image in index 0
Click on "Change to 0" button
Click on Another Image (ex: Image index 1)
Click on "Change to 0" button
Notice it does not change to the index 0 image

https://github.com/gradio-app/gradio/assets/12725292/1bf8dbc4-4ad0-438d-9885-8b06e17cd1b8

**Comment by abidlabs** [comment]
Interesting, nice catch! I'll take a look @dawoodkhan82

**Comment by abidlabs** [comment]
Should be fixed now @dawoodkhan82! Big thanks @hannahblair for helping me debug this

**Review by dawoodkhan82 — APPROVED** [review]
lgtm!

**Pull request merged**
