### PR TITLE
Allow full screen mode in interactive gr.Image

### PR DESCRIPTION
**Pull request by hannahblair**
## Description

I've updated gr.Image to allow for full screen mode which I can imagine might be useful in some cases. I'm wondering if this was ever an active decision and/or can anyone see if this could be problematic? 

That said, I'm thinking this full screen button should actually be rewritten in a separate PR to be reusable and cut down on the repeated code. I'll raise an issue for it!

Closes: #10051

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Testing and Formatting Your Code

1. PRs will only be merged if tests pass on CI. We recommend at least running the backend tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the backed tests: `bash scripts/run_backend_tests.sh`

2. Please run these bash scripts to automatically format your code: `bash scripts/format_backend.sh`, and (if you made any changes to non-Python files) `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Going to get this in the for the launch!

**Comment by tripleS-Dev** [comment]
> Tested, works super well, including with webcam in full screen mode, which is pretty handy actually. LGTM
> 
> Test code:
> 
> ```python
> import gradio as gr
> 
> with gr.Blocks() as main:
>     with gr.Row():
>         image1 = gr.Image("cat.jpg", interactive=True, show_download_button=True, show_fullscreen_button=True)
>         image2 = gr.Image("cat.jpg", interactive=False, show_download_button=True, show_fullscreen_button=True)
>         image1.change(lambda x:x, image1, image2)
> 
> main.launch()
> ```

The download button still doesn't appear. It will be consistent and useful to see download buttons.

**Comment by abidlabs** [comment]
The download button does not appear in any of our components when `interactive=True` -- it only appears when `interactive=False` -- we can consider adding it, but you could use e.g. a `gr.DownloadButton` that has the same value as the Image in the meantime

**Comment by tripleS-Dev** [comment]
> The download button does not appear in any of our components when `interactive=True` -- it only appears when `interactive=False` -- we can consider adding it, but you could use e.g. a `gr.DownloadButton` that has the same value as the Image in the meantime

SmartSelect_20241128_100725_Moonlight (Debug)

**Comment by tripleS-Dev** [comment]
> The download button does not appear in any of our components when `interactive=True` -- it only appears when `interactive=False` -- we can consider adding it, but you could use e.g. a `gr.DownloadButton` that has the same value as the Image in the meantime

I didn't see the docs that it doesn't work when interactive = true. I think there should be either an add text or a feature. But I actually need the download button on the image. 
SmartSelect_20241128_100725_Moonlight (Debug)

**Comment by tripleS-Dev** [comment]
> Tested, works super well, including with webcam in full screen mode, which is pretty handy actually. LGTM
> 
> Test code:
> 
> ```python
> import gradio as gr
> 
> with gr.Blocks() as main:
>     with gr.Row():
>         image1 = gr.Image("cat.jpg", interactive=True, show_download_button=True, show_fullscreen_button=True)
>         image2 = gr.Image("cat.jpg", interactive=False, show_download_button=True, show_fullscreen_button=True)
>         image1.change(lambda x:x, image1, image2)
> 
> main.launch()
> ```

And here, interactive=True, and there is a problem that the reduce button does not appear when entering the full screen and the raise button is maintained.

**Pull request merged**
