### PR TITLE
Fix bug where ImageEditor cannot be used as custom component template

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Closes: #6746 

Still need to sort out dev mode with @pngwn !

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by SkalskiP** [comment]
I can't wait to see how you merge it :)

**Comment by SkalskiP** [comment]
Hi, 👋🏻 just letting you know that I installed `gradio` locally from this branch, and `gradio cc create` works but `gradio cc dev` fails.

**Comment by freddyaboulton** [comment]
Thanks @SkalskiP ! Yep, it's on our radar. Something is up with vite. Will look into it today.

**Comment by 4thfever** [comment]
Hi,
I am trying to make my own ImageEditor.
I know the this PR is not merged yet. I just tried to use it by calling
 pip install https://gradio-builds.s3.amazonaws.com/e096a67f72bc50cdf718b8f98800d1cb5a7464e3/gradio-4.10.0-py3-none-any.whl

to create my own component. It is successfully created, however, after I run gradio cc dev, it has some errors.
image
Sorry to bother you. Just want to provide some possible useful information to you.

**Comment by freddyaboulton** [comment]
Thank you @4thfever ! Yes looking into it

**Comment by pngwn** [comment]
@4thfever's issue looks like it is related to the other windows permissions errors.

**Comment by pngwn** [comment]
Closing for now just to clean up, will revive soon.

**Pull request closed without merging**
