### PR TITLE
Refactor `normalise_file` and `annotatedimage/Index.svelte`

### PR DESCRIPTION
**Pull request by whitphx**
Fix suggestions I found when working on #6133

### CODE REVIEW

**Review by aliabd — APPROVED** [review]
Code changes lgtm! Though probably better to wait for https://github.com/gradio-app/gradio/pull/6133 to be merged first and test before merging this.

**Comment by aliabd** [comment]
I think merging in https://github.com/gradio-app/gradio/pull/6133 threw me off and now not sure how to fix the `js/annotatedimage/Index.svelte` file. Will wait for you to take a look.

**Comment by abidlabs** [comment]
Hi @whitphx I recently made a lot of changes to `normalise_files` (well I got rid of it altogether), just a heads up.

**Comment by whitphx** [comment]
Yeah that's a good news!
Will close this PR.

**Pull request closed without merging**
