### PR TITLE
Fix Safari video playback

### PR DESCRIPTION
**Pull request by aliabid94**
Fixes: #3134

### CODE REVIEW

**Comment by abidlabs** [comment]
@aliabid94 are you sure this fixes the issue? I duplicated the original Space and installed the version of `gradio` from this branch and I'm still seeing the same issue: https://huggingface.co/spaces/abidlabs/audioldm-text-to-audio-generation

**Comment by dawoodkhan82** [comment]
Still see the issue as well. Also on the deployed Space for this PR

**Comment by abidlabs** [comment]
Turns out I hadn't installed the wheel correctly. Now it's working for me: https://huggingface.co/spaces/abidlabs/audioldm-text-to-audio-generation

Also tested locally and works well. LGTM!

**Comment by aliabid94** [comment]
I synced with @abidlabs, his Space had the wrong gradio version. It worked fine when he updated. @dawoodkhan82 how did you test it?

**Review by abidlabs — APPROVED** [review]

**Comment by dawoodkhan82** [comment]
Don't see the issue anymore actually. Not sure what it was. LGTM

**Pull request merged**
