### PR TITLE
Access username from `gr.Request` class

### PR DESCRIPTION
**Pull request by abidlabs**
Allows access to the username of a logged-in user from the `gr.Request()` object using the `.username` attribute. Test code:

```py
import gradio as gr

def create_greeting(request: gr.Request):
    return gr.Markdown.update(value=f"Thanks for logging in, {request.username}")

with gr.Blocks() as demo:
    user_ip = gr.Markdown(value="Not logged in")

    demo.load(create_greeting, inputs=None, outputs=user_ip)

demo.launch(auth=("admin", "admin"))
``` 

* Fixes: #3259

### CODE REVIEW

**Review by freddyaboulton — APPROVED** [review]
Beautiful @abidlabs !

**Comment by dwipper** [comment]
Hi @abidlabs @freddyaboulton. I upgraded my spaces to Gradio 4.0.2. Unfortunately, the login styling is broken again, so it looks like the fix didn't get pushed to the new build.

**Comment by tpastore-01123** [comment]
Hi sorry but I dont understand where is that Request parameter coming from if the inputs is = None :S Im trying to get the username at the breakpoint() of this code:

**Comment by freddyaboulton** [comment]
The request is passed when the `PROMO_ASSISTANT.answer` function is run by the web server, not when the demo is being created.

**Comment by tpastore-01123** [comment]
oh thanks for your pormpt response, so I should be able to access a request parameter as a keyword argument inside PROMO_ASSISTANT.answer ?

**Comment by dwipper** [comment]
@tpastore-01123 There's a pretty good example here of how it works: https://www.gradio.app/docs/request . My understanding is that when I function is called on a Gradio component, gr.Request is available as a incoming param on the function, even though it isn't passed as an input= param.

**Comment by tpastore-01123** [comment]
Nice I see now username from inside the .answer method. Though my use case is that I want to manage different sessions for different usernames having independent ChatInterfaces for each, so I dont know if this is possible since "chatbot" is outside that scope

**Comment by pjharel** [comment]
@tpastore-01123 Not to be considered prod-ready, but this code allows multi-user sessions through a "sessions" dictionary that keeps track of session_ids and usernames. I only keep the 5 most recent session_ids per user, in case one user has multiple tabs and different information need to be stored within each session. The log_history just prints to the console for additional checks.

```python
import gradio as gr
import uuid
import time

class SessionManager:
    def __init__(self):
        self.sessions = {}
        self.current_session_id = None

    def get_current_user(self, req: gr.Request):
        for user, session_list in self.sessions.items():
            if user == req.username:
                return user
        return "No user logged in with this username"

    def get_user(self, req: gr.Request):
        session_id = str(uuid.uuid4())
        timestamp = time.time()
        if req.username not in self.sessions:
            self.sessions[req.username] = [(session_id, timestamp)]
        else:
            self.sessions[req.username].append((session_id, timestamp))
            self.sessions[req.username].sort(key=lambda x: x[1]) # sort by timestamp
            if len(self.sessions[req.username]) > 5:
                self.sessions[req.username].pop(0) # remove the oldest sessions
        current_user = self.get_current_user(req)
        return {user : gr.Markdown(value=f"Thanks for logging in, {req.username}, with session ID {session_id}. Current user: {current_user}")}

manager = SessionManager()

def display_user(req: gr.Request):
    current_user = manager.get_current_user(req)
    log_history(req)
    return {"user_display": current_user}

def log_history(req: gr.Request):
    current_user = manager.get_current_user(req)
    print(current_user)

with gr.Blocks() as demo:
    user = gr.Markdown(value="User not logged in")

    user_display = gr.Textbox(label="Display User")
    display_btn = gr.Button("Display User")

    demo.load(manager.get_user, None, user)
    display_btn.click(fn=display_user, inputs=None, outputs=user_display)

if __name__ == "__main__":
    demo.launch(
        server_name="127.0.0.1",
        show_api=False,
        server_port=8000,
        debug=True,
        auth=[('user1','123'), ('user2','456'), ('user3','789')])
```

**Comment by tpastore-01123** [comment]
Hi again! Related to this...  I've been trying to add

**Comment by peeter2** [comment]
Instead of username does anyone have a clue how to get the email?

**Pull request merged**
