### PR TITLE
added try except block in `state.py`

### PR DESCRIPTION
**Pull request by SrijanSahaySrivastava**
added try except block in `state.py` which will raise a "ValueError"

## Description

added try except block in `state.py` which will raise a "ValueError" if the object cannot be deep copied.

Fix: #5737

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks for the PR @SrijanSahaySrivastava! Left some comments. 

It would be great to add a test in `test/test_components.py` to test this change.

**Comment by SrijanSahaySrivastava** [comment]
> Thanks for the PR @SrijanSahaySrivastava! Left some comments. 
> 
> It would be great to add a test in `test/test_components.py` to test this change. 

For some reason i can't see any of your comment.

I'll create some tests for it till then.

**Comment by abidlabs** [comment]
Ah sorry I think they were in a pending state. You should be able to see them now

**Comment by SrijanSahaySrivastava** [comment]
@abidlabs please check the changes now.

**Comment by abidlabs** [comment]
This looks much better! The only thing is that a lambda function *can* in fact be deep-copied, so I've changed the test to try to instantiate with the gradio module itself, which is not deep-copyable. 

Thanks for contributing this PR @SrijanSahaySrivastava! I'll merge it in after the tests run

**Comment by SrijanSahaySrivastava** [comment]
@hannahblair 😄  I sent it!!!

**Comment by SrijanSahaySrivastava** [comment]
@hannahblair I've sent the mail, but haven't received any follow up. Do i have to follow a specific structure?

**Pull request merged**
