### PR TITLE
Refactoring playground

### PR DESCRIPTION
**Pull request by whitphx**
## Description

Refactoring before working on the Playground features, e.g. requirements.

Main changes are
* Use `@gradio/code/BaseCode` as the code element like #8804
* Stop creating multiple `Code` elements one for each `demo` and mount a single `Code` instead.

### CODE REVIEW

**Review by aliabd — COMMENTED** [review]
Thanks @whitphx for the changes. all make sense to me but one thing we do lose with using BaseCode are the copy and download buttons. Is it simpler to add them ourselves? Or should we just use Code?

**Comment by whitphx** [comment]
@aliabd Thanks I missed it. I added them as 57653b9.

**Review by aliabd — APPROVED** [review]
Thanks @whitphx!

**Comment by aliabd** [comment]
@whitphx will merge this as I want to make some changes to playground and don't want to create too many conflicts

**Pull request merged**
