### PR TITLE
Turn Submit Button into Cancel Button for Interfaces with generators

### LINKED ISSUE #2497: Modify interfaces with generators so that submit button turns into stop button
- [x] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
As of gradio 3.6, interfaces that use generators will automatically have a Stop button added. It would be nicer if the submit button turned into a stop button when you clicked it and the stop button automatically turned back into a submit button when the prediction finished or when it was clicked.

### PR DESCRIPTION
**Pull request by freddyaboulton**
# Description

Fixes #2497

To test, run `fake_diffusion` or `fake_diffusion_with_gif` demos or test with the Atari agents space: https://huggingface.co/spaces/freddyaboulton/atari_agents

new_stop_button

At the end of the generation, the stop button will switch back to a submit button

stop_button_switch_back

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have added a short summary of my change to the CHANGELOG.md
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by abidlabs** [comment]
Very cool that you were able to accomplish this entirely with backend changes @freddyaboulton! 

One issue I noticed is that if the generator function throws an error, the stop button does not get converted back to a submit button. E.g. 

```py
import gradio as gr
import time

def test(x):
    yield 1
    time.sleep(1)
    yield 2
    time.sleep(1)
    yield 3
    time.sleep(1)
    yield 1/0
    time.sleep(1)
    yield 4

gr.Interface(test, "textbox", "textbox").queue().launch()
```

With backend changes, I'm not sure if there is a way to get the button to change back if an error is thrown. But I think at the very least, if the clear button is clicked, the stop button should disappear and the submit button should reappear

**Comment by freddyaboulton** [comment]
Good catch @abidlabs !

I made it so that the Stop button always reverts back to the Submit button even if there is an exception in the function.

Demo here with your code:

stop_button_error

**Comment by abidlabs** [comment]
Amazing PR @freddyaboulton, works perfectly for me.

**Review by abidlabs — APPROVED** [review]

**Comment by freddyaboulton** [comment]
Thank you for the review @abidlabs !

**Pull request merged**
