### PR TITLE
Handle GIFs correct in `gr.Image` preprocessing

### PR DESCRIPTION
**Pull request by abidlabs**
We can finally handle GIFs in `gr.Image` closing one of our oldest issues! Fixes: https://github.com/gradio-app/gradio/issues/1965, Fixes: https://github.com/gradio-app/gradio/issues/5174

Screen Recording 2024-06-20 at 3 33 32 PM

Also removes up some old methods that are not used anymore

### CODE REVIEW

**Review by aliabd — COMMENTED** [review]
Hmm i'm still seeing a very weird issue.. 

https://github.com/gradio-app/gradio/assets/9021060/5496d748-a49b-466d-8586-50b0506cab41

vs main 

https://github.com/gradio-app/gradio/assets/9021060/f286220d-fd08-4266-b80b-893bc99dc14a

with just 

```python 
import gradio as gr
gr.Interface(lambda x:x, "image", "image").launch()
```

Maybe i'm not supposed to use defaults for gifs?

**Comment by abidlabs** [comment]
Ok so basically by default, `gr.Image()` converts to a numpy array which is not valid for GIFs. For GIFS, you need to set `type` to either `filepath` or `PIL`. Let me add that to the docstrings

**Comment by abidlabs** [comment]
Yeah hmm let me see

**Comment by abidlabs** [comment]
Oh okay so what's happening is that when a PIL image is passed into a `gr.Image()` output component, the `format` parameter coerces it into the specified format, which is "webp" by default. So you'd need to do:

```py
import gradio as gr

demo = gr.Interface(lambda x:x, gr.Image(type="pil"), gr.Image(format="gif"))
    
demo.launch()
```

or you can keep it as a filepath, like this:

```py
import gradio as gr

demo = gr.Interface(lambda x:x, gr.Image(type="filepath"), "image")
    
demo.launch()
```

Slightly confusing, but I think its best we can do without a breakage

**Review by aliabd — APPROVED** [review]
Ok, i'm fine with it as is. Consider changing the docs a bit. You could even add a section on GIFs :) 

Thanks!

**Comment by abidlabs** [comment]
Yeah I'll do that!

**Pull request merged**
