### PR TITLE
Fixes SVG Icons 

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Closes: #9587

SVG icons could not be displayed because the backend would return them with `content_disposition_type="attachment"`. Developers could not set them in `allowed_paths` because they get moved to the cache and so the actual path fetched by the client is different to what the developer would know.

My proposed fix is to mark svg files moved to the cache before the app is running as "allowed" since they are developer supplied paths. 

You can run this demo to verify that arbitrary svgs are not marked as allowed after the app is running

```python
import gradio as gr


with gr.Blocks() as demo:
    button = gr.Button("button", icon="clean.svg")
    button.click(lambda: gr.Button("button", icon="arrow.svg"), None, button)

demo.launch()
```

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Could we just treat the `icon` of a `gr.Button` as a static file automatically, like we do with avatar images? 

https://github.com/gradio-app/gradio/blob/39a0e8c2fb038eb0afc213fa6290c9b2acee7941/gradio/components/chatbot.py#L281

**Comment by freddyaboulton** [comment]
I think button icons are already processed via `serve_static_file`. The problem is that `serve_static_file` treats files as `created` instead of `allowed` so svg's can't be loaded inline

**Comment by abidlabs** [comment]
Could we check if a file was specified before the app was running, in which case serve the file inline? I think that would be  a better, more general fix

**Comment by freddyaboulton** [comment]
I don't follow. That's what I'm doing but only if the file is an svg. We could remove the svg mimetype check from this PR but I wanted to modify the file serving logic as little as possible for security reasons hehe

**Comment by abidlabs** [comment]
Thanks @freddyaboulton this indeed works, but I think there's a more efficient way, which is to not move such files to the cache altogether.

Currently, inside the `async_move_files_to_cache`, we mark svgs as safe if they are are created before the app as running by adding them to the set of static files. But in that case, why did we move them to the cache at all? We have to do this chain:

Component constructor --> `serve_static_file` --> `async_move_files_to_cache` --> `_mark_svg_as_safe`, i.e. 

Instead, I'd suggest that we just mark svgs as safe directly in the `serve_static_file` file and not call `async_move_files_to_cache` for such files:

Component constructor --> `serve_static_file` --> `_mark_svg_as_safe`

Otherwise, this looks great. If possible, it'd be great to turn your demo into a test to ensure that arbitrary svgs are not marked as allowed after the app is running

**Comment by abidlabs** [comment]
This is not ready right @freddyaboulton? You don't do the check to see if its running or not anymore. 

e.g. In your original example

```py
import gradio as gr


with gr.Blocks() as demo:
    button = gr.Button("button", icon="clean.svg")
    button.click(lambda: gr.Button("button", icon="arrow.svg"), None, button)

demo.launch()
```

The `arrow.svg` will now show up

**Review by abidlabs — CHANGES_REQUESTED** [review]
security

**Review by abidlabs — APPROVED** [review]
lgtm thanks so much @freddyaboulton!

**Comment by freddyaboulton** [comment]
Thank you @abidlabs!!

**Pull request merged**
