### PR TITLE
Add Japanese translations for login UI

### PR DESCRIPTION
**Pull request by kazuhitoyokoi**
I added Japanese translations for login UI. It will be useful for Japanese users.

Screenshot 2024-12-10 at 20 13 10

### CODE REVIEW

**Review by abidlabs — APPROVED** [review]
code changes look good, thanks @kazuhitoyokoi for the contribution!

**Review by hysts — APPROVED** [review]
LGTM!

**Comment by abidlabs** [comment]
Thanks @kazuhitoyokoi @hysts!

**Comment by whitphx** [comment]
@kazuhitoyokoi Hi great to see you there, and thank you for your contribution 🤗 It looks perfect!
Super glad that you got involved to Gradio and even dispatched the PR!

**Pull request merged**
