### PR TITLE
Lite worker refactoring

### PR DESCRIPTION
**Pull request by whitphx**
## Description

Small refactorings on Lite. Not high priority. Plz review this when you have time.

### CODE REVIEW

**Review by aliabd — APPROVED** [review]
This LGTM @whitphx, thanks!

**Comment by aliabd** [comment]
not sure why lite unit test is failing

**Comment by whitphx** [comment]
Maybe the old commits were the problem? Merging the current main solved it.

Now different unit tests are failing. Will fix them.

**Comment by whitphx** [comment]
Found that the `requestAnimationFrame` trick is still needed because the timing of `connectedCallback` called may not be specified in the [spec](https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element-conformance) and we still need to care the case where the callback is called before parsing the child elements.

**Pull request merged**
