### PR TITLE
Fix Json component serialization bug

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Closes: #8916

You can test with `demo/json_component/run.py`

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks @freddyaboulton can you explain the change quickly? Trying to understand how this change fixed the json serialization

**Comment by freddyaboulton** [comment]
We changed the return type of the json component's postprocess to be a pydantic model for security reasons. Pydantic models get automatically serialized in the queue/api functions. But the `/config` route uses a custom `ORJsonResponse` that does not serialize pydantic models. So manually serializing the `value` prop so that it is already serialized when we call `get_config`.

**Review by abidlabs — APPROVED** [review]
Ah got it, thanks!

**Comment by freddyaboulton** [comment]
Thanks for the reviews everyone!

**Pull request merged**
