### PR TITLE
Replace `pip` with `uv` in our CI

### PR DESCRIPTION
**Pull request by abidlabs**
I tested `uv` on a fork of `gradio` and found that when a PR requires refreshing the cache, it shaves ~30 seconds off of the python action in our CI.

Here are the approximate runtimes:

| Package manager | No caching |  Caching | 
| ------------- | ------------- | --- |
| `pip`  | [7 min 31 seconds](https://github.com/gradio-app/gradio/pull/7443)  | [6 min 10 seconds](https://github.com/gradio-app/gradio/pull/7407) |
| `uv`  | [6 min 56 seconds](https://github.com/abidlabs/gradio/pull/17)  | [6 min 6 seconds](https://github.com/abidlabs/gradio/pull/18) |

Closes: https://github.com/gradio-app/gradio/issues/7442

### CODE REVIEW

**Comment by abidlabs** [comment]
Ah interesting, thanks @akx. Just to understand your comment, we already cache the `venv` where `uv` installs the python libraries after we create the environment. So I agree I can remove `cache: pip` if it serves no purpose. But otherwise, what cache am I missing? 

```py
    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python_version }}
        cache: pip
        cache-dependency-path: |
          client/python/requirements.txt
          requirements.txt
          test/requirements.txt
    - name: Create env
      shell: bash
      run: |
        python -m pip install --upgrade uv
        uv venv venv
    - uses: actions/cache@v4
      id: cache
      with:
        path: |
          venv/*
          client/python/venv
```

**Comment by akx** [comment]
I would maybe probably just opt to cache `~/.cache/uv` instead, since `uv` creating a venv + installing from cache should be very snappy indeed.

**Comment by abidlabs** [comment]
Agreed, `uv` is quite fast at creating the venv but there's no need to create it again if the requirements haven't changed. I'll open up this PR for review and get @pngwn's thoughts as well

**Comment by pngwn** [comment]
Are we sure this is mature enough to rly on? I agree that it is very interesting but it was released about a week ago and isn't really battle tested.

I for example cannot perform a fresh install of `scikit-image==0.19.3` with `uv` as the wheel fails to build. I have no such issues with `pip`.

This also only save us 30 seconds some of the time, which is nice but hardly game-changing. Most of our CI time is spent elsewhere.

**Comment by pngwn** [comment]
I think we should revisit in a short while when some of the kinks have been worked out. It would be nice to speed things up, both locally and in CI.

**Comment by abidlabs** [comment]
Will leave the issue open but close this for now

**Pull request closed without merging**
