### PR TITLE
Pause autoscrolling if a user scrolls up in a `gr.Textbox` and resume autoscrolling if they go all the way down

### PR DESCRIPTION
**Pull request by abidlabs**
QoL improvement for autoscrolling in `gr.Textbox`

Closes: #5518 

Test code:

```py
import gradio as gr
import time

s = "abcd deaf asdfhasd asdfla;"*1000

def test(x):
    for i in range(len(s)):
        time.sleep(0.001)
        yield s[: i+1]

gr.Interface(test, "textbox", gr.Textbox(max_lines=4, autoscroll=True)).queue().launch()
```

### CODE REVIEW

**Comment by dawoodkhan82** [comment]
@abidlabs When the textbox first starts filling up, I have to scroll down a bit to "activate" the autoscroll.

**Comment by abidlabs** [comment]
@dawoodkhan82 I can't repro that behavior. What code are you using to test?

Can you test on the latest version? Happy to sync on this if needed.

**Review by dawoodkhan82 — APPROVED** [review]
Cannot reproduce the issue I was seeing before. So should be good to merge

**Comment by abidlabs** [comment]
Sounds good thanks @dawoodkhan82 and @hysts. Let me know if the issue comes back.

**Comment by yvrjsharma** [comment]
I tried it [here](https://huggingface.co/spaces/ysharma/testing_gradio_wheels) successfully. However, the scrollbar doesn't appear in the textbox. Do you know why that is happening?

**Pull request merged**
