### PR TITLE
Updating typing in `utils.py` and `templates.py`

### PR DESCRIPTION
**Pull request by 1nF0rmed**
# Description

~This is still WIP.~

Associated Issue: https://github.com/gradio-app/gradio/issues/2552
Comment Reference: https://github.com/gradio-app/gradio/issues/2552#issuecomment-1366796379

This PR deals with updating the typing to match the usage and adding any missing typing.
Files being handled in this PR:

- [x]  [utils.py](https://github.com/gradio-app/gradio/blob/main/gradio/utils.py)
- [x]  [templates.py](https://github.com/gradio-app/gradio/blob/main/gradio/templates.py)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks for starting this @1nF0rmed!

**Comment by abidlabs** [comment]
How's it going @1nF0rmed? I am aiming to finish up the other files over this weekend and so will be happy to help with these files afterwards

**Comment by 1nF0rmed** [comment]
@abidlabs I'm looking at finishing `utils.py` over a couple of hours and then `templates.py` before the weekend ends.

**Comment by 1nF0rmed** [comment]
I've updated the typing in `utils.py`. Will continue working on `templates.py` later in the weekend.

**Comment by 1nF0rmed** [comment]
@abidlabs 
I have updated the typing in `templates.py` as well. 
When you have time, please check my changes, as I will also update the typing in the respective code comments.

**Comment by abidlabs** [comment]
This looks fantastic! Thanks for going through and fixing these files @1nF0rmed. I only see two additional changes that need to be made and then we can merge this in:

* We're switching from `Optional[X]` to `X | None` syntax for typing parameters that can take `None` as a value, as it's a bit clearer. Would you be able make the changes in both `utils.py` and `templates.py`?
* Can you update `scripts\type_check_backend.sh` to type check both `utils.py` and `templates.py`?

Thanks @1nF0rmed!

**Comment by 1nF0rmed** [comment]
@abidlabs I've made the following changes:

- Updated `Optional[X]` to `X | None` in both `utils.py` and `templates.py`
- Added both files to `scripts\type_check_backend.sh`

**Comment by abidlabs** [comment]
We're almost there @1nF0rmed. Let me see if I can fix the issue that popped up and then will merge it in. For some reason, CircleCI is only running when I make the commits

**Comment by 1nF0rmed** [comment]
Thanks @abidlabs, for the last push! 

It looks like it's ready for merging now

**Comment by abidlabs** [comment]
Yes it does! Thank you @1nF0rmed for the nice improvement to the library

**Pull request merged**
