### PR TITLE
Add deploy_discord to docs

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Oversight on my part from #4960 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by freddyaboulton** [comment]
@aliabd Why doesn't it show up in the vercel preview?

**Comment by aliabd** [comment]
run `python generate_jsons/generate.py` from inside `js/_website` and commit the json files. But make sure you have an editable pip install of gradio and gradio_client

**Comment by aliabd** [comment]
(hopefully this will be much easier soon)

**Review by aliabd — APPROVED** [review]
LGTM thanks @freddyaboulton! I updated the jsons so it shows up in preview. Will merge

**Pull request merged**
