### PR TITLE
Prevent overflow in Model3D

### PR DESCRIPTION
**Pull request by hannahblair**
## Description

Ensures that if a background is set, the border radius of the Model3D component is still respected, and prevents any overflow.

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
I actually don't see the issue in the original Space anymore: 

image

Were you able to confirm the issue locally @hannahblair? If so can you share a repro?

**Comment by abidlabs** [comment]
Oh this is good to fix too, but I thought the original issue was referring to the image icons being cut off (the icons under the cat image here):

image

**Review by aliabd — COMMENTED** [review]
I still see overflow in the input 

Screen Shot 2024-08-02 at 5 47 26 PM

I think you need to add the same rules to `.input-model` in `Model3DUpload.svelte`

**Review by aliabd — APPROVED** [review]
LGTM! :)

**Pull request merged**
