### PR TITLE
Refactor Chatinterface to use Chatbot instead of gr.State variables

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Closes: #8812 
Closes: #8847

The issue is that the chatbot preprocess does not run because the input to the event handler is a gr.State variable instead of a gr.Chatbot. 

I refactored chat_interface to use the gr.Chatbot as the input/output component but there may be some unintended consequences.

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by freddyaboulton** [comment]
Thoughts on this approach @dawoodkhan82 @abidlabs ? Not sure how else to fix

**Comment by dawoodkhan82** [comment]
@freddyaboulton Haven't tested yet, but this should be fine. Basically same change we made to the chatbot demos a while back.

**Comment by abidlabs** [comment]
The reason we used state previously was because it simplified API usage — you didn’t have to provide the history when hitting the /chat endpoint. Haven’t taken a deep look here yet

**Comment by abidlabs** [comment]
Given that we are still using `chatbot_state` in the API functions, this should be okay. Let me test it out

**Comment by abidlabs** [comment]
Generally looks good @freddyaboulton. We need to also update the `_append_multimodal_history()` method as well though I believe, since right now the multimodal chatinterface demos aren't working, e.g. `demo/chatinterface_multimodal/run.py`

**Comment by freddyaboulton** [comment]
Thanks for testing @dawoodkhan82 @abidlabs ! I think the multimodal issue has been fixed!

**Review by abidlabs — APPROVED** [review]
lgtm @freddyaboulton nice fix!

**Pull request merged**
