### PR TITLE
Only connect to heartbeat if needed

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Closes: #8022 

Rather than always connecting to the heartbeat route, we should do so only when gr.State variables are used (to clean up state) or when the `unload` event is set. Users may still run into the browser limit, however. 

EDIT: I originally wanted to raise an error or message when the page locked up due to the connection limit. But the browser will block all requests after the limit is reached so we won't be able to fetch the config and progressively load the app.

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Will this be compatible with gr.render() -- now that we can dynamically create components, a developer might include a workflow that dynamically creates `gr.State()` components? 

The only other idea I can think of is to use long polling instead of a persistent SSE connection for the heartbeat

**Review by pngwn — APPROVED** [review]
Looks great! Thanks @freddyaboulton!

Note: this should working fine with the render decorator because we refresh the config, as freddy mentioned.

**Review by aliabid94 — APPROVED** [review]
LGTM!

**Comment by freddyaboulton** [comment]
Thanks for the reviews all!

**Pull request merged**
