### PR TITLE
Redesign `gr.Button()`

### PR DESCRIPTION
**Pull request by hannahblair**
## Description

Some notes/highlights: 
- Buttons `translateY` by 0.5px on hover. You could argue it could `translateY` by -0.5px but I noticed in a demo that the button can get slightly cut off when moving down.
- Removed all drop shadows and gradients
- Decreased overall radius size from lg to md in large buttons, and from sm to xs in small buttons

Also adds an Origin theme which retains all the old styling. 

Demo

```
import gradio as gr

icon = "https://cdn.icon-icons.com/icons2/2620/PNG/512/among_us_player_red_icon_156942.png"
with gr.Blocks() as demo: # also try with gr.Blocks(theme=gr.themes.Origin()) as demo:

   gr.Button(variant="primary")
   gr.Button(variant="secondary")
   gr.Button(variant="stop")

   gr.Button(variant="primary", size="sm")
   gr.Button(variant="secondary", size="sm")
   gr.Button(variant="stop", size="sm")

   gr.Button(variant="primary", icon=icon)
   gr.Button(variant="secondary", icon=icon)
   gr.Button(variant="stop", icon=icon)


   gr.Button(variant="primary", size="sm", icon=icon)
   gr.Button(variant="secondary", size="sm", icon=icon)
   gr.Button(variant="stop", size="sm", icon=icon)

demo.launch()
```

Closes: #8789 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by pngwn** [comment]
i like it, burnished orange

**Comment by abidlabs** [comment]
Huge fan of the changes @hannahblair! Everything looks good except that the stop button with light mode looks very faded out. I'd suggest darken the red & using a white font:

image

similar to the primary button:

image

**Comment by abidlabs** [comment]
Looks perfect!

**Review by abidlabs — COMMENTED** [review]
Nice, tested the buttons again and they look great in both dark mode and light mode!

**Pull request merged**
