### PR TITLE
fix file upload text

### LINKED ISSUE #900: [`blocks-dev`] file input is broken
### Describe the bug

Tried running these two demos:
* `demo\zip_two_files\run.py`
* `demo\zip_to_json\run.py`

But they were unrunnable because the file input is broken:
* Before you select the file, it says "drop an audio file" instead of "drop a file"
* After you drop the file, the file takes over the whole screen making you unable to click submit (see screenshot)

### Reproduction

* `demo\zip_two_files\run.py`
* `demo\zip_to_json\run.py`

### Screenshot

image

### Logs

_No response_

### System Info

```shell
blocks-dev
```

### Severity

blocker

### PR DESCRIPTION
**Pull request by pngwn**
Closes #900

### CODE REVIEW

**Comment by pngwn** [comment]
Not sure if this is the only thing that needs fixing, everything else seemed to work.

**Comment by abidlabs** [comment]
(The other demo, `demo\zip_to_json\run.py` works great)

**Comment by pngwn** [comment]
@abidlabs I have cleaned up the file display a little (since it looked horrific) and added an explicit download link. This won't be final until victor has worked his magic but makes things a little more usabl for now. I've also added the cursor for upload inputs.

Screenshot 2022-04-07 at 19 02 21

**Comment by abidlabs** [comment]
✅

**Review by abidlabs — APPROVED** [review]

**Pull request merged**
