### PR TITLE
Prevent path traversal in `/file` routes

### PR DESCRIPTION
**Pull request by abidlabs**
Prevents path traversal in `/file` routes

[Internal discussion here](https://huggingface.slack.com/archives/C02SPHC1KD1/p1685485378960919)

### CODE REVIEW

**Comment by abidlabs** [comment]
Actually needs more work, converting to draft

**Comment by abidlabs** [comment]
Should be ready now

**Review by aliabid94 — APPROVED** [review]
lgtm

**Comment by abidlabs** [comment]
Thanks @aliabid94!

**Pull request merged**
