### PR TITLE
Fix file upload on windows

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

🥳 

image

Closes: #6246

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Niceee! Very interesting.

**Comment by abidlabs** [comment]
I haven't been able to test on Windows, but code looks good & file upload on Linux and Mac continues to work. 

Let's get this in!

**Review by abidlabs — APPROVED** [review]

**Comment by pngwn** [comment]
i have no idea what any of this means. i'm assuming it is just typical windows shenanigans.

**Comment by freddyaboulton** [comment]
If my lil dinky windows laptop can now upload files, hopefully everyone's can 😆

**Comment by abidlabs** [comment]
You were able to repro the original issue on your laptop?

**Comment by freddyaboulton** [comment]
Yea I have a separate windows laptop that I rarely use. I was able to repro the problem and confirm the fix.

**Comment by ndurner** [comment]
Confirmed to be working. Thanks a lot!

**Comment by TRUEJASONFANS** [comment]
@freddyaboulton  thanks bro for your quick fix!

**Pull request merged**
