### PR TITLE
Add Jinja2 language to Code component

### PR DESCRIPTION
**Pull request by CISC**
## Description

Adds Jinja2 support to Code component, mainly because I need it in [GGUF Editor](https://huggingface.co/spaces/CISCai/gguf-editor), but it certainly can be useful for others as well to either edit model chat templates or other templating tasks.

I'm targetting this toward 5.0 due to its imminent release, and it being a very small and unintrusive PR it could hopefully be included in its release. Let me know if alternate action should be considered additionally/instead.

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks @CISC for the PR. Taking a look

**Comment by abidlabs** [comment]
LGTM, thanks for the contribution @CISC!

image

**Review by abidlabs — APPROVED** [review]
will merge in once CI finishes

**Comment by CISC** [comment]
@abidlabs Thank you! Mind having a look at gradio-app/awesome-demos#18 too?

**Pull request merged**
