### PR TITLE
Lite: Support AnnotatedImage on Wasm

### PR DESCRIPTION
**Pull request by whitphx**
## Description

This PR makes `gr.AnnotatedImage` Wasm-compatible.

Closes: #6131

### Object detection
CleanShot 2023-10-29 at 15 38 13@2x

<details>

```html
<gradio-lite>
<gradio-requirements>
transformers_js_py
</gradio-requirements>

<gradio-file name="app.py" entrypoint>
from transformers_js import import_transformers_js, as_url
import gradio as gr

transformers = await import_transformers_js()
pipeline = transformers.pipeline
pipe = await pipeline('object-detection', "Xenova/yolos-tiny")

async def detect(input_image):
    result = await pipe(as_url(input_image))
    gradio_labels = [
        # List[Tuple[numpy.ndarray | Tuple[int, int, int, int], str]]
        (
            (
                int(item["box"]["xmin"]),
                int(item["box"]["ymin"]),
                int(item["box"]["xmax"]),
                int(item["box"]["ymax"]),
            ),
            item["label"],
        )
        for item in result
    ]
    annotated_image_data = input_image, gradio_labels
    return annotated_image_data, result

demo = gr.Interface(
    detect,
    gr.Image(type="filepath"),
    [
        gr.AnnotatedImage(),
        gr.JSON(),
    ]
)

demo.launch()
</gradio-file>

</gradio-lite>
```

The sample image is from https://vancouver.ca/streets-transportation/homer-street-upgrades.aspx

</details>

### Segmentation

CleanShot 2023-10-29 at 15 51 16@2x

<details>

```shell
mkdir images
cd images
wget https://gradio-builds.s3.amazonaws.com/demo-files/base.png
wget https://gradio-builds.s3.amazonaws.com/demo-files/buildings.png
cd ..
python -m http.server
```

```html
<gradio-lite>

<gradio-file name="base.png" url="/images/base.png" />
<gradio-file name="buildings.png" url="/images/buildings.png" />

<gradio-file name="app.py" entrypoint>
import gradio as gr
from PIL import Image
import numpy as np

base_image = Image.open("base.png")
building_image = Image.open("buildings.png")

# Create segmentation mask
building_image = np.asarray(building_image)[:, :, -1] > 0

with gr.Blocks() as demo:
    gr.AnnotatedImage(
        value=(base_image, [(building_image, "buildings")]),
        height=500,
    )

demo.launch()
</gradio-file>

</gradio-lite>
```
</details>

### CODE REVIEW

**Review by aliabid94 — APPROVED** [review]
LGTM

**Comment by whitphx** [comment]
Thanks!
Gradio-lite is now not working after v4 merge, so plz wait for fixing the problem before resolving the conflict.

**Comment by whitphx** [comment]
Current impl has the same problem as what https://github.com/gradio-app/gradio/pull/6398#issuecomment-1843184084 referred to the `Image` component.
Will fix it with the same solution as well.

**Review by aliabd — APPROVED** [review]
Everything LGTM! Nice work @whitphx 

This is good to merge :)

**Pull request merged**
