### PR TITLE
enable lazy caching for chatinterface

### PR DESCRIPTION
**Pull request by abidlabs**
Finally figured out a relatively simple way to enable lazy caching for ChatInterface. Closes: https://github.com/gradio-app/gradio/issues/9981

This PR also introduces another variable `GRADIO_RESET_EXAMPLES_CACHE` which is needed to avoid cache conflicts with the new e2e test I added.

### CODE REVIEW

**Comment by hysts** [comment]
Thanks! I've confirmed that it's working for "lazy", but while testing this PR, I noticed something is wrong with "eager". Not sure if this is a bug from the beginning or if this is introduced in this PR, but when I use the wheel in this PR, even if I set `cache_mode="eager"`, `indices.csv` is not updated at the app launch while `log.csv` is updated, and the example caching takes place at your first run.

You can add `time.sleep(10)` or something to make it more noticeable:
```py
import time

import gradio as gr


def fn(message, history):
    time.sleep(10)
    return message


gr.ChatInterface(
    fn=fn,
    cache_examples=True,
    cache_mode="eager",
    examples=[["hey"], ["hello"]],
    type="messages",
).launch()

```

**Comment by abidlabs** [comment]
Ah nice catch, I'll fix this

**Comment by abidlabs** [comment]
Should be fixed now!

**Review by hysts — APPROVED** [review]
Thanks! LGTM!

**Comment by abidlabs** [comment]
Thanks for the rapid review @hysts!

**Pull request merged**
