### PR TITLE
ensure Dataframes in background tabs are visible when the tab is selected

### LINKED ISSUE #7349: Dataframe appears empty on mobile
### Describe the bug

Dataframe appears empty on mobile

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

https://chat.lmsys.org/?leaderboard

(working on better repro)

### Screenshot

image

### Logs

_No response_

### System Info

```shell
gradio==4.17.0
```

### Severity

Blocking usage of gradio

### PR DESCRIPTION
**Pull request by pngwn**
Closes #7349.

See comment below for details.

### CODE REVIEW

**Comment by pngwn** [comment]
Alright, I think I have this working now:

Old:

https://github.com/gradio-app/gradio/assets/12937446/b17a195c-1bf2-4d76-98d7-6121a7479c1a

New:

https://github.com/gradio-app/gradio/assets/12937446/b5f56401-ba9c-437a-81eb-6d9f9620a3fe

The issue was to do with heights not being reported correctly (or at all) for certain devices. I do not know why. It will remain forever a mystery.

I changed how we become notified of dimensions changes and that seems to have done the trick.

The CSS being broken is a separate issue.

If you have access to a device that didn't work then please try this preview: https://pngwn-7349-df-repro-fix.hf.space/

**Comment by pngwn** [comment]
This PR represents the least fun I've had in years. I might frame it as a reminder.

**Comment by pngwn** [comment]
Those test failures are weird but i can repro locally.

**Review by abidlabs — APPROVED** [review]
Brilliant @pngwn thanks for taking care of this!

**Comment by pngwn** [comment]
work pls

**Pull request merged**
