### PR TITLE
Fix fake_diffusion by slider to only have int so range() doesn't fail

### PR DESCRIPTION
**Pull request by abhishekkr**
## Description

I tried this demo on Gradio Docs and the run failed for me, when I tweaked slider value.

Cause was default increment allows float values and range(steps) fails for float values. Thus solving it in Gradio's idiomatic way... adding step=1 to Slider would only allow steps:int to be used. Avoiding error scenarios.

Closes: #7166

### CODE REVIEW

**Comment by abidlabs** [comment]
Nice catch @abhishekkr! LGTM.

**Comment by abidlabs** [comment]
We'll need to update the demo notebooks as well (we have a notebook for each demo). You can do that by doing:

`cd demo && python generate_notebooks.py` 

or you can let maintainers edit this PR and I'm happy to make that change. Then we should be good to merge!

**Comment by abhishekkr** [comment]
> We'll need to update the demo notebooks as well (we have a notebook for each demo). You can do that by doing:
> 
> `cd demo && python generate_notebooks.py`
> 
> or you can let maintainers edit this PR and I'm happy to make that change. Then we should be good to merge!

will do :)

**Comment by abhishekkr** [comment]
@abidlabs have updated the PR's commit for notebook changes

**Comment by abidlabs** [comment]
Thanks @abhishekkr!

**Review by freddyaboulton — APPROVED** [review]

**Pull request merged**
