### PR TITLE
Apply different formatting for the types in component docstrings

### PR DESCRIPTION
**Pull request by aliabd**
Makes the types colored and italic in the component docstrings. 

Closes: #1763 

Before: 

Screen Shot 2022-11-22 at 4 46 17 PM

After: 

Screen Shot 2022-11-22 at 4 49 49 PM

### CODE REVIEW

**Comment by abidlabs** [comment]
Cool @aliabd! Wdyt about making it monospace (i.e. code font) instead of italics?

**Comment by aliabd** [comment]
@abidlabs 

Screen Shot 2022-11-22 at 5 27 51 PM

**Comment by abidlabs** [comment]
Looks great to me @aliabd! Initially I was confused why it wasn't showing for me locally, then realized I had to switch to viewing `main` lol

**Review by abidlabs — APPROVED** [review]

**Comment by aliabd** [comment]
@abidlabs hahaha yeah, always happens to me

**Pull request merged**
