### PR TITLE
fix chatbot example code

### PR DESCRIPTION
**Pull request by petrov826**
As I reported in https://github.com/gradio-app/gradio/issues/3031, the chatbot demo code in https://gradio.app/interface-state has a bug. We need to cast `random.randint(1, 10)` to `str` explictly.

### CODE REVIEW

**Comment by petrov826** [comment]
This is my first time to make a PR for large-scale open source project. If I had skipped some of the work steps, please let me know.

**Comment by abidlabs** [comment]
Running the checks now!

**Comment by abidlabs** [comment]
It looks like you just need to do 2 additional things:
* Add an entry in `CHANGELOG.md` crediting yourself with the fix
* Run this command `pip install nbformat && cd demo && python generate_notebooks.py` to generate the updated jupyter notebook for your demo

**Comment by petrov826** [comment]
@abidlabs Thank you for showing me what I need to do!

**Review by freddyaboulton — APPROVED** [review]
Thank you for the fix @petrov826 !

**Pull request merged**
