### PR TITLE
reuse httpx client to reduce number of TIME_WAIT connections

### PR DESCRIPTION
**Pull request by dodysw3**
## Description

This PR changes gradio python client instance to reuse httpx client connection and uses http2 if possible. The intention is to keep number of TIME_WAIT TCP connections low to avoid hitting outbound connection limit on shared NAT gateway.

Closes: #7890

### CODE REVIEW

**Comment by abidlabs** [comment]
Do we need to pass in an instance of a Client as an argument into the constructor? It seems relatively uncommon to need to recycle the httpx client across more than one Gradio client so it should be enough to create one at init time and use it for all calls to predict() and submit()

**Comment by dodysw3** [comment]
> Do we need to pass in an instance of a httpx client as an argument into the constructor? It seems relatively uncommon to need to recycle the httpx client across more than one Gradio client so it should be enough to create one at init time and use it for all calls to predict() and submit()

agree, removing it, better also not exposing so we can switch to different protocol/library later without breaking change.

**Comment by freddyaboulton** [comment]
Can we call `close` in the destructor?

**Comment by abidlabs** [comment]
I don’t think we need to explicitly destroy the httpx async client. It should get garbage collected when all references to the Python Gradio Client end, right? Do you notice any issues if you don’t explicitly close it?

**Comment by abidlabs** [comment]
Converting to draft for now, let us know if ready for review @dodysw3

**Comment by dodysw3** [comment]
> Converting to draft for now, let us know if ready for review @dodysw3
Thanks apologize this taking much time.

> I don’t think we need to explicitly destroy the httpx async client. It should get garbage collected when all references to the Python Gradio Client object end, right? ...

Thanks, I realized my current understanding of how async works in Python is limited. In my use case, actually I did encountered deadlock (infinite loop) inside fsspec/asyn.py, specifically this block:
```
    while True:
        # this loops allows thread to get interrupted
        if event.wait(1):
            break
        if timeout is not None:
            timeout -= 1
            if timeout < 0:
                raise FSTimeoutError
```
when the client process exiting. It took me a while to debug; unfortunately after merging the dev branch with latest gradio main I'm no longer able to reproduce, I will try to revert to old code again later.

>Do you notice any issues if you don’t explicitly close it?

Only that the client TCP connections are still established when nothing references the Python Gradio Client object, I also found destructor method is not called immediately when references are removed (or out of scope), which might be the reason. In my case, it's not an issue as a single Gradio Client object is reused for all predict()s, but leaving connections open after finishes using Gradio Client object seems like a resource leak to me.

**Comment by dodysw3** [comment]
Illustration of the problem, it seemed launching a new thread when the process is exiting will lead to deadlock, this is just Python general behaviour that leads to general advice not to run complex operations on destructors. In my PR case, running utils.synchronize_async() leads to fsspec to potentially (recreate) new thread to run its own event loop -- caused deadlock since the Python process is exiting -- and the event.wait(1) will never be signaled since the threads never starts. If this analysis correct, I don't wish to proceed with this PR until Gradio Python client API is to run it within try..finally or context with-statements to ensure the cleanup happens. Thanks @abidlabs @freddyaboulton for the exercise!

```
import asyncio
import threading
import time


class Client:
    def __del__(self):
        print("If this is called after loop END, it will deadlock")
        th = threading.Thread(target=lambda: time.sleep(1))
        th.start()
        print("this is never reached")


async def main():
    c = Client()
    c.c = c
    # intentionally create cyclical reference so it will not immediately be destroyed

if __name__ == '__main__':
    print("Begin")
    asyncio.run(main())
    print("End")
```

**Comment by abidlabs** [comment]
Hmm I see let us know if you want us to take another look at this PR or if we should mark this as closed for now

**Comment by dodysw3** [comment]
Hi @abidlabs reopening again this for a quick ask of your insight of this PR.

1. Adding optional parameter in gradio python Client() to explicitly enable persistent connection; as a more explicit desire for user to increase performance with compromise of not forgetting to call .close() afterward.
2. Added wrapper classes to httpx.Client that optionally disable context-manager to reused https.Client instance (it will be cleaned up when close() is called); this way existing codes don't have to care if it's in "persistent-mode" or not, the class will reuse httpx.Client if available or revert to old behaviour.

Documentation update can guide users on how to use this correctly. Thanks for looking!

**Comment by freddyaboulton** [comment]
Hi @dodysw3 , we're going to remove the async client shortly so that only the sync client is used (https://github.com/gradio-app/gradio/issues/7581). Then we shouldn't have the deadlock async issue your seeing now. I think we should close this PR and re-open this once that's done.  Would still love your contribution. Thanks for your hard work on this.

**Pull request closed without merging**
