### PR TITLE
Remove `generate_sample()` method

### PR DESCRIPTION
**Pull request by space-nuko**
Related: #3438

### CODE REVIEW

**Comment by abidlabs** [comment]
@aliabd do we use `.generate_sample()` anywhere? I thought we used it to generate the samples in the "view API" page:

image

But I searched the codebase and can't find it actually being used anywhere so maybe the "view API" page is being populated in some other way?

**Comment by aliabd** [comment]
Right, we don't use it anymore. We now document the examples for api docs in the `index.ts` files for every component (where we also document types). Here's where your screenshot got the examples for [image](https://github.com/gradio-app/gradio/blob/19eaafb2adf1e9de49d172cc1c4695f977b691b0/ui/packages/app/src/components/Image/index.ts#L12), [audio](https://github.com/gradio-app/gradio/blob/19eaafb2adf1e9de49d172cc1c4695f977b691b0/ui/packages/app/src/components/Audio/index.ts#L14) and [text](https://github.com/gradio-app/gradio/blob/19eaafb2adf1e9de49d172cc1c4695f977b691b0/ui/packages/app/src/components/Textbox/index.ts#L11).

**Comment by abidlabs** [comment]
Gotcha thanks for the clarification @aliabd. 

@space-nuko this PR LGTM! If you can just add yourself to the changelog, then we'll merge it in.

**Comment by abidlabs** [comment]
Thanks @space-nuko for the fix, merged in.

**Comment by abidlabs** [comment]
I've changed #3438 to a tracking issue and marked this task as complete

**Pull request merged**
