### PR TITLE
Ensure `gradio_client` is backwards compatible with `gradio==3.24.1`

### PR DESCRIPTION
**Pull request by abidlabs**
[As discussed internally](https://huggingface.slack.com/archives/C02QZLG8GMN/p1690856034533989), some of the changes to the client were not fully backwards compatible, which broke older versions of `gradio` if they were using later versions of the client. This fixes that, at least for `gradio==3.24.1` (I have not tested other versions of `gradio`). 

To test:

1. Install `gradio==3.24.1`
2. Install the latest version of `gradio_client` from pypi
3. Run any Gradio app (it will not work)
4. Install `gradio_client` from this branch
5. It should work

### CODE REVIEW

**Comment by freddyaboulton** [comment]
I think we're going to do a hard pin of gradio_client in gradio requirements instead

**Comment by abidlabs** [comment]
We should do both @freddyaboulton -- make this fix to address older versions of `gradio` while also pinning `gradio_client` going forward (I'll add the pin to this PR)

**Review by freddyaboulton — APPROVED** [review]
Thanks @abidlabs !

**Comment by abidlabs** [comment]
Appreciate the review @freddyaboulton

**Comment by pngwn** [comment]
The hard pin needs to be updated in CI because the requirements get updated every time we make a release. i'll find that and take care of it.

**Comment by freddyaboulton** [comment]
Thanks @pngwn !

**Comment by pngwn** [comment]
https://github.com/gradio-app/gradio/pull/5222

**Pull request merged**
