### PR TITLE
Lite: Capture stdout and stderr from the main thread

### PR DESCRIPTION
**Pull request by whitphx**
## Description

Makes it possible to capture the stdout and stderr in the Pyodide env from the main thread `WorkerProxy` like https://github.com/gradio-app/gradio/pull/9984/files#diff-b8397e16be06799abe4aad0399bc152c2b4e62c7294845513ed1c72e4950f3c3R91-R98
```
		controller.addEventListener("stdout", (event) => {
			const message = (event as CustomEvent).detail as string;
			// ...
		});
		controller.addEventListener("stderr", (event) => {
			const message = (event as CustomEvent).detail as string;
			// ...
		});
```

Closes: #6108

### CODE REVIEW

**Comment by aliabd** [comment]
@whitphx Interesting, build errors are not showing up in stderr. Basically any error before the demo is built. like this for example: 

```python
import gradio as gr

1/0

def fn(x):
    return x

demo = gr.Interface(
    fn=fn,
    inputs=gr.Textbox(),
    outputs=gr.Textbox(),
)

demo.launch()

```

Screenshot 2024-12-16 at 4 22 53 PM

**Comment by whitphx** [comment]
Looks like those different types of errors are thrown from different places, one of which already has an error handler but another doesn't, and errors not caught are printed in stderr.
* I will investigate where the handler should be added.
* At the same time, I think we should keep this stdout/stderr mechanism as a general fallback.

**Comment by whitphx** [comment]
@aliabd I added a new event to capture such errors. wdyt about this?

**Comment by whitphx** [comment]
Looks like the error capturing itself is working in my env, though I found the `<ErrorDisplay />`'s style is broken in the embedded mode which I should fix.

CleanShot 2024-12-18 at 16 38 32@2x

```html
<!doctype html>
<!-- A demo HTML file to test the bundled JS and CSS files -->
<html>
	<head>
		<meta charset="utf-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1, shrink-to-fit=no, maximum-scale=1"
		/>

		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link
			rel="preconnect"
			href="https://fonts.gstatic.com"
			crossorigin="anonymous"
		/>
		<script type="module" crossorigin src="./dist/lite.js"></script>
		<link rel="stylesheet" href="./dist/lite.css" />
	</head>

	<body style="padding: 10px; height: 100%; width: 100%">
		<h2>Dedicated Worker</h2>
		<gradio-lite>
import gradio as gr

1/0

def fn(x):
    return x

demo = gr.Interface(
    fn=fn,
    inputs=gr.Textbox(),
    outputs=gr.Textbox(),
)

demo.launch()
		</gradio-lite>

		<h2>Shared Worker</h2>
		<gradio-lite shared-worker>
import gradio as gr

1/0

def fn(x):
    return x

demo = gr.Interface(
    fn=fn,
    inputs=gr.Textbox(),
    outputs=gr.Textbox(),
)

demo.launch()
		</gradio-lite>
	</body>
</html>

```

**Comment by aliabd** [comment]
Sorry @whitphx what i meant to say was that i'm not sure how to use the python-error event. I added an event listener like you did for stdout and stderr but it doesn't seem like the event is triggering.

**Comment by whitphx** [comment]
@aliabd Ahh, my bad.
That error occurred here: https://github.com/gradio-app/gradio/pull/9984/files#diff-e807a6ad56ed34cac3ca1753bd3ab2dad9e2042d80c2fb21e55834d417f42f7aR118-R120 that was not caught,
so I added `init-code-run-error` event dispatcher there.
Now you can capture the event like this:
```js
controller.addEventListener("init-code-run-error", (e) => {
	console.log("init-code-run-error", e);
});
```

The event structure is getting complicated so maybe we should redesign it..

**Review by aliabd — APPROVED** [review]
Nice @whitphx this worked for what I wanted, I merged it into my branch for the playground error fixing, and it worked as intended. 

Like you said some of the errors  on stderr aren't as specific and the event listeners are getting a bit bloated but this is enough for now so let's just revisit in the future.

**Pull request merged**
