### PR TITLE
Bugfix: Fix color and size keys in theme builder app

### PR DESCRIPTION
**Pull request by shubhamofbce**
## Description

Theme builder was not generating correct keys for Colors and Size, So I have updated the builder app to start showing the correct attributes of color and size.
The fixed theme builder is also deployed on hf space: https://huggingface.co/spaces/shubhamofbce/theme-color-fix

Closes: #6711  #7688 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by shubhamofbce** [comment]
@abidlabs @freddyaboulton This is ready for review.

**Comment by abidlabs** [comment]
@aliabid94 could you take this one?

**Comment by shubhamofbce** [comment]
@abidlabs or @aliabid94 Any updates on this.

**Comment by aliabid94** [comment]
taking a look

**Comment by abidlabs** [comment]
Thanks for the fix @shubhamofbce @aliabid94!

**Pull request merged**
