### PR TITLE
Way to change page's tab title in interface

### PR DESCRIPTION
**Pull request by charlielito**
This is to partially solve #385 . Would you implement it this way?

### CODE REVIEW

**Comment by abidlabs** [comment]
My preference would be to simply use the `Interface` `title` as the tab title as well, to avoid adding another parameter. @charlielito do you encounter use cases where this would not suffice?

**Comment by charlielito** [comment]
> My preference would be to simply use the `Interface` `title` as the tab title as well, to avoid adding another parameter. @charlielito do you encounter use cases where this would not suffice?

Yes, you might be right, `title` is enough

**Comment by abidlabs** [comment]
LGTM. Tested and it works: 

image

**Comment by abidlabs** [comment]
Thanks so much @charlielito for the fix! I will keep #386 open because we will still work on adding favicon support

**Comment by TalhaAhmadSaddique** [comment]
there is any update on how can i add my favicon icon in gradio tab?

**Comment by TalhaAhmadSaddique** [comment]
@charlielito do you have any update? i used head parameter of gradio.blocks but its not working... 
image

**Comment by charlielito** [comment]
> @charlielito do you have any update? i used head parameter of gradio.blocks but its not working... image

You need to use the `tab_title` parameter in the constructor of `gr.Interface` ....

**Pull request merged**
