### PR TITLE
Enable gradio to work on kaggle

### PR DESCRIPTION
**Pull request by freddyaboulton**
# Description

Enable gradio to run on kaggle notebooks via share link

Test with this notebook: https://www.kaggle.com/code/freddyboultonhf/kaggle-gradio-share

Basically install this gradio build: https://gradio-builds.s3.amazonaws.com/kaggle-launch/attempt-1/gradio-3.17.0-py3-none-any.whl

image

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have added a short summary of my change to the CHANGELOG.md
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by dawoodkhan82** [comment]
having trouble installing that gradio build in a kaggle notebook `Could not install packages due to an OSError:`

**Comment by freddyaboulton** [comment]
@dawoodkhan82 did you enable internet access for your kaggle notebook? I was having troubles at first too. You have to authenticate your kaggle account with a phone number and then you will see this "Internet" toggle button in the settings tab

image

**Comment by dawoodkhan82** [comment]
> @dawoodkhan82 did you enable internet access for your kaggle notebook? I was having troubles at first too. You have to authenticate your kaggle account with a phone number and then you will see this "Internet" toggle button in the settings tab on the right hand side of the notebook
> 
> image

Yes it works. Didn't realize I signed in using my hf email instead of my kaggle verified email.

**Review by dawoodkhan82 — APPROVED** [review]

**Comment by freddyaboulton** [comment]
Thank you for the review @dawoodkhan82 !

**Pull request merged**
