### PR TITLE
Getting old Python unit tests to pass on `blocks-dev`

### PR DESCRIPTION
**Pull request by abidlabs**
Continuing to update demos to the new syntax and creating issues as I find them...

### CODE REVIEW

**Comment by abidlabs** [comment]
I'm opening this branch up, the main thing I did here was to go through all of the unit tests and fix everything so that the unit tests pass. 

I'm getting some weird behavior in which the individual unit tests run and pass just fine. However, if I try to run all of them at once with `python -m unittest`, I get the following errors for almost every test:

```
Traceback (most recent call last):
  File "C:\Users\islam\dev\gradio-repos\gradio\test\test_tunneling.py", line 21, in test_create_tunnel
    io = Interface(lambda x: x, "text", "text")
  File "C:\Users\islam\dev\gradio-repos\gradio\gradio\interface.py", line 172, in __init__
    self.input_components = [get_component_instance(i) for i in inputs]
  File "C:\Users\islam\dev\gradio-repos\gradio\gradio\interface.py", line 172, in <listcomp>
    self.input_components = [get_component_instance(i) for i in inputs]
  File "C:\Users\islam\dev\gradio-repos\gradio\gradio\components.py", line 2807, in get_component_instance
    return shortcut[0](**shortcut[1])
  File "C:\Users\islam\dev\gradio-repos\gradio\gradio\components.py", line 251, in __init__
    super().__init__(label=label, css=css, **kwargs)
  File "C:\Users\islam\dev\gradio-repos\gradio\gradio\components.py", line 48, in __init__
    super().__init__()
  File "C:\Users\islam\dev\gradio-repos\gradio\gradio\blocks.py", line 21, in __init__
    Context.root_block.blocks[self._id] = self
AttributeError: 'dict' object has no attribute 'blocks'
```

@aliabid94 @FarukOzderim have you seen this error before?

**Comment by FarukOzderim** [comment]
hmm it seems like there is some problem with `Context`

I tried running

**Comment by abidlabs** [comment]
I'm still getting the same problem @FarukOzderim:

image

**Comment by abidlabs** [comment]
After a LOT of debugging, I've isolated the issue to the `test_context.py` file. Running that seems to cause errors for all of the other tests. I've removed that test, along with a few others, and will be bringing tests back as we implement features

**Pull request merged**
