### PR TITLE
Add sort to bar plot

### PR DESCRIPTION
**Pull request by Chaitanya134**
## Description

Added sorting functionality to the bar plot chart rendering process.
Introduced two new arguments: sort_by and reverse to the BarPlot class, allowing users to specify the sorting axis and order.

Closes: #3350 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Instead of adding two parameters, I'd suggest we just add a single `sort_by` parameter that can be `Literal["x", "y", "-x", "-y"]` in line with altair's existing sorting approach.

**Review by freddyaboulton — COMMENTED** [review]
Thanks for the nice PR @Chaitanya134 ! Let's rename `sort_by` to `sort` and we can merge this in!

**Comment by Chaitanya134** [comment]
Thanks for the suggestions! I did the changes, and I'm really grateful to help.

**Comment by freddyaboulton** [comment]
Thanks @Chaitanya134 ! Will merge this in.

**Comment by abidlabs** [comment]
We may need to update a backend test to account for the new parameter in `gr.Barplot` @freddyaboulton?

**Comment by freddyaboulton** [comment]
Ci fixed + I added a small test!

**Pull request merged**
