### PR TITLE
Allow render() to return self

### PR DESCRIPTION
**Pull request by Raul9595**
# Description

Updated render() function in Blocks to return self

Please include: 
* relevant motivation
* a summary of the change 
* which issue is fixed. 
* any additional dependencies that are required for this change.

Closes: #2484 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by Raul9595** [comment]
Hi @vzakharov and @abidlabs, can you please review the PR?

**Comment by abidlabs** [comment]
Thanks @Raul9595 for submitting, happy to review this!

**Comment by abidlabs** [comment]
Just a couple of quick notes -- the PR # needs to be updated, and perhaps we can add a quick test to ensure everything works as expected. Otherwise, LGTM! Since these are pretty quick, I'm happy to fix it myself and merge.

**Comment by abidlabs** [comment]
All tests are passing, thanks again @Raul9595!

**Pull request merged**
