### PR TITLE
chore: update versions

### PR DESCRIPTION
**Pull request by pngwn**
This PR was opened by the [Changesets release](https://github.com/changesets/action) GitHub action. When you're ready to do a release, you can merge this and the packages will be published to npm automatically. If you're not ready to do a release yet, that's fine, whenever you add more changesets to main, this PR will be updated.

# Releases
### Features

-   [#5699](https://github.com/gradio-app/gradio/pull/5699) [`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2) - Improve chatbot accessibility and UX.  Thanks [@hannahblair](https://github.com/hannahblair)!
-   [#5569](https://github.com/gradio-app/gradio/pull/5569) [`2a5b9e03b`](https://github.com/gradio-app/gradio/commit/2a5b9e03b15ea324d641fe6982f26d81b1ca7210) - Added support for pandas `Styler` object to `gr.DataFrame` (initially just sets the `display_value`).  Thanks [@abidlabs](https://github.com/abidlabs)!

### Fixes

-   [#5735](https://github.com/gradio-app/gradio/pull/5735) [`abb5e9df4`](https://github.com/gradio-app/gradio/commit/abb5e9df47989b2c56c2c312d74944678f9f2d4e) - Ensure images with no caption download in gallery.  Thanks [@hannahblair](https://github.com/hannahblair)!
-   [#5754](https://github.com/gradio-app/gradio/pull/5754) [`502054848`](https://github.com/gradio-app/gradio/commit/502054848fdbe39fc03ec42445242b4e49b7affc) - Fix Gallery `columns` and `rows` params.  Thanks [@abidlabs](https://github.com/abidlabs)!
-   [#5755](https://github.com/gradio-app/gradio/pull/5755) [`e842a561a`](https://github.com/gradio-app/gradio/commit/e842a561af4394f8109291ee5725bcf74743e816) - Fix new line issue in chatbot.  Thanks [@dawoodkhan82](https://github.com/dawoodkhan82)!
-   [#5731](https://github.com/gradio-app/gradio/pull/5731) [`c9af4f794`](https://github.com/gradio-app/gradio/commit/c9af4f794060e218193935d7213f0991a374f502) - Added timeout and error handling for frpc tunnel.  Thanks [@cansik](https://github.com/cansik)!
-   [#5766](https://github.com/gradio-app/gradio/pull/5766) [`ef96d3512`](https://github.com/gradio-app/gradio/commit/ef96d351229272738fc3c9680f7111f159590341) - Don't raise warnings when returning an updated component in a dictionary.  Thanks [@abidlabs](https://github.com/abidlabs)!
-   [#5767](https://github.com/gradio-app/gradio/pull/5767) [`caf6d9c0e`](https://github.com/gradio-app/gradio/commit/caf6d9c0e1f5b867cc20f2b4f6abb5ef47503a5f) - Set share=True for all Gradio apps in Colab by default.  Thanks [@abidlabs](https://github.com/abidlabs)!

### Patch Changes

-   Updated dependencies \[]:
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1

### Patch Changes

-   Updated dependencies \[[`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2)]:
    -   @gradio/icons@0.2.0
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1
    -   @gradio/upload@0.3.1

### Patch Changes

-   Updated dependencies \[[`abb5e9df4`](https://github.com/gradio-app/gradio/commit/abb5e9df47989b2c56c2c312d74944678f9f2d4e), [`e842a561a`](https://github.com/gradio-app/gradio/commit/e842a561af4394f8109291ee5725bcf74743e816), [`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2), [`502054848`](https://github.com/gradio-app/gradio/commit/502054848fdbe39fc03ec42445242b4e49b7affc), [`2a5b9e03b`](https://github.com/gradio-app/gradio/commit/2a5b9e03b15ea324d641fe6982f26d81b1ca7210)]:
    -   @gradio/gallery@0.4.1
    -   @gradio/chatbot@0.5.0
    -   @gradio/dataframe@0.3.0
    -   @gradio/markdown@0.3.0
    -   @gradio/icons@0.2.0
    -   @gradio/annotatedimage@0.2.1
    -   @gradio/atoms@0.1.3
    -   @gradio/audio@0.3.6
    -   @gradio/code@0.2.1
    -   @gradio/dropdown@0.3.1
    -   @gradio/file@0.1.5
    -   @gradio/form@0.0.6
    -   @gradio/highlightedtext@0.3.2
    -   @gradio/image@0.3.1
    -   @gradio/json@0.1.1
    -   @gradio/label@0.2.1
    -   @gradio/model3d@0.2.3
    -   @gradio/plot@0.2.1
    -   @gradio/statustracker@0.2.1
    -   @gradio/textbox@0.4.1
    -   @gradio/timeseries@0.0.7
    -   @gradio/upload@0.3.1
    -   @gradio/video@0.0.10
    -   @gradio/accordion@0.1.1
    -   @gradio/box@0.0.5
    -   @gradio/checkbox@0.2.1
    -   @gradio/checkboxgroup@0.3.1
    -   @gradio/colorpicker@0.1.3
    -   @gradio/html@0.0.5
    -   @gradio/number@0.3.1
    -   @gradio/radio@0.3.1
    -   @gradio/slider@0.2.1
    -   @gradio/row@0.0.1
    -   @gradio/button@0.2.1
    -   @gradio/uploadbutton@0.0.8

### Patch Changes

-   Updated dependencies \[[`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2)]:
    -   @gradio/icons@0.2.0

### Patch Changes

-   Updated dependencies \[[`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2)]:
    -   @gradio/icons@0.2.0
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1
    -   @gradio/upload@0.3.1
    -   @gradio/button@0.2.1

### Patch Changes

-   Updated dependencies \[]:
    -   @gradio/atoms@0.1.3

### Patch Changes

-   Updated dependencies \[]:
    -   @gradio/upload@0.3.1

### Patch Changes

-   Updated dependencies \[]:
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1

### Patch Changes

-   Updated dependencies \[]:
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1

### Patch Changes

-   Updated dependencies \[[`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2)]:
    -   @gradio/icons@0.2.0
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1
    -   @gradio/upload@0.3.1

### Patch Changes

-   Updated dependencies \[]:
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1

### Patch Changes

-   Updated dependencies \[[`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2)]:
    -   @gradio/icons@0.2.0
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1

### Patch Changes

-   Updated dependencies \[[`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2)]:
    -   @gradio/icons@0.2.0
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1
    -   @gradio/upload@0.3.1

### Patch Changes

-   Updated dependencies \[[`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2)]:
    -   @gradio/icons@0.2.0
    -   @gradio/atoms@0.1.3

### Patch Changes

-   Updated dependencies \[[`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2)]:
    -   @gradio/icons@0.2.0
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1

### Patch Changes

-   Updated dependencies \[]:
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1

### Patch Changes

-   Updated dependencies \[[`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2)]:
    -   @gradio/icons@0.2.0
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1
    -   @gradio/upload@0.3.1

### Patch Changes

-   Updated dependencies \[[`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2)]:
    -   @gradio/icons@0.2.0
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1

### Patch Changes

-   Updated dependencies \[[`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2)]:
    -   @gradio/icons@0.2.0
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1

### Patch Changes

-   Updated dependencies \[[`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2)]:
    -   @gradio/icons@0.2.0
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1
    -   @gradio/upload@0.3.1

### Patch Changes

-   Updated dependencies \[]:
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1

### Patch Changes

-   Updated dependencies \[[`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2)]:
    -   @gradio/icons@0.2.0
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1

### Patch Changes

-   Updated dependencies \[]:
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1

### Patch Changes

-   Updated dependencies \[]:
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1

### Patch Changes

-   Updated dependencies \[[`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2)]:
    -   @gradio/icons@0.2.0
    -   @gradio/atoms@0.1.3

### Patch Changes

-   Updated dependencies \[[`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2)]:
    -   @gradio/icons@0.2.0
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1

### Patch Changes

-   Updated dependencies \[[`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2)]:
    -   @gradio/icons@0.2.0
    -   @gradio/atoms@0.1.3
    -   @gradio/statustracker@0.2.1
    -   @gradio/upload@0.3.1

### Patch Changes

-   Updated dependencies \[[`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2)]:
    -   @gradio/icons@0.2.0
    -   @gradio/atoms@0.1.3

### Patch Changes

-   Updated dependencies \[]:
    -   @gradio/upload@0.3.1
    -   @gradio/button@0.2.1

### Patch Changes

-   Updated dependencies \[[`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2)]:
    -   @gradio/icons@0.2.0
    -   @gradio/atoms@0.1.3
    -   @gradio/image@0.3.1
    -   @gradio/statustracker@0.2.1
    -   @gradio/upload@0.3.1

### Features

-   [#5699](https://github.com/gradio-app/gradio/pull/5699) [`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2) - Improve chatbot accessibility and UX.  Thanks [@hannahblair](https://github.com/hannahblair)!

### Fixes

-   [#5755](https://github.com/gradio-app/gradio/pull/5755) [`e842a561a`](https://github.com/gradio-app/gradio/commit/e842a561af4394f8109291ee5725bcf74743e816) - Fix new line issue in chatbot.  Thanks [@dawoodkhan82](https://github.com/dawoodkhan82)!

### Features

-   [#5569](https://github.com/gradio-app/gradio/pull/5569) [`2a5b9e03b`](https://github.com/gradio-app/gradio/commit/2a5b9e03b15ea324d641fe6982f26d81b1ca7210) - Added support for pandas `Styler` object to `gr.DataFrame` (initially just sets the `display_value`).  Thanks [@abidlabs](https://github.com/abidlabs)!

### Fixes

-   [#5755](https://github.com/gradio-app/gradio/pull/5755) [`e842a561a`](https://github.com/gradio-app/gradio/commit/e842a561af4394f8109291ee5725bcf74743e816) - Fix new line issue in chatbot.  Thanks [@dawoodkhan82](https://github.com/dawoodkhan82)!

### Fixes

-   [#5735](https://github.com/gradio-app/gradio/pull/5735) [`abb5e9df4`](https://github.com/gradio-app/gradio/commit/abb5e9df47989b2c56c2c312d74944678f9f2d4e) - Ensure images with no caption download in gallery.  Thanks [@hannahblair](https://github.com/hannahblair)!
-   [#5754](https://github.com/gradio-app/gradio/pull/5754) [`502054848`](https://github.com/gradio-app/gradio/commit/502054848fdbe39fc03ec42445242b4e49b7affc) - Fix Gallery `columns` and `rows` params.  Thanks [@abidlabs](https://github.com/abidlabs)!

### Features

-   [#5699](https://github.com/gradio-app/gradio/pull/5699) [`8f0fed857`](https://github.com/gradio-app/gradio/commit/8f0fed857d156830626eb48b469d54d211a582d2) - Improve chatbot accessibility and UX.  Thanks [@hannahblair](https://github.com/hannahblair)!

### Fixes

-   [#5755](https://github.com/gradio-app/gradio/pull/5755) [`e842a561a`](https://github.com/gradio-app/gradio/commit/e842a561af4394f8109291ee5725bcf74743e816) - Fix new line issue in chatbot.  Thanks [@dawoodkhan82](https://github.com/dawoodkhan82)!

### CODE REVIEW

**Review by freddyaboulton — COMMENTED** [review]
The only thing I noticed is that in `image_mod_default_image` the output image is off-center and smaller than normal?

image

**Comment by abidlabs** [comment]
Thanks @freddyaboulton! That issue is present on the last release of `gradio` as well (I just confirmed). It looks like we have an existing issue for it: https://github.com/gradio-app/gradio/issues/1888 -- which should get addressed in the `gr.Image` refactor -- so I'll go ahead and do the release anyways.

**Review by abidlabs — APPROVED** [review]
lgtm!

**Comment by freddyaboulton** [comment]
So crazy, that's not present in the v4 branch right now 🤔

**Pull request merged**
