### PR TITLE
implement missing methods handle nested dict

### PR DESCRIPTION
**Pull request by radames**
Quick fix for #3454 

with this extra methods on `class Obj` we can now do

```python

request.headers["user-agent"]

"user-agent" in request.headers

dict(request.headers)

for key, value in request.headers:
    print(key, value)

```
still missing `.keys()`, `.values()` `.items()`

### CODE REVIEW

**Review by freddyaboulton — COMMENTED** [review]
Looks good to me @radames ! Thank you for writing the tests as well.

Supporting the missing attributes you mention should be straightforward, no?

```python
    def keys(self):
        return self.__dict__.keys()

    def values(self):
        return self.__dict__.values()

    def items(self):
        return self.__dict__.items()
```

Should we do that in this PR?

**Comment by abidlabs** [comment]
LGTM @radames! Tested and confirmed that accessing via attributes continues to work, while adding support for accessing via keys. As @freddyaboulton suggested, let's add the missing methods (and credit you in the changelog) and we should be good to merge

**Comment by radames** [comment]
thanks @abidlabs and @freddyaboulton , update with the missing attributes and add extra asserts

**Comment by abidlabs** [comment]
Thank you so much @radames!

**Pull request merged**
