### PR TITLE
Adding new themes to Gradio 5.0

### LINKED ISSUE #9435: Create new themes for Gradio 5.0
- [ x ] I have searched to see if a similar issue already exists.

**Is your feature request related to a problem? Please describe.**  
Updated themes in Gradio 5.0 would help industry users create even more 🔥 apps

**Describe the solution you'd like**  
Add more built-in themes to Gradio 5.0

**Additional context**  
Related discussion: https://huggingface.slack.com/archives/C03BHNJCBC4/p1725624314953559

### PR DESCRIPTION
**Pull request by allisonwhilden**
## Description

The goal of this PR is to add some new themes to Gradio 5.0. This is my first time contributing. I'm super happy to iterate based on any suggestions. I'm also happy to explore creating other themes -- but wanted to get some feedback on what I had first.

You can see screenshots of all the themes here: https://www.figma.com/board/k9U8uV3Q2yreqgBZnj8l4V/Gradio-5.0-Theme-Exploration?node-id=0-1&t=vESHTwl6w4TDUE4l-1

image
image
image

## ⚠️ Notes
Both `slider_color` and `panel_background_fill_dark` don't appear to be affecting the components (at least as I'd expect them to). Please let me know if this is known, or others have experienced there, or if there is anything I can try. Thank you!

## 🎯 PRs Should Target Issues

Closes #9435 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by pngwn** [comment]
This is cool! Thank you!

Out of curiosity, how did you find the experience of generating themes and working with the theming system?

**Comment by allisonwhilden** [comment]
There was a little bit of a learning curve for me, but in general, it was really nice once I figured it out. I found myself switching between existing themes and the base to find the various attributes I may want to try. 

One example is that I struggled a bit to figure out how to change the fill color of the selected token in a multiselect dropdown. I tried a bunch of values, and finally figured out that a checkbox fill controlled it. 

There were also a few times when I didn't quite have the flexibility I wanted. For example, for Headlines, I wanted to mimic newspapers, and wanted a very large header. But I didn't want to increase the size of the rest of the type ramp. I didn't quite figure out how to do this, so I moved on.

I also realized I may not have best used the system in a couple of places. For example -- knowing when to store a secondary color value and use that throughout the definition vs. hardcoding specific color hues. I may be able to do some cleanup of this before I merge to make the themes easier to tweak down the road.

But overall, I really like the system and it seems really flexible and powerful. Being able to reference other variables made it really easy to quickly test other hues to see what it would look like by just changing it in one place. I think if I play around with it a bit more, it is a system I could get pretty fast with.

**Comment by pngwn** [comment]
Thanks for the feedback, we can always expand/ tweak the theming system based on feedback, so this is very helpful.

**Comment by pngwn** [comment]
@aliabid94 @hannahblair could you take a look at this as you are the theming wizards.

**Comment by aliabid94** [comment]
Thanks for the PR @allisonwhilden! I'm gonna make some tweaks to these if that's okay. it's great to have some more themes in gradio out of the box!

**Comment by allisonwhilden** [comment]
@hannahblair re: the line. I was trying a thing for the headline theme with only a top border (trying to be reminiscent of some newspaper styles). Because of this, I turned off the radius size because you get that weird artifact in CSS with a top border only + border-radius. But I'm entirely flexible with everything, so I'm happy to leave that style, try something else, etc. Or remove that theme altogether if it isn't a good fit.

**Comment by allisonwhilden** [comment]
I've made the above suggested changes. Thanks!

However, when I ran `bash scripts/format_backend.sh` as suggested by @hannahblair above, it found ten errors. It fixed one automatically (I believe the ordering of imports). The nine other issues it found didn't have fixes available but were in files I didn't touch (so I assume it should be out of the scope of this PR).

Let me know how else I can help prepare this PR or any changes/feedback to address. Thank you!

**Comment by aliabid94** [comment]
Just working on tweaking these themes a little, should have the changes in soon :)

**Comment by aliabid94** [comment]
Okay PR ready for review! I did the following with the new themes:
- To "citrus" I added some fun little button effects and some other "3d" effects
- "colorful" I renamed to "seafoam" and added some other aesthetic changes
- I deleted "headlines" since it looked pretty similar to "monochrome", but copied several of its new ideas into "monochrome",  (such as the primary vs secondary button styles)

Additionally, I fixed a lot of little issues across all the themes. "Glass" I changed very significantly. The others I just made as pixel-perfect as I could. 

I also fixed quite a few bugs, including the fact that the theme builder wasn't working because of some hacky JS that we had added (new removed).

**Review by abidlabs — APPROVED** [review]
lgtm great work @allisonwhilden @aliabid94! I'm just going to update the themes docs in this PR to add a bit more description for each theme, and also update some of the demos to use these themes, and then will merge this in

**Comment by abidlabs** [comment]
Oh you're right! Its the new theme that we create in the theming guide. I was wondering why the name sounded familiar..

**Comment by abidlabs** [comment]
How about "Ocean"?

**Comment by abidlabs** [comment]
Added a bit more to the docs and demos, and renamed seafoam -> ocean.

Will let @aliabid94 address the issues @hannahblair discovered and merge in when ready!

**Review by abidlabs — APPROVED** [review]

**Comment by yvrjsharma** [comment]
Just a minor issue, but with the 'Citrus' theme, the audio bars don't follow the theme color; instead, they follow the (primary) Orange Gradio 4 color:
image 

Tried taking a closer look to confirm, and I think the bars are indeed orange :
image

I tried the same test with the new Ocean theme and the updated Monochrome theme, and indeed, the audio bars follow the theme color for both of these.

**Comment by aliabid94** [comment]
> Just a minor issue, but with the 'Citrus' theme, the audio bars don't follow the theme color; instead, they follow the (primary) Orange Gradio 4 color. Is this the expected behavior?

No they do follow the theme color, the audio bars just use a slightly darker shade than the buttons.

**Comment by aliabid94** [comment]
I'll go ahead and merge, @hannahblair if you still see the issues you raised lmk

**Pull request merged**
