### PR TITLE
Fix gallery select event with custom height and allow_preview=False

### PR DESCRIPTION
**Pull request by freddyaboulton**
# Description

Closes: #4543

When setting a height on the gallery, the select event is not being triggered when `allow_preview=False` because `can_zoom` is being calculated as `False`. 

Not too familiar with the gallery code but I assumed the `can_zoom` logic is correct. Since the gallery won't zoom with `allow_preview=False`, my fix is to set `can_zoom=true` in that case to trigger the event. But please check me @pngwn @hannahblair @aliabid94  @dawoodkhan82 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have added a short summary of my change to the CHANGELOG.md
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Review by pngwn — APPROVED** [review]
Hmm. Interesting. When `allow_preview=False` technically it isn't possible to 'select' an image (going by the semantics of 'selected' in this component). You are just clicking it, but maybe that distinction isn't important. I do think we should probably refactor this code to handle selection + full size previewing separately to avoid confusion. And also because i think we should implement `multi-select` for the gallery too at some point (and you obviously can't preview multiple fullsize images at once).

If we're happy with the select semantics in this PR them I'm happy for it to be merged (code looks fine).

cc @abidlabs @aliabd @dawoodkhan82 @hannahblair

**Comment by abidlabs** [comment]
The semantics are good for me. We use `.select()` in other components to mean that you've selected on some *portion* of the value as opposed to clicking on the entire thing, and we provide the event data to go along with that. E.g. in `gr.Image` clicking on a particular pixel triggers the `.select()` event handler even though there is no change in the UI. `So in this case, I think `.select()` still works.

**Comment by pngwn** [comment]
Sounds good. Happy to merge then!

**Comment by abidlabs** [comment]
Sounds good let’s merge it in

**Pull request merged**
