### PR TITLE
Keep pnginfo metadata for gallery

### PR DESCRIPTION
**Pull request by wfng92**
# Description

Please include: 
* relevant motivation
Unlike the `Image` component, the `Gallery` component does not save with `pnginfo`. It would be great if the images in the `Gallery` component can be saved with metadata.

* a summary of the change 
Refactored the following code into a function (for re-usability) which take in a `PIL.Image` and returns the corresponding metadata that can be used directly when saving.

https://github.com/gradio-app/gradio/blob/ba67036df8a7d66f346af6b60d6db96a8718eea2/gradio/processing_utils.py#L140-L150

* which issue is fixed. 
None

* any additional dependencies that are required for this change.
None

Closes: # (issue)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [ ] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by abidlabs** [comment]
Hi @wfng92 thanks for the contribution! This refactoring generally looks good, but can you also please add a unit test to confirm that the `save_pil_to_file()` method saves the metadata correctly? Something similar to this should work: https://github.com/gradio-app/gradio/blob/190687e7162aef912753b103ed73fc67d17a654e/test/test_processing_utils.py#L66

In addition, please add a line in the `CHANGELOG.md` to give yourself credit for the contribution, thanks!

**Comment by wfng92** [comment]
> Hi @wfng92 thanks for the contribution! This refactoring generally looks good, but can you also please add a unit test to confirm that the `save_pil_to_file()` method saves the metadata correctly? Something similar to this should work:
> 
> https://github.com/gradio-app/gradio/blob/190687e7162aef912753b103ed73fc67d17a654e/test/test_processing_utils.py#L66
> 
> In addition, please add a line in the `CHANGELOG.md` to give yourself credit for the contribution, thanks!

Added a test for `save_pil_to_file()` function. Also, I have updated the `CHANGELOG.md` file as well. Let me know if it works for you.

**Comment by abidlabs** [comment]
Thanks for making the update @wfng92! LGTM. It looks like we need to run the formatter (`.\scripts\format_backend.sh`) but I can go ahead and do that. Once the CI tests pass, we'll go ahead and merge it in

**Comment by abidlabs** [comment]
Merging, thanks again for the contribution @wfng92!

**Pull request merged**
