### PR TITLE
chore: update versions

### PR DESCRIPTION
**Pull request by pngwn**
This PR was opened by the [Changesets release](https://github.com/changesets/action) GitHub action. When you're ready to do a release, you can merge this and the packages will be published to npm automatically. If you're not ready to do a release yet, that's fine, whenever you add more changesets to main, this PR will be updated.

# Releases
### Patch Changes

-   Updated dependencies \[[`5d51fbc`](https://github.com/gradio-app/gradio/commit/5d51fbce7826da840a2fd4940feb5d9ad6f1bc5a), [`34f9431`](https://github.com/gradio-app/gradio/commit/34f943101bf7dd6b8a8974a6131c1ed7c4a0dac0)]:
    -   @gradio/upload@0.5.4
    -   @gradio/client@0.9.1
    -   @gradio/button@0.2.11

### Patch Changes

-   Updated dependencies \[[`5d51fbc`](https://github.com/gradio-app/gradio/commit/5d51fbce7826da840a2fd4940feb5d9ad6f1bc5a), [`34f9431`](https://github.com/gradio-app/gradio/commit/34f943101bf7dd6b8a8974a6131c1ed7c4a0dac0)]:
    -   @gradio/upload@0.5.4
    -   @gradio/client@0.9.1

### Patch Changes

-   Updated dependencies \[[`5d51fbc`](https://github.com/gradio-app/gradio/commit/5d51fbce7826da840a2fd4940feb5d9ad6f1bc5a), [`34f9431`](https://github.com/gradio-app/gradio/commit/34f943101bf7dd6b8a8974a6131c1ed7c4a0dac0)]:
    -   @gradio/upload@0.5.4
    -   @gradio/client@0.9.1

### Patch Changes

-   Updated dependencies \[[`5d51fbc`](https://github.com/gradio-app/gradio/commit/5d51fbce7826da840a2fd4940feb5d9ad6f1bc5a)]:
    -   @gradio/upload@0.5.4

### Patch Changes

-   Updated dependencies \[[`5d51fbc`](https://github.com/gradio-app/gradio/commit/5d51fbce7826da840a2fd4940feb5d9ad6f1bc5a)]:
    -   @gradio/upload@0.5.4
    -   @gradio/button@0.2.11

### Patch Changes

-   Updated dependencies \[[`5d51fbc`](https://github.com/gradio-app/gradio/commit/5d51fbce7826da840a2fd4940feb5d9ad6f1bc5a), [`34f9431`](https://github.com/gradio-app/gradio/commit/34f943101bf7dd6b8a8974a6131c1ed7c4a0dac0)]:
    -   @gradio/upload@0.5.4
    -   @gradio/client@0.9.1

### Patch Changes

-   Updated dependencies \[[`5d51fbc`](https://github.com/gradio-app/gradio/commit/5d51fbce7826da840a2fd4940feb5d9ad6f1bc5a), [`34f9431`](https://github.com/gradio-app/gradio/commit/34f943101bf7dd6b8a8974a6131c1ed7c4a0dac0)]:
    -   @gradio/upload@0.5.4
    -   @gradio/client@0.9.1

### Patch Changes

-   Updated dependencies \[[`5d51fbc`](https://github.com/gradio-app/gradio/commit/5d51fbce7826da840a2fd4940feb5d9ad6f1bc5a), [`34f9431`](https://github.com/gradio-app/gradio/commit/34f943101bf7dd6b8a8974a6131c1ed7c4a0dac0)]:
    -   @gradio/upload@0.5.4
    -   @gradio/client@0.9.1
    -   @gradio/image@0.5.1

### Patch Changes

-   Updated dependencies \[[`5d51fbc`](https://github.com/gradio-app/gradio/commit/5d51fbce7826da840a2fd4940feb5d9ad6f1bc5a), [`34f9431`](https://github.com/gradio-app/gradio/commit/34f943101bf7dd6b8a8974a6131c1ed7c4a0dac0)]:
    -   @gradio/upload@0.5.4
    -   @gradio/client@0.9.1

### Patch Changes

-   Updated dependencies \[[`5d51fbc`](https://github.com/gradio-app/gradio/commit/5d51fbce7826da840a2fd4940feb5d9ad6f1bc5a), [`34f9431`](https://github.com/gradio-app/gradio/commit/34f943101bf7dd6b8a8974a6131c1ed7c4a0dac0)]:
    -   @gradio/upload@0.5.4
    -   @gradio/client@0.9.1
    -   @gradio/image@0.5.1

### Patch Changes

-   Updated dependencies \[[`5d51fbc`](https://github.com/gradio-app/gradio/commit/5d51fbce7826da840a2fd4940feb5d9ad6f1bc5a), [`34f9431`](https://github.com/gradio-app/gradio/commit/34f943101bf7dd6b8a8974a6131c1ed7c4a0dac0)]:
    -   @gradio/upload@0.5.4
    -   @gradio/client@0.9.1
    -   @gradio/button@0.2.11

### Patch Changes

-   Updated dependencies \[[`5d51fbc`](https://github.com/gradio-app/gradio/commit/5d51fbce7826da840a2fd4940feb5d9ad6f1bc5a), [`34f9431`](https://github.com/gradio-app/gradio/commit/34f943101bf7dd6b8a8974a6131c1ed7c4a0dac0)]:
    -   @gradio/upload@0.5.4
    -   @gradio/client@0.9.1
    -   @gradio/image@0.5.1

### Fixes

-   [#6693](https://github.com/gradio-app/gradio/pull/6693) [`34f9431`](https://github.com/gradio-app/gradio/commit/34f943101bf7dd6b8a8974a6131c1ed7c4a0dac0) - Python client properly handles hearbeat and log messages. Also handles responses longer than 65k.  Thanks [@freddyaboulton](https://github.com/freddyaboulton)!

### Fixes

-   [#6693](https://github.com/gradio-app/gradio/pull/6693) [`34f9431`](https://github.com/gradio-app/gradio/commit/34f943101bf7dd6b8a8974a6131c1ed7c4a0dac0) - Python client properly handles hearbeat and log messages. Also handles responses longer than 65k.  Thanks [@freddyaboulton](https://github.com/freddyaboulton)!

### Features

-   [#6781](https://github.com/gradio-app/gradio/pull/6781) [`a807ede`](https://github.com/gradio-app/gradio/commit/a807ede818e0690949aca41020e75a96f0110ece) - Fix backend tests on Windows.  Thanks [@abidlabs](https://github.com/abidlabs)!

### Fixes

-   [#6525](https://github.com/gradio-app/gradio/pull/6525) [`5d51fbc`](https://github.com/gradio-app/gradio/commit/5d51fbce7826da840a2fd4940feb5d9ad6f1bc5a) - Fixes Drag and Drop for Upload.  Thanks [@dawoodkhan82](https://github.com/dawoodkhan82)!
-   [#6780](https://github.com/gradio-app/gradio/pull/6780) [`51e241a`](https://github.com/gradio-app/gradio/commit/51e241addd20dad9a0cdf3e72f747cab112815d1) - Fix flaky CI tests (again 😓 ).  Thanks [@freddyaboulton](https://github.com/freddyaboulton)!
-   [#6693](https://github.com/gradio-app/gradio/pull/6693) [`34f9431`](https://github.com/gradio-app/gradio/commit/34f943101bf7dd6b8a8974a6131c1ed7c4a0dac0) - Python client properly handles hearbeat and log messages. Also handles responses longer than 65k.  Thanks [@freddyaboulton](https://github.com/freddyaboulton)!

### Fixes

-   [#6525](https://github.com/gradio-app/gradio/pull/6525) [`5d51fbc`](https://github.com/gradio-app/gradio/commit/5d51fbce7826da840a2fd4940feb5d9ad6f1bc5a) - Fixes Drag and Drop for Upload.  Thanks [@dawoodkhan82](https://github.com/dawoodkhan82)!

### Fixes

-   [#6525](https://github.com/gradio-app/gradio/pull/6525) [`5d51fbc`](https://github.com/gradio-app/gradio/commit/5d51fbce7826da840a2fd4940feb5d9ad6f1bc5a) - Fixes Drag and Drop for Upload.  Thanks [@dawoodkhan82](https://github.com/dawoodkhan82)!

### Patch Changes

-   Updated dependencies \[]:
    -   @gradio/code@0.3.1

### Patch Changes

-   Updated dependencies \[[`5d51fbc`](https://github.com/gradio-app/gradio/commit/5d51fbce7826da840a2fd4940feb5d9ad6f1bc5a), [`34f9431`](https://github.com/gradio-app/gradio/commit/34f943101bf7dd6b8a8974a6131c1ed7c4a0dac0)]:
    -   @gradio/upload@0.5.4
    -   @gradio/client@0.9.1

### Patch Changes

-   Updated dependencies \[[`5d51fbc`](https://github.com/gradio-app/gradio/commit/5d51fbce7826da840a2fd4940feb5d9ad6f1bc5a), [`34f9431`](https://github.com/gradio-app/gradio/commit/34f943101bf7dd6b8a8974a6131c1ed7c4a0dac0)]:
    -   @gradio/model3d@0.4.9
    -   @gradio/upload@0.5.4
    -   @gradio/client@0.9.1
    -   @gradio/annotatedimage@0.3.11
    -   @gradio/audio@0.6.1
    -   @gradio/button@0.2.11
    -   @gradio/chatbot@0.5.3
    -   @gradio/code@0.3.1
    -   @gradio/dataframe@0.4.1
    -   @gradio/dataset@0.1.11
    -   @gradio/file@0.4.1
    -   @gradio/fileexplorer@0.3.11
    -   @gradio/gallery@0.4.12
    -   @gradio/image@0.5.1
    -   @gradio/imageeditor@0.1.4
    -   @gradio/uploadbutton@0.3.2
    -   @gradio/video@0.2.1

### Patch Changes

-   Updated dependencies \[[`5d51fbc`](https://github.com/gradio-app/gradio/commit/5d51fbce7826da840a2fd4940feb5d9ad6f1bc5a), [`34f9431`](https://github.com/gradio-app/gradio/commit/34f943101bf7dd6b8a8974a6131c1ed7c4a0dac0)]:
    -   @gradio/upload@0.5.4
    -   @gradio/client@0.9.1
    -   @gradio/file@0.4.1

### CODE REVIEW

**Comment by abidlabs** [comment]
Demos LGTM, and tests are all passing (thanks @freddyaboulton!)

**Comment by apmoore1** [comment]
Hi,
This might not be the correct place to raise this, but I do not think the Drag and Drop for Upload fix worked #6525 I have tested it on my local machine using gradio version 4.9.1 and 4.11.0. I have also tested it on the following two spaces:
https://huggingface.co/spaces/gradio-pr-deploys/pr-6779-all-demos
https://huggingface.co/spaces/gradio-pr-deploys/pr-6826-all-demos
Using the `zip_files` demo whereby I could not upload a one line text file via drag and drop but could if I click on the file component rather than drag and drop.

My machine is running Ubuntu 22.04.3 LTS.

If you need any other detail please let me know. If I need to raise this issue somewhere else on the GitHub repository happy to do so.

Thanks for creating and maintaining this project!

**Comment by abidlabs** [comment]
@apmoore1 would you be able to create a new issue with these repro details?

**Comment by apmoore1** [comment]
Submitted a new issue #6888 , it turned out the bug was more difficult to find than I thought, but everything is explained in the new issue.

**Comment by abidlabs** [comment]
Thanks @apmoore1 for debugging and creating the issue!

**Pull request merged**
