### PR TITLE
Add a cli command to list available templates

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Add a cli command to list all the available templates with some nice metadata about the kind of component.

gradio_cc_show

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Love it @freddyaboulton, particularly the "Beginner Friendly" tags. 

The only thing is that when all of the components are printed, you miss the simple components since they go all the way to the top. Is it possible to print only as many items that can fit on the terminal screen and then a user has to press the enter key to see more? If not, then maybe we put the "Beginner Friendly" ones at the bottom?

**Comment by freddyaboulton** [comment]
Great idea @abidlabs ! It was really easy to add pagination actually. 

gradio_cc_show_paginate

There's a note in the rich docs about how some shells may not support colors with pagination, so I added a parameter `--color` or `--no-color` to let people disable them if something goes wrong.

**Comment by abidlabs** [comment]
Thanks @freddyaboulton! Pagination looks great. I'm seeing this on the VSCode terminal, which I guess doesn't show colors: 

image

If I do `--no-colors`, it looks much better:

image

But the default `gradio cc show` command output on the top looks broken. Is there any way to detect whether the terminal can support colors and just show the appropriate output?

**Comment by freddyaboulton** [comment]
No easy way from what I can tell. Let's remove the colors and keep pagination.

**Comment by freddyaboulton** [comment]
Added some emojis to make them "pop" a bit

**Comment by abidlabs** [comment]
Beautiful! Thanks for updating the PR @freddyaboulton

**Review by abidlabs — APPROVED** [review]

**Comment by freddyaboulton** [comment]
Thank you for the helpful feedback!!

**Pull request merged**
