### PR TITLE
Fix image height content fit

### PR DESCRIPTION
**Pull request by hannahblair**
## Description

Adds full height to the image wrapper to ensure that long images fit the container. 

Closes: #9080

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Review by aliabid94 — APPROVED** [review]
LGTM! Noticed this also stretches out images smaller than the height or width of the container to fit the container now. Not sure if that is desired or not.

**Review by aliabid94 — APPROVED** [review]
Looks great! Agree that newlines should be supported, either by replacing '\n' with <br>, or supporting any markdown in the placeholder.

**Comment by abidlabs** [comment]
> Noticed this also stretches out images smaller than the height or width of the container to fit the container now

Hmm I don't think this is intended, right @hannahblair?

**Comment by aliabid94** [comment]
Hmm now I've noticed that a standalone gr.Image takes up much more vertical space. Here's my demo:

```python
import gradio as gr
from PIL import Image, ImageDraw


with gr.Blocks() as demo:
    image = gr.Image()

    with gr.Row():
        width = gr.Slider(100, 1000, 100, label="Width")
        height = gr.Slider(100, 1000, 100, label="Height")

    @gr.on(triggers=[width.change, height.change, demo.load], inputs=[width, height], outputs=image)
    def update_image(width, height):
        img = Image.new('RGB', (width, height), color='white')
        draw = ImageDraw.Draw(img)
        draw.rectangle(
            [(0, 0), (width - 1, height - 1)],
            outline='red',
            width=5
        )
        return img

if __name__ == "__main__":
    demo.launch()
```

Here's what this looks like on main:

Screenshot 2024-08-19 at 12 12 14 PM

On this PR:

Screenshot 2024-08-19 at 12 12 49 PM

**Comment by aliabid94** [comment]
Ran the demo with the heoght fixed to 500px, code below. If the image is taller than 500px it is getting cut off.

Screenshot 2024-08-20 at 10 34 12 AM

```python
import gradio as gr
from PIL import Image, ImageDraw


with gr.Blocks() as demo:
    image = gr.Image(height="500px")

    with gr.Row():
        width = gr.Slider(100, 1000, 100, label="Width")
        height = gr.Slider(100, 1000, 100, label="Height")

    @gr.on(triggers=[width.change, height.change, demo.load], inputs=[width, height], outputs=image)
    def update_image(width, height):
        img = Image.new('RGB', (width, height), color='white')
        draw = ImageDraw.Draw(img)
        draw.rectangle(
            [(0, 0), (width - 1, height - 1)],
            outline='red',
            width=5
        )
        return img

if __name__ == "__main__":
    demo.launch()
```

**Comment by aliabid94** [comment]
Still see the massive image when the height is unfixed:
Screenshot 2024-08-20 at 4 35 14 PM

**Comment by whitphx** [comment]
I pushed a patch as a suggestion but its `ImagePreview` styling strategy became different from `ImageUpload`'s one in that `ImagePreview`'s `img` is `max-width: 100%; max-height: 100%` while `ImageUpload`'s `img` is `width: 100%; height: 100%; object-fit: scale-down`.
Will consider of another impl for consistency.

**Review by aliabid94 — APPROVED** [review]
Works perfectly, thanks @hannahblair!

**Pull request merged**
