### PR TITLE
Proposal: remove `gr.make_waveform` and remove `matplotlib` as a dependency

### PR DESCRIPTION
**Pull request by abidlabs**
On the topic of reducing Gradio's dependencies, this PR removes `matplotlib` as a dependency. The only place where its really needed is `gr.make_waveform`, which is a rarely-used function, and is less needed now that `gr.Audio` comes with a nice waveform of its own.

Targeting `5.0-dev` as its a breaking change. The other option would be to keep `gr.make_waveform` but raise an exception if `matplotlib` is not installed, in order to have one fewer breaking change in 5.0, open to suggestions.

### CODE REVIEW

**Comment by abidlabs** [comment]
@whitphx could use your help getting the E2E tests to pass, thanks!

**Comment by freddyaboulton** [comment]
I'm ok with the approach taken here since make_waveform has been incorporated into the front-end.

**Comment by dawoodkhan82** [comment]
Fine with removing `make_waveform`.

**Review by freddyaboulton — APPROVED** [review]

**Comment by abidlabs** [comment]
Thanks @whitphx for fixing the lite tests!

**Comment by whitphx** [comment]
Thanks!

**Pull request merged**
