### PR TITLE
Improve UI on the Playground

### PR DESCRIPTION
**Pull request by aliabd**
Makes a few changes to the UI: 

- AI generation will work on every demo, and not just on a blank page. 
- Clearer note on whether the prompt will update existing code or generate code on an empty editor. 
- Placeholder will show suggested prompts 
- If there's an error, it's highlighted on an error modal 
- Can cancel generation if it's not working as expected. 

Preview here: https://playground-ai-always.gradio-website.pages.dev/playground

### CODE REVIEW

**Comment by allisonwhilden** [comment]
Looks great, @aliabd! I'm enjoying playing with it. Will let you know if I have more feedback. The only thing I noticed so far is a very minor visual nit -- the grey fill on the sidebar doesn't always extend all the way to the bottom:
image
I would expect the grey background to always take the full height of the window.

**Comment by aliabd** [comment]
Thanks @allisonwhilden and @abidlabs for the feedback! 

@abidlabs I made things more compact and made your changes, but I kept the note about updating the prompt so we can keep the clear button which I've found useful. It also acts as a space for showing errors from the console. But I kept it floating above the input so it takes much less visual space. 

Screenshot 2024-09-28 at 3 58 16 AM

**Comment by abidlabs** [comment]
Nice @aliabd! all my points are addressed and the updated design looks great honestly.

Just one nit: the border separating the code numbers and the code body has a discontinuity towards the bottom:

image

**Comment by aliabd** [comment]
@abidlabs Should be good now

**Review by abidlabs — APPROVED** [review]
LGTM!

**Pull request merged**
