### PR TITLE
Improve `gr.Code`

### LINKED ISSUE #6041: issues with code component
### Describe the bug

Few things:

- Using the Code component on its own is an exercise in frustration. This is probably true for most of our component but I've experienced it first hand now. 
  - You need to pass a million props, many of which don't make sense on their own. 
  - Some prop don't really work as expected. `show_label={false}` in combination with a `label` is broken. 
  - i18n remains an issue.
- The code component doesn't want to occupy its full height for whatever reason. You get left with a dangling line because of this. 

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

code component

### Screenshot

_No response_

### Logs

_No response_

### System Info

```shell
all
```

### Severity

I can work around it

### PR DESCRIPTION
**Pull request by hannahblair**
## Description

1. Adds a touch of spacing in the code gutter 
2. Ensures we use the `min_width` param which wasn't being applied to the frontend
3. Fixes the download and copy icon effect on click
4. Adds line wrapping to the code editor to prevent having to scroll horizontally to edit non-visible code
5. Sets `max_lines` to `None` by default **(breaking change)**. This means that by default the Code component will fill the container and expand with the content just as the other components do. Setting `max_lines` to a number will still fix the height. 

|   | base | new |
|--------|--------|--------|
| 1 | image | image |
| 2 | image   |  image |
| 3 |  Kapture 2024-09-26 at 14 32 30 | Kapture 2024-09-26 at 14 29 30 |
| 4 | Screenshot 2024-09-27 at 18 42 20 | Screenshot 2024-09-27 at 18 38 01 |

Closes: #9414 
Closes #6041 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by aliabid94** [comment]
> I'm wondering if some users will want the component just to auto fill the container (thus unset the height):

I think this looks better and also is consistent with all other Blocks that fill to match the height of neighboring containers

**Review by aliabid94 — APPROVED** [review]
LGTM, thanks @hannahblair !

**Comment by aliabid94** [comment]
Another thing that'd be nice is if I click in the code component but below the text, the text cursor appears at the end so I can start typing. Referring to this red dead zone:

Screenshot 2024-09-26 at 3 49 00 PM

**Review by pngwn — APPROVED** [review]
Thanks for taking care of this @hannahblair!

I agree with @aliabid94's comments but they aren't blocking.

**Comment by aliabid94** [comment]
nice, thanks for implementing! Looks great! my only concern now is that as I keep typing more lines, the editor just expands indefinitely, e.g. here

Screenshot 2024-09-27 at 11 42 18 AM


```python
import gradio as gr

with gr.Blocks() as demo:
    with gr.Row():
        img = gr.Image(label="Name")
        code = gr.Code()
        ocode = gr.Code()
    btn = gr.Button("Run")
    
    btn.click(lambda x:x, code, ocode)

if __name__ == "__main__":
    demo.launch()
```

**Comment by pngwn** [comment]
> I've addressed this by actually introducing line wrapping into the code editor which I think makes it much more usable

I really think this should be an option if we add it. Line wrapping is not standard for code editors and (imo) is a worse UX.

**Comment by abidlabs** [comment]
The new icons and styling look great!

**Pull request merged**
