### PR TITLE
Adds docstrings for `gr.WaveformOptions`, `gr.Brush`, and `gr.Eraser`, fixes examples for `ImageEditor`, and allows individual images to be used as the initial `value` for `ImageEditor`

### PR DESCRIPTION
**Pull request by abidlabs**
Other minor refactoring as well.

Closes: https://github.com/gradio-app/gradio/issues/6338
Closes: https://github.com/gradio-app/gradio/issues/6634

Note that this doesn't actually surface the documentation (that's a separate issue: #6633)

Edit: thanks to @pngwn's suggestion, now:

Closes: #6784
Closes: https://github.com/gradio-app/gradio/issues/6752

### CODE REVIEW

**Review by pngwn — APPROVED** [review]
Looks good to me!

The value type is currently incorrect though (#6784). It should be set to the types duct defined above (or None). Could we fixed that here too?

**Comment by abidlabs** [comment]
Fixed the `value` and also fixed examples for `ImageEditor`, so now you can pass in a dict to use as the examples. It will render as just a regular image. It will render the composite image if available, and if not, will fall back to use the background image.

**Comment by abidlabs** [comment]
@hannahblair just fyi I did notice this issue while testing out the waveform options: https://github.com/gradio-app/gradio/issues/6801

**Comment by pngwn** [comment]
I don't know that I agree with the post process change. The main reason for splitting Image and InageEditor was the consistency of the signatures and this introduces some inconsistency. 

That said preprocessor is still consistent, so it might not be that bad. And it is is consistent regardless of type which was the main issue with the previous Image.

**Review by pngwn — APPROVED** [review]
I'm convinced! Thansk for taking care of this @abidlabs!

**Comment by abidlabs** [comment]
Thanks @hannahblair and @pngwn for reviewing!

**Pull request merged**
