### PR TITLE
Add css variable for controlling chatbot user message border accent

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description
We got some feedback that the border color of user messages in the default theme is a bit hash. 

Added `chatbot_user_message_border_color_accent` and `chatbot_user_message_border_color_accent_dark` variables to the theme class to control this. Defaults to `border_color_accent` so there shouldn't be any noticeable changes except for default theme.

### Before
image

### After
image

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests & Changelog

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

1. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`
  
1. Unless the pull request is labeled with the "no-changelog-update" label by a maintainer of the repo, all pull requests must update the changelog located in `CHANGELOG.md`:

Please add a brief summary of the change to the Upcoming Release section of the `CHANGELOG.md` file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

### CODE REVIEW

**Comment by freddyaboulton** [comment]
Trying with a previously created theme

```python
import gradio as gr
import random
import time

with gr.Blocks(theme="freddyaboulton/dracula_revamped") as demo:
    chatbot = gr.Chatbot()
    msg = gr.Textbox()
    clear = gr.ClearButton([msg, chatbot])

    def respond(message, chat_history):
        bot_message = random.choice(["How are you?", "I love you", "I'm very hungry"])
        chat_history.append((message, bot_message))
        time.sleep(2)
        return "", chat_history

    msg.submit(respond, [msg, chatbot], [msg, chatbot])

if __name__ == "__main__":
    demo.launch()

```

image

**Comment by abidlabs** [comment]
Tested all of our built-in themes. Looks good @freddyaboulton!

**Comment by abidlabs** [comment]
cc @gary149

**Review by abidlabs — APPROVED** [review]

**Comment by freddyaboulton** [comment]
Thanks @abidlabs !!

**Comment by gary149** [comment]
Nice!

**Pull request merged**
