### PR TITLE
Allows selection of directories in File Explorer

### PR DESCRIPTION
**Pull request by aliabid94**
When file_count="single", you can still select a directory - it will just allow selecting one directory and that will be the value. If file_count="multiple", selecting directories automatically selects all their content as well.

Fixes: #9812

### CODE REVIEW

**Comment by freddyaboulton** [comment]
@aliabid94 @xorangezq In order to select a directory you have to click on the directory icon in the list of children (see below). That still works as of 5.0. 
image

The checkbox next to the directory name means "select all the children" which is why it's non-clickable when `file_count="single"`.

So this PR is more about changing the design of the FileExplorer as opposed to fixing a bug. If we go with this approach, then I suggest we remove the directory icon from the list of children since it's now redundant and it's always non-clickable when file_count="single".

directory_click

But what I don't like about this new design is that the top level checkbox now does two things - select all the children and also select the directory itself.

What if instead we removed the "select all children" checkbox when file_count="single"?

**Comment by aliabid94** [comment]
Oh I completely missed the "." folder selector. In that case, this PR isn't needed - and yes we can hide the checkbox on file_count="single". cc: @xorangezq

**Comment by aliabid94** [comment]
Updated PR to hide folder checkbox on file_count="single":
Screenshot 2024-10-31 at 2 04 11 PM

**Comment by xorangezq** [comment]
> Oh I completely missed the "." folder selector.

Me too, completely missed the "." folder selector.

Thanks for noting us and verifying in 5.0 @freddyaboulton 
Thanks for your work @aliabid94

**Review by freddyaboulton — APPROVED** [review]
Nice @aliabid94 !

**Comment by sglbl** [comment]
@aliabid94  But this has a disadvantage. 
If we want to show only the directories to user (since I want them to select a folder), I can make glob show only the directories. But this time it cannot select a folder because of "." is not visible.

```python
gr.FileExplorer(label="Input documents directory path", glob="./**/", 
    file_count="single", root_dir="./data/example_inputs/")`
```
image

I'm not opening an issue for that because for now it's not that important.

**Pull request merged**
