### PR TITLE
Support custom pipelines in `gr.Interface.from_pipeline`

### PR DESCRIPTION
**Pull request by not-lain**
## Description

this will support custom pipelines

Closes: #7964

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by not-lain** [comment]
I was running the following notebook : https://colab.research.google.com/drive/1i08Tw0VpfEJZ5TI6Hkq8h0rJHkcpzAZT?usp=sharing
and I ran into the following problem : 
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/route_utils.py", line 261, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1782, in process_api
    inputs = await self.preprocess_data(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1494, in preprocess_data
    inputs_cached = await processing_utils.async_move_files_to_cache(
  File "/usr/local/lib/python3.10/dist-packages/gradio/processing_utils.py", line 410, in async_move_files_to_cache
    return await client_utils.async_traverse(
AttributeError: module 'gradio_client.utils' has no attribute 'async_traverse'
Keyboard interruption in main thread... closing server.
Killing tunnel 127.0.0.1:7860 <> https://c6807a1e4eb8056212.gradio.live/
```
I don't think it's related to this pr but wanted to share it, would be great if i can get a comment on this
Also friendly pinging @abidlabs for review

**Comment by abidlabs** [comment]
Hi @not-lain sorry for the delay in responding. The problem I see is that this doesn't really add support for custom pipelines generally, correct? In the sense that if I were to define a new custom pipeline that does not share its name / task with an existing transformers pipeline, there's no way for gradio to infer what the right input / output components should be. This only adds support for custom pipelines that share their task name with an existing transformers pipeline, which seems fairly limiting?

**Comment by not-lain** [comment]
@abidlabs no you are right on point, when defining a pipeline using the transformers library, a person can define whatever task they want (there are no constraints on the task name), I thought that by specifying the correct task might be a good feature to have.
I also agree with you on every bit of information that you mentioned.

**Comment by abidlabs** [comment]
Thanks for confirming @not-lain -- I would suggest we close this PR then as it could be misleading to users as we're not really adding support for custom pipelines. And simply setting the task name to be the same as an existing pipeline as not a standard spec for pipelines as far as I'm aware.

**Pull request closed without merging**
