### PR TITLE
Lite: Set the home dir path per appId at each runtime

### PR DESCRIPTION
**Pull request by whitphx**
## Description

Fix the bug introduced in the SharedWorker mode (#6099).

#6099 introduced app-level home dirs (`/home/pyodide/<appId>`) so each app running on a SharedWorker has separated home dir on the file system.
However, the current directory is not set properly in the Python environment, so file access methods such as `open()` with relative paths which are assumed to be resolved based on the app-level home dir can fail.
This PR fixes it, by calling `os.chdir()` and setting `os.environ["HOME"].

### CODE REVIEW

**Comment by whitphx** [comment]
Here is an example:

`app.py`
```python
import gradio as gr

def fn():
    with open("text.txt") as f:
        return f.read()


demo = gr.Interface(fn=fn, inputs=None, outputs="text")

demo.launch()
```

`text.txt`
```
Lorem ipsum
```

The points are
* `text.txt` is mounted to FS specified as a relative path, `text.txt`. It is assumed to be mounted at `<app-home-dir>/text.txt`.
* `open()` tries to read the file with a relative path. It is assumed to read the file from `<app-home-dir>/text.txt`. Before #6099, it actually worked.
* However, after #6099, this started to fail. This PR fixes it.

**Comment by whitphx** [comment]
I found this branch is not working because it is originally for v3, but the main is now v4 and it's been merged to this branch, then this branch fails to build.
To test this PR, plz rebase to `lite-v4` or wait until it's merged.

**Review by aliabd — APPROVED** [review]
Thanks for clarifying @whitphx, tested and lgtm!

**Comment by whitphx** [comment]
Thanks!

**Comment by pngwn** [comment]
@whitphx What is the status of this PR? Is it waiting on the lite v4 branch?

If it isn't currently ready + working can we close it and reopen later?

**Pull request merged**
