### PR TITLE
Miscellaneous formatting improvements to website

### LINKED ISSUE #1717: Miscellaneous formatting improvements to website after PR 1578
- [x] I have searched to see if a similar issue already exists.

In the review of #1578, we noticed some miscellaneous things we'd like to improve about the new website design:

- [x] No sidebars in the guides

- [x] **kwargs in Series/Parallel is shown as required when it is not
image

- [x] No example Number/Text (other input component) in the docs
### Old website
image
### Current website locally
image

- [x] No example output HighlightedText component in the docs
### Old Website
image
### Current website locally
image

- [x] Missing docstring descriptions for parameters of `Row`, `Column`
image

- [x] Missing description for `color_map` in `Chatbot`
### Old website
image
### Current website locally
image

- [x] The text on "Developing faster with reload mode" guide is not aligned
image

### PR DESCRIPTION
**Pull request by aliabd**
Small formatting fixes to docs and guides.

Fixes #1717

### CODE REVIEW

**Review by freddyaboulton — APPROVED** [review]
Looks good to me @aliabd ! Thanks for making these improvements.

Only thing is that `color_map` in Chatbot is still undocumented. Looks like we deprecated that parameter in favor of `Chatbot.style`. Maybe we just add `color_map` to the docstring saying it's deprecated? Not blocking merge though

**Comment by abidlabs** [comment]
> Only thing is that color_map in Chatbot is still undocumented. Looks like we deprecated that parameter in favor of Chatbot.style. Maybe we just add color_map to the docstring saying it's deprecated? Not blocking merge though

Seems unnecessary to document the `color_map` parameter if it's deprecated I think? Let's instead make sure we document the `style()`, as mentioned in #1757

**Comment by abidlabs** [comment]
> @abidlabs can you document the visible and variant params in BlockContext? Just fill the content where I put the TODO

Done @aliabd!

**Comment by aliabid94** [comment]
LGTM

**Pull request merged**
