### PR TITLE
Fix semiver import

### PR DESCRIPTION
**Pull request by pngwn**
# Description

Fix external `semiver` import to ensure CDN links work correctly.

Please include: 
* relevant motivation
* a summary of the change 
* which issue is fixed. 
* any additional dependencies that are required for this change.

Closes: # (issue)

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by abidlabs** [comment]
looks reasonable to me, is there a way test off of this branch?

**Comment by pngwn** [comment]
The only way I've tested is by inspecting the output. Previously there was an `import semiver from 'semiver'` at the top of the file. Now that is gone and the code has been inlined. You can see this by running `pnpm build` in the `js/client` directory and inspecting the `dist/index.js` file. There isn't a simple way to test this via CDN right now.

**Comment by abidlabs** [comment]
Good to know, thanks @pngwn. imo good to merge in

**Comment by abidlabs** [comment]
Good to know, thanks @pngwn. imo good to merge in

**Pull request merged**
