### PR TITLE
Docstring argument fixes

### PR DESCRIPTION
**Pull request by akx**
# Description

* Some of the docstrings for arguments were out of date c.f. the actual arguments.
  * For arguments I couldn't find descriptions for, I used `TODO: undocumented`; that's easy enough for someone to grep and fix.

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks @akx we can fix these docstring issues and merge this. Just FYI, `_js` is intentionally undocumented because it is intended for internal use at this point, and it's API may change, until we close #2479

**Comment by akx** [comment]
> Thanks @akx we can fix these docstring issues and merge this. Just FYI, `_js` is intentionally undocumented because it is intended for internal use at this point, and it's API may change, until we close #2479

The parameter is being used in the wild, which was exactly why I was confused about the lack of docstring...

Would you like me to remove that change from the PR, or maybe add "experimental, may change" or something to the doc?

**Comment by abidlabs** [comment]
> The parameter is being used in the wild, which was exactly why I was confused about the lack of docstring...

Makes sense, I'll add some documentation which explicitly states that this is an experimental parameter. 

Btw can you allow maintainers to push to this PR? I'll fix the remaining docstrings

**Comment by freddyaboulton** [comment]
Hi @akx ! This looks good to me. Can you re-open the PR with permission for outside commits so that @abidlabs can fix the remaining docstrings? Thank you.

**Comment by akx** [comment]
> Btw @akx can you allow maintainers to push to this PR? I'll fix the remaining docstrings

Done. Sorry for the delay

**Comment by abidlabs** [comment]
Thanks @akx! Fixing the docstrings now

**Comment by abidlabs** [comment]
I'm running into some issues trying to push changes to this branch. Started a new PR with these changes (#3740)

**Pull request closed without merging**
