### PR TITLE
Fixed visibility issue for all notebooks on GitHub

### PR DESCRIPTION
**Pull request by Archit-Kohli**
## Description

This pull request just changes the inner JSON format of all run.ipynb files in gradio/demo/<any-project> and makes the cell ids strings, thus making it a valid notebook which can now be seen in GitHub itself

Closes: #5916 

Please merge my pull request and if possible add the hacktoberfest label

### CODE REVIEW

**Comment by pngwn** [comment]
@Archit-Kohli Thanks for taking care of this!

We also need to update the python file that generates the notebooks to make sure we don't reintroduce this problem. It is in `demo/generate_notebooks.py`. Could you update that as well?

**Comment by Archit-Kohli** [comment]
Just did that 👍

**Comment by Archit-Kohli** [comment]
> @Archit-Kohli Thanks for taking care of this!
> 
> We also need to update the python file that generates the notebooks to make sure we don't reintroduce this problem. It is in `demo/generate_notebooks.py`. Could you update that as well?

Just did that 👍

**Comment by abidlabs** [comment]
Thank you @Archit-Kohli this is very nice!

**Comment by Archit-Kohli** [comment]
Sure

**Pull request merged**
