### PR TITLE
Adds `.expand()` and `.collapse()` events to `gr.Accordion`

### PR DESCRIPTION
**Pull request by abidlabs**
This PR was produced via programmatic use of `aider` + a lot of human intervention. More details available [internally](https://huggingface.slack.com/archives/C02SPHC1KD1/p1730334560275149)

Test with:

```py
import gradio as gr

with gr.Blocks() as demo:
    with gr.Accordion("See Details") as accordion:
        gr.Markdown("lorem ipsum")

    t = gr.Textbox()

    accordion.expand(lambda: "Accordion is expanded", None, t)
    accordion.collapse(lambda: "Accordion is collapsed", None, t)

if __name__ == "__main__":
    demo.launch()
```

Closes: https://github.com/gradio-app/gradio/issues/5197

### CODE REVIEW

**Comment by abidlabs** [comment]
If there are any minor changes that need to be made, anyone should feel free to push to this branch. Thanks!

**Comment by freddyaboulton** [comment]
Should we expect that changing the `open` prop from python triggers the `collapse` or `expand` event? Otherwise LGTM!

**Comment by freddyaboulton** [comment]
Ok since the issue specifically calls out the Button, then it makes sense for expand/collapse to only trigger on user input.

**Comment by abidlabs** [comment]
Thanks for merging this in @freddyaboulton!

**Pull request merged**
