### PR TITLE
Fixes Drag and Drop for Upload

### PR DESCRIPTION
**Pull request by dawoodkhan82**
## Description
Fixes the issue around the mime-type checks in the Upload component, which was causing errors for drag and dropping files.

Closes: #6490

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Review by freddyaboulton — COMMENTED** [review]
Can you modify the `model3d_component_events.spec.ts` and maybe write some 2e2 tests for `gr.File`? We have some for UploadButton but not File. There's an example of DnD in `video_component_events.spec.ts`.

**Comment by abidlabs** [comment]
Looks like this might have broken a couple of functional tests? I'm rerunning them now

**Comment by dawoodkhan82** [comment]
Hmm, so the failing functional tests, are actually passing for me locally. Also by re-running these tests i notice some of them are pretty flaky.

**Comment by dawoodkhan82** [comment]
Tests are passing now! Ready for re-review @abidlabs @freddyaboulton

**Comment by abidlabs** [comment]
Nice @dawoodkhan82! The issue is fixed for me for the `gr.File()` component, but not for the `gr.Model3D` component. Here's the code I'm trying, and I'm attaching the file (its a zipped .obj file) as well. Are you able to repro?

```py
import gradio as gr

def noop(*args):
    return None

demo = gr.Interface(
    fn=noop,
    inputs=[gr.File(), gr.Model3D(), gr.Image()],
    outputs=None,
)

demo.launch()
```

[Bunny.obj.zip](https://github.com/gradio-app/gradio/files/13665067/Bunny.obj.zip)

**Comment by abidlabs** [comment]
@dawoodkhan82 and I looked into it, it seems like it only affects `.obj` files

**Comment by dawoodkhan82** [comment]
@abidlabs Fixed, without (hopefully) breaking anything else!

**Comment by abidlabs** [comment]
Awesome @dawoodkhan82 works for me! Thanks for finding the solution.

**Review by abidlabs — APPROVED** [review]

**Comment by abidlabs** [comment]
I'll go ahead and merge this in so that we can do a patch release with #6693 and this

**Pull request merged**
