### PR TITLE
Quick Fix: Multiple file download not working

### PR DESCRIPTION
**Pull request by dawoodkhan82**
# Description
Download button was not working for file output component.

https://user-images.githubusercontent.com/12725292/188239825-d842e4cc-4225-4b34-b958-05f5e93ab05c.mov

Please include: 
* relevant motivation
* a summary of the change 
* which issue is fixed. 
* any additional dependencies that are required for this change.

Closes: #2150 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by abidlabs** [comment]
This isn't working for me. I tried running the following code:

```py
import gradio as gr


def a(img):
    return ["lion.jpg", "cantina.wav"]


with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column():
            with gr.Row():
                input_img = gr.File()
            with gr.Row():
                btn = gr.Button(value="submit")
        with gr.Column():
            with gr.Row():
                output_img = gr.File()

    btn.click(fn=a, inputs=[input_img], outputs=[output_img])

demo.launch(inbrowser=True)
```

(Files attached to this comment)

I get the mouse change when I hover over download, but I'm unable to download them when I click on them:

image

**Comment by abidlabs** [comment]
Here's the `lion.jpg` file: This isn't working for me. I tried running the following code:

```py
import gradio as gr


def a(img):
    return ["lion.jpg", "lion.jpg"]


with gr.Blocks() as demo:
    with gr.Row():
        with gr.Column():
            with gr.Row():
                input_img = gr.File()
            with gr.Row():
                btn = gr.Button(value="submit")
        with gr.Column():
            with gr.Row():
                output_img = gr.File()

    btn.click(fn=a, inputs=[input_img], outputs=[output_img])

demo.launch(inbrowser=True)
```

FIle here: lion

I get the mouse change when I hover over download, but I'm unable to download them when I click on them:

image

**Comment by abidlabs** [comment]
Is this ready to be reviewed again @dawoodkhan82?

**Comment by dawoodkhan82** [comment]
> Is this ready to be reviewed again @dawoodkhan82?

yup, should be fixed now

**Review by freddyaboulton — APPROVED** [review]
This works for me @dawoodkhan82 ! @abidlabs May be worth trying again?

**Comment by abidlabs** [comment]
LGTM as well, thanks for making the fix @dawoodkhan82!

**Pull request merged**
