### PR TITLE
fix(Image): Image mod is mask or color-sketch bug;

### PR DESCRIPTION
**Pull request by AmyOrz**
click undo -> the shadow line not real time change

## Description

the gradio-ui component Image -> Sketch.svelte: 
```
	function redraw_image(_lines) {
		clear_canvas();

		if (value_img) {
			if (source === "webcam") {
				ctx.temp.save();
				ctx.temp.translate(width, 0);
				ctx.temp.scale(-1, 1);
				ctx.temp.drawImage(value_img, 0, 0);
				ctx.temp.restore();
			} else {
				draw_cropped_image();
			}

			if (!lines || !lines.length) {
				ctx.drawing.drawImage(canvas.temp, 0, 0, width, height);
			}
		}

		draw_lines({ lines: _lines });
		line_count = _lines.length;

		// if (lines.length) {
		// 	lines = _lines;
		// }

                // real time change the canvas
		lines = _lines;
		ctx.drawing.drawImage(canvas.temp, 0, 0, width, height);
		ctx.mask.drawImage(canvas.temp_fake, 0, 0, width, height); 

		if (lines.length == 0) {
			dispatch("clear");
		}
	}
```

```
	let draw_lines = ({ lines }) => {
		lines.forEach((line) => {
			const { points: _points, brush_color, brush_radius } = line;
			draw_points({
				points: _points,
				brush_color,
				brush_radius
			});

			if (mode === "mask") {
				draw_fake_points({
					points: _points,
					brush_color,
					brush_radius
				});
			}

			// points = _points;                          // this line has error

			return;
		});
		saveLine({ brush_color, brush_radius });
		if (mode === "mask") {
			save_mask_line();
		}
	};
```

### CODE REVIEW

**Comment by pngwn** [comment]
Could you provide some more information on how recreate this bug please?

**Comment by AmyOrz** [comment]
I'm sorry, this is first time i get a RP. 
this bug is work in the gradio/demo/blocks_mask -> io5a.

when mod is color-sketch, gr.Image(source="upload", tool="color-sketch"):
first time I get 3 line
image

and then I click the undo and submit, I get a error result:
image

I review the Sketch.svelte code and find this bug.

**Comment by pngwn** [comment]
I can't reproduce this on main. @AmyOrz Do you have a copy of the image you used here so I can test?

**Comment by AmyOrz** [comment]
ok, I will provide more information for you.
in the gradio/demo/blocks_mask -> io3a, io3b, io5a demo has the same bug:
1. first time I draw 3 line in canvas, get this result:
image
2.then i click the undo icon and draw other line, click submit button get this result:
image
3.click undo icon, two line is disappear. click submit button get error result; 
image

**Pull request closed without merging**
