### PR TITLE
Dropdown issues

### PR DESCRIPTION
**Pull request by aliabid94**
This PR fixes a lot of the dropdown issues raised by @space-nuko. GIF below shows new behavior of dropdown:

Recording 2023-03-20 at 13 05 07

code for demo at bottom.

Changes in this PR:
- Changes cursor from select to pointer in single dropdown mode
- Allows dropdown to be re-clicked after focus (fixes: #3532)
- Prevents dropdown from getting clipped by calculating size from ends of window, and directing dropdown toward side with more space. Will use full window space, and scroll beyond that (fixes: #3539, fixes: #3530).
- Overflow only happens in y-direction, no horizontal scrollbars (fixes: #3533)
- Search when multiselect=False (fixes: #3538)

``` 
import gradio as gr

with gr.Blocks() as demo:
    gr.Markdown(
    """
    # Hello World!
    Start typing below to see the output.
    """)
    gr.Dropdown(list("abcd"))
    gr.Dropdown(list("abcdefghijklmnopqrstuvwxyz"))
    gr.Dropdown(list("abcdefghijklmnopqrstuvwxyz"), multiselect=True)
    gr.Dropdown(list("abcd"))
    gr.HTML("""
    <div style="height: 600px; width: 240px; background-color: blue"></div>
    """)

if __name__ == "__main__":
    demo.launch()
```

### CODE REVIEW

**Comment by abidlabs** [comment]
Tested and works well @aliabid94. Nice PR!

**Review by abidlabs — APPROVED** [review]

**Comment by space-nuko** [comment]
LGTM 👍

**Comment by space-nuko** [comment]
Actually there's one issue I found, it has to do with the multiselect dropdown

Every other time you click on a choice it closes the list, even though you could still select/unselect other options

[output.webm](https://user-images.githubusercontent.com/24979496/226490051-d958f9d0-d38b-42b4-bace-14f7cefa49f7.webm)

**Comment by aliabid94** [comment]
Fixed the issue space nuko pointed out. Also moved the dropdown so it does not cover the input text. Also now you can type to search when multiselect=False, fixes #3538

**Comment by abidlabs** [comment]
Nice fixes @aliabid94! Thanks for raising these great issues @space-nuko

**Review by abidlabs — APPROVED** [review]

**Pull request merged**
