### PR TITLE
Playground requirements tab

### PR DESCRIPTION
**Pull request by whitphx**
## Description

Add a tab to set the requirements in the playground.

CleanShot 2024-09-27 at 17 55 46@2x

Also added a Transformers example.

### CODE REVIEW

**Review by aliabd — COMMENTED** [review]
Thanks @whitphx for the PR. I fixed some merge conflicts with my recent changes but I noticed a few issues here: 
- There’s a weird height problem. The preview section is now shorter than the code section. You can see it in the bottom space of the preview window. 
- Not all the demos have a requirements.txt file (for some reason), we should add the missing ones. For example kinematics demo uses pandas and numpy but they’re not showing up in the Packages section on playground. 
- The requirements are not passed on the “share your app” and “deploy to spaces” urls. It should be doable just following the same code I wrote. But if there's a problem let me know. 
- [nit] the font for the unselected tab is too light.

**Comment by whitphx** [comment]
@aliabd Thank you!
I fixed them but the tab font.
The tab UI is just same as `gr.Tab` so we should discuss it as a general design issue for Gradio?

**Review by aliabd — APPROVED** [review]
Great! thanks @whitphx everything looks great :fire:

**Comment by aliabd** [comment]
Actually @whitphx it looks like the notebooks match test and format check are still failing

**Comment by whitphx** [comment]
The `js-test`'s failure will be fixed by https://github.com/gradio-app/gradio/pull/9486

**Comment by whitphx** [comment]
@aliabd Thank you! WIll merge this once

**Pull request merged**
