### PR TITLE
Properly Restart Queue After App is Closed

### LINKED ISSUE #2980: gradio.Blocks.close() does not work if queue is enabled
### Describe the bug

`.close()` call finishes almost instantaneously when the queue is disabled.

If the queue is enabled, and any queued request has been made, the call hangs for about 60 seconds, then it finishes, but if I create another `Blocks` instance and launch it after that, it's just broken, none of requests work - first one produces "Event loop is closed" error message, the next ones just hang.

Code to reproduce is included.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import time

import gradio as gr


need_restart = False
testval = 0


def create_demo():
    with gr.Blocks(analytics_enabled=False) as res:
        button_test = gr.Button('Test')
        button_restart = gr.Button('Restart')
        label = gr.Label()

        def test():
            global testval
            testval += 1
            return testval

        def restart():
            global need_restart
            need_restart = True

        button_test.click(test, [], [label])
        button_restart.click(restart, [], [])

    return res


while True:
    print("Starting...")

    demo = create_demo()

    # broken
    demo.queue().launch(share=False, prevent_thread_lock=True)

    # works
    # demo.launch(share=False, prevent_thread_lock=True)

    while not need_restart:
        time.sleep(0.5)

    print("Closing demo...")

    need_restart = False
    testval = 0

    demo.close()
```

### Screenshot

_No response_

### Logs

```shell
no exceptions
```

### System Info

```shell
gradio-3.16.1, Windows 10, python 3.10.6
```

### Severity

blocking upgrade to latest gradio version

### PR DESCRIPTION
**Pull request by freddyaboulton**
# Description

Fixes #2980

The original issue was caused by

- The `stopped` flag of the queue was not set to False when the queue was restarted, so `start_processing` was not actually running
-  The `startup_events` were not re-running after restart
- The `httpx` Client was scoped to the original event loop since it was attached to the class. Now it's scoped to the running event loop by virtue of being instantiated when the queue starts running

Original Reproducer in the ticket now working properly
queue_close_fix

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by AUTOMATIC1111** [comment]
I'm sorry to ask for more while you are solving this for me but can anything be done about those 6 seconds?

**Comment by freddyaboulton** [comment]
No worries!

I suspect it can be reduced. I’m not sure why it was set to 60 seconds to begin with. Would 1 second be better? 

Are you expecting to close and restart apps frequently @AUTOMATIC1111 ?

**Comment by AUTOMATIC1111** [comment]
For users this is used when they update extensions or change settings that require remaking UI and for me and other people who develop for my program this is to reload the UI without restarting the whole program. The current (without queues) time to restart in the repro code is immediate, so having to wait 6 seconds would be a downgrade.

**Comment by aliabid94** [comment]
Will try to get this in this week!

**Comment by dawoodkhan82** [comment]
Getting an "event loop is closed" error when clicking test after restart. @freddyaboulton 

Screenshot 2023-01-23 at 2 23 46 PM

**Review by aliabid94 — APPROVED** [review]
Great work, thanks @freddyaboulton!

**Comment by freddyaboulton** [comment]
Thanks for the review @aliabid94 !

@dawoodkhan82 Can't reproduce - what python version are you using?

queue_close_2

**Comment by dawoodkhan82** [comment]
@freddyaboulton version 3.10.9

**Comment by freddyaboulton** [comment]
@dawoodkhan82 And I synched on this and it's all working now! Thanks for the reviews everyone!

**Pull request merged**
