### PR TITLE
Video and File event trigger fix

### PR DESCRIPTION
**Pull request by tomchang25**
# Description

- Finish change event of File, Video.
- Finish play, pause event of StaticVideo
- Add a event trigger demo

Closes: #3096, #3069

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks for the PR @tomchang25! @dawoodkhan82 would you be able to give this a look?

**Review by pngwn — CHANGES_REQUESTED** [review]
The changes look good! I've tested those and they are working as expected.

The media files that have been added are far too large, however, especially the video files. Can we remove those and choose something much much smaller? Preferably something below 0.5MB. We need to make sure these files are not just removed from the project but also removed from the GIT history.

**Comment by pngwn** [comment]
Unfortunately those files are still in the history, even though they have been removed from the file tree. The actual git history needs to be rewritten to get rid of the objects. I can take a look at this when I have time. Removing objects from history is slightly tedious. 

Note: The reason we don't want large files in the history is that everyone has to download the full history when they do a simple clone. They could do a shallow clone but then they'd encounter other difficulties which we want to avoid.

**Comment by tomchang25** [comment]
Done. @pngwn @abidlabs

**Review by pngwn — APPROVED** [review]
Looks great. Thank for taking care of that!

**Pull request merged**
