### PR TITLE
Fix loading files from embedded spaces

### PR DESCRIPTION
**Pull request by freddyaboulton**
# Description

Partial fix to #3176. The issue is that we're not using the upstream root to fetch files.

You can test with the following document

```html
<script type="module"
src="https://gradio-dev-cdn.s3.amazonaws.com/3.18.0b1/gradio.js">
</script>

<div>
    <gradio-app space="gradio/gallery_component"></gradio-app>
</div>

<div>
    <gradio-app space="gradio/video_component"></gradio-app>
</div>

<div>
    <gradio-app space="gradio/main_note"></gradio-app>
</div>

<div>
    <gradio-app space="gradio/model3D"></gradio-app>
</div>
```

embedding_fix

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by pngwn** [comment]
This looks good to me, this was removed recently so would be good to check that removal wasn't on purpose.

@abidlabs This was changed here: https://github.com/gradio-app/gradio/commit/f37d17089d074db7776d9ca16663234648e9e3e6#diff-6b0c6bc69dd496f77266204877e9786d6126070b1e38e7c523a5d11f2db51e1a was this intentional?

**Comment by abidlabs** [comment]
Ah no that looks like a mistake on my end, thanks for fixing!

**Review by pngwn — APPROVED** [review]
lgtm!

**Review by aliabid94 — APPROVED** [review]
LGTM

**Comment by freddyaboulton** [comment]
Thanks for the reviews everyone!!

**Pull request merged**
