### PR TITLE
Updated our analytics on creation of Blocks/Interface

### PR DESCRIPTION
**Pull request by abidlabs**
Three quick changes to our analytics on creation of Blocks/Interface:

* We actually fire the analytics when Blocks are created (previously, it was only when Interface was created)
* We record whether it was a Blocks or Interface that was created (using "mode")
* We also record which Gradio version they are running

I've also updated the `gradio-api-server` running to accept these analytics. We should keep in mind that we'll see an artificial bump in the "initiation" analytics as a result of this. For retrospective analysis, we should stick to launch analytics, which correctly record whenever Blocks are launched

### CODE REVIEW

**Comment by dawoodkhan82** [comment]
@abidlabs wont adding tests with analytics enabled, inflate the analytics?

**Comment by dawoodkhan82** [comment]
@abidlabs the tests with analytics_enabled are mocked right?

**Review by freddyaboulton — APPROVED** [review]
Looks good to me @abidlabs ! I think we're mocking the requests so we should be good to go.

That being said, I don't think we're setting `analytics_enabled` to False in the `all_demos` demo that's being deployed to spaces so we should do that! I can do that too, up to you!

**Review by dawoodkhan82 — APPROVED** [review]

**Comment by abidlabs** [comment]
Thanks for the review, guys! Will update `all_demos`, fix the tests, and then merge in.

**Comment by krrishdholakia** [comment]
Hey! @abidlabs, if i enable analytics where do I go to see the analytics for my space (if that's even possible?)

**Pull request merged**
