### PR TITLE
Reduce CPU usage of dev mode

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Closes: #7095

We're watching the files of the gradio source code in addition to the demo. This increases the number of files that are polled for changes by an order of magnitude and most users are not installing gradio from source and making changes to the source code. 

Fix:
- Only watch the gradio source code if installed in edit mode from source. There isn't a foolproof way to determine this but I have implemented a heuristic that should work most of the time. This change will only be "breaking" users who install gradio from pypi and who edit the source code in the `site-packages` directory. I think that's a small proportion of users and they can always do an editable install to get around this.
- Introduce a short sleep between watch iterations. I'm using 0.05 seconds which should be fast enough so that users can't notice while freeing up the CPU core running the watch thread a bit.

There are other watch file algorithms we can use (https://pypi.org/project/watchfiles/) that are potentially more efficient but they would require installing other dependencies. With this change CPU usage is about 2% which I think is ok.

### utilization in this PR
Screenshot 2024-01-22 at 6 21 27 PM

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks @freddyaboulton! Changes look good to me, but here's the performance I'm getting:

* At baseline, python consumes ~1% of CPU (some background python processes)
* On `main`, running `gradio cc dev`, python consumes ~98% of CPU
* On this branch, running `gradio cc dev`, python consumes ~60% of CPU

I assume that this is because I've installed from source. I haven't been able to test what happens when you install from pypi since this is not published yet. Is this is consistent with what you expect?

**Comment by freddyaboulton** [comment]
Yea I was seeing 50-60% if you do an editable install. You can test what would happen on a pypi install by omitting the `-e` flag when installing from source. So `pip install <gradio-dir>` will place it in `site-packages` and dev mode will no longer watch the gradio lib source.

if you run dev mode in a directory that has hundreds of python files then the CPU usage will be high. That's expected though and that should be the small minority of cases though.

**Comment by abidlabs** [comment]
Ah I see. Well I tested installing from source (but omitting the `-e` flag) and I still get around the same CPU usage: ~50-60% when running `gradio cc dev` in a brand new component directory. Increasing the timeout to 0.1 seconds brings the CPU usage down to 30% but at that point performance of reload mode is degrading. So this PR generally looks good to me (its certainly better than what we have now) but perhaps we can do a quick sync to figure out why there's a discrepancy between the cpu usage numbers we're seeing @freddyaboulton

**Comment by freddyaboulton** [comment]
Thanks for the review @abidlabs !

I looked into it and I understand the discrepancy. I was getting low usage rate running dev mode in a directory with only two python files. If you run dev mode in a custom component directory, lots of files get created, e.g. `frontend`, `frontend/node_modules`. The way dev mode works is that we recursively watch all python and css files in the directory from which its called. So we end up iterating through files in the frontend directory (of which there are many because of `node_modules`). This is technically unnecessary since a separate process is watching the frontend directory but I'm not sure how we can change this without introducing a breaking change to reload mode. 

The current change is an improvement and the CPU utilization we see now in cc dev mode should be ok for the large majority of machines imo since machines are multicore.

**Comment by abidlabs** [comment]
Can we skip watching the `frontend` folder altogether? We shouldn't need the Python reloader to watch those since the frontend server is already watching them.

**Review by abidlabs — APPROVED** [review]
Sounds reasonable to me. Thanks @freddyaboulton!

**Comment by freddyaboulton** [comment]
Thanks @abidlabs !

**Pull request merged**
