### PR TITLE
Quick Fix: Fixes autoplay parameter for Audio/Video in Chatbot

### PR DESCRIPTION
**Pull request by dawoodkhan82**
## Description

 Fixes autoplay parameter for Audio/Video in Chatbot.

Closes: #9346

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Testing and Formatting Your Code

1. PRs will only be merged if tests pass on CI. We recommend at least running the backend tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the backed tests: `bash scripts/run_backend_tests.sh`

2. Please run these bash scripts to automatically format your code: `bash scripts/format_backend.sh`, and (if you made any changes to non-Python files) `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
I tested with this:

```py
import gradio as gr

value = [(
    "Hello",
    gr.Audio("test.wav", autoplay=False)
)]

with gr.Blocks() as demo:
    b = gr.Button()
    c = gr.Chatbot(type="tuples")

    b.click(lambda : value, None, c)

demo.launch()
```

and what I'm seeing is that the audio starts playing immediately, suggesting that `autoplay` is now true in all cases. We don't want that, we want the `autoplay` property to be respected, and by default be turned off.

**Comment by dawoodkhan82** [comment]
@abidlabs Ah yes! will fix.

**Comment by dawoodkhan82** [comment]
@abidlabs Seems like the same issue exists for `Video`.

**Review by abidlabs — APPROVED** [review]
Didn't test for `Video`, but I can confirm that this solves the issue for `Audio`!

**Comment by abidlabs** [comment]
Will go ahead and merge now that CI is passing!

**Pull request merged**
