### PR TITLE
Custom component fixes

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

@gradio/markdown is not a dependency of @gradio/atoms so dev/build was broken for components that used them.

The `sanitize-html` library cannot be imported in the browser I think (uses `require` and has no export named `default`). I tried messing with `optimizeDeps` in the component config but it didn't work. So just changing the code in MarkdownCode to defer the import.

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by freddyaboulton** [comment]
Not sure why `npm-previews` is failing but `js-test` is unrelated.

You can test the markdown sanitize change like this

```python
import gradio as gr

gr.Interface(lambda x: f"Hello {x}", gr.Textbox(label="Name", info="**YOUR** name"), "textbox")
```

**Review by freddyaboulton — COMMENTED** [review]
Thank you for pairing on this @pngwn 🐐

**Review by pngwn — APPROVED** [review]
Looks great. Thanks @freddyaboulton!

**Comment by freddyaboulton** [comment]
Thank you @pngwn !!

**Pull request merged**
