### PR TITLE
Plot Component

### PR DESCRIPTION
**Pull request by dawoodkhan82**
# Description

Please include: 
* relevant motivation
* a summary of the change 
* which issue is fixed. 
* any additional dependencies that are required for this change.

Fixes: # (issue)

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by abidlabs** [comment]
Somewhat related -- the current plot output (which uses "plot" as a type of Image output), has an ugly gray background for matplotlib plots. Would it be possible to remove this as part of this PR?

image

**Comment by dawoodkhan82** [comment]
@pngwn can't seem to figure out the jQuery issue; when trying to import bokeh. Lmk if you have some time to take a look with me.

**Comment by dawoodkhan82** [comment]
@pngwn Seems like for format checks fail on the CDN script loading. How can we ignore this?

**Comment by abidlabs** [comment]
@dawoodkhan82 rethinking what I said earlier, it actually does make sense to get this PR in before we merge “blocks-dev” because that way we can release 2.9.2 and publicize the new plot component

After we merge blocks-dev, we probably won’t be going any regular releases, just pre release until 3.0 is ready for a launch, so this allows us to have multiple things we can publicize

**Comment by dawoodkhan82** [comment]
> 

Yeah that make sense

**Comment by abidlabs** [comment]
Tests are passing, I'm just tweaking the demo and we should be good!

**Comment by abidlabs** [comment]
LGTM

**Pull request merged**
