### PR TITLE
Fix backend tests on CI

### PR DESCRIPTION
**Pull request by abidlabs**
* Ensures that CI on Windows fails if any of the pytests fail
* Ensures that both python client tests and core gradio tests run when either are changed

### CODE REVIEW

**Comment by abidlabs** [comment]
Removing `coverage` seems to fix the issues for Windows CIs. Now, they "successfully fail", as you can see here:

* https://github.com/gradio-app/gradio/actions/runs/6805412176/job/18504878095?pr=6330
* https://github.com/gradio-app/gradio/actions/runs/6805412176/job/18504878322?pr=6330

**Comment by abidlabs** [comment]
Fixing this revealed several tests that are broken on Windows: https://github.com/gradio-app/gradio/actions/runs/6805506600/job/18505174184?pr=6330 -- let me fix those

**Comment by abidlabs** [comment]
Also, as pointed out by @aliabid94 recently, we should run the python client tests when the core library changes and vice versa, since they can affect each other

**Comment by abidlabs** [comment]
>  Also, as pointed out by @aliabid94 recently, we should run the python client tests when the core library changes and vice versa, since they can affect each other (now that we release both together)

Note that this will actually slow down the CI a little bit but we can get a significant speed up once we follow this PR with one addressing https://github.com/gradio-app/gradio/issues/6220

**Review by pngwn — APPROVED** [review]
Looks good to me!  Thanks for figuring this one out @abidlabs!

**Comment by abidlabs** [comment]
Thanks @pngwn appreciate the review!

**Review by freddyaboulton — COMMENTED** [review]
Thanks @abidlabs !

**Pull request merged**
