### PR TITLE
Allow setting plotly margins

### PR DESCRIPTION
**Pull request by aliabid94**
Plotly margins, when explicitly set, were being overwritten, so users couldn't specify them. Fixed now. See discussion here:
https://huggingface.slack.com/archives/C02QZLG8GMN/p1729596330205269

See modified outbreak_forecast demo below:
```python
import gradio as gr
from math import sqrt
import numpy as np
import pandas as pd
import plotly.express as px

def outbreak(r, month, countries, social_distancing):
    months = ["January", "February", "March", "April", "May"]
    m = months.index(month)
    start_day = 30 * m
    final_day = 30 * (m + 1)
    x = np.arange(start_day, final_day + 1)
    pop_count = {"USA": 350, "Canada": 40, "Mexico": 300, "UK": 120}
    if social_distancing:
        r = sqrt(r)
    df = pd.DataFrame({"day": x})
    for country in countries:
        df[country] = x ** (r) * (pop_count[country] + 1)

    fig = px.line(df, x="day", y=countries)
    fig.update_layout(
          # title="Outbreak in " + month,
          xaxis_title="Cases",
          yaxis_title="Days Since Day 0",
          margin=dict(l=0, r=100, t=30, b=0),
      )
    return fig


inputs = [
    gr.Slider(1, 4, 3.2, label="R"),
    gr.Dropdown(["January", "February", "March", "April", "May"], label="Month", value="March"),
    gr.CheckboxGroup(
        ["USA", "Canada", "Mexico", "UK"], label="Countries", value=["USA", "Canada"]
    ),
    gr.Checkbox(label="Social Distancing?"),
]
outputs = gr.Plot()

demo = gr.Interface(
    fn=outbreak,
    inputs=inputs,
    outputs=outputs,
)

demo.launch()
```

### CODE REVIEW

**Review by freddyaboulton — APPROVED** [review]
LGTM @aliabid94 ! Tested and works well

**Comment by albertvillanova** [comment]
Thanks for allowing passing margins.

However, please note that the bug I reported was not that margins were ignored. My reported bug is that, without specifying margins, some labels are cut off from the resulting figure. See example: https://huggingface.co/spaces/albertvillanova/bug-plotly-line-polar
- The resulting figure only shows 4 labels: GPQA, IFEval, MMLU-Pro and MuSR.
- However the plot has 6 labels: the top (BBH) and bottom (MATH) labels are cut off

Code:
```python
import gradio as gr
import pandas as pd
import plotly.express as px


DATA = {"BBH": [0.2, 0.7], "GPQA": [0.4, 0.5], "IFEval": [0.6, 0.3], "MATH": [0.2, 0.7], "MMLU-Pro": [0.4, 0.5], "MuSR": [0.6, 0.3]}


def display_plot():
    df = pd.DataFrame(DATA, index=["model-1", "model-2"])
    fig = px.line_polar(
        df.melt(ignore_index=False, var_name="Benchmark", value_name="Score").reset_index(names="Model"),
        r="Score", theta="Benchmark", color="Model",
        line_close=True,
        range_r=[0, 1],
        color_discrete_sequence=["#FF9D00", "#32343D"],
    )
    return fig


with gr.Blocks() as demo:
    plot = gr.Plot()
    btn = gr.Button()

    btn.click(
        fn=display_plot,
        outputs=plot,
    )

demo.launch()
```

**Comment by hysts** [comment]
@albertvillanova 

I think this fixes your issue. 
When I run your sample code with the changes in this PR, I get the following:



You can try it yourself by uninstalling `gradio` and running the `pip install` command in [this comment](https://github.com/gradio-app/gradio/pull/9805#issuecomment-2430164650).

**Comment by albertvillanova** [comment]
@hysts, thanks for checking and for the hint how I can check next time! :hugs:

**Pull request merged**
