### PR TITLE
Skip view_api request in js client when auth enabled

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Closes: #5403

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by pngwn** [comment]
The only issue with this is that we use the view api payload to correctly upload binary data where necessary. 

I don't think the client works for auth enabled apps anyway though, so it might not make a difference. This won't affect gradio itself (yet) because gradio components upload binary data early, rather than sending it to the client.

**Comment by freddyaboulton** [comment]
@pngwn I think we're ok. `auth_required` is only set in the config when the user has not authenticated yet. Upon successful authentication, the page is refreshed and a new client is created. Since `auth_required` is not set in the config, the api will be fetched.

Relevant backend code in routes.py

```python
            if app.auth is None or user is not None:
                config = app.get_blocks().config
                config["root"] = root_path
            else:
                config = {
                    "auth_required": True,
                    "auth_message": blocks.auth_message,
                    "space_id": app.get_blocks().space_id,
                    "root": root_path,
                }
```

**Review by pngwn — APPROVED** [review]
Looks great! Thanks @freddyaboulton!

**Comment by freddyaboulton** [comment]
Thanks for the review @pngwn !

**Pull request merged**
