### PR TITLE
Fix Lite to work on FireFox

### PR DESCRIPTION
**Pull request by whitphx**
## Description

Context: [internal link](https://huggingface.slack.com/archives/C02QZLG8GMN/p1727352575363519?thread_ts=1727341327.772879&cid=C02QZLG8GMN)

Lite doesn't work on FireFox when the script is loaded in the cross-origin manner as below (this screenshot was taken in an env where the Lite is served from `localhost:8000` and the parent page is from `localhost:8080`).
CleanShot 2024-10-04 at 14 34 51@2x

This is because, on FireFox, `new WebWorker()` throws the `SecurityError` asynchronously, while it's synchronous on Chrome, so the synchronous `try-catch` surrounding it doesn't work.

Closes: https://github.com/gradio-app/gradio/issues/8860

### CODE REVIEW

**Comment by abidlabs** [comment]
Nice @whitphx, looks like this would close https://github.com/gradio-app/gradio/issues/8860 as well

**Comment by aliabd** [comment]
@whitphx while it does load on firefox now, I get a weird connection error running a simple interface. 

```
Wasm HTTP error 
Object { request: {…}, response: {…}, bodyText: '{"detail":[{"type":"missing","loc":["body"],"msg":"Field required","input":null}]}', bodyJson: {…} }
​
bodyJson: Object { detail: (1) […] }
​
bodyText: '{"detail":[{"type":"missing","loc":["body"],"msg":"Field required","input":null}]}'
​
request: Object { path: "/gradio_api/queue/join", query_string: "", method: "POST", … }
​
response: Object { status: 422, headers: {…}, body: Uint8Array(82) }
​
<prototype>: Object { … }
```

here's the code: 

```python
import gradio as gr
gr.Interface(lambda x:x, "text", "text").launch()
```

**Comment by whitphx** [comment]
@aliabd hmm I couldn't reproduce the error...
My Firefox version is 131.0 (aarch64).

Do these look good?

CleanShot 2024-10-08 at 10 35 46@2x

```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://gradio-lite-previews.s3.amazonaws.com/594bbbbc5a47fae1a86fd44459da81c3711bd1c3/dist/lite.css" />
    <script type="module" src="https://gradio-lite-previews.s3.amazonaws.com/594bbbbc5a47fae1a86fd44459da81c3711bd1c3/dist/lite.js""></script>
</head>
<body>
<gradio-lite>
    import gradio as gr
    gr.Interface(lambda x:x, "text", "text").launch()
</gradio-lite>
</body>
</html>
```

```shell
python -m http.server
```

**Comment by whitphx** [comment]
Looks like the failing tests are from the main branch, and `functional-lite` passed in this PR.

**Review by abidlabs — APPROVED** [review]
Brilliant! Tested https://e3eeefd9.gradio-website.pages.dev/playground in both Chrome and Firefox and it works. I'll go ahead and merge this in so that the Playground is accessible to Firefox users

**Pull request merged**
