### PR TITLE
Prevent file traversals

### PR DESCRIPTION
**Pull request by abidlabs**
[Internal thread](https://huggingface.slack.com/archives/C02QZLG8GMN/p1702901295299349)

### CODE REVIEW

**Review by freddyaboulton — APPROVED** [review]
Thanks @abidlabs !

**Review by freddyaboulton — COMMENTED** [review]
Would be nice to write a unit test for this!

**Comment by abidlabs** [comment]
I tried to write a unit test but for some reason I can't reproduce this behavior with fastapi's test client. Only curl seems to have this effect (and only if you pass in `--path-as-is` flag)

**Comment by abidlabs** [comment]
Apparently due to this PR https://github.com/urllib3/urllib3/pull/1487. Let me see if I can write a unit test a different way

**Comment by abidlabs** [comment]
Ok added a quick unit test. Thanks for the review @freddyaboulton! Will merge after CI is green

**Pull request merged**
