### PR TITLE
fix(chat_interface.py): fix 'submit_btn' not being set to 'None'

### PR DESCRIPTION
**Pull request by TALLEC-Scott**
## Description

I had an issue : [Issue with MultimodalTextbox #7993](https://github.com/gradio-app/gradio/issues/7993) 

Issue where Submit_btn was not set to None when an instance of 'gr.MultimodalTextbox' was passed to 'textbox' argument of 'ChatInterface'.

Closes: #7993

### CODE REVIEW

**Comment by TALLEC-Scott** [comment]
Hey @abidlabs, it seems that the one test that was making every automated check fail (for everyone it seems) has been set to skip in the main branch. Now my commit passes the automated tests, you can now remerge or approve my merge. thx.

**Comment by dawoodkhan82** [comment]
Any reason why this was closed? @TALLEC-Scott @abidlabs ?

**Comment by TALLEC-Scott** [comment]
@dawoodkhan82 I fixed it in another patch I wrote. #8013

**Comment by abidlabs** [comment]
So is https://github.com/gradio-app/gradio/issues/7993 no longer an issue then @TALLEC-Scott @dawoodkhan82?

**Comment by TALLEC-Scott** [comment]
yes @abidlabs. Just closed the issue.

**Comment by abidlabs** [comment]
Thanks!

**Pull request closed without merging**
