### PR TITLE
Add button to change between front and back camera

### LINKED ISSUE #818: Adding Rear Camera Support for Mobile Phones
Currently the source=webcam option to input images and videos defaults to the Front camera of the Mobile Phone, it would be great to have it supported for the Rear camera as well as it would be required in certain situations. Hope this gets added :)

### PR DESCRIPTION
**Pull request by thepelkus-too**
# Description

Previously, the webcam component defaulted to the user-facing camera and could not be switched to the rear-facing camera. With this change, a button is added to the webcam component to switch between front and rear cameras.

_Note:_ the button will appear even on desktop machines due to front/rear camera detection being non-trivial and the feeling that it seems better to have it present when it's nonfunctional than to not have it when it's available and desired; see https://stackoverflow.com/questions/65485170/getusermedia-detect-front-camera. That said, definitely open to revisiting this aspect if folks have ideas.

_Another note:_ still getting acquainted with this codebase, and I've barely looked at the tests. If this seems like a good opportunity to add a test for the new UI, please let me know.

Suggestions always appreciated!

Closes #818 

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by abidlabs** [comment]
Cool thanks for the PR @thepelkus-too for this longstanding issue! @pngwn do you have thoughts on this implementation and UI?  

image

**Comment by pngwn** [comment]
We need to clean up the existing streams before starting a new one. Will take a look at this early next week.

**Comment by pngwn** [comment]
There are some issues that are difficult to debug, working on them but they might be related to #4159. So I might take care of that first. They are only slightly related to this PR.

**Comment by abidlabs** [comment]
Thanks @pngwn. Btw a very related issue is #4252 -- would this PR allow one to switch between multiple arbitrary webcams or only front/back on mobile?

**Comment by pngwn** [comment]
Maybe we should just do that instead. Since it covers this case too.

**Comment by pngwn** [comment]
This PR is only for front/ back.

**Comment by abidlabs** [comment]
> Maybe we should just do that instead. Since it covers this case too.

Yeah I think we should. If it's a lot more work to support additional webcams, then I think it's fine to just close this PR and handle after 4.0 release.

**Comment by pngwn** [comment]
There would be some design work I think and we may want to support both camera flip mode for mobile and select any input device. It would be better to solve those problems together, so let's push to 4.0.

**Comment by pngwn** [comment]
@thepelkus-too Thanks for this PR but we have decided to revisit in 4.0 to support even more input devices that just mobile front and back.

**Comment by thepelkus-too** [comment]
> @thepelkus-too Thanks for this PR but we have decided to revisit in 4.0 to support even more input devices that just mobile front and back. 

No worries, just trying to pitch in where I can!

**Comment by loris2222** [comment]
Hello, how could I obtain the proposed behavior without waiting for 4.0?
It looks like patching local `.svelte` files is not an option

**Comment by nitinss17** [comment]
@pngwn @abidlabs 
Can we please add this feature soon? I can see the button but it doesn't change to back cam when I click back camera, it's stuck in front camera. I really need to use back cam as it has higher resolution and the person can see object on screen before capturing. 

I was waiting for 4.0 release but even after realise I see no change to back cam ..

**Pull request closed without merging**
