### PR TITLE
Make sure the Tool accordion is closed if it is not the last message

### LINKED ISSUE #9776: Be able to display chat messages accordion closed by default for assistant message
- [x] I have searched to see if a similar issue already exists.
- related to https://github.com/gradio-app/gradio/issues/9081

**Is your feature request related to a problem? Please describe.**  
In gradio chatbot, with type "message", you can add a title in metadata to get a accordion with a title and content inside
By default, this accordion is closed for role user, and open for role assistant

**Describe the solution you'd like**  
It would be nice to be able to have this accordio closed or opened by default with a parameter in the ChatMessage
Something like 
`               ChatMessage(role = "user", content = "user_test", metadata={"title":"title_user"}, accordio = "opened"),
                ChatMessage(role ="assistant", content = "assistant_test", metadata={"title":"title_assistant"}), accordio = "closed"),
`

image

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Closes #9776 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by pngwn** [comment]
Did AI write the PR title or are you just drunk?

**Comment by freddyaboulton** [comment]
@pngwn 😂

**Review by aliabid94 — APPROVED** [review]
Thanks @freddyaboulton, code looks good! 
I think this should also be configurable via metadata, I agree with https://github.com/gradio-app/gradio/issues/9776#issuecomment-2439625065, something like e.g. 
```python
ChatMessage(
            role="assistant",
            content="...",
            metadata={"title": "...", open=True},
        )
```

I could see users wanting to always hide logic when its verbose, or always have it visible.

**Comment by freddyaboulton** [comment]
Thanks @aliabid94 ! yea that's reasonable - I'll open a separate PR for that!

**Pull request merged**
