### PR TITLE
Lite: HTTPX client improvement

### PR DESCRIPTION
**Pull request by whitphx**
## Description

~~Refactoring to use the same HTTPX client object both for the normal Gradio and Lite.~~
Changed this PR to be just a refactoring on the HTTPX client impl. See the conversation below.

### CODE REVIEW

**Comment by whitphx** [comment]
The Lite E2E test is failing but it was from #9339.
The changes in this PR has an effect on the `image_remote_url` E2E test and it's successful.

**Comment by abidlabs** [comment]
@whitphx we can just skip the `resolve_with_google_dns` method when we are in Lite. That method was added to prevent SSRF attacks, which are not relevant in the browser context anyways

**Comment by abidlabs** [comment]
cc @aliabid94

**Review by abidlabs — APPROVED** [review]
This looks fine to me @whitphx but just curious why we discard the headers instead of just setting `self.response.stream(decode_content=False)`?

**Comment by whitphx** [comment]
@abidlabs Thanks! That's an important point. I updated the comment to answer the question!

**Comment by abidlabs** [comment]
Ah interesting, thanks so much for the fix @whitphx! LGTM, let's go ahead and merge this in

**Pull request merged**
