### PR TITLE
Textbox Shift + Enter key Refactor

### PR DESCRIPTION
**Pull request by dawoodkhan82**
# Description
- if lines = 1 and max_lines > 1, keep that Enter submits and adds that Shift+Enter creates a new line (same Discord/Slack expected behavior the user only see one line, so they expect enter to submit imo)
- if lines > 1, then it is visually a textarea and not an input field anymore, so then the logic of Enter goes to the next line, and Shift+Enter submits makes sense to me
- if lines == 1 and max_lines == 1 then enter submits

Please include: 
* relevant motivation
* a summary of the change 
* which issue is fixed. 
* any additional dependencies that are required for this change.

Closes: #2061

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by dawoodkhan82** [comment]
Some issues:
Max_lines doesnt seem to currently work
Ctrl key doesn't currently work with these changes, I can work on adding that if needed

**Comment by abidlabs** [comment]
I think it's fine (actually better) to stick to just Shift+Enter because it's more clear when there's a single way to do it + shift is cross-platform whereas ctrl/cmd isn't

**Comment by abidlabs** [comment]
Maybe we can tackle #2103 as part of this PR as well @dawoodkhan82?

**Comment by dawoodkhan82** [comment]
> Maybe we can tackle #2103 as part of this PR as well @dawoodkhan82?

Will make a separate pr for this. Want to get this merged

**Comment by dawoodkhan82** [comment]
@abidlabs can you confirm this works as expected, so I can merge

**Comment by abidlabs** [comment]
Works perfectly, thanks for the clear explanation in the PR!

**Review by abidlabs — APPROVED** [review]

**Pull request merged**
