### PR TITLE
Pin fastapi test version to 0.87.0

### PR DESCRIPTION
**Pull request by freddyaboulton**
# Description

Looks like the new fastapi version (0.87.0, released yesterday) has a hard pin on starlette 0.21.0 which introduces breaking changes to the testclient. 

https://github.com/tiangolo/fastapi/pull/5471

Rather than putting a pin in the version in `requirements.txt` (which would force all users to upgrade fastapi/starlette versions), I am only putting a pin in the version of fastapi installed for the unit tests.

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by abidlabs** [comment]
@freddyaboulton should we update the tests themselves instead to use the latest version of fastapi? Don't have a strong opinion, but looks like there is a handy [bump tool](https://github.com/tiangolo/fastapi/pull/5471)

**Comment by freddyaboulton** [comment]
@abidlabs Either works but not both. Either we do `>=0.87` or `==0.86.0` in `requirements.in`. Given that the only difference is in `TestClient` I didn't see the need to upgrade and change the code. What do you think/prefer? We can also upgrade later if we want if we don't upgrade now. This won't be user facing.

**Comment by freddyaboulton** [comment]
@abidlabs Upgraded to 0.87 instead!

**Comment by abidlabs** [comment]
Cool LGTM thanks @freddyaboulton!

**Review by abidlabs — APPROVED** [review]

**Pull request merged**
