### PR TITLE
Upload files from iPhone fix

### PR DESCRIPTION
**Pull request by dawoodkhan82**
## Description

Skips `mime_type` check when uploading files from iPhone, since mime types are not always guaranteed with iPhone upload. 

Closes: #7471

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by dawoodkhan82** [comment]
Having trouble testing this with browserstack. Also this essentially skips the file type check, so not the best solution. Open to suggestions!

**Comment by aliabid94** [comment]
I am not able to reproduce the original issue - off of main, I set the types to ".pdf" and it did filter to only pdfs. What did you see @dawoodkhan82 ?

**Comment by dawoodkhan82** [comment]
@aliabid94 You tested on iPhone?

**Comment by aliabid94** [comment]
yep. I was able to select only pdfs

**Pull request closed without merging**
