### PR TITLE
Version 3.28.1

### PR DESCRIPTION
**Pull request by abidlabs**

### CODE REVIEW

**Comment by freddyaboulton** [comment]
In the deployed space in the `blocks_mask` demo, taking a photo with `5c` makes the image component disappear.

blocks_mask_5c_bug

**Comment by abidlabs** [comment]
@freddyaboulton I can confirm the issue, but it looks like it was a pre-existing condition: https://huggingface.co/spaces/gradio-pr-deploys/pr-3996-all-demos

**Comment by abidlabs** [comment]
I suggest we make that an issue and release this version if everything else looks ok

**Comment by freddyaboulton** [comment]
Sounds good @abidlabs ! I can file an issue for that. 

The other thing I noticed was that in `blocks_update` the animal drop down is not updated when the species is updated. This may be due to the recent dropdown changes.

dropdown_update_bug

**Comment by abidlabs** [comment]
Ah you're right here's a simple repro:

```py
import gradio as gr

choices = ["apple", "banana"]

gr.Interface(lambda x:x, gr.Dropdown(choices=choices), gr.Dropdown(choices=choices)).launch()
```

This is a pretty bad bug. @aliabid94 could you take a look at this?

**Comment by freddyaboulton** [comment]
Rest of the deployed demos look good to me!

**Comment by aliabid94** [comment]
Ok I think I fixed it in this PR

**Comment by abidlabs** [comment]
LGTM, thanks @aliabid94! The failing tests are because of Spaces-related issues as far as I can tell, so I will go ahead and merge!

**Pull request merged**
