### PR TITLE
fix: allow multiple flagging directories

### PR DESCRIPTION
**Pull request by EgonFerri**
## Description

In order to solve the issue grant the possibility to link different flagging directories to different interfaces in the case of multiple interfaces like gr.TabbedInterface, I tried moving flagging_dir also as a parameter of flag(), and so as a parameter of __call__ in FlagMethod (all in flagging.py).
Subsequently, I adapted some code in interface.py, helpers.py, and tests to make it all work. 

This is my first public PR, I tried my best to do everything right but if not please tell me what could be done better. 

## 🎯 Target Issue

Closes: #5692

## Tests

1. I followed the guidelines to contribute (https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and ran the tests: `bash scripts/run_all_tests.sh`. All test passed except sum test linked to hugging face that were not related with the addressed issue, and broke also before my changes (for unloadable spaces or hugginface API limit reach).

2. I ran `bash scripts/format_backend.sh` to lint my code.

### CODE REVIEW

**Comment by EgonFerri** [comment]
Could you review this, please? @abidlabs (:

**Comment by abidlabs** [comment]
Thanks so much @EgonFerri will take a look when I have a chance!

**Comment by abidlabs** [comment]
Hi @EgonFerri this is a nice PR, but all of these changes should not be necessary as far as I understand. Each Interface has its own FlaggingCallback, and each FlaggingCallback has its own `self.flagging_dir` attribute, which is where the data should be saved. 

I can reproduce the bug, but I think this approach (changing the `.flag()` method signature) to solve it is incorrect, since each FlaggingCallback instance already has the information it needs in order to save the data.

I don't have bandwidth to look into this more, but perhaps the information above might guide you towards a solution.

**Comment by abidlabs** [comment]
Ah good catch @EgonFerri. 

How about we simply fix this by changing the default value of `flagging_callback` to `None`, and then in the constructor, doing

```py
        if flagging_callback is None:
            flagging_callback = CSVLogger()
```

**Comment by EgonFerri** [comment]
@abidlabs your suggested approach was indeed the best way to solve the issue, I think. I opened a new [pull request](https://github.com/gradio-app/gradio/pull/6011) that addresses the issue in a more concise and straightforward way.

**Pull request closed without merging**
