### PR TITLE
Fix #5504

### LINKED ISSUE #5504: Can't use `str` builtin function as `fn` for `gradio.Interface`
### Describe the bug

```shell
# want to check what shape the Audio returns for mono and stereo inputs
python3 -c 'import gradio; gradio.Interface(str, gradio.Audio(), gradio.Textbox()).launch()'
# File "/home/vadimkantorov/.local/lib/python3.8/site-packages/gradio/interface.py", line 376, in __init__
#    param_names = inspect.getfullargspec(self.fn)[0]
#  File "/usr/lib/python3.8/inspect.py", line 1144, in getfullargspec
#    raise TypeError('unsupported callable') from ex
#TypeError: unsupported callable
```

```python
# equivalent, but works
import gradio
def f(audio):
    return str(audio)
gradio.Interface(f, gradio.Audio(), gradio.Textbox()).launch()
```

`gradio.Interface` [docs](https://www.gradio.app/docs/interface) say that the `fn`'s type is `Callable`, so the error is quite ironic :) 
image

Overall, this is minor and currently boils down to python's inspect.getfullargspec strangely not supporting many builtin functions: https://github.com/python/cpython/issues/76533

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

python3 -c 'import gradio; gradio.Interface(str, gradio.Audio(), gradio.Textbox()).launch()'

### Screenshot

_No response_

### Logs

_No response_

### System Info

```shell
`gradio.__version__`: '3.39.0'
```

### Severity

I can work around it

### PR DESCRIPTION
**Pull request by SrijanSahaySrivastava**
## Description (Reopened)
catch if `param_names = inspect.getfullargspec(self.fn)[0]` doesn't get arguments.

raise error only when uncallable functions are called.

Closes: #5504 

base branch :- v4

### CODE REVIEW

**Comment by SrijanSahaySrivastava** [comment]
@abidlabs i've reopened the PR. please go through the changes.

i'm kinda confused with what is actually causing the issue.

**Comment by abidlabs** [comment]
Hi @SrijanSahaySrivastava. In principle, these changes look good, but since we merged v4 into main, the git histories have messed up. Would you be able to open a new PR targeting main with these changes?

Sorry for the back-and-forth, but we should be able to get this reviewed pretty quickly after its targeting `main`.

**Comment by SrijanSahaySrivastava** [comment]
So should i reopen the pr with main branch as base?

**Comment by abidlabs** [comment]
Yes please! I'll go ahead and close this one

**Pull request closed without merging**
