### PR TITLE
Configure playwright to automatically retry failing tests up to 3 times

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Tests that pass when they are retried are reported as flaky by playwright

image

So the idea here is to notice the flakes but not slow down development velocity. 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Amazing thank you @freddyaboulton!

**Review by abidlabs — APPROVED** [review]

**Comment by abidlabs** [comment]
This applies to the Lite tests as well? IIRC one of them was flaky

**Comment by abidlabs** [comment]
I've made functional tests a required test again in light of this

**Comment by freddyaboulton** [comment]
Yes should apply to lite as well! Thanks @abidlabs !

**Pull request merged**
