### PR TITLE
Fix codeblock

### PR DESCRIPTION
**Pull request by Keldos-Li**
# Description

Hi gradio team, what I did may fix 2 little issues related to codeblock in chatbot messages:

1. **Code may exceed codeblock boundary if message width is narrow:**
   iShot_2023-05-17_上午11 59 06
   Now a scroll bar is added when there is a long code line.
   iShot_2023-05-17_下午12 00 31

2. **There is an extra blank space after the code block.** This is caused by `<code>` tag, which added a line in pre.
   iShot_2023-05-17_下午12 23 14
    So I made some change in `<pre><code>` tag
   iShot_2023-05-17_下午12 22 29

final look:
image

------

By the way, I would like to tell you that I'm also a developer using gradio to build a LLM project: [Chuanhu Chat](https://github.com/GaiZhenbiao/ChuanhuChatGPT) (10.3k stars). In fact, we have implemented the functions of code blocks and code highlighting and code copy a few months ago, so now we've come back to adapt to the new Gradio and found the problem...
imageimage

 (_**I'd say it'll be so hard for we developers to catch up with gradio updates.**_.. And you guys don't even include any changelog in your github releases...😢)

----
<details><summary>
Oh, and do you have interest in Slider styles?
</summary>

I tried to make sliders look consistent and pretty in various web browsers in [our repo](https://github.com/GaiZhenbiao/ChuanhuChatGPT/pull/734) : 

before
image
(Firefox, Chrome and Safari in turn)
after
image
However I am not very familiar with gradio... I don't know how to fix it in your code. Could you fix that?
</details>

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by pngwn** [comment]
These are nice changes. @dawoodkhan82 could we bring these into your markdown PR?

**Comment by pngwn** [comment]
@Keldos-Li Could you create a new issue for the issues with the slider? I agree we need to improve the Slider somewhat.

**Comment by Keldos-Li** [comment]
> @Keldos-Li Could you create a new issue for the issues with the slider? I agree we need to improve the Slider somewhat.

My bad. I just opened #4255.

----

And... Umm.... I just saw #4150, and it seems that my PR is not very necessary after that.……So sad...😭

**Comment by abidlabs** [comment]
It looks like we can close this in light of #4150, which also addresses the horizontal overflow issue. Thanks @Keldos-Li for the creating the issue around the sliders.

**Pull request closed without merging**
