### PR TITLE
Add microphone input to `gr.MultimodalTextbox`

### PR DESCRIPTION
**Pull request by WizKnight**
This PR adds support for microphone input to the `gr.MultimodalTextbox` component, allowing users to record audio directly within the component.

The following changes were made:

- Added a new `sources` parameter to the `gr.MultimodalTextbox` constructor to control the available input sources (file upload and/or microphone).
- Updated the backend (`multimodal_textbox.py`) to handle audio data from the microphone.
- Modified the frontend (`MultimodalTextbox.svelte`) to include a microphone button and implement audio recording and sending functionality.

This feature enhances the flexibility and usability of the `gr.MultimodalTextbox` component, enabling more interactive and multimodal applications.

Closes: #9494

### CODE REVIEW

**Comment by WizKnight** [comment]
Hi @abidlabs :),  I've added the initial implementation of the microphone feature. I would appreciate if you could review the changes and provide feedback on whether the implementation is progressing as intended.

**Comment by dawoodkhan82** [comment]
Hey @WizKnight thanks for the PR! We'll review this soon, since we're currently heads down with the 5.0 launch.

**Comment by dawoodkhan82** [comment]
Just from a quick look, I wonder if we can use any of the existing Audio components here. Maybe the `AudioRecorder`

**Comment by dawoodkhan82** [comment]
@WizKnight Thanks for the contribution, but since this is still a draft I'll open up a PR soon to implement this feature.

**Comment by abidlabs** [comment]
Let's close this PR then. Thank you @WizKnight for starting this work!

**Pull request closed without merging**
