### PR TITLE
support domains

### LINKED ISSUE #3269: update embeds to support subdomain
A new API will support getting space info via the API. This will exist soon and the embed functionality needs updating to support it.

### PR DESCRIPTION
**Pull request by pngwn**
closes #3269.

### CODE REVIEW

**Comment by abidlabs** [comment]
Working good so far. Here's the Spaces I've tested so far:

```html

	<script
	type="module"
	src="https://gradio.s3-us-west-2.amazonaws.com/3.20.0b1/gradio.js"
></script>

<gradio-app src="https://abidlabs-image-identity-slow.hf.space"></gradio-app>
```

Which worked ✅ 

image

Live interface works as well ✅ 

```html

	<script
	type="module"
	src="https://gradio.s3-us-west-2.amazonaws.com/3.20.0b1/gradio.js"
></script>

<gradio-app src="https://abidlabs-titanic-survival-2.hf.space"></gradio-app>

```

image

Using the `src` attribute, we can also embed gradio demos not hosted on Spaces, e.g. 

```html
	<script
	type="module"
	src="https://gradio.s3-us-west-2.amazonaws.com/3.20.0b1/gradio.js"
></script>

<gradio-app src="https://63aee4aab291ffdafd.gradio.live"></gradio-app>
```

And in this case, they don't have the Space border ✅

image

Still looking into error states

**Comment by abidlabs** [comment]
I checked two error states: 

1 A Space with a runtime error:

```html
	<script
	type="module"
	src="https://gradio.s3-us-west-2.amazonaws.com/3.20.0b1/gradio.js"
></script>

<gradio-app src="https://abidlabs-titanic-survival-3.hf.space"></gradio-app>
```

image


2. an invalid `src` (non-existent Space): 

```html
	<script
	type="module"
	src="https://gradio.s3-us-west-2.amazonaws.com/3.20.0b1/gradio.js"
></script>

<gradio-app src="https://abidlabs-titanic-survival-4.hf.space"></gradio-app>
```

Here, the embed would just load forever without showing any sort of error:

image

Note that if you were to specify a non-existent Space using the `space=` attribute, then it does show an error, so there is this small inconsistency

**Comment by freddyaboulton** [comment]
The only thing I noticed is that the buttons are not clickable for me if I am embedding an older version of main. 

Example: loading `video_component` vs `video_component_main`

```html
<script type="module"
src="https://gradio.s3-us-west-2.amazonaws.com/3.20.0b1/gradio.js">
</script>


<div>
    <gradio-app src="https://gradio-video-component-main.hf.space"></gradio-app>
</div>

<div>
    <gradio-app src="https://gradio-video-component.hf.space"></gradio-app>
</div>
```

image

Other than that works great for me! Thanks @pngwn

**Comment by abidlabs** [comment]
Yeah I noticed what @freddyaboulton is describing as well, but I figured that's okay we don't necessarily support compatibility with different versions of gradio

**Comment by freddyaboulton** [comment]
Yea good point @abidlabs

**Comment by pngwn** [comment]
Added handling for empty and invalid/ non existent `space` `src` and `host`.

**Review by freddyaboulton — APPROVED** [review]
Pushed to https://gradio-dev-cdn.s3.amazonaws.com/3.20.0b2/gradio.js

and the error states are handled well for me. Thanks for the fix @pngwn ! 


image

**Comment by abidlabs** [comment]
Likewise just finished testing, works great @pngwn! LGTM

**Review by abidlabs — APPROVED** [review]

**Pull request merged**
