### PR TITLE
Component support for updating elem_classes

### PR DESCRIPTION
**Pull request by Kilig947**
## Description

Please include a concise summary, in clear English, of the changes in this pull request. If it closes an issue, please mention it here.

Closes: #(issue) https://github.com/gradio-app/gradio/issues/4590

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests & Changelog

elem_class branch
image

main branch
image

Please add a brief summary of the change to the Upcoming Release section of the `CHANGELOG.md` file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

### CODE REVIEW

**Comment by abidlabs** [comment]
Hi @Kilig947 this PR is based off an older version of the Gradio. We've sinced refactored `components.py` so that each component is in a separate file. Would you be able to update your PR accordingly?

**Comment by abidlabs** [comment]
I'll go ahead and close this for now @Kilig947, feel free to reopen if you'd like to contribute this

**Comment by Kilig947** [comment]
> I'll go ahead and close this for now @Kilig947, feel free to reopen if you'd like to contribute this

Yes, I've merged the latest main branch.

**Comment by Kilig947** [comment]
> > I'll go ahead and close this for now @Kilig947, feel free to reopen if you'd like to contribute this
> 
> Yes, I've merged the latest main branch.



> I'll go ahead and close this for now @Kilig947, feel free to reopen if you'd like to contribute this

How do I open this pr? I can't find my branch in new pr.😢
image

**Comment by abidlabs** [comment]
Just reopened this PR @Kilig947, feel free to push to it

**Comment by abidlabs** [comment]
Actually this branch is going to be quite out of date at this point @Kilig947. I suggest moving your changes to a new branch and then opening the PR just as you did before. I'll close this.

**Pull request closed without merging**
