### PR TITLE
Copy button on code blocks

### PR DESCRIPTION
**Pull request by aliabd**
### All code blocks will include a copy button in top right corner. demo below:

https://user-images.githubusercontent.com/9021060/153450201-adc1bd71-104d-4e31-af27-309f84f7b896.mov

* this affects getting started and all guides, but not index. (can add if desired)
* only gets added to python / bash code blocks (so not csv or directory, which doesn't make sense imo) 
* fixed issue with getting started getting skipped
* feedback welcome, including on design

Closes: #591

### CODE REVIEW

**Comment by aliabd** [comment]
Noticed some design issues with overflowing code blocks (doesn't stay on top right, doesn't overlay well on text) 

https://user-images.githubusercontent.com/9021060/153460537-1aaf5429-4bdc-417d-b891-ff99bb36009b.mov


https://user-images.githubusercontent.com/9021060/153460517-dbda7ff3-1f85-444e-ac0b-c78930510573.mov



@aliabid94 any ideas here?

**Comment by aliabd** [comment]
changes:
* primary color is darker grey with better contrast, and will flash light orange as click feedback. 
* fixed overlay and overflow issue 
* for simplicity I actually had it apply to all codeblocks (including csv and dir), I can change this though if it makes sense.



https://user-images.githubusercontent.com/9021060/153592177-fe2cd70e-fd1d-4077-bb33-1a16f17de774.mov

https://user-images.githubusercontent.com/9021060/153592186-41da2476-841c-482b-b2a7-04e00bdff8b4.mov



anything else?

**Comment by aliabd** [comment]
Actually, changed the flashing color to be stronger orange:

https://user-images.githubusercontent.com/9021060/153593296-ab3d0ef4-b6ba-4117-9bfe-10b6ab90db74.mov

**Comment by abidlabs** [comment]
Looks great to me!

**Review by abidlabs — APPROVED** [review]

**Comment by aliabd** [comment]
Made copy button only visible when hovering over the code block 


https://user-images.githubusercontent.com/9021060/153619801-bb9f85e2-2d3e-447b-aa11-cbd30db6570b.mov

**Review by aliabid94 — APPROVED** [review]
LGTM

**Comment by FarukOzderim** [comment]
> Made copy button only visible when hovering over the code block
> Untitled.mov

@aliabd I think this might it implicit, I believe it would be better if it is always visible.

**Pull request merged**
