### PR TITLE
Run `pnpm i` with pnpm@8.6.0 to re-generate the lock file

### PR DESCRIPTION
**Pull request by whitphx**
# Description

I simply ran `pnpm i` with `pnpm@8.6.0` to re-generate the lock file with the latest version format (`6.1`).
The lock file version has been upgraded from `6.0` to `6.1` with `pnpm@8.1.0` as written in  https://github.com/pnpm/pnpm/blob/main/lockfile/lockfile-file/CHANGELOG.md

# Checklist:

- [ ] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by whitphx** [comment]
I will work on the CI fix because it may conflict with #4394

**Review by pngwn — COMMENTED** [review]
We will want to upgrade the pnpm version installed in CI to version 8 too and also update the documentation for contributors.

**Comment by whitphx** [comment]
Thanks,
> upgrade the pnpm version installed in CI to version 8 too

Yes, I will do it after #4394 as written above.

> also update the documentation for contributors.

I updated `CONTRIBUTING.md`: d622400

**Comment by pngwn** [comment]
Feel to make both of these changes in a single PR if that is easier.

**Review by pngwn — APPROVED** [review]
Looks great thanks!

**Comment by pngwn** [comment]
Thanks again @whitphx!

**Comment by whitphx** [comment]
Thank you!

**Pull request merged**
