### PR TITLE
fix #3282 avoid in-place dict updates

### LINKED ISSUE #3282: gr.update on multiple output components errors when output created using list multiplication but succeeds with list comprehension
### Describe the bug

`[gr.update(visible=value) for _ in range(2)]` works.
`[gr.update(visible=value)]*2` gives error below.

Toggle the checkbox to trigger.

I printed in the function body to check differences in the 2 variants. They look the same.
```
True
variant1: [{'visible': False, '__type__': 'generic_update'}, {'visible': False, '__type__': 'generic_update'}]
variant2: [{'visible': False, '__type__': 'generic_update'}, {'visible': False, '__type__': 'generic_update'}]
```

I tried debugging the python file and see that the failure variant can stop on my breakpoint at `gradio/components.py", line 1534, in postprocess` but the successful variant does not stop at the breakpoint? 
Why is the successful variant working? And why is it not stopping at my breakpoint like the failure variant does? Are they going down different code paths?

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```
import gradio as gr

num_images = 2

with gr.Blocks() as demo:
    im_list = [gr.Image() for i in range(num_images)]
    def change_visibility(value):
        variant1 = [gr.update(visible=value) for _ in range(2)]
        variant2 = [gr.update(visible=value)]*2
        
        print(variant1 == variant2)
        print('variant1:', variant1)
        print('variant2:', variant2)
        
        # return variant1
        return variant2
    
    checkbox = gr.Checkbox(value=True, label='Show image1')
    checkbox.change(change_visibility, inputs=checkbox,outputs=im_list) 
    
if __name__ == "__main__":
    demo.launch()
```

### Screenshot

_No response_

### Logs

```shell
Traceback (most recent call last):
  File "/Users/hanqi/code/ahrefs/venv/lib/python3.8/site-packages/gradio/routes.py", line 384, in run_predict
    output = await app.get_blocks().process_api(
  File "/Users/hanqi/code/ahrefs/venv/lib/python3.8/site-packages/gradio/blocks.py", line 1027, in process_api
    data = self.postprocess_data(fn_index, result["prediction"], state)
  File "/Users/hanqi/code/ahrefs/venv/lib/python3.8/site-packages/gradio/blocks.py", line 964, in postprocess_data
    prediction_value = block.postprocess(prediction_value)
  File "/Users/hanqi/code/ahrefs/venv/lib/python3.8/site-packages/gradio/components.py", line 1534, in postprocess
    raise ValueError("Cannot process this value as an Image")
ValueError: Cannot process this value as an Image
```
```


### System Info

```shell
Python 3.8.12 (default, Dec  8 2021, 11:22:00) 
[Clang 12.0.5 (clang-1205.0.22.11)] 
Gradio version 3.19.1
MacOS Big Sur version 11.3
```

### Severity

annoying

### PR DESCRIPTION
**Pull request by gitgithan**
# Description

In `def get_specific_update` of `blocks.py`, `generic_update = generic_update.copy()` was added to prevent `postprocess_data` overwriting later dictionary elements in `predictions` during `for i, output_id in enumerate(dependency["outputs"])`. 
This occurs when the components were created with `[gr.update(visible=value)]*2` which causes 2 references to the same object to be created. 
When the first object in `predictions` meets `del generic_update["__type__"]` in `def get_specific_update`, all following objects in `predictions` also get their `__type__` removed. 
This causes `if utils.is_update(prediction_value)` check to fail (should not fail) from the 2nd element of `predictions` on because `return isinstance(val, dict) and "update" in val.get("__type__", "")` has no `__type__` anymore so it goes down else path instead into `prediction_value = block.postprocess(prediction_value)` and errors inside.

**Note**
I assume the updated dictionary is only 1 level deep with no mutable values. Shallow copy would not be sufficient if this dictionary ever gets mutable values

Closes: https://github.com/gradio-app/gradio/issues/3282#issuecomment-1456404332

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by gitgithan** [comment]
@freddyaboulton 
Few questions about the general PR process and specific codebase observations
1. How do contributors fill the changelog with the PR number when the PR hasn't been created yet? It looks like the workflow is to push some commits first to get a PR number and fail `check-changelog`, then add another commit to add the changelog once i have the PR number. This means each contribution requires at least 2 commits to the git log? I know I could have created changelog without PR number first then edit later, but was more natural to do it in one go.

2. There was a failing test even before i made any changes? (`test_components.py::TestModel3D::test_in_interface`) 
3. In `CONTRIBUTING.md`,  `bash scripts/run_circleci.sh` i get  `Error: requires at least 1 arg(s), only received 0`, i was expecting some `.circleci/config.yml` but can't find it?

**Testing**
Is my way of testing correct? I wrote it based on observing neighboring tests in the same class.
I'm not sure if that's the simplest possible test (whether any input/outputs can be removed?) and why I must initialize the components. I thought `checkbox.change(change_visibility, inputs=checkbox, outputs=im_list)` was necessary to make the 0 in `demo.postprocess_data(0` work, but not sure if that's how the integer references the user defined functions, inputs, outputs objects.

**Review by abidlabs — APPROVED** [review]
LGTM! Thanks @gitgithan for the contribution and for adding the test

**Comment by abidlabs** [comment]
> How do contributors fill the changelog with the PR number when the PR hasn't been created yet?

Currently, you can't. This will be fixed when we tackle https://github.com/gradio-app/gradio/issues/2431 (third bullet point), agreed it would improve the developer experience

> There was a failing test even before i made any changes? (test_components.py::TestModel3D::test_in_interface)

That's very strange. Do you mean it was failing locally? What OS are you running?

> In CONTRIBUTING.md, bash scripts/run_circleci.sh i get Error: requires at least 1 arg(s), only received 0, i was expecting some .circleci/config.yml but can't find it?

Thanks for noting this. We no longer use CircleCI so we need to update the contributing guidelines. I'll open an issue to track

**Comment by abidlabs** [comment]
Created an issue here for your last point: https://github.com/gradio-app/gradio/issues/3406

Thanks again for the great PR and great feedback @gitgithan! Will go ahead and merge

**Comment by gitgithan** [comment]
> That's very strange. Do you mean it was failing locally? What OS are you running?

Yes fails locally with `bash scripts/run_all_tests.sh` from `CONTRIBUTING.md`.
Also fails when i individually run that particular test in the VSCode test beaker icon on left panel. 
I'm using mac big sur 11.3. 
Below error looks like .txt is generated but the check endswith gltf.

```
./test/test_components.py::TestModel3D::test_in_interface Failed: [undefined]AssertionError: assert False
 +  where False = <built-in method endswith of str object at 0x119cdeed0>('.gltf')
 +    where <built-in method endswith of str object at 0x119cdeed0> = '/var/folders/x1/jvkctbr51vvgvwwpw7m2l_fm0000gn/T/Boxabdb9e60cc6dda6a2f81d4764a34e24fd47220509a788219e16779754072681e88277aba8baa417e3wj7o712.txt'.endswith
self = <test.test_components.TestModel3D object at 0x125490e20>

    def test_in_interface(self):
        """
        Interface, process
        """
        iface = gr.Interface(lambda x: x, "model3d", "model3d")
        input_data = "test/test_files/Box.gltf"
        output_data = iface(input_data)
>       assert output_data.endswith(".gltf")
E       AssertionError: assert False
E        +  where False = <built-in method endswith of str object at 0x119cdeed0>('.gltf')
E        +    where <built-in method endswith of str object at 0x119cdeed0> = '/var/folders/x1/jvkctbr51vvgvwwpw7m2l_fm0000gn/T/Boxabdb9e60cc6dda6a2f81d4764a34e24fd47220509a788219e16779754072681e88277aba8baa417e3wj7o712.txt'.endswith

test/test_components.py:1838: AssertionError
```

**Comment by abidlabs** [comment]
Can reproduce on my end. Will open an issue for this, thanks again for flagging @gitgithan

**Comment by gitgithan** [comment]
I would like to check why does my profile not show on https://github.com/gradio-app/gradio/graphs/contributors? 
I notice at the top `Contributions to main, excluding merge commits and bot accounts` 
Was mine counted as merge commit and excluded? But aren't all PRs merge commits since they get merged to main eventually?

**Comment by abidlabs** [comment]
Hi @gitgithan yes it should have been included as all PR merges are merges to main. I'm not sure to be honest, maybe it takes a few days to show up?

**Pull request merged**
