### PR TITLE
Create a CSS file for Gradio-lite to preload before /theme.css becomes available

### PR DESCRIPTION
**Pull request by whitphx**
## Description

Currently, in the Wasm mode, no style is applied to the frontend until the server starts running and `/theme.css` is available.
CleanShot 2023-06-29 at 18 41 51@2x

To apply the default style from the beginning, the default theme CSS will be built beforehand and loaded first at runtime with this PR.
CleanShot 2023-06-29 at 18 42 18@2x

Closes: #(issue)

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests & Changelog

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

1. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`
  
1. Unless the pull request is labeled with the "no-changelog-update" label by a maintainer of the repo, all pull requests must update the changelog located in `CHANGELOG.md`:

Please add a brief summary of the change to the Upcoming Release section of the `CHANGELOG.md` file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

### CODE REVIEW

**Review by pngwn — CHANGES_REQUESTED** [review]
We don't want to commit this file as is because it will quickly get out of date. We have a way to generate a css file for a theme in the python library.

I think @hannahblair has added a script to do exactly this in another PR, so maybe we could wait for that and use the same method. This will guarantee the css theme loaded is always up to date with no effort.

**Comment by whitphx** [comment]
OK!

**Comment by whitphx** [comment]
@pngwn @hannahblair Plz let me know when the static CSS generation is available :)

**Comment by pngwn** [comment]
We can just reuse the script and call `python scripts/generate_theme.py` in CI. We could put the step on of the install deps actions tho, just need to figure out which one.

We can make the script accept args so we can `python scripts/generate_theme.py path/to/output-file.css` for different usecases.

**Comment by whitphx** [comment]
@hannahblair Thanks! I will use it after the PR is merged :D
It would be ok to make it accept the target path argument either in your PR or mine in the future when it becomes actually necessary for my use (following YAGNI) 👍

**Pull request closed without merging**
