### PR TITLE
Fix bug in mount_gradio_app with queue enabled

### LINKED ISSUE #2937: AttributeError: 'Blocks' object has no attribute 'progress_tracking'
### Describe the bug

from fastapi import FastAPI
import gradio as gr
app = FastAPI()
from ps import demo
from py import demo1
app = gr.mount_gradio_app(app, demo, path="/ps")
app = gr.mount_gradio_app(app, demo1, path="/py")

  File "D:\ProgramData\Anaconda3\lib\site-packages\starlette\routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "D:\ProgramData\Anaconda3\lib\site-packages\starlette\routing.py", line 566, in __aenter__
    await self._router.startup()
  File "D:\ProgramData\Anaconda3\lib\site-packages\starlette\routing.py", line 648, in startup
    await handler()
  File "D:\ProgramData\Anaconda3\lib\site-packages\gradio\routes.py", line 621, in start_queue
    gradio_app.get_blocks().startup_events()
  File "D:\ProgramData\Anaconda3\lib\site-packages\gradio\blocks.py", line 1667, in startup_events
    utils.run_coro_in_background(self._queue.start, (self.progress_tracking,))
AttributeError: 'Blocks' object has no attribute 'progress_tracking'

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

3.15 ok 3.16 bug

### Screenshot

on

### Logs

```shell
on
```

### System Info

```shell
3.16
```

### Severity

annoying

### PR DESCRIPTION
**Pull request by freddyaboulton**
# Description

Fixes #2937 and adds unit test for `mount_gradio_app`

# Checklist:

- [x] I have performed a self-review of my own code
- [x] I have added a short summary of my change to the CHANGELOG.md
- [x] My code follows the style guidelines of this project
- [x] I have commented my code in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Review by abidlabs — APPROVED** [review]
LGTM, thanks for adding the test!

**Comment by freddyaboulton** [comment]
Thanks for the review @abidlabs !

**Comment by wuyuliyu** [comment]
The error is still there
ps.py's a gradio file
**import gradio as gr with gr.Blocks() as demo1: gr.Markdown( """ # <center>okokok """)**
from ps import demo1

D:\FastAPI> & D:/ProgramData/Anaconda3/python.exe d:/FastAPI/main.py
INFO: Started server process [12256]
INFO: Waiting for application startup.
ERROR: Traceback (most recent call last):
File "D:\ProgramData\Anaconda3\lib\site-packages\starlette\routing.py", line 671, in lifespan
async with self.lifespan_context(app):
File "D:\ProgramData\Anaconda3\lib\site-packages\starlette\routing.py", line 566, in aenter
await self._router.startup()
File "D:\ProgramData\Anaconda3\lib\site-packages\starlette\routing.py", line 648, in startup
await handler()
File "D:\ProgramData\Anaconda3\lib\site-packages\gradio\routes.py", line 621, in start_queue
gradio_app.get_blocks().startup_events()
File "D:\ProgramData\Anaconda3\lib\site-packages\gradio\blocks.py", line 1667, in startup_events
utils.run_coro_in_background(self._queue.start, (self.progress_tracking,))
AttributeError: 'Blocks' object has no attribute 'progress_tracking'

ERROR: Application startup failed. Exiting.

**Comment by FurkanGozukara** [comment]
entire community is broken with this error right now

kohya and other gradio apps

**Pull request merged**
