### PR TITLE
Allows updating `interactive` property for components

### PR DESCRIPTION
**Pull request by abidlabs**
Right now, you cannot update a component's "interactivity" using the standard `gr.component.update()` method: some components like `Number` actually accept `interactive` as a parameter to their `update()` method, but it has no effect, while others like `Textbox` don't accept it at all and error out.

In this PR, I'm working on fixing that. Note that the `interactive` parameter is a little different than others because it is used indirectly to set a component's `mode` property, which is what actually reflects whether a component is static or dynamic. Because "mode" is only used in the frontend, we shouldn't ask backend users to change "mode" but instead update the "mode" ourselves based on what users pass in for `interactive`. 

So I've done that in this draft PR for the `Number` component. Does this look like a reasonable approach @pngwn? If so, I'll implement it for the other components as well. 

You can test with code like this:

```py
import gradio as gr

with gr.Blocks() as demo:
    a = gr.Checkbox()
    c = gr.Textbox()
    b = gr.Number()
    a.change(lambda x:(x, gr.Number.update(interactive=x)), a, [c, b])
    
demo.launch()
```

Closes: #1574

### CODE REVIEW

**Comment by pngwn** [comment]
Yeah, this should work fine. The only thing preventing this is returning the key from `update`, everything else should already be in place (although it will need testing, there could be some edge cases).

Just need to make sure we only do it for components that actually have an interactive and non-interactive mode.

**Comment by abidlabs** [comment]
Implemented and tested with the following components:
* Textbox
* Number
* Slider
* Checkbox
* Radio
* CheckboxGroup
* Dropdown
* Image
* Video
* Audio
* File
* Dataframe
* Timeseries

**Comment by abidlabs** [comment]
Ready for a final review @pngwn or @aliabid94!

**Comment by aliabid94** [comment]
LGTM!

**Comment by miguelwon** [comment]
Hi!
Is this working with Buttons? I would to change `interactive` parameter.

**Comment by pngwn** [comment]
@miguelwon Yes, this should work with `gr.Button`.

**Pull request merged**
