### PR TITLE
Add download button to selected images in `Gallery`

### PR DESCRIPTION
**Pull request by hannahblair**
## Description

Adds a download button icon next to the clear button when selecting image in a `Gallery`.

**_Note - edge case for cross-origin data_**

We currently don't convert the image values passed into the `Gallery` component to base64 like we do with `Image`. This means that if a cross-origin `href` is used (e.g. an external image link on unsplash) in the anchor tag, it doesn't directly download to the user's file system, but rather opens up a new tab with the image link (due to browser security policy). We can either leave this be or implement base 64 conversion to `Gallery` images. Open to thoughts!

Demo 

```
import gradio as gr
import pathlib

current_dir = pathlib.Path(__file__).parent

images = [str(current_dir / "../../test/test_files/bus.png"), str(current_dir / "../../test/test_files/cheetah1.jpg")]

with gr.Blocks() as demo:
    with gr.Row():  
        gal2 = gr.Gallery(
            value=images,
            label="Gallery local files",
            show_download_button=True,
        )

    with gr.Row():
        gal1 = gr.Gallery(
            label="Gallery external imgs",
            value=[
                "https://source.unsplash.com/random/?Dog&1",
                "https://source.unsplash.com/random/?Dog&2",
                "https://source.unsplash.com/random/?Dog&3",
            ],
            show_download_button=True,
        )

demo.launch()
```

Closes: #4307 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by aliabid94** [comment]
Thanks Hannah, looks great but I couldn't get it to work right when running demo/gallery_selections/run.py and setting `show_download_button=True`. See screenshot below:
Screen Shot 2023-07-26 at 12 12 31 PM

The download button links to "127.0.0.1:7860/[Object object]".

**Comment by abidlabs** [comment]
> it doesn't directly download to the user's file system, but rather opens up a new tab with the image link (due to browser security policy). We can either leave this be or implement base 64 conversion to Gallery images. Open to thoughts

Let's leave as is. Conversion to base64 can be very slow for large images. In fact, there's an existing issue to _not_ convert `Image` component images to base64 (#3158), part of the 4.0 milestone

**Comment by dawoodkhan82** [comment]
Can we have the download button show by default. Do we need a param for this at all? Maybe I'm missing something.

**Review by dawoodkhan82 — CHANGES_REQUESTED** [review]
@hannahblair I'm also seeing the same error @aliabid94 was seeing. The download button still links to `http://localhost:9876/[object%20Object]` for me.
Screenshot 2023-07-28 at 8 13 46 PM

**Review by dawoodkhan82 — APPROVED** [review]

**Pull request merged**
