### PR TITLE
Fix Chatbot Pending Message Issues

### PR DESCRIPTION
**Pull request by dawoodkhan82**
## Description

Closes: #6385

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by dawoodkhan82** [comment]
@hannahblair Do you mean the `Pending` message component? Didn't remove it, just moved it.

**Comment by dawoodkhan82** [comment]
> QQ - Do you reckon the styling (padding/height) of the pending bubble/panel should match the messages?

Yes, you're right! Was going to open a new issue for re-designing the pending message bubble. But I can just match the height of the bubble to the messages in this PR for now.

**Comment by dawoodkhan82** [comment]
Fixed pending animation as part of this PR.

**Comment by abidlabs** [comment]
Looks very nice! Thanks @dawoodkhan82 and @hannahblair! Merging so that we can get it out for the release

**Pull request merged**
