### PR TITLE
alternative-tech-stack-look

### PR DESCRIPTION
**Pull request by FarukOzderim**
- positioning tweaks

Pete and Victor suggests having open source stack below in the readme. Though I quite like the previous one because of
- the positioning and layout at the beginning
- emphasizing our open source stack in the beginning
I think it can start a culture in open source community 🐱. Nevertheless I think both could work. WDYT @abidlabs and @aliabd?

> Also, I don't really get those logos it might be confusing for users. They should be at the end.

> The tech isn't the point though, OSS or not, they shouldn't be so prominent. I think it makes sense to put them below the information about the library.

see slack [thread](https://huggingface.slack.com/archives/C02QZLG8GMN/p1653921182885029)

## Old
image

## New
image

### CODE REVIEW

**Comment by abidlabs** [comment]
Also `README.md` should not be edited directly. Instead, edit `readme_template.md` and run `python render_readme.py` to make the changes to the readme. Otherwise, these edits will get overridden next time `render_readme.py` is run

**Comment by FarukOzderim** [comment]
> Hmmm I don't love it being located here right before the quickstart. As someone reading through the readme, it's not clear what these logos represent. A user might think, _should I use Gradio if I'm already using one of these libraries_? I also don't think that we should put more content _before_ the quickstart as we want users to get to the quickstart as quickly as possible.
> 
> My suggestion would be to put this before or after the System Requirements section and say something like: "Gradio is built using many wonderful open-source libraries:" and then have the logos

1. How do you feel about this design btw?
image

2. The only concern I have about this is our Quickstart is way too long(like a few pages), and it would not have visibility under it.
3. A bit different context, why do we have that long Quickstart in the README? We already provide it in the webpage. WDYT about showing a trailer/short_version of the quick_start in README, then forward users to the original getting_started? I don't think we actually want people in README too long for this, should really forward them to original quickstart for a better UX, both before and after the Quickstart trailer.

**Comment by abidlabs** [comment]
> 1. How do you feel about this design btw?

It's not clear what the logos represent in this design either

> 2. The only concern I have about this is our Quickstart is way too long(like a few pages), and it would not have visibility under it.

Is there a particular reason why we are pushing for this to have visibility? I don't see it as a particularly strong value to users to know what libraries Gradio is built with, so I think it's fine if appears at the bottom. 

> 3. why do we have that long Quickstart in the README

Some users may not click through to the website, so it's cool for them to know what can be done with Gradio directly from the readme.

**Comment by FarukOzderim** [comment]
> > 3. why do we have that long Quickstart in the README
> 
> Some users may stumble onto the readme but not click through to the website, so it's cool for them to know what can be done with Gradio directly from the readme.

OK, got you about 1 and 2. But I don't think our README is good in terms of UX we really should direct users to webpage after a quick intro about quickstart IMO.
> We already provide it in the webpage. WDYT about showing a trailer/short_version of the quick_start in README, then forward users to the original getting_started? I don't think we actually want people in README too long for this, should really forward them to original quickstart for a better UX, both before and after the Quickstart trailer.

**Comment by FarukOzderim** [comment]
OK then, this is the final look, please LMK if you approve @abidlabs. Made system reqs shorter as well.

image

**Comment by abidlabs** [comment]
LGTM! Just note that you should make these changes in "readme_template.md" and then run "python render_readme.py". Otherwise, they'll get overridden when "render_readme.py" is run

**Comment by FarukOzderim** [comment]
Made changes in #1421, closing this PR.

**Pull request closed without merging**
