### PR TITLE
fix tab layout

### LINKED ISSUE #3670: Huge empty space in `gr.Tab()`
### Describe the bug

The simple tabbed layout with two columns below has a large empty area in `gradio==3.23.0`.

This empty area did not exist in `3.16.0`.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

```python
import gradio as gr

with gr.Blocks(analytics_enabled=False) as interface:
    with gr.Row():
        with gr.Tab('Chat history'):
            with gr.Row():
                with gr.Column():
                    gr.Markdown('Upload')
                    upload_chat_history = gr.File(type='binary', file_types=['.json', '.txt'])
                with gr.Column():
                    gr.Markdown('Download')
                    download = gr.File()
                    download_button = gr.Button(value='Click me')

interface.launch()
```

### Logs

```shell
--
```

### System Info

```shell
gradio==3.23.0
```

### Severity

annoying

### PR DESCRIPTION
**Pull request by pngwn**
# Description

Closes #3670.

Please include: 
* relevant motivation
* a summary of the change 
* which issue is fixed. 
* any additional dependencies that are required for this change.

Closes: # (issue)

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have added a short summary of my change to the CHANGELOG.md
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by abidlabs** [comment]
@pngwn looks like this change breaks the row of tab names if they exceed the width of the page. You can see it in the deployed Spaces link: https://huggingface.co/spaces/gradio-pr-deploys/pr-4419-all-demos, where it only shows the names of a subset of tabs:

image

**Comment by pngwn** [comment]
Good catch, will fix this.

**Comment by pngwn** [comment]
@abidlabs think this works now.

**Comment by abidlabs** [comment]
LGTM @pngwn!

**Pull request merged**
