### PR TITLE
Website Refactoring and Styling 

### PR DESCRIPTION
**Pull request by aliabd**
Fixes some of the issues in #1731 

- [x] Refactor duplicated JS code from guides and doc templates
- [x] Spacing and footer of embedded demos (min-height)
- [x] Anchor leaves little space from top

### CODE REVIEW

**Comment by abidlabs** [comment]
@aliabd is this ready to be reviewed? Or are you working on the other two items as part of this PR?

**Comment by aliabd** [comment]
Still working on the other two

**Comment by abidlabs** [comment]
Do you wanna convert this PR to a draft in the meantime?

**Comment by aliabd** [comment]
Ready for review

**Comment by abidlabs** [comment]
@aliabid94 can you review this one? Embedded demos still aren't working for me so can't test

**Pull request merged**
