### PR TITLE
Add an option to enable header links for markdown

### PR DESCRIPTION
**Pull request by pngwn**
## Description

Adds an option to enable `header_link` for markdown. Disabled by default to keep existing behaviour.

Run `demo/markdown_example` to see it in action.

I made it consistent with github header links since people seem familiar with that. This required some spacing tweaks but quite minor.

Closes: https://github.com/gradio-app/gradio/issues/4512 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by abidlabs** [comment]
Cool that it handles duplicate headers as well within a single `Markdown` component. One edge case it doesn't handle is if you have the same headers across different Markdown components, e.g.

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.Markdown(
"""
# A
abc
# A
abc
# B
def
""",
        header_links=True
    )
    gr.Markdown(
"""
# A
abc
# A
abc
# B
def
""",
        header_links=True
    )
    
demo.launch()
```

Very niche though, so this PR LGTM.

**Review by abidlabs — APPROVED** [review]

**Comment by pngwn** [comment]
Oh that's actually a pretty easy fix. Will push.

**Comment by pngwn** [comment]
Think that should do it.

**Comment by abidlabs** [comment]
Nice! LGTM, for real this time

**Pull request merged**
