### PR TITLE
[WIP] Add DatasetViewer class

### PR DESCRIPTION
**Pull request by freddyaboulton**
# Description

A very rough WIP of what it would look like to add a dataset viewer "widget" to gradio. 

### To demo this

```python
import gradio as gr
import datasets

apes = gr.DatasetViewer("huggingnft/boredapeyachtclub")
imdb = gr.DatasetViewer("imdb")
speech = gr.DatasetViewer(datasets.load_dataset("asapp/slue", "voxpopuli", split="train"))
with gr.Blocks() as demo:
    with gr.Tabs():
        with gr.Tab("Image Dataset"):
            apes.render()
        with gr.Tab("NLP Dataset"):
            imdb.render()
        with gr.Tab("Audio Dataset"):
            speech.render()

demo.launch()
```

You can also just launch an individual DatasetViewer

```python
imdb = gr.DatasetViewer("imdb").launch()
```

You will have to wait for the datasets library to cache all the data. Can take a while!

Some improvements that come to mind:
- Display audio files in Dataset component
- Support streaming datasets to prevent downloading the entire dataset
- Pass in a filepath

We also need to better display large amounts of text in a text box and add scroll bars to the dataset. Similar to #2666 and #2667 

I initially wanted to do the sql query component of it as well but I was having trouble getting [datasets_sql](https://github.com/mariosasko/datasets_sql) to work. Will need to catch up with @mariosasko to figure out why.

If you run into`MemoryError: Cannot allocate write+execute memory for ffi.callback()` you may need to upgrade to 3.10 [[Apple M1] MemoryError: Cannot allocate write+execute memory for ffi.callback()](https://github.com/huggingface/datasets/issues/4965#top)

FYI @abidlabs 

# Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have added a short summary of my change to the CHANGELOG.md
- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

# A note about the CHANGELOG

Hello 👋 and thank you for contributing to Gradio!

All pull requests must update the change log located in CHANGELOG.md, unless the pull request is labeled with the "no-changelog-update" label.

Please add a brief summary of the change to the Upcoming Release > Full Changelog section of the CHANGELOG.md file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

If you would like to elaborate on your change further, feel free to include a longer explanation in the other sections.
If you would like an image/gif/video showcasing your feature, it may be best to edit the CHANGELOG file using the 
GitHub web UI since that lets you upload files directly via drag-and-drop.

### CODE REVIEW

**Comment by julien-c** [comment]
> You will have to wait for the datasets library to cache all the data. Can take a while!

the idea is to use https://github.com/huggingface/datasets-server instead of datasets in the future, right?

**Comment by freddyaboulton** [comment]
> the idea is to use https://github.com/huggingface/datasets-server instead of datasets in the future, right?

Yes I think the datasets server would simplify things! Right now, the main limitation is that it only supports 100 rows and it can truncate the response. Very excited for https://github.com/huggingface/datasets-server/pull/631, so that we can do sql + stream the results over http.

**Comment by abidlabs** [comment]
Very exciting @freddyaboulton! 

Is the idea that the `DatasetViewer` would also include some ability to explore the dataset as well or just display the dataset? If it's just to display the dataset, how would it differ from `gr.Dataset()`? 

>* Display audio files in Dataset component
>* Support streaming datasets to prevent downloading the entire dataset
>* Pass in a filepath

All of these are great ideas -- if we are using `datasets` library for now, then I [streaming is already supported](https://huggingface.co/docs/datasets/stream) out-of-the-box for all datasets, correct?

**Comment by abidlabs** [comment]
cc @yvrjsharma, would love your thoughts, particularly how we could make this abstraction useful for the PlaygroundAI dataset visualization you shared last week

**Comment by freddyaboulton** [comment]
@abidlabs I started out with adding a text box to DatasetViewer that would allow users to write sql queries but I couldn’t get the datasets_sql library to work. I’ll work with Mario to figure it out. 

I’m not sure if streaming is supported for all datasets but we’ll need https://github.com/huggingface/datasets-server/pull/631 to support sql for all datasets over http. Needless to say, I’ll work with the datasets team to make sure we can create a roadmap towards arbitrary data analysis with sql over http.

**Comment by julien-c** [comment]
datasets streaming is not supported for all datasets, which is why we wish for this integration to use `datasets-server`

Strategically, it will be a great showcase of what that new API enables. And it's going to be ready (in an initial version) in the next couple of weeks, so I'd rather not duplicate efforts and for this to use `datasets-server` from the get go

WDYT?

cc @severo @lhoestq

**Comment by julien-c** [comment]
(Something like `datasets_sql` will also be more future-proof robust with the new API too)

**Comment by severo** [comment]
+1. The idea is that every dataset will be available in parquet format over HTTP, thus the viewer should not depend on the "datasets" library.

Besides this, the datasets server also has an infrastructure to preprocess things (stats on the columns, NLP metrics, etc.) so instead of computing them in Gradio, it would be better to create a new "worker" in the datasets server and access the result through the HTTP API too. This way, it's computed once and for all by the datasets server, and everybody can access it.

**Comment by freddyaboulton** [comment]
@julien-c @severo I agree the "data on the hub" case is best handled by the datasets server. Definitely plan on using it when it's ready! But for this feature to be most useful, we should let users visualize/explore their data wherever it lives - database, local file, s3 etc - provided it's compatible with the datasets library. For those cases we'd still need the datasets library right? I don't think we'd be duplicating efforts.

Also, what do you mean by `(Something like datasets_sql will also be more future-proof robust with the new API too)`?

**Comment by julien-c** [comment]
> For those cases we'd still need the datasets library right? I don't think we'd be duplicating efforts.

For local only Gradio, yes. But for most use cases we would push the datasets-server, that's where many upcoming features will live (and the code is open source too)

**Comment by abidlabs** [comment]
Some more thoughts around the `DatasetViewer` class

A) Demoing a model is a very well-defined use-case, and as such we've been able to build the `gr.Interface()` abstraction in a very general manner: if you have pretty much any machine learning model you'd like to demo, you can use `gr.Interface` to build the input/output UIs and then add other flourishes, like a title, description, examples, etc. However, viewing a dataset is less defined: do we have a good sense of what people want to do when they explore a dataset? Currently, the `DatasetViewer` dataset is **only designed to let users filter** datasets. I think it's fine to start here, but I imagine there are other things we should support (e.g. find duplicate entries, see the embeddings of the data etc.) How support these use cases down the line with the `DatasetViewer` class? (@freddyaboulton perhaps your work with the data measurement tool has given you some ideas)

B) A UI works for pretty much anyone. But querying via SQL is not always the most user-friendly approach to explore a dataset. Should we allow users to query a dataset using other languages (e.g. pandas syntax, or thinking even more out-of-the-box: natural language). 

These are things we can add later, but I want to bring them up now so that we design the `DatasetViewer` class in the most general way possible. cc @aliabid94 @pngwn @osanseviero @merveenoyan for your thoughts!

**Comment by freddyaboulton** [comment]
Going to close for now and circle back later!

**Pull request closed without merging**
