### PR TITLE
Fix ParamViewer css

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Fixes: #7111 

The problem was that we were using `prefers-color-scheme` as opposed to the built-in theme variables. Rather than adding component specific css variables (we agreed to not do that anymore) I tried to recreate the existing style with the current theme variables. I think I got close but there may be some discrepancies. I think it'd be best to not introduce new theme variables though.

### Dark mode
Left is this pr, right is main for both

darkmode

### Light mode

lightmode

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by freddyaboulton** [comment]
We should add some stories but will hold off until we agree on the final style.

**Comment by pngwn** [comment]
I think the screenshots look fine but that isn't what I'm seeing locally:

There seem to be three issues:
- There is too much spacing for the main  arg/type text causing misalignment (as well as making that box too big).
- The text for the arg/ type is too small
- The boxes have double border when collapsed/ when at the bottom. 

Screenshot 2024-01-25 at 15 59 11
Screenshot 2024-01-25 at 15 59 24

Screenshot 2024-01-25 at 16 00 06

Screenshot 2024-01-25 at 15 58 42
Screenshot 2024-01-25 at 15 58 57

**Comment by pngwn** [comment]
Demo i used to test:

```py
import gradio as gr

with gr.Blocks() as demo:
    gr.Markdown("The `round()` function in Python takes two parameters")
    gr.ParamViewer(
        {
            "number": {
                "type": "int | float",
                "description": "The number to round",
                "default": None,
            },
            "ndigits": {
                "type": "int",
                "description": "The number of digits to round to",
                "default": "0",
            },
            "shape": {
                "type": "int",
                "default": "0",
            },
            "shape_two": {"type": "float", "default": "0.0"},
        }
    )

if __name__ == "__main__":
    demo.launch()
    ```

**Review by pngwn — APPROVED** [review]
Looks great! Thanks @freddyaboulton!

**Comment by freddyaboulton** [comment]
Thanks for the help and review @pngwn !

**Pull request merged**
