### PR TITLE
ensure image is always drawn

### LINKED ISSUE #3381: You can't upload an image for sketch in 3.20.0
### Describe the bug

It's hard to recognize the sketchpad boundary when using gradio 3.20.0.

https://user-images.githubusercontent.com/25161192/222938887-bdfaefeb-ef6e-41c4-97db-0e7640ddb60f.mp4

It was shown like this when using gradio 3.19.1.

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Reproduction

https://huggingface.co/spaces/hysts-debug/gradio-issue-3381

[Here](https://huggingface.co/spaces/hysts-debug/gradio-issue-3305) is a Space with the same code using gradio 3.19.1.

### Screenshot

_No response_

### Logs

```shell
none
```

### System Info

```shell
gradio==3.20.0
```

### Severity

annoying

### PR DESCRIPTION
**Pull request by pngwn**
fixes #3381.

Regression introduced in #3351.

### CODE REVIEW

**Review by abidlabs — APPROVED** [review]

**Comment by pngwn** [comment]
oh i dno, let me remove that.  leftover from another branch i think.

**Comment by pngwn** [comment]
> Is there a way to add a frontend test to prevent this regression from happening in the future?

Yes, and i plan to but will take a little time. Didn't want to delay this PR for it.

**Comment by pngwn** [comment]
Will merge when CI passes + i've done a final check with the deployed spaces.

**Comment by abidlabs** [comment]
Sounds good, thanks @pngwn!

**Comment by pngwn** [comment]
All looks good.

**Pull request merged**
