### PR TITLE
Only publish wheel to pypi

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

Cut down pypi storage in half by not uploading the source distribution. People can get the source distribution from github tagged releases. Not sure of any unintended breaking "changes" though. Maybe people who use `pip install --no-binary`. But not sure why they would do that.

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Review by abidlabs — APPROVED** [review]
sounds good, let's see if anyone complains about not having the source available on pypi

**Comment by abidlabs** [comment]
Will merge this in to use for the release, thanks @freddyaboulton!

**Comment by FliegendeWurst** [comment]
> sounds good, let's see if anyone complains about not having the source available on pypi

Not having the source packaged means you need to run:

```
pnpm i --frozen-lockfile --ignore-scripts
GRADIO_VERSION=$new_version pnpm build
```

When building gradio. This is somewhat annoying.

**Comment by FliegendeWurst** [comment]
> Maybe people who use `pip install --no-binary`. But not sure why they would do that.

I think this includes almost every Linux distribution.

**Pull request merged**
