### PR TITLE
Fix filename too long in `processing_utils.decode_base64_to_file` and `processing_utils.create_tmp_copy_of_file`

### PR DESCRIPTION
**Pull request by SkyTNT**
Shorten the filename if it is too long in `processing_utils.decode_base64_to_file` and `processing_utils.create_tmp_copy_of_file`

Closes: #2681

### CODE REVIEW

**Comment by abidlabs** [comment]
Thanks for creating this PR @SkyTNT!

I looked into the code a little bit as I was reviewing this PR and it seems we already trim the prefix in `utils.strip_invalid_filename_characters()` to 200 characters. We call this method in `processing_utils.create_tmp_copy_of_file()` but not in `processing_utils.decode_base64_to_file()`. I think we add a call to this method in `processing_utils.decode_base64_to_file()`, that should be sufficient, right?

**Comment by SkyTNT** [comment]
> Thanks for creating this PR @SkyTNT!
> 
> I looked into the code a little bit as I was reviewing this PR and it seems we already trim the prefix in `utils.strip_invalid_filename_characters()` to 200 characters.
> 
> We call this method in `processing_utils.create_tmp_copy_of_file()` but not in `processing_utils.decode_base64_to_file()`. I think we add a call to this method in `processing_utils.decode_base64_to_file()`, that should be sufficient, right?

I don't think so. `strip_invalid_filename_characters` just simply trim the str but not the bytes. The bytes length of prefix may still be too long.

**Comment by abidlabs** [comment]
I see thanks for clarifying. Let's modify the `utils.strip_invalid_filename_characters()` function to trim the filename based on bytes instead of characters, then. That's the right place for this logic to live.

Would you be able to do that @SkyTNT?

**Comment by SkyTNT** [comment]
Done!

**Comment by abidlabs** [comment]
Thanks @SkyTNT for the fix. I think we'll want to add a test to confirm and then add an entry in the changelog to give you credit and then we should be good to merge in!

**Comment by abidlabs** [comment]
Sure happy to next week!

**Comment by abidlabs** [comment]
Thank you so much for the nice PR @SkyTNT. Tested & merged in

**Pull request merged**
