### PR TITLE
Adds `height` and `zoom_speed` parameters to `Model3D` component, as well as a button to reset the camera position

### PR DESCRIPTION
**Pull request by abidlabs**
Follow-up PR for `gr.Model3D` that:

* adds a `height` parameter (also makes the height of InteractiveModel3D the same as StaticModel3D -- they were previously different)
* disables panning (better for mobile-responsiveness)
* reduces the zoom speed (but allows this be configured as the best zoom speed may be different for different use cases)
* Based on review feedback, a button to reset the camera position 

I wrestled with adding stories for `Model3D` but unfortunately I don't think the Babylon JS viewer plays well within storybook.

Closes: #989 
Closes: #4330

### CODE REVIEW

**Review by dawoodkhan82 — APPROVED** [review]
LGTM, tested and zoom/height kwargs work great

**Comment by dawoodkhan82** [comment]
We might have an issue for this already. But I think we should add functionality for a button/double clicking to reset the zoom/rotate of the object back to it's origin.

**Comment by dawoodkhan82** [comment]
@abidlabs While testing, I noticed the `model3D-demo` has no demo, can we delete that in this pr

**Comment by abidlabs** [comment]
Thanks @dawoodkhan82 for the review! I agree with the "reset camera" suggestion -- let me add it to this PR. 

What do you mean the "model3D-demo has no demo"? Are you referring to this file? https://github.com/gradio-app/gradio/blob/3d-fixes/demo/model3D/run.py

**Comment by dawoodkhan82** [comment]
@abidlabs Actually nvm, I had an empty demo dir called `model3D_demo` but that just existed for me locally, not sure why

**Comment by abidlabs** [comment]
@dawoodkhan82 added a "reset"/"undo" button to both the static and interactive -- lmk if you think the icon is intuitive or a different one would be better:

image

**Comment by dawoodkhan82** [comment]
@abidlabs Tested the undo button on the `model3D` demo. Works great! Quick question: It seems like we're disposing the scene and adding the object back as a way of resetting the camera. Is this the best way? Will it be too expensive/slow when its a large 3d model file with meshes and textures?

**Comment by abidlabs** [comment]
Good point! There's probably a better way, let me see

**Comment by abidlabs** [comment]
Fixed so that only the camera is reset, but otherwise the canvas stays the same. Noticeably faster to reset now & also did some other cleanups. Thanks for the suggestion @dawoodkhan82!

**Review by dawoodkhan82 — APPROVED** [review]
lgtm

**Comment by abidlabs** [comment]
Thanks for all of the reviews @dawoodkhan82 appreciate it!

**Comment by longshiine** [comment]
Could you also add the option to set camera panning (true/false)? To use the ability to move objects from the application, we have built and used a edited source code...

**Comment by abidlabs** [comment]
Hi @longshiine would you be interested in opening a PR for this? I think we could probably support this in the core component but it would be helpful to see the changes that you've made

**Comment by longshiine** [comment]
Ah, it's not a big change at the moment.
Inside the create_camera of shared/utils.ts

// helperCamera.panningSensibility = 0;
helperCamera.attachControl(true, true, 2);

I just changed it to and built it.
So, I was wondering if you have any plans to add options like allow_panning to gr.model3D() in the future.

**Comment by abidlabs** [comment]
Hi @longshiine the reason we disabled panning was that it ruined the experience of the 3D viewer on mobile. We could potentially add a flag, but there's probably a better way. We'll revisit this after we release 4.0 -- feel free to create a separate issue for this.

**Pull request merged**
