### PR TITLE
Fix Node.js start in Windows

### LINKED ISSUE #9903: Error loading SSR mode
### Describe the bug

My Python version is 3.12..7 and I've just installed node.js v22.9.0 and set into system variables "GRADIO_NODE_PATH" the file path. But when I add ssr_mode=True in the launch function the code runs infinitely and I have to stop it, and when I add a node_port=7890, the code run and the app is running normally but I get these warnings:

Cannot start Node server on any port in the range 7890-7890.
Please install Node 20 or higher and set the environment variable GRADIO_NODE_PATH to the path of your Node executable.
You can explicitly specify a port by setting the environment variable GRADIO_NODE_PORT.
* Running on local URL:  http://127.0.0.1:7860/, with SSR ⚡

To create a public link, set `share=True` in `launch()`.

### Have you searched existing issues?  🔎

- [X] I have searched and found no existing issues

### Reproduction

```python
import gradio as gr
with gr.Blocks(title="Coworker",css=css,fill_height=True,theme=theme) as sg:
    with gr.Row():
        with gr.Column(scale=1):
            logout_button = gr.Button("Exit",icon='../static/exit.png',variant='secondary',size='sm', link="/logout",scale=0)   
        with gr.Column(scale=9):
            gr.Markdown("<h1>Coworker(Beta)</h1>",rtl=True)
        with gr.Column(scale=10):
            gr.Markdown("<p><img src='/file=../static/sglogo-circle.png' width='50' height='50'></p>",rtl=True)

    textbox=gr.Textbox(rtl=True,placeholder="از من بپرس ...", container=True,submit_btn=True,stop_btn=True,render=False)
    chatbot=gr.Chatbot(render=False,type='messages',rtl=True,bubble_full_width=False,avatar_images=[None,"../static/coworkerlogo.png"],show_share_button=False,label='Coworker',show_label=False,render_markdown=True,show_copy_button=True,scale=7)
    chatbot.like(vote, None, None)
    gr.ChatInterface(main,
                        type='messages',
                        chatbot=chatbot,
                        textbox=textbox,
                        analytics_enabled=False,               
                        examples=["کاربر خدمات الکترونیک رو چطور میتونم تعریف کنم؟","گزارش مبلغی انبار به تفکیک الگوی سند انبار","نحوه ثبت سند حسابداری در راهکاران"],
                        show_progress='hidden',
                        )

sg.queue(default_concurrency_limit =None)
auth_message = """
    <p><P align=right></p><p>لطفا نام کاربری و رمز عبور سازمانی خود را بدون پسوند همکاران سیستم وارد کنید</p><p><P align=right></p>
"""
try:
    sg.launch(auth=login,share=False,favicon_path="../static/coworkerlogo.png", inline=False, inbrowser=True, allowed_paths=["../static/back.png", "../static/sglogo-circle.png", "../static/coworkerlogo.png"], max_threads=1000,ssr_mode=True,node_port=7890)
except Exception as e:
    print(f"Error launching Gradio interface: {e}")

### Screenshot

_No response_

### Logs

_No response_

### System Info

```shell
Gradio Environment Information:
------------------------------
Operating System: Windows
gradio version: 5.4.0
gradio_client version: 1.4.2

------------------------------------------------
gradio dependencies in your environment:

aiofiles: 23.2.1
anyio: 4.6.2
audioop-lts is not installed.
fastapi: 0.115.2
ffmpy: 0.4.0
gradio-client==1.4.2 is not installed.
httpx: 0.27.2
huggingface-hub: 0.25.2
jinja2: 3.1.4
markupsafe: 2.1.5
numpy: 2.1.2
orjson: 3.10.7
packaging: 24.1
pandas: 2.2.3
pillow: 10.4.0
pydantic: 2.9.2
pydub: 0.25.1
python-multipart==0.0.12 is not installed.
pyyaml: 6.0.2
ruff: 0.6.9
safehttpx: 0.1.1
semantic-version: 2.10.0
starlette: 0.40.0
tomlkit==0.12.0 is not installed.
typer: 0.12.5
typing-extensions: 4.12.2
urllib3: 2.2.3
uvicorn: 0.31.1
authlib; extra == 'oauth' is not installed.
itsdangerous; extra == 'oauth' is not installed.


gradio_client dependencies in your environment:

fsspec: 2024.9.0
httpx: 0.27.2
huggingface-hub: 0.25.2
packaging: 24.1
typing-extensions: 4.12.2
websockets: 12.0
```

### Severity

I can work around it

### PR DESCRIPTION
**Pull request by rrg92**
## Description

Fix node start error in Windows systems, due to file nomenclature.  Fix #9903

Closes: #9903

### CODE REVIEW

**Comment by yvrjsharma** [comment]
This fixes issue #9903 for me on a Windows 11 machine. I also left a detailed comment [here](https://github.com/gradio-app/gradio/issues/9903#issuecomment-2490139556).

**Review by yvrjsharma — APPROVED** [review]
Fixes the issue #9903 for me on a windows 11 machine.

**Comment by rrg92** [comment]
Thank you fast answer and reviews!

**Comment by JackismyShephard** [comment]
@abidlabs What is the ETA on the release of the next gradio version with this fix?

**Comment by abidlabs** [comment]
Probably early next week!

**Pull request merged**
