### PR TITLE
Ensure frontend functions work when they don't return a value

### PR DESCRIPTION
**Pull request by pngwn**
## Description

We now expect some kind of value to be passed into a 'submit' even if it is an empty array (no data). This normally happens even where there are no component inputs, the exception to this is when the frontend function returns nothing or a falsey value. Since the return value of the frontend function gets passed into the 'submit' call, this was causing an error. 
 
I have added a default value to the problematic function to address this, and added a few unit tests to prevent regressions.

Closes: #8495 

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

2. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`

### CODE REVIEW

**Comment by aliabid94** [comment]
The root problem is that `Payload.data` is supposed to be of `unknown[]`, but if the js function does not return anything, `Payload.data` gets set to `undefined`, which is not of type `unknown[]`. This will cause issues downstream, which currently is manifesting in `map_data_to_params`.  I believe the appropriate way to fix the overall problem would be to modify `process_frontend_fn` to return  `[]` when the result is undefined.

**Comment by pngwn** [comment]
Yeah I can change that. I'm not sure what other downstream issues it would cause though. This has been the behaviour forever, it just hasn't been erroring until now.

**Comment by aliabid94** [comment]
Actually its probably enough to just type Payload.data as `unknown[]  | undefined` and keep the parent logic. I just meant the reason that things broke is because the typing was wrong - Payload.data could be undefined as well - and this caused an issue downstream in `map_data_to_params`, but if we simply fix the typing, then the typechecker should also catch anywhere else we assumed it to be a list.

**Comment by pngwn** [comment]
I think it's cleaner to always return an array from the frontend function, so I've added some logic for that. Should be good now.

**Review by aliabid94 — APPROVED** [review]
awesome LGTM!

**Pull request merged**
