### PR TITLE
Pydantic V2 hotfix and patch release

### PR DESCRIPTION
**Pull request by freddyaboulton**
## Description

fastapi 0.100.0 got released an hour ago and it supports pydantic v2 which introduces some changes that invalidate our models. This causes requests to fail with 422 error code. You can see that here: https://huggingface.co/spaces/gradio/calculator_main

I updated the models to match pydantic v2 using the [migration guide](https://docs.pydantic.dev/2.0/migration/#required-optional-and-nullable-fields) and its backwards compatible change with pydantic v1.

I installed pydantic v1 on this branch locally and the demo still works:
pydanctic_v1_run

## 🎯 PRs Should Target Issues

Before your create a PR, please check to see if there is [an existing issue](https://github.com/gradio-app/gradio/issues) for this change. If not, please create an issue before you create this PR, unless the fix is very small. 

Not adhering to this guideline will result in the PR being closed. 

## Tests & Changelog

1. PRs will only be merged if tests pass on CI. To run the tests locally, please set up [your Gradio environment locally](https://github.com/gradio-app/gradio/blob/main/CONTRIBUTING.md) and run the tests: `bash scripts/run_all_tests.sh`

1. You may need to run the linters: `bash scripts/format_backend.sh` and `bash scripts/format_frontend.sh`
  
1. Unless the pull request is labeled with the "no-changelog-update" label by a maintainer of the repo, all pull requests must update the changelog located in `CHANGELOG.md`:

Please add a brief summary of the change to the Upcoming Release section of the `CHANGELOG.md` file and include
a link to the PR (formatted in markdown) and a link to your github profile (if you like). For example, "* Added a cool new feature by `[@myusername](link-to-your-github-profile)` in `[PR 11111](https://github.com/gradio-app/gradio/pull/11111)`".

### CODE REVIEW

**Review by abidlabs — APPROVED** [review]
LGTM nice fix @freddyaboulton! 

Tested with old (0.96) and latest (0.100) versions of `fastapi` and can confirm demos work properly in both.

**Comment by freddyaboulton** [comment]
Thanks for the review @abidlabs !

**Comment by abidlabs** [comment]
Just FYI @freddyaboulton some of the flaky tests might be timing out

**Comment by freddyaboulton** [comment]
Yea they're gonna time out until we install this version in them or pin pydantic.

I can do that in https://github.com/gradio-app/gradio/pull/4834. In https://github.com/gradio-app/gradio/pull/4834 I'm moving test spaces to gradio-tests org from our personal accounts so that we can all make changes more easily in the future.

**Comment by abidlabs** [comment]
Ah yeah it's because https://huggingface.co/spaces/freddyaboulton/calculator is broken. 

We should fix that manually and the version upgrade should take of everything else

**Pull request merged**
